// Stammdaten der Übung L14 (Felder siehe uebungVorlage.md). Langtexte in texte.json, Kurz-Checks in quiz.js.
{id:"L14", st:1, t:"Verriegelungen", sub:"Kollisionen im Handbetrieb ausschließen", ue:3, vor:"L13", repo:"4", bild:["03-schaltschrank.jpg","Tableau Handbetrieb an der Schaltschranktür"], typ:"programmieren",
 einst:"Übungsumfang: <i>Verzinnen: Portal −MM1…−MM4</i> = <i>SPS steuert</i>, <i>Band, Anschlag, Vereinzeler</i> = <i>Bandmodul automatisch</i>, <i>Zinnbad: Temperatur und Füllstand</i> = <i>Regler automatisch</i>, <i>Kühlwassertank: Nachspeisung</i> = <i>Niveauregler automatisch</i>. Quelle der Ausgänge unter <i>Verbindung</i>: <i>PLCSIM Advanced</i>. Jetzt schreibt dein Programm die Ventile −MB1 bis −MB8 des Portals. Steht −SA3 auf HAND, überlässt das Bandmodul den Anschlag −MM5 (−MB9) und den Vereinzeler −MM6 (−MB10) deinem Programm und hält Rollenkurve, Band 2 und Prüfstation an. Schreibst du −MB10 nicht, öffnet die Feder den Vereinzeler, und die Körbe stauen sich am Anschlag. Die Handtaster findest du auf dem Tableau an der Schaltschranktür (Seitenleiste: <i>Schaltschranktür −A1: Handbetrieb</i>).",
 ziele:["Verriegelungen aus Kollisionsgefahren ableiten","Freigaben je Bewegung als eigene Bedingung programmieren","Verriegelungen systematisch prüfen und dokumentieren"],
 sig:"SA3 PF7 MB10 SF11 SF12 SF13 SF14 SF15 SF16 SF17 SF18 SF19 SF20 BG1 BG2 BG3 BG4 BG5 BG6 BG7 BG8 BG14 BG15 BG40 MB1 MB2 MB3 MB4 MB5 MB6 MB7 MB8 MB9",
 sit:"Nach einer Störung hängt der Korb über dem Bad. Der Instandhalter muss die Zylinder einzeln fahren können, ohne das Portal zu beschädigen. Dein Handbetrieb aus L13 erlaubt bisher jede Bewegung in jeder Lage.",
 tab:{cap:"Mindest-Verriegelungen (vom Betreiber vorgegeben)", ...T(["Bewegung","Nur erlaubt, wenn"],[["−MM3 zum Bad / zum Band","Korb angehoben (−BG3)"],["−MM2 senken","über dem Band (−BG5) oder über dem Bad bei offener Abdeckung (−BG6 und −BG7)"],["−MM1 lösen","abgesenkt (−BG4) und über dem Band (−BG5)"],["−MM4 abdecken","Korb angehoben (−BG3) oder über dem Band (−BG5)"]])},
 plan:["Fülle die Vorlage „Gefährdungsmatrix Portal und Anschlag“ aus. Deine Liste gefährlicher Kombinationen aus L13 siehst du direkt darunter, die Tabelle des Betreibers steht in der Aufgabe. Je Bewegung trägst du ein, in welcher Lage sie gefährlich ist (Korb oben oder unten, über Band oder Bad, Abdeckung offen oder zu, Anschlag offen oder zu, Korb eingehängt oder nicht), was passieren würde und welche Freigabe das verhindert. Die Beispielzeile −MM3 zum Bad zeigt dir, wie es geht. Die Zeilen für den Anschlag −MM5 und für Heben und Senken am Übergabeplatz fehlen in der Tabelle des Betreibers. Du füllst sie selbst. Prüfe jede Zeile am Zwilling und lasse die Matrix von der Lehrkraft abzeichnen, bevor du programmierst."],
 auf:["Lege einen FC <code>Interlock</code> (Verriegelung) mit Bausteinkopf an und rufe ihn im OB1 vor <code>Manual</code> auf. Die Endlagen kommen als Inputs herein, die Freigaben gehen als Outputs hinaus, und der OB1 legt sie in <code>PlantData</code> ab. Trage die Freigaben in die Vorlage „Variablenliste PlantData“ ein.","Bilde je Bewegung eine Freigabe, z. B. <code>releaseToBath</code> aus der Endlage „−MM2 oben“. Formuliere jede Freigabe positiv („erlaubt, wenn … gemeldet ist“) und schreibe in den Kommentar, welche Kollision sie verhindert.","Erweitere <code>Manual</code> um je einen Input je Freigabe und verschalte sie im OB1 aus PlantData. Eine Spule wird nur angesteuert, wenn Taster UND Freigabe anstehen. Beim Anschlag −MB9 wirkt die Freigabe auf die Taster, also auf das Setzen und Rücksetzen der gespeicherten Stellung, nicht auf das Dauersignal an −MB9.","Programmiere die Rückmeldung an −PF7: Drückt der Bediener einen Taster, dessen Freigabe fehlt, blinkt −PF7 mit 1 Hz (Clock als Multiinstanz in Manual). −PF7 behält genau eine Schreibstelle: Dauerlicht in HAND, Blinken bei Sperre.","Ergänze die Verriegelungen, die in der Tabelle des Betreibers fehlen: die Freigabe releaseStopper für den Anschlag −MM5 und Heben bzw. Senken am Übergabeplatz. Begründe jede Ergänzung mit einer konkreten Kollision.","Entscheide: Ein Taster ist gedrückt, die Freigabe kommt erst danach. Darf die Bewegung dann starten? Setze deine Entscheidung um und begründe sie.","Prüfe jede Verriegelung einzeln am Ventilausgang im Signalmonitor und trage das Ergebnis in die Vorlage „Prüfprotokoll Verriegelungen am Ventilausgang“ ein. Prüfe in der Querverweisliste die Schreibstellen."],
 hilfe:{1:["Welche Endlage muss gemeldet sein, damit die Bewegung keinen Schaden anrichtet? Schreibe die Antwort als Satz mit „erlaubt, wenn“.","Übersetze jede Zeile der Betreibertabelle und deiner Matrix in eine Zuweisung an einen Output release…. Nur UND und ODER auf Signale, die 1 melden, keine Negation einer Endlage.","<code>#releaseToBath := #mm2Up; #releaseToConveyor := #mm2Up; #releaseLower := #mm3AtConveyor OR (#mm3AtBath AND #coverOpen); #releaseUnhook := #mm2Down AND #mm3AtConveyor; #releaseCoverClose := #mm2Up OR #mm3AtConveyor;</code>"], 3:["Wann soll −PF7 dauernd leuchten, wann blinken? Kann es dafür zwei Zuweisungen geben?","Bilde zuerst #tempBlocked: irgendein Taster gedrückt UND seine Freigabe fehlt. Dann eine einzige Zuweisung für −PF7.","<code>#tempBlocked := (#btnToBath AND NOT #releaseToBath) OR (#btnLower AND NOT #releaseLower) OR …; #instClock(halfPeriod := #BLINK_HALF_PERIOD); #lampManual := #manualMode AND (NOT #tempBlocked OR #instClock.pulse);</code>"], 4:["Was passiert am Übergabeplatz, wenn der Korb eingehängt ist und der Anschlag geschlossen bleibt? Was passiert, wenn der Anschlag schließt, während der Korb zwischen oben und unten hängt?","Heben und Senken über dem Band nur mit offenem Anschlag (−BG15), wenn ein Korb eingehängt ist (−BG1). Den Anschlag darf das Programm nur bewegen (öffnen oder schließen), wenn −MM2 in einer Endlage steht. Diese Freigabe heißt releaseStopper.","Lösungsskizze, prüfe sie am Zwilling: <code>#releaseRaise := #mm3AtBath OR #stopperOpen OR #mm1Released; #releaseLower := (#mm3AtConveyor AND (#stopperOpen OR #mm1Released)) OR (#mm3AtBath AND #coverOpen); #releaseStopper := #mm2Up OR #mm2Down;</code> Diese releaseLower ersetzt deine Zeile aus Schritt 2. Beim Anschlag sperrt releaseStopper nur das Setzen und Rücksetzen deiner gespeicherten Stellung, nicht das Dauersignal an −MB9: Fiele −MB9 bei jeder Fahrt von −MM2 ab, schlösse die Feder den Anschlag unter dem Korb. Begründe jede Zeile mit der Kollision aus deiner Matrix."], 5:["Was hast du in L13 über Tippbetrieb und unerwarteten Anlauf gelernt?","Lässt du die Bewegung starten, sobald die Freigabe kommt, fährt der Zylinder ohne neuen Befehl los. Verlangst du eine neue Flanke am Taster, fährt er erst nach erneutem Drücken.","Eine mögliche Lösung: Die Spule braucht die steigende Flanke des Tasters, während die Freigabe ansteht, und bleibt danach angesteuert, solange Taster und Freigabe anstehen. Begründe deine Wahl mit dem Schutz gegen unerwarteten Anlauf."]},
 lf:[["Warum braucht −MM2 zum Absenken über dem Bad zwei Bedingungen, über dem Band nur eine?",[0]],["Warum verriegelst du auf die gemeldete Endlage (z. B. −BG3) und nicht auf den zuletzt gegebenen Befehl „anheben“?",[1]],["Ein Taster wird gedrückt gehalten, während die Freigabe erst kommt. Soll die Bewegung dann starten? Begründe mit dem Tippbetrieb aus L13 und dem Schutz gegen unerwarteten Anlauf.",[1]]],
 lfk:["Welche Kombination stoppt der Zwilling selbst (Meldung unter Ereignisse), und warum reicht das an einer echten Anlage nicht? Woran hast du im Signalmonitor gesehen, dass deine eigene Verriegelung trotzdem wirkt?"],
 pr:[["Jede Verriegelung einzeln geprüft: Taster in verbotener Lage → zugehöriger Ventilausgang (z. B. −MB5) bleibt 0, im Signalmonitor geprüft, nicht nur an der Bewegung",[1,2]],["Freigabe fehlt bei gedrücktem Taster → −PF7 blinkt mit 1 Hz, sonst Dauerlicht in HAND",[1]],["Sensor der Freigabe auf 0 forcen (z. B. −BG3) → zugehöriger Taster wirkungslos",[1,2]],["Gefährdungsmatrix vollständig und von der Lehrkraft abgezeichnet",[0]],["Interlock greift auf keine PLC-Variable zu, alle Endlagen kommen über Inputs; −MB1 bis −MB9 und −PF7 haben je genau eine Schreibstelle",[1]]],
 ergebnis:[{n:"FC Interlock", a:"neu", h:"eine Freigabe je Bewegung, über PlantData an Manual (ab L16 an die Befehlsausgabe)"},{n:"FB Manual", a:"erweitert", h:"Spule nur mit Freigabe, −PF7 blinkt bei Sperre"},{n:"Gefährdungsmatrix", a:"neu", h:"abgezeichnet, Testplan und Doku für den Betreiber"}, {n:"globaler DB PlantData", a:"erweitert", h:"neue Einträge in der Variablenliste PlantData: Freigabe −MM1 lösen, Freigabe −MM2 senken, Freigabe −MM2 anheben …"}],
 plus:"Zeige in einer Beobachtungstabelle zu jeder gesperrten Bewegung, welche Bedingung fehlt: Lege in Manual je Bewegung eine statische Variable <code>#statBlocked…</code> an (Taster gedrückt UND Freigabe fehlt) und beobachte sie. So findet der Instandhalter den Grund ohne Programmiergerät.",
 tpls:[
 {id:"gefahr", cap:"Gefährdungsmatrix Portal und Anschlag", phase:2, head:["Bewegung","gefährlich, wenn … (Lage)","mögliche Folge","Freigabe positiv formuliert","Sensoren der Freigabe","am Zwilling geprüft (Datum, Beobachtung)","abgezeichnet"], muster:["−MM3 zum Bad","Korb nicht ganz oben: −MM2 abgesenkt oder unterwegs (−BG3 = 0)","Korb schleift über Band und Badrand, Haken und Korb werden beschädigt","erlaubt, wenn −MM2 oben meldet (−BG3 = 1)","−BG3","Datum: −BG3 auf 0 geforct, −SF15 gedrückt, −MB5 bleibt 0. Bei wirklich abgesenktem Korb sperrt der Zwilling −MM3 zusätzlich selbst und meldet „Kollision: −MM3 fährt nicht, Tauchzylinder −MM2 ist nicht oben (−BG3)“","Kürzel der Lehrkraft"], rows:[["−MM1 einhängen"],["−MM1 lösen"],["−MM2 senken über dem Band (Übergabeplatz)"],["−MM2 senken über dem Bad"],["−MM2 anheben über dem Band (Übergabeplatz)"],["−MM2 anheben über dem Bad"],["−MM3 zum Bad"],["−MM3 zum Band"],["−MM4 abdecken"],["−MM4 öffnen"],["−MM5 öffnen"],["−MM5 schließen"]], inputs:6, leer:2},
 {id:"verriegelpruef", cap:"Prüfprotokoll Verriegelungen am Ventilausgang", phase:4, head:["Nr.","Bewegung (Taster)","Ausgangslage (angefahren oder geforct)","erwartete Reaktion am Ventilausgang","beobachtete Reaktion im Signalmonitor","i.O."], muster:["Beispiel","−MM3 zum Bad (−SF15)","−BG3 auf 0 geforct (Korb nicht oben)","−MB5 bleibt 0, −PF7 blinkt mit 1 Hz","−MB5 = 0, −PF7 blinkt","i.O."], rows:[["1","−MM1 lösen (−SF12)"],["2","−MM2 senken (−SF13)"],["3","−MM2 anheben (−SF14)"],["4","−MM3 zum Bad (−SF15)"],["5","−MM3 zum Band (−SF16)"],["6","−MM4 abdecken (−SF17)"],["7","−MM5 öffnen (−SF19)"],["8","−MM5 schließen (−SF20)"]], inputs:4, leer:2},
 {id:"plantdata", erweitert:"L05:plantdata", cap:"Variablenliste PlantData", phase:4, head:["Inhalt","ab Übung","Variablenname","Datentyp","remanent (ja oder nein, warum)","schreibt (Baustein, über den OB1)","liest"], muster:["Betriebsbereitschaft","L05","ready","Bool","nein, nach dem Neustart muss neu gestartet werden","Operation (Output ready)","Indication"], rows:[["Freigabe −MM1 lösen","L14"],["Freigabe −MM2 senken","L14"],["Freigabe −MM2 anheben","L14"],["Freigabe −MM3 zum Bad","L14"],["Freigabe −MM3 zum Band","L14"],["Freigabe −MM4 abdecken","L14"],["Freigabe −MM5 (releaseStopper)","L14"]], inputs:5, leer:1}
]
,
 bezug:[
 {von:"L13", id:"kombis", phase:2, wozu:"Deine Liste gefährlicher Kombinationen aus L13 ist der Ausgangspunkt für die Gefährdungsmatrix."}
]
}
