// Stammdaten der Übung L27 (Felder siehe uebungVorlage.md). Langtexte in texte.json, Kurz-Checks in quiz.js.
{id:"L27",
 st:3,
 t:"Kühlwassertank: Zweipunktregelung",
 sub:"Regelkreis, Grenzschalter und Drahtbruch",
 ue:3,
 vor:"L16, L25",
 repo:"21",
 bild:["14-kuehlwassertank.jpg","Kühlwassertank mit −BL2, −BG38, −BG39, −MB17 und −MB18"],
 typ:"programmieren",
 einst:"Übungsumfang: <i>Kühlwassertank: Nachspeisung = SPS regelt</i> (dein Programm speist nach). <i>Band, Anschlag, Vereinzeler = SPS steuert</i>: Dein Förderprogramm aus L23 bis L25 läuft weiter und schaltet die Pumpe −QA7, nur dann liegt auch der Trockenlaufschutz bei dir. <i>Verzinnen: Portal −MM1…−MM4 = Portal automatisch</i>. Den Ablasshahn (Seitenleiste <i>Prozess</i>) nutzt du als Störgröße.",
 ziele:["Steuern und Regeln unterscheiden und den Regelkreis am Kühlwassertank mit seinen Größen beschreiben","eine Zweipunktregelung mit zwei Grenzschaltern programmieren","nach dem Ruhestromprinzip einen Drahtbruch erkennen, sicher reagieren und melden"],
 sig:"BG38 BG39 MB17 MB18 QA7 SF4",
 sit:"Beim Abschrecken verliert der Tank Wasser. Bisher hat ein eigener Niveauregler nachgespeist. Jetzt übernimmt dein Programm diese Aufgabe, vorerst nur mit zwei Grenzschaltern, und die Pumpe darf nie trocken laufen.",
 plan:["Zeichne den Regelkreis des Kühlwassertanks (Vorlage Regelkreis) und benenne in der Vorlage „Begriffe des Regelkreises am Kühlwassertank“ an deiner Anlage Regelgröße, Führungsgröße, Regeldifferenz, Stellgröße, Störgrößen, Stellglied, Regelstrecke und Messglied.","Trage in der Vorlage „Schaltpunkte am Kühlwassertank“ ein, was −BG38 und −BG39 melden und in welchem Zustand −MB17 bei steigendem und bei fallendem Pegel ist. Eine Tankskizze mit den Schaltpunkten 25 % und 90 % kannst du zusätzlich zeichnen."],
 auf:["Lege einen FB <code>TankLevel</code> mit Bausteinkopf an und rufe ihn im OB1 vor der Befehlsausgabe auf. Trage −MB17 in <code>CommandOutput</code> ein.","Öffne −MB17, sobald −BG38 abfällt, und schließe es, sobald −BG39 abfällt. Dazwischen behält das Ventil seinen Zustand (statische Variable, rücksetzdominant).","Stelle das Regelventil −MB18 fest auf 100 %: <code>TankLevel</code> schreibt 27648 auf den Analogausgang %QW80 und ist dessen einzige Schreibstelle.","Gib die Pumpe −QA7 nur frei, solange −BG38 „bedeckt“ meldet (Trockenlaufschutz). Die Freigabe wirkt als Verriegelung in der Befehlsausgabe und gilt damit auch für den Pumpenbefehl aus <code>Quench</code> (L25).","Unterscheide „voll“ von „Drahtbruch an −BG39“ ohne den Analogwert −BL2: Lege eine Signalkombination oder einen zeitlichen Verlauf fest, sperre bei Drahtbruch die Nachspeisung und melde eine Störung. Quittiert wird mit einer Flanke an −SF4. Solange die Ursache besteht, bleibt die Nachspeisung gesperrt. Ergänze zum Schluss deine „Ausgangsliste“ um −MB17, −MB18 und die neue Bedingung von −QA7 und prüfe sie in der Querverweisliste."],
 hilfe:{"1":["Zwischen 25 und 90 % melden beide Grenzschalter dasselbe, egal ob der Pegel steigt oder fällt. Woher weiß dein Programm dann, ob −MB17 offen sein soll?","Das Ventil braucht ein Gedächtnis: setzen, wenn −BG38 abfällt; rücksetzen, wenn −BG39 abfällt. Rücksetzen hat Vorrang (L03).","<code>IF NOT #minCovered THEN #statRefill := TRUE; END_IF;</code> <code>IF NOT #maxFree OR #statWireBreak THEN #statRefill := FALSE; END_IF;</code> Ausgang <code>refillCmd := #statRefill;</code> an <code>CommandOutput</code>."], "3":["Wo muss eine Sperre stehen, damit sie für jeden Pumpenbefehl gilt, egal aus welchem Baustein er kommt?","<code>TankLevel</code> gibt einen Ausgang <code>pumpRelease</code> aus. In <code>CommandOutput</code> verknüpfst du ihn mit UND in die Zeile für −QA7. Der Befehl aus <code>Quench</code> bleibt, wie er ist.","In <code>CommandOutput</code>: −QA7 := (Pumpenbefehl Quench) UND pumpRelease. In <code>TankLevel</code>: <code>#pumpRelease := #minCovered;</code> (−BG38 über die Schnittstelle)."], "4":["Welche Kombination der beiden Grenzschalter kann es physikalisch nicht geben? Und wie schnell kann der Pegel überhaupt von „unter 90 %“ auf „voll“ springen?","Möglichkeit 1: −BG38 meldet „unter Minimum“ und −BG39 gleichzeitig „voll“, das geht nur mit Fehler. Möglichkeit 2: −BG39 fällt ab, obwohl −MB17 seit langer Zeit zu ist und der Pegel nicht steigen kann. Wähle eine Regel, begründe sie und lasse sie eine kurze Verzögerungszeit lang anstehen.","<code>#instWireTimer(IN := NOT #maxFree AND NOT #minCovered, PT := #WIRE_DELAY);</code> <code>IF #instWireTimer.Q THEN #statWireBreak := TRUE; END_IF;</code> Rücksetzen nur mit Flanke an −SF4 UND <code>#maxFree</code> wieder 1. Prüfe auch den Fall, dass −BG39 abfällt, während −MB17 zu ist und der Ablasshahn offen ist."]},
 lf:[["Warum ist die Nachspeisung schon mit zwei Grenzschaltern ein Regelkreis und keine Steuerung? Zeige es an deiner Regelkreis-Skizze.",[0]],["Warum meldet −BG39 bei Drahtbruch „voll“ und −BG38 „leer“? Warum ist beides die sichere Seite?",[2]],["Warum braucht der Zustand „Ventil offen“ ein Gedächtnis, und warum muss der Speicher rücksetzdominant sein?",[1]]],
 lfk:["Wie lange hat ein Nachspeisevorgang von 25 auf 90 % mit offenem Ablasshahn gedauert, und wie passt das zum Zulauf von rund 1,5 %/s?"],
 pr:[["Mit offenem Ablasshahn pendelt der Pegel über mindestens zwei Nachspeisevorgänge zwischen 25 und 90 %",[0,1]],["Ereignisliste: keine Meldung „Kühlwassertank läuft über“ und keine Meldung „Umwälzpumpe −MA3 läuft trocken“",[1,2]],["−BG39 im Signalmonitor auf 0 forcen, während der Tank nicht voll ist → keine Nachspeisung mehr; die Störmeldung kommt spätestens, wenn −BG38 abfällt (Ablasshahn offen)",[2]],["Quittieren mit −SF4, solange −BG39 noch geforct ist → Meldung bleibt, Nachspeisung bleibt gesperrt; nach Rücknahme des Force und Quittieren speist dein Programm wieder nach",[2]],["−BG38 auf 0 forcen → −QA7 bleibt 0, auch wenn <code>Quench</code> die Pumpe anfordert",[2]]],
 plus:"Überwache zusätzlich die Füllzeit: Steigt der Pegel nach dem Öffnen von −MB17 nicht innerhalb einer begründeten Zeit wieder über −BG38, meldet dein Programm „Nachspeisung gestört“. Teste es, indem du −MB18 vorübergehend auf 0 % stellst.",
 ergebnis:[{n:"FB TankLevel", a:"neu", h:"Zweipunktregelung mit Grenzschaltern, Drahtbruch −BG39, −MB18 fest 100 %"},{n:"FB CommandOutput", a:"erweitert", h:"−MB17, Freigabe Trockenlaufschutz für −QA7"},{n:"Regelkreis Kühlwassertank", a:"neu", h:"Grundlage für L28 bis L30"}, {n:"Ausgangsliste", a:"erweitert", h:"neue Zeilen: −MB17, −MB18 (%QW80), −QA7"}, {n:"Schaltpunkte am Kühlwassertank", a:"neu", h:"Ein- und Ausschaltpunkt mit Begründung"}],
 tpls:[
 {id:"begriffe", cap:"Begriffe des Regelkreises am Kühlwassertank", phase:2, head:["Begriff","am Kühlwassertank","Signal bzw. Gerät"], muster:["Beispiel Zinnbad: Stellglied","Halbleiterrelais der Heizung","−TB1"], rows:[["Regelgröße"],["Führungsgröße"],["Regeldifferenz"],["Stellgröße"],["Störgrößen"],["Stellglied"],["Regelstrecke"],["Messglied"]], inputs:2},
 {id:"schaltpunkte", cap:"Schaltpunkte am Kühlwassertank", phase:2, head:["Pegel bzw. Lage","−BG38","−BG39","−MB17"], muster:["Beispiel: Tank voll, 95 %","1 (Gabel bedeckt)","0 (Gabel bedeckt)","zu"], rows:[["Pegel steigt, zwischen 25 und 90 %"],["Pegel erreicht 90 %"],["Pegel fällt, zwischen 90 und 25 %"],["Pegel fällt unter 25 %"],["Drahtbruch an −BG39, Pegel bei 50 %"]], inputs:3},
 {id:"pegel", cap:"Pegelverlauf über mehrere Nachspeisevorgänge", phase:4, head:["Vorgang","−MB17 öffnet bei (%)","−MB17 schließt bei (%)","Dauer 25 → 90 % (s)","Bemerkung"], muster:["Rechenbeispiel ohne Abfluss","25","90","rund 43 (65 % ÷ 1,5 %/s)","mit offenem Ablasshahn dauert es länger"], rows:[["1"],["2"],["3"]], inputs:4},
 {id:"schreib", erweitert:"L02:schreib", cap:"Ausgangsliste", phase:4, head:["Ausgang","Bedeutung","ab Übung","schreibt (Baustein, einzige Stelle)","Bedingung oder Befehl kommt von","in der Querverweisliste geprüft"], muster:["−PF2","Bad bereit","L02","FB Indication (bis L03 FC), Aufruf im OB1","−BG9 UND −BG10, ODER Lampentest −SF4","ja, eine Schreibstelle"], rows:[["−MB17","Nachspeisen Frischwasser","L27"],["−MB18 (%QW80)","Regelventil, fest 100 %","L27"],["−QA7","Pumpe, jetzt mit Trockenlaufschutz −BG38","L27"]], inputs:3}
]
}
