// Stammdaten der Übung L02 (Felder siehe uebungVorlage.md). Langtexte in texte.json, Kurz-Checks in quiz.js.
{id:"L02", st:1, t:"Verknüpfungen", sub:"UND, ODER, NICHT, XOR im ersten Baustein", ue:3, vor:"L01", repo:"–", bild:["02-bedienpult.jpg","Meldeleuchten −PF1 bis −PF4 am Bedienpult"], typ:"programmieren",
 einst:"Übungsumfang: <i>Verzinnen: Portal −MM1…−MM4</i> = <i>Portal automatisch</i>, <i>Band, Anschlag, Vereinzeler</i> = <i>Bandmodul automatisch</i>, <i>Zinnbad: Temperatur und Füllstand</i> = <i>Regler automatisch</i>, <i>Kühlwassertank: Nachspeisung</i> = <i>Niveauregler automatisch</i>. Unter <i>Verbindung</i> steht die Quelle der Ausgänge auf <i>PLCSIM Advanced</i>, die Bridge ist verbunden. Die Anlage läuft also von selbst, dein Programm schaltet nur die Meldeleuchten.",
 ziele:["Grundverknüpfungen UND, ODER, NICHT und XOR in einem FC programmieren und im OB1 aufrufen","Funktionstabellen vor dem Programmieren aufstellen und am Zwilling prüfen","Öffner in der Hardware und Negation im Programm sicher unterscheiden","jeden Ausgang an genau einer Stelle schreiben und das mit der Querverweisliste nachweisen"],
 sig:"BG9 BG10 BG40 BG14 BG15 SF4 PF1 PF2 PF3 PF4",
 sit:"Der Schichtleiter will am Bedienpult auf einen Blick sehen, ob das Zinnbad bereit ist und ob ein Korb wartet. Außerdem soll ein Lampentest alle Meldeleuchten prüfen, und der Anschlag −MM5 soll sich selbst überwachen: Er darf nie beide Endlagen zugleich melden.",
 plan:["Fülle die Funktionstabelle zur Endlagen-Plausibilität von −MM5 vor dem Programmieren aus (Vorlage „Funktionstabelle Endlagen-Plausibilität −MM5“).","Schreibe in der Vorlage „Bedingungen der Meldeleuchten als Satz“ für jede Meldeleuchte ihre Bedingung als ganzen Satz auf. Die Beispielzeile zu −PF3 zeigt dir, wie es geht. Lege erst danach fest, ob du den Eingang auf 1 oder auf 0 abfragst.","Lege die Schnittstelle des FC Indication in der Vorlage „Schnittstelle FC Indication“ fest: Die PLC-Variablen stehen schon drin, du vergibst Parameternamen, Datentyp und Bedeutung."],
 auf:["Lege einen FC <code>Indication</code> in FUP an (<i>Programmbausteine</i>, <i>Neuen Baustein hinzufügen</i>, <i>Funktion</i>) und fülle den Bausteinkopf aus: Bausteintitel, Bausteinkommentar mit dem Zweck, unter <i>Eigenschaften</i>, <i>Information</i> Autor und Version.","Lege die Schnittstelle an: −BG9, −BG10, −BG40, −BG14, −BG15 und −SF4 als Input, die Leuchten −PF1 bis −PF4 und <code>stopperPlausible</code> als Output.","UND: Programmiere −PF2 „Bad bereit“: Die Leuchte geht an, wenn −BG9 UND −BG10 in Ordnung melden.","NICHT: Programmiere −PF3 „Füllhöhe unterschritten“: Die Leuchte geht an, wenn −BG10 nicht meldet.","Zuweisung: Programmiere −PF4 „Korb vorhanden“, die Leuchte zeigt −BG40.","ODER: Baue den Lampentest in die vorhandenen Zuweisungen ein. Solange −SF4 gedrückt ist, leuchten −PF1 bis −PF4 zusätzlich zu ihrer eigentlichen Bedingung. −PF1 hat noch keine eigene Bedingung und zeigt vorerst nur den Lampentest.","XOR: Bilde den Output <code>stopperPlausible</code> aus −BG14 XOR −BG15 und prüfe ihn Zeile für Zeile gegen deine Funktionstabelle.","Rufe <code>Indication</code> im OB1 auf und verschalte jeden Parameter mit seiner PLC-Variable. Übersetze, lade und teste am Zwilling.","Prüfe in der Querverweisliste, dass jede Leuchte −PF1 bis −PF4 genau eine schreibende Stelle hat, und trage das Ergebnis in die Vorlage „Ausgangsliste“ ein. Die Ausgangsliste zeigt dir für jeden Ausgang den einzigen Baustein, der ihn schreibt, und woher seine Bedingung kommt. Du führst sie bis L34 weiter.","Stelle den Baustein auf KOP um (Rechtsklick auf <code>Indication</code>, <i>Eigenschaften</i>, <i>Allgemein</i>, <i>Sprache</i>) und vergleiche die Darstellung. In KOP gibt es keine XOR-Anweisung. Notiere, wie TIA das Netzwerk mit stopperPlausible darstellt. Halte den Vergleich in der Vorlage „Vergleich FUP, KOP und SCL“ fest. Stelle danach wieder auf FUP zurück.","SCL: Lege in der Schnittstelle von <code>Indication</code> unter Temp die Variable <code>tempBathReadyScl</code> (Bool) an. Füge hinter dem letzten Netzwerk mit Rechtsklick, <i>SCL-Netzwerk einfügen</i>, ein Netzwerk ein und schreibe dort <code>#tempBathReadyScl := (#temperatureOk AND #levelOk) OR #lampTest;</code> Übersetze, lade und vergleiche im Programmstatus: <code>#tempBathReadyScl</code> und <code>#lampBathReady</code> müssen immer gleich sein. Trage die SCL-Zeile jedes Netzwerks in die Vorlage „Vergleich FUP, KOP und SCL“ ein. Lösche danach das SCL-Netzwerk und die Temp-Variable wieder."],
 fw:{0:[1,10,14], 1:[2,9], 2:[3,15,12], 3:[5,3,12], 4:[15,3], 5:[6,8,12], 6:[11,3,16], 7:[2,17,0], 8:[13,7,8], 9:[4,14], 10:[12,16,14]},
 hilfe:{5:["Wie viele Gründe gibt es, dass −PF2 leuchtet? Wie schreibst du mehrere Gründe in eine einzige Zuweisung?","Nimm die vorhandene Bedingung und den Lampentest als zwei Eingänge einer ODER-Box. Der Ausgang der ODER-Box geht auf die Zuweisung von −PF2.","In SCL gelesen: <code>#lampBathReady := (#temperatureOk AND #levelOk) OR #lampTest;</code> Genauso für −PF3 und −PF4. Für −PF1 bleibt nur <code>#lampOperation := #lampTest;</code>"], 6:["Wann soll stopperPlausible 1 sein? Schaue in deine Funktionstabelle.","XOR ist 1, wenn genau einer der beiden Eingänge 1 ist. In FUP findest du die Box in der Task Card <i>Anweisungen</i> unter <i>Einfache Anweisungen</i>, <i>Bitverknüpfungen</i>, <i>X: EXKLUSIV ODER-Verknüpfung</i>.","FUP: X-Box mit den Eingängen #stopperClosed und #stopperOpen, Ausgang auf #stopperPlausible. Test: −BG14 und −BG15 gemeinsam auf 1 forcen → 0; einen von beiden auf 0 → 1."], 7:["Was tut ein FC, solange ihn niemand aufruft?","Ziehe Indication aus der Projektnavigation in ein Netzwerk des OB1. Lege an jeden Input die passende PLC-Variable, an jeden Output die Leuchte.","Beispiel: Input temperatureOk mit \"BG9_Temperatur\", Output lampBathReady mit \"PF2_Temperatur\". Den Output stopperPlausible legst du auf eine Temp-Variable des OB1, z. B. #stopperPlausible, und siehst ihn im Programmstatus."], 10:["Wo fügst du in einem FUP-Baustein ein Netzwerk in einer anderen Sprache ein?","Rechtsklick auf das letzte Netzwerk, <i>SCL-Netzwerk einfügen</i>. Die Temp-Variable legst du vorher in der Schnittstelle unter Temp an, Datentyp Bool.","SCL-Netzwerk: <code>#tempBathReadyScl := (#temperatureOk AND #levelOk) OR #lampTest;</code> Im Programmstatus steht rechts neben der Zeile der Wert. Er muss immer zum Ausgang der ODER-Box von −PF2 passen."]},
 lf:[["Warum bildest du „Füllhöhe unterschritten“ mit einer Negation im Programm, statt den Sensor −BG10 als Öffner zu verdrahten? Was ginge dabei verloren?",[2]],["Welche Verknüpfung entsteht, wenn du in KOP zwei Kontakte in Reihe und wenn du sie parallel schaltest?",[0]],["Warum ist XOR für die Endlagen eines Zylinders eine sinnvolle Plausibilitätsprüfung? Welcher Zustand ist während der Bewegung kurz zulässig?",[1]]],
 lfk:["Was zeigt die Querverweisliste für −PF2? Was würde sie zeigen, wenn du den Lampentest als zweite Zuweisung dahinter geschrieben hättest, und welche Zuweisung würde dann gewinnen?"],
 pr:[["−BG9 oder −BG10 im Signalmonitor auf 0 forcen → −PF2 aus",[0,1]],["−BG10 auf 0 forcen → −PF3 leuchtet",[2]],["−SF4 gedrückt → −PF1 bis −PF4 an, losgelassen → wieder der echte Zustand",[0]],["Funktionstabelle XOR vollständig; −BG14 und −BG15 gemeinsam auf 1 forcen → stopperPlausible = 0 (Programmstatus)",[1]],["Querverweisliste: −PF1 bis −PF4 haben je genau eine schreibende Stelle, nämlich beim Aufruf von Indication im OB1",[3]],["Bausteinkopf ausgefüllt, jedes Netzwerk mit Titel und Kommentar, im Code nur symbolische Namen",[0]]],
 ergebnis:[{n:"FC Indication", a:"neu", h:"Leuchtenlogik, schreibt über seine Outputs −PF1 (nur Lampentest), −PF2, −PF3, −PF4"},{n:"OB1 Main", a:"erweitert", h:"ruft Indication auf und verschaltet die PLC-Variablen"},{n:"Funktionstabelle Plausibilität −MM5", a:"neu"}, {n:"Ausgangsliste", a:"neu", h:"jeder Ausgang mit seiner einzigen Schreibstelle, wächst mit jeder Übung"}],
 plus:"Bilde zusätzlich die Endlagen-Plausibilität für den Tauchzylinder −MM2 (−BG3, −BG4) als weiteren Output. Beobachte im Programmstatus während des automatischen Zyklus, wie oft und wie lange beide Endlagen 0 melden, und notiere die längste Dauer.",
 tpls:[
 {id:"xor", fw:[11,3], felder:["01","01"], cap:"Funktionstabelle Endlagen-Plausibilität −MM5", phase:2, head:["−BG14 zu","−BG15 offen","plausibel (XOR)","Störung"], rows:[["0","0"],["0","1"],["1","0"],["1","1"]], inputs:2},
 {id:"leuchten", fw:[3,5], felder:["text","text","text","text"], cap:"Bedingungen der Meldeleuchten als Satz", phase:2, head:["Ausgang","Bedeutung","leuchtet, wenn … (ganzer Satz)","beteiligte Eingänge","abgefragt auf 1 oder 0","Verknüpfung"], muster:["−PF3","Füllhöhe unterschritten","−PF3 leuchtet, wenn die Füllhöhe nicht in Ordnung ist","−BG10","0","NICHT, ODER Lampentest"], rows:[["−PF1","nur Lampentest (vorerst)"],["−PF2","Bad bereit"],["−PF4","Korb vorhanden"],["stopperPlausible","Endlagen −MM5 plausibel"]], inputs:4},
 {id:"schnitt", fw:[2,9], felder:["text","text","text"], cap:"Schnittstelle FC Indication", phase:2, head:["Bereich","PLC-Variable","Parametername (deine Wahl)","Datentyp","Bedeutung"], muster:["Input","Beispiel: SF1_Start","startButton","Bool","1 = START gedrückt"], rows:[["Input","BG9_Temperatur"],["Input","BG10_Fuellhoehe"],["Input","BG40_Korb_am_Anschlag"],["Input","BG14_MM5_zu"],["Input","BG15_MM5_offen"],["Input","SF4_Quittieren"],["Output","PF1_Automatik"],["Output","PF2_Temperatur"],["Output","PF3_Fuellhoehe"],["Output","PF4_Korb"],["Output","keine (nur beobachten)"]], inputs:3},
 {id:"schreib", fw:[13,8,7], felder:["text","text","janein"], cap:"Ausgangsliste", phase:4, head:["Ausgang","Bedeutung","ab Übung","schreibt (Baustein, einzige Stelle)","Bedingung oder Befehl kommt von","in der Querverweisliste geprüft"], muster:["Beispiel aus L13: −PF7","Handbetrieb","L13","FB Manual, Aufruf im OB1","−SA3 auf HAND","ja, eine Schreibstelle"], rows:[["−PF1","Lampentest","L02"],["−PF2","Bad bereit","L02"],["−PF3","Füllhöhe unterschritten","L02"],["−PF4","Korb vorhanden","L02"]], inputs:3},
 {id:"fupkop", fw:[4,14,12], felder:["text","text","text","text"], cap:"Vergleich FUP, KOP und SCL", phase:4, head:["Netzwerk","Darstellung in FUP","Darstellung in KOP","Zeile in SCL","Was fällt dir auf?"], muster:["−PF1 (nur Lampentest)","Zuweisungsbox, Eingang −SF4","ein Schließerkontakt −SF4 vor der Spule −PF1","#lampOperation := #lampTest;","gleiche Logik, andere Darstellung"], rows:[["−PF2 Bad bereit (UND)"],["−PF3 Füllhöhe (NICHT)"],["−PF4 Korb vorhanden mit Lampentest (ODER)"],["stopperPlausible (XOR)"]], inputs:4}
]
}
