// Kurz-Checks der Übung L03: ein = Eingangs-Check in Phase 1 (nur Vorwissen aus den vor-Übungen), aus = Abschluss-Check in Phase 6.
// Frage: [Frage, [Antwort 0, Antwort 1, Antwort 2], Index der richtigen Antwort, Begründung]
{ein:[
  ["Ein FC wird im OB1 aufgerufen. Woher bekommt er seine Signale?",["über seine Inputs, verschaltet beim Aufruf im OB1","er liest sie selbst aus dem Signalmonitor","aus einem Merker"],0,"So hast du Indication in L02 angeschlossen."],
  ["Ein Ausgang wird an zwei Stellen im Programm geschrieben. Welcher Wert erreicht die Leuchte?",["der Wert der letzten Zuweisung im Zyklus","der Wert der ersten Zuweisung","beide abwechselnd"],0,"Am Zyklusende wird das Prozessabbild der Ausgänge ausgegeben (L02)."]],
 aus:[
  ["START und STOP wirken gleichzeitig. Was muss die Anlage tun?",["einschalten","ausgeschaltet bleiben (rücksetzdominant)","den letzten Zustand halten"],1,"Bei Maschinen hat Aus Vorrang: in TIA die Box SR mit R1 bzw. STOP in Reihe vor der Selbsthaltung."],
  ["Neue Stilregel: Wo speicherst du die Betriebsbereitschaft?",["als statische Variable im FB (Instanz-DB)","in einem globalen Merker","in einer temporären Variable"],0,"Statische Variablen liegen im Instanz-DB und behalten ihren Wert über Zyklen. Temporäre Variablen liegen nur während des Aufrufs im Lokaldatenstack."],
  ["Neue Stilregel: Welcher Name passt zu einer R_TRIG-Multiinstanz für den START-Taster?",["#instStartTrig","#Start_Flanke","#statStart"],0,"Präfix inst für Instanzen im FB, englisch, camelCase."],
  ["Neue Stilregel: Warum rufst du R_TRIG als Multiinstanz auf?",["Seine Daten liegen dann im Instanz-DB deines FB, es entstehen keine verstreuten DBs.","Weil R_TRIG sonst nicht flankengesteuert ist.","Weil Multiinstanzen schneller sind."],0,"Der FB trägt alles in sich, was er braucht."],
  ["Neue Stilregel: Im FB Operation steht #instStartTrig(CLK := \"SF1_Start\"). Was ist falsch?",["Der FB greift direkt auf eine PLC-Variable zu, statt sie über einen Input zu bekommen.","Nichts, das ist richtig.","R_TRIG braucht einen Merker."],0,"Richtig ist ein Input start, der im OB1 mit \"SF1_Start\" verschaltet wird."],
  ["Welche Flankenanweisungen gibt es in SCL?",["nur R_TRIG und F_TRIG","P, N, P_TRIG und R_TRIG","keine, Flanken gibt es nur in KOP und FUP"],0,"Die anderen bildest du in SCL von Hand: #tempPulse := #signal AND NOT #statSignalOld; #statSignalOld := #signal;"],
  ["Zwei P-Boxen verwenden denselben Flankenmerker. Was sagt die TIA-Hilfe dazu?",["Nicht erlaubt: Das Bit wird überschrieben, das Ergebnis ist nicht mehr eindeutig.","Erlaubt, wenn beide dasselbe Signal abfragen.","Erlaubt, TIA legt automatisch zwei Bits an."],0,"Jede Flanke bekommt ihren eigenen Flankenmerker, im FB als statische Variable."],
  ["Worin unterscheidet sich P_TRIG von R_TRIG?",["P_TRIG speichert den Vorzustand in einem Flankenmerker, R_TRIG ist ein FB und speichert ihn in seiner Instanz.","P_TRIG erkennt fallende Flanken.","Es gibt keinen Unterschied, nur den Namen."],0,"Beide liefern an Q einen Zyklus lang 1. Für Flanken im FB nimmst du R_TRIG als Multiinstanz."],
  ["Was bewirkt --(P)-- (Operand bei positiver Signalflanke setzen)?",["Wechselt das VKE vor der Spule von 0 auf 1, ist der Operand über der Spule einen Zyklus lang 1.","Der Operand wird dauerhaft auf 1 gesetzt.","Die Spule fragt einen einzelnen Operanden auf eine Flanke ab."],0,"Die Spule wertet das VKE der ganzen Verknüpfung davor aus, unter ihr steht ein Flankenmerker."]]}
