// Stammdaten der Übung L28 (Felder siehe uebungVorlage.md). Langtexte in texte.json, Kurz-Checks in quiz.js.
{id:"L28",
 st:3,
 t:"Analogwert, Hysterese, Plausibilität",
 sub:"Zwei Messungen gegeneinander prüfen",
 ue:3,
 vor:"L27",
 repo:"22",
 bild:["14-kuehlwassertank.jpg","Radarsensor −BL2 im Tankdeckel"],
 typ:"programmieren",
 einst:"Wie L27: <i>Kühlwassertank: Nachspeisung = SPS regelt</i>, <i>Band, Anschlag, Vereinzeler = SPS steuert</i> (dein Förderprogramm sprüht am Kühlplatz), <i>Verzinnen: Portal −MM1…−MM4 = Portal automatisch</i>. Den Ablasshahn nutzt du als Störgröße.",
 ziele:["einen Analogwert in Prozent umrechnen und Werte außerhalb des Nennbereichs bewusst behandeln","eine Zweipunktregelung mit Hysterese am stetigen Messwert bauen und sie der Grenzschalter-Logik unterordnen","zwei unabhängige Messungen gegeneinander auf Plausibilität prüfen"],
 sig:"BL2 BG38 BG39 MB17 SF4",
 sit:"Der Radarsensor −BL2 liefert den Füllstand stetig. Damit soll dein Programm den Pegel in einem engeren Band halten. Die Grenzschalter bleiben als unabhängige Sicherheitsebene.",
 plan:["Lege in der Vorlage „Festlegungen zu −BL2“ fest und begründe: Wie behandelt dein Programm Rohwerte von −BL2 außerhalb 0 bis 27648 (begrenzen oder als Fehler werten)? Wie lang ist die Verzögerungszeit der Plausibilitätsprüfung?","Ergänze die Vorlage „Schaltpunkte am Kühlwassertank“ aus L27 um die neuen Schaltpunkte 60 % und 80 % und die Plausibilitätsgrenzen 20 % und 95 %."],
 auf:["Erweitere deinen FB <code>TankLevel</code> aus L27: Rechne −BL2 (%IW72) mit <code>NORM_X</code> und <code>SCALE_X</code> in Prozent (REAL) um und setze deine Festlegung für Werte außerhalb des Nennbereichs um.","Baue eine Testumschaltung für −BL2 ein (wie in L11 und L25), damit du falsche Messwerte vorgeben kannst.","Programmiere die Zweipunktregelung mit Hysterese: −MB17 auf, wenn der Pegel unter 60 % sinkt, zu, wenn er 80 % überschreitet.","Ordne die Grenzschalter-Logik aus L27 dem Analogwert über: Meldet −BG39 „voll“ oder Drahtbruch, wird nicht nachgespeist, egal was −BL2 anzeigt. −QA7 bleibt nur bei bedecktem −BG38 frei. Trage die neue Bedingung von −MB17 in deine „Ausgangsliste“ ein.","Plausibilität: −BL2 über 95 % bei freiem −BG39 oder unter 20 % bei bedecktem −BG38, länger als deine Verzögerungszeit → Meldung „Messung gestört“, Rückfall auf die Grenzschalter-Logik aus L27, Quittieren mit −SF4.","Zeichne Pegel und −MB17 über mehrere Schaltspiele mit einem Trace auf (wie in L25)."],
 hilfe:{"0":["Was rechnet NORM_X mit einem Rohwert über 27648, und willst du dieses Ergebnis weiterverwenden?","Prüfe zuerst den Rohwert. Liegt er im Nennbereich, rechnest du um. Liegt er darüber oder darunter, entscheidest du: begrenzen (LIMIT) oder Messung ungültig setzen.","<code>#statLevelValid := #tempRaw >= 0 AND #tempRaw <= #RAW_MAX;</code> <code>#tempNorm := NORM_X(MIN := 0, VALUE := #tempRaw, MAX := #RAW_MAX);</code> <code>#statLevel := SCALE_X(MIN := 0.0, VALUE := #tempNorm, MAX := #LEVEL_MAX);</code>"], "2":["Was soll −MB17 tun, wenn der Pegel genau zwischen 60 und 80 % steht?","Wie in L27 brauchst du ein Gedächtnis: Setzen unter 60 %, rücksetzen über 80 %, dazwischen bleibt der Zustand. Die Schaltpunkte sind lokale Konstanten.","<code>IF #statLevel < #LEVEL_ON THEN #statRefill := TRUE; END_IF;</code> <code>IF #statLevel > #LEVEL_OFF THEN #statRefill := FALSE; END_IF;</code>"], "3":["Welche Information ist vertrauenswürdiger, wenn Grenzschalter und Radar sich widersprechen?","Bilde zuerst den Wunsch der Analogregelung und verknüpfe danach mit UND die Sperre aus den Grenzschaltern. Die Sperre steht als Letztes und hat damit Vorrang.","<code>#refillCmd := ((NOT #statMeasFault AND #statRefill) OR (#statMeasFault AND #statRefillLimit)) AND #maxFree AND NOT #statWireBreak;</code> Dabei ist <code>#statRefillLimit</code> deine Grenzschalter-Logik aus L27 als Rückfallebene. Ist die Messung ungültig (<code>#statLevelValid</code> = 0), setzt du <code>#statMeasFault</code> ebenfalls."], "4":["Wie schnell kann sich der Pegel höchstens ändern, und wie lange brauchen −BL2 und die Grenzschalter, um das zu melden?","Bilde den Widerspruch als Bool und lasse ihn durch einen TON (Multiinstanz) laufen. Erst wenn er länger als deine Verzögerungszeit ansteht, setzt du die gespeicherte Meldung. Quittieren: Flanke an −SF4 und Widerspruch weg.","<code>#tempConflict := (#statLevel > #PLAUS_HIGH AND #maxFree) OR (#statLevel < #PLAUS_LOW AND #minCovered);</code> <code>#instPlausTimer(IN := #tempConflict, PT := #PLAUS_DELAY);</code> <code>IF #instPlausTimer.Q THEN #statMeasFault := TRUE; END_IF;</code>"]},
 lf:[["Warum braucht die Zweipunktregelung eine Hysterese? Was passiert ohne?",[1]],["Warum ist eine Ansprechverzögerung bei der Plausibilitätsprüfung sinnvoll, und was passiert, wenn sie zu kurz oder zu lang ist?",[2]],["Ein eingefrorener Messwert liegt im gültigen Bereich. Wie erkennt dein Programm ihn trotzdem?",[2]],["Ein Rohwert von 28500 kommt an. Was spricht fürs Begrenzen, was dafür, ihn als Fehler zu werten?",[0]]],
 lfk:["Wie viele Schaltspiele hat −MB17 in deinem Trace in 10 Minuten gemacht, und wie stark schwankt der Pegel jetzt im Vergleich zu L27?"],
 pr:[["Schaltpunkte 60 % und 80 % im Trace nachgewiesen",[1]],["−BG39 auf 0 forcen bei Pegel um 50 % → keine Nachspeisung, obwohl −BL2 unter 60 % liegt",[1]],["Testwert für −BL2 = 30000 (über dem Nennbereich) → Verhalten wie in deiner Planung festgelegt, Meldung",[0]],["Testwert 27000 (rund 98 %) bei freiem −BG39 → nach der Verzögerungszeit „Messung gestört“, die Nachspeisung arbeitet mit der Grenzschalter-Logik weiter",[2]],["Normalbetrieb mit Ablasshahn und Sprühkühlung über mehrere Schaltspiele: kein Fehlalarm, keine Meldung „Kühlwassertank läuft über“ oder „Umwälzpumpe −MA3 läuft trocken“",[1,2]]],
 plus:"Mache die Schaltpunkte 60 % und 80 % zu Eingängen von <code>TankLevel</code>. Prüfe im Programm, dass der Einschaltpunkt immer mindestens 10 % unter dem Ausschaltpunkt liegt und beide mit Abstand zwischen den Grenzschaltern bleiben. Sonst gelten die Konstanten weiter, und dein Programm meldet die falsche Eingabe.",
 ergebnis:[{n:"FB TankLevel", a:"erweitert", h:"−BL2 in %, Testumschaltung, Hysterese 60/80 %, Plausibilität, Rückfall auf L27"},{n:"Trace Kühlwassertank", a:"neu", h:"Pegel und −MB17 über mehrere Schaltspiele"}, {n:"Ausgangsliste", a:"erweitert", h:"neue Zeilen: −MB17"}, {n:"Schaltpunkte am Kühlwassertank", a:"erweitert", h:"neue Zeilen: L28: Pegel fällt unter 60 %, L28: Pegel steigt über 80 %, L28: −BL2 über 95 %, −BG39 meldet frei, L28: −BL2 unter 20 %, −BG38 meldet bedeckt"}],
 tpls:[
 {id:"festlegung", cap:"Festlegungen zu −BL2", phase:2, head:["Fall","Festlegung","Begründung"], muster:["Beispiel L25: −BT2 außerhalb 0 bis 27648","Messung ungültig, Korb wird nicht freigegeben, Meldung","Ein falscher Wert darf nie freigeben"], rows:[["Rohwert von −BL2 über 27648"],["Rohwert von −BL2 unter 0"],["Verzögerungszeit der Plausibilitätsprüfung"]], inputs:2},
 {id:"schaltpunkte", erweitert:"L27:schaltpunkte", cap:"Schaltpunkte am Kühlwassertank", phase:2, head:["Pegel bzw. Lage","−BG38","−BG39","−MB17"], muster:["Beispiel: Tank voll, 95 %","1 (Gabel bedeckt)","0 (Gabel bedeckt)","zu"], rows:[["L28: Pegel fällt unter 60 %"],["L28: Pegel steigt über 80 %"],["L28: −BL2 über 95 %, −BG39 meldet frei"],["L28: −BL2 unter 20 %, −BG38 meldet bedeckt"]], inputs:3},
 {id:"schreib", erweitert:"L02:schreib", cap:"Ausgangsliste", phase:4, head:["Ausgang","Bedeutung","ab Übung","schreibt (Baustein, einzige Stelle)","Bedingung oder Befehl kommt von","in der Querverweisliste geprüft"], muster:["−PF2","Bad bereit","L02","FB Indication, Aufruf im OB1","−BG9 UND −BG10, ODER Lampentest −SF4","ja, eine Schreibstelle"], rows:[["−MB17","Nachspeisen, jetzt mit Hysterese 60/80 % am Analogwert −BL2, ersetzt die Zeile aus L27","L28"]], inputs:3}
]
,
 bezug:[
 {von:"L27", id:"pegel", phase:5, wozu:"Vergleiche die Schwankung des Pegels mit deinen Werten aus L27."}
]
}
