// Kurz-Checks der Übung L12: ein = Eingangs-Check in Phase 1 (nur Vorwissen aus den vor-Übungen), aus = Abschluss-Check in Phase 6.
// Frage: [Frage, [Antwort 0, Antwort 1, Antwort 2], Index der richtigen Antwort, Begründung]
{ein:[
  ["−PF3 soll leuchten, wenn …",["die Füllhöhe ausreicht.","die Füllhöhe unterschritten ist.","die Temperatur erreicht ist."],1,"−BG10 meldet 1 = in Ordnung. Die Leuchte zeigt den Mangel, also die Negation (L02)."],
  ["Wie kommt ein Ergebnis von einem Baustein zu einem anderen?",["Der OB1 legt den Output in PlantData ab und verschaltet ihn mit dem Input des anderen Bausteins.","Der andere Baustein liest den Instanz-DB.","Über einen Merker."],0,"So hast du es in L05 eingeführt."]],
 aus:[
  ["StartRelease ist ein FC. Was passiert mit seinen Daten, wenn der Aufruf zu Ende ist, und warum passt das hier?",["Die Daten lagen nur in einem temporären Speicherbereich, der nach dem Aufruf freigegeben wird. StartRelease braucht keine Werte aus dem letzten Zyklus, deshalb passt ein FC.","Die Daten bleiben im Instanz-DB des FC erhalten. Deshalb kann er sich alles bis zum nächsten Zyklus merken.","Die Daten werden in Merkern gesichert und im nächsten Zyklus wieder geladen."],0,"Ein FC hat keinen Instanz-DB und keinen Bereich Static. Beim Aufruf bekommt er nur einen temporären Speicherbereich (Lokaldatenstack), und der wird nach dem Aufruf wieder freigegeben. Für eine reine Verknüpfung der aktuellen Sensorwerte genügt das. Muss sich ein Baustein etwas merken, nimmst du einen FB."],
  ["Welche Endlagen bilden die Grundstellung des Portals?",["−BG1, −BG3, −BG5, −BG7","−BG2, −BG4, −BG5, −BG8","−BG2, −BG3, −BG6, −BG8"],1,"−MM1 gelöst, −MM2 unten, −MM3 über dem Band, −MM4 abgedeckt."],
  ["Ein Endlagensensor der Grundstellung hat Drahtbruch. Was zeigt homePosition?",["0, die Anlage startet nicht","1, der Fehler bleibt unbemerkt","einen zufälligen Wert"],0,"Der Sensor liefert 0, also fehlt eine UND-Bedingung. Das ist die sichere Seite."]]}
