// Stammdaten der Übung L12 (Felder siehe uebungVorlage.md). Langtexte in texte.json, Kurz-Checks in quiz.js.
{id:"L12", st:1, t:"Grundstellung und Freigabe", sub:"Ein FC für die Startfreigabe, der Schnitt zum Anlagenprogramm", ue:3, vor:"L11", repo:"1", bild:["02-bedienpult.jpg","Bedienpult mit Meldeleuchten −PF1 bis −PF4"], typ:"programmieren",
 einst:"Übungsumfang: <i>Verzinnen: Portal −MM1…−MM4</i> = <i>SPS steuert</i>, <i>Band, Anschlag, Vereinzeler</i> = <i>Bandmodul automatisch</i>, <i>Zinnbad: Temperatur und Füllstand</i> = <i>Regler automatisch</i>, <i>Kühlwassertank: Nachspeisung</i> = <i>Niveauregler automatisch</i>. Quelle der Ausgänge unter <i>Verbindung</i>: <i>PLCSIM Advanced</i>. Dein Programm schreibt noch keine Ventile. Schalte erst auf <i>SPS steuert</i>, wenn −BG2, −BG4, −BG5 und −BG8 melden, oder setze danach die Anlage unter <i>Verbindung</i> zurück. Dann bleibt das Portal in Grundstellung stehen. So kannst du jede Endlage einzeln forcen, ohne dass eine Portalsteuerung darauf reagiert. Nur für die letzte Beobachtung stellst du kurz auf <i>Portal automatisch</i>.",
 ziele:["die Grundstellung über gemeldete Endlagen abfragen","Freigabe und Startbedingung unterscheiden und begründen","eine Freigabe so bilden, dass jeder Sensor- oder Leitungsfehler auf der sicheren Seite liegt"],
 sig:"BG2 BG4 BG5 BG8 BG9 BG10 KF2 BG40 PF2 PF3 PF4",
 sit:"Die Anlage darf nur starten, wenn das Portal in Grundstellung steht, das Zinn heiß genug ist, genug Zinn im Bad ist und das Sicherheitsrelais freigibt. Ab dieser Übung entsteht das Programm, das die Anlage später wirklich steuert.",
 plan:["Fülle die Vorlage „Verkürzte Funktionstabelle der Startfreigabe“ aus: In jeder Zeile fehlt genau eine Bedingung. Zeichne die Verknüpfung als FUP-Skizze.","Lege die Schnittstelle von StartRelease in der Vorlage „Schnittstelle FC StartRelease“ fest: zu jedem Signal die PLC-Variable bzw. den Platz in PlantData, deinen Parameternamen und den Datentyp. Die Beispielzeile gehört nicht in deinen FC."],
 auf:["Nimm den Aufruf von <code>Operation</code> aus dem OB1 und verschiebe den FB in eine Bausteingruppe <code>Uebungen</code>. Mache dasselbe mit den Übungsbausteinen <code>TypeLab</code> (L07), <code>BitPattern</code> (L08), <code>BcdLab</code> (L09) und <code>ProductionStats</code> (L10), und lege auch den Übungs-DB <code>NumberLab</code> (L06) in die Gruppe. Nimm in <code>Indication</code> die Zuweisungen für −PF1 und −PF5 und die Inputs ready und msgLightCurtain heraus. Nimm dort auch den Lauflicht-Test (Inputs runLightMode und runLightPattern, L08) und das Blinken von −PF4 bei fast vollem Puffer (Input bufferAlmostFull, L10) aus den Zuweisungen von −PF2 bis −PF4 heraus. Prüfe in der Querverweisliste, dass −PF1 und −PF5 danach keine Schreibstelle mehr haben.","Lege einen FC <code>StartRelease</code> (Startfreigabe) mit Bausteinkopf an und rufe ihn im OB1 auf. Er bekommt alle Signale über Inputs, seine Outputs legt der OB1 in <code>PlantData</code> ab.","Bilde den Output homePosition: 1 nur, wenn −MM1 gelöst, −MM2 abgesenkt, −MM3 über dem Band und −MM4 Bad abgedeckt melden. Die Sensoren findest du in deiner Vorlage „Grundstellung: welche Endlagen melden 1?“ aus L01.","Bilde den Output readyToStart aus Grundstellung, −BG9, −BG10 und −KF2, ohne Speicher. Notiere, ob −BG40 in die Freigabe gehört.","Teste jede Bedingung einzeln: eine Endlage oder ein Signal im Signalmonitor auf 0 forcen, homePosition und readyToStart in PlantData beobachten, zurücknehmen.","Lösche ready, msgLightCurtain, runLightMode, runLightPattern und bufferAlmostFull aus PlantData. bathTempOk und tinLevelLow aus L11 bleiben, denn BathMonitor läuft weiter. Ergänze die Vorlagen „Ausgangsliste“ und „Variablenliste PlantData“ und prüfe in der Querverweisliste: −PF2 bis −PF4 schreibt nur Indication, jede Variable in PlantData hat genau einen Schreiber."],
 hilfe:{0:["Welche Leuchten hat Operation bisher über Indication mit Bedingungen versorgt? Was passiert mit den Inputs von Indication, wenn niemand sie mehr verschaltet? Welche Inputs von Indication kamen von den Übungsbausteinen aus L08 und L10?","Rechtsklick auf Programmbausteine, Neue Gruppe Uebungen, Operation hineinziehen. Im OB1 das Netzwerk mit dem Aufruf löschen. Genauso TypeLab, BitPattern, BcdLab und ProductionStats, dazu den DB NumberLab in die Gruppe ziehen. In Indication die Zuweisungen von lampOperation und lampAck sowie die Inputs ready und msgLightCurtain löschen. In den Zuweisungen von −PF2 bis −PF4 die Umschaltung auf das Lauflicht (runLightMode, runLightPattern) und bei −PF4 das Pufferblinken (bufferAlmostFull) herausnehmen und diese Inputs löschen, danach den Aufruf im OB1 aktualisieren.","Querverweisliste von \"PF1_Automatik\" und \"PF5_Quittieren\": keine schreibende Stelle mehr. \"PF2_Temperatur\" bis \"PF4_Korb\": je eine Stelle beim Aufruf von InstIndication. Der Lampentest wirkt jetzt auf −PF2 bis −PF4."], 3:["Welche Bedingungen müssen alle gleichzeitig erfüllt sein? Muss sich der FC dafür etwas merken?","Eine einzige UND-Verknüpfung aus homePosition, temperatureOk, levelOk und safetyOk genügt. Kein Speicher, kein IF ohne ELSE.","<code>#homePosition := #mm1Released AND #mm2Down AND #mm3AtConveyor AND #mm4Closed; #readyToStart := #homePosition AND #temperatureOk AND #levelOk AND #safetyOk;</code> Beide Outputs werden in jedem Aufruf geschrieben. −BG40 gehört nicht hinein: Der Korb wechselt im Zyklus planmäßig, er ist eine Startbedingung des ersten Schritts (L17)."]},
 lf:[["Ein Endlagensensor der Grundstellung hat Drahtbruch. Was zeigt homePosition, und warum ist das die sichere Seite?",[0,2]],["Welche Bedingung gehört in die Freigabe, welche nur in die Startbedingung des ersten Schritts?",[1]],["−PF2 nutzt seit L11 den Temperaturbereich, die Freigabe den Schalter −BG9. Warum ist es sinnvoll, dass die Freigabe auch an einem Schalter hängt, der ohne dein Rechenprogramm meldet?",[1,2]]],
 lfk:["Schalte zum Schluss kurz auf „Portal automatisch“ und beobachte homePosition während eines ganzen Zyklus. Wann fällt sie weg, wann kommt sie wieder? Was bedeutet das für eine Freigabe, die während des Zyklus anstehen muss?"],
 pr:[["Jede Grundstellungs-Endlage einzeln auf 0 forcen → homePosition = 0",[0,2]],["−BG9 auf 0 forcen → −PF2 aus und readyToStart = 0",[1,2]],["−BG10 auf 0 forcen → −PF3 blinkt und readyToStart = 0",[2]],["Not-Halt betätigt → readyToStart = 0",[1,2]],["Operation, TypeLab, BitPattern, BcdLab und ProductionStats werden nicht mehr aufgerufen; ready, msgLightCurtain, runLightMode, runLightPattern und bufferAlmostFull aus PlantData gelöscht; Querverweisliste: −PF1 und −PF5 ohne Schreibstelle, −PF2 bis −PF4 je eine (Indication), jede Variable in PlantData mit genau einem Schreiber, darunter homePosition und readyToStart in PlantData",[0]]],
 ergebnis:[{n:"FC StartRelease", a:"neu", h:"liefert homePosition und readyToStart über PlantData (gebraucht in L15 und L17)"},{n:"FB Indication", a:"umgebaut", h:"schreibt nur noch −PF2, −PF3, −PF4, ohne Lauflicht-Test und Pufferblinken"},{n:"FB Operation, FB TypeLab, FB BitPattern, FB BcdLab, FB ProductionStats, DB NumberLab", a:"umgebaut", h:"aus dem OB1 genommen, liegen in der Gruppe Uebungen"},{n:"FB BathMonitor, FB Counting", a:"übernommen", h:"laufen weiter, PlantData ohne die Variablen der Übungsbausteine"}, {n:"globaler DB PlantData", a:"erweitert", h:"neue Einträge in der Variablenliste PlantData: Grundstellung, Startfreigabe, gelöscht: ready und msgLightCurtain …"}, {n:"Ausgangsliste", a:"erweitert", h:"neue Zeilen: −PF1, −PF2, −PF3, −PF4, −PF5"}],
 plus:"Zeige in einer Beobachtungstabelle, welche Bedingung von readyToStart gerade fehlt: Gib je Bedingung einen Bool-Output aus StartRelease (z. B. missingHome, missingTemperature) und lege ihn im OB1 in PlantData ab. So findet der Bediener den Grund ohne Programmiergerät.",
 tpls:[
 {id:"freigabe", cap:"Verkürzte Funktionstabelle der Startfreigabe", phase:2, head:["Fall","homePosition","−BG9","−BG10","−KF2","readyToStart"], muster:["alle Bedingungen erfüllt","1","1","1","1","1"], rows:[["Grundstellung fehlt (eine Endlage 0)"],["Temperatur nicht erreicht"],["Füllhöhe zu gering"],["Not-Halt oder Schutzfeld (−KF2 = 0)"]], inputs:5},
 {id:"schnitt", cap:"Schnittstelle FC StartRelease", phase:2, head:["Bereich","Signal","PLC-Variable bzw. Platz in PlantData","Parametername (deine Wahl)","Datentyp"], muster:["Input","Beispiel: Freigabe Lichtvorhang −BG20","BG20_Lichtvorhang_frei","lightCurtainFree","Bool"], rows:[["Input","Temperatur −BG9"],["Input","−MM1 gelöst"],["Input","−MM2 abgesenkt"],["Input","−MM3 über dem Band"],["Input","−MM4 Bad abgedeckt"],["Input","Füllhöhe −BG10"],["Input","Freigabe −KF2"],["Output","Grundstellung"],["Output","Startfreigabe"]], inputs:3},
 {id:"schreib", erweitert:"L02:schreib", cap:"Ausgangsliste", phase:4, head:["Ausgang","Bedeutung","ab Übung","schreibt (Baustein, einzige Stelle)","Bedingung oder Befehl kommt von","in der Querverweisliste geprüft"], muster:["−PF2","Bad bereit","L02","FB Indication (bis L03 FC), Aufruf im OB1","−BG9 UND −BG10, ODER Lampentest −SF4","ja, eine Schreibstelle"], rows:[["−PF1","Betriebsbereitschaft (bis L15 dunkel)","L12"],["−PF2","Bad bereit wie L11, ohne Lauflicht-Test","L12"],["−PF3","Füllhöhe und Wartungshinweis wie L11, ohne Lauflicht-Test","L12"],["−PF4","Korb vorhanden, 5 s Nachleuchten (L04), ohne Lauflicht-Test und Pufferblinken","L12"],["−PF5","Meldung Lichtvorhang (bis L19 dunkel)","L12"]], inputs:3},
 {id:"plantdata", erweitert:"L05:plantdata", cap:"Variablenliste PlantData", phase:4, head:["Inhalt","ab Übung","Variablenname","Datentyp","remanent (ja oder nein, warum)","schreibt (Baustein, über den OB1)","liest"], muster:["Betriebsbereitschaft","L05","ready","Bool","nein, nach dem Neustart muss neu gestartet werden","Operation (Output ready)","Indication"], rows:[["Grundstellung","L12"],["Startfreigabe","L12"],["gelöscht: ready und msgLightCurtain","L12"],["gelöscht: runLightMode, runLightPattern (L08) und bufferAlmostFull (L10)","L12"]], inputs:5}
]
,
 bezug:[
 {von:"L01", id:"grundst", phase:2, wozu:"Welche Endlagen in Grundstellung 1 melden, hast du in L01 festgehalten."}
]
}
