// Stammdaten der Übung L36 (Felder siehe uebungVorlage.md). Langtexte in texte.json, Kurz-Checks in quiz.js.
{id:"L36",
 st:4,
 t:"Fehlersuche und Taktzeit",
 sub:"Systematisch eingrenzen, messbar verbessern",
 ue:4,
 vor:"L22, L35",
 repo:"15, 16",
 bild:["10-drosselventile.jpg","Drosselrückschlagventile: jede Richtung einzeln einstellbar"],
 typ:"auslegen",
 einst:"Teil A: dein gesamter Stand aus den bisherigen Übungen. Übungsumfang: <i>Verzinnen: Portal −MM1…−MM4 = SPS steuert</i>, <i>Band, Anschlag, Vereinzeler = SPS steuert</i>, <i>Zinnbad: Temperatur und Füllstand = SPS regelt</i>, <i>Kühlwassertank: Nachspeisung = SPS regelt</i>, unter <i>Antriebe</i> wie in L32 bis L35. Die Störfälle löst die Lehrkraft aus; du änderst den Übungsumfang nicht. Teil B: <i>Verzinnen: Portal −MM1…−MM4 = SPS steuert</i> genügt, alles andere darf automatisch laufen.",
 ziele:["eine Fehlersuchstrategie anwenden (Symptom, Vermutung, Prüfschritt, Ursache)","Ergebnisse mit Messungen belegen","eine Taktzeit unter Randbedingungen optimieren, ohne die Mechanik stärker zu belasten"],
 sig:"TA2 BG20 BG9 KF2 BG1",
 sit:"<b>Teil A:</b> Die Lehrkraft löst verdeckt Störungen aus, z. B. eine Umrichterstörung, eine Person im Lichtvorhang, ein abkühlendes Zinnbad, eine zugedrehte Drossel oder einen geforcten Sensor. <b>Teil B:</b> Der Betreiber will mehr Körbe pro Stunde, ohne die Mechanik zu gefährden.",
 plan:["Lege vor Teil A dein Vorgehen fest: Welche Werkzeuge (Ereignisliste, Signalmonitor, Beobachtungstabelle, Programmstatus, Weg-Zeit-Diagramm, Diagnosepuffer) nutzt du in welcher Reihenfolge, und warum?","Zerlege vor Teil B den Zyklus deiner Schrittkette in Bewegungszeiten, Wartezeiten und feste Prozesszeiten (Fahrzeitentabelle aus L22, Tauch- und Abtropfzeit) und schätze, wie viel Einsparung überhaupt möglich ist. Trage die Zerlegung und deine Schätzung in die Vorlage „Zyklus zerlegen“ ein."],
 auf:["Teil A: Führe für jeden Störfall die Vorlage „Fehlerprotokoll“: Symptom, Vermutung, Prüfschritt, Ursache, Behebung, Zeit.","Notiere zu jedem Störfall, ob dein Programm ihn sauber gemeldet hat. Fehlende oder irreführende Meldungen schreibst du als Verbesserungsvorschlag auf.","Teil B: Miss die aktuelle Taktzeit über mehrere Zyklen im Dauerbetrieb. Setze im Weg-Zeit-Diagramm die Messlinien von einer Endlagenflanke (z. B. −MM1 erreicht „eingehängt“, −BG1) bis zur selben Flanke im nächsten Zyklus. Trage Taktzeit und Drosselwerte in die Vorlage „Messprotokoll Taktzeit“ ein.","Nimm deine Fahrzeitentabelle aus L22 als Ausgangswert. Stelle die Drosseln so ein, dass die Taktzeit sinkt, ohne dass sich Bewegungen überschneiden. Öffne keine Drossel über 80 % ohne schriftliche Begründung. Tauch- und Abtropfzeit bleiben unverändert.","Miss die Taktzeit erneut, berechne die Einsparung in %, miss die geänderten Fahrzeiten, trage sie in die Vorlage „Fahrzeiten und Überwachungszeiten“ ein und passe deine Überwachungszeiten aus L22 an.","Prüfe für jeden Schritt deiner Schrittkette, ob er parallel zu einem anderen laufen könnte, und begründe in der Vorlage „Parallelisierungskandidaten“, warum das möglich oder unzulässig ist."],
 hilfe:{0:["Was siehst du wirklich, und was davon ist schon eine Vermutung?","Beschreibe nur, was du siehst (was steht, was meldet die Anlage, seit wann). Dann eine Vermutung und genau ein Prüfschritt, der sie bestätigt oder widerlegt. Halbiere dabei die Signalkette Sensor, Eingang, Programm, Ausgang, Aktor.","Beispiel: Symptom „Portal steht in Schritt 3, Meldung Laufzeitstörung Anheben“. Vermutung „−BG3 meldet nicht“. Prüfschritt: Signalmonitor zeigt −BG3 = 0, Zeile als geforct markiert. Ursache: Force auf −BG3. Behebung: Force zurücknehmen. Zeit 4 min."], 2:["Warum misst du nicht von START bis „fertig“, sondern von einer Flanke bis zur selben Flanke im nächsten Zyklus?","Weg-Zeit-Diagramm groß öffnen, Zeitfenster 120 s, Dauerbetrieb laufen lassen, <i>Anhalten</i>. Ein Klick setzt Messlinie 1, ein zweiter Messlinie 2. Die Linien rasten an den Flanken der Endlagensensoren ein, Δt steht oben. Mit dem eigenen Programm gibt es keine Schrittmarken, deshalb misst du an Endlagen.","Messlinie 1 an die Flanke, an der −MM1 „eingehängt“ erreicht, Messlinie 2 an dieselbe Flanke im nächsten Zyklus. Mindestens drei Zyklen messen, Mittelwert und Spannweite angeben. Körbe pro Stunde = 3600 s / Taktzeit."], 3:["Welche Bewegungen bestimmen die Taktzeit überhaupt?","Nimm die Fahrzeitentabelle aus L22. Ändere immer nur eine Drossel und miss die Fahrzeit. Das Drosselfenster zeigt dir zu jeder Einstellung die erwartete Fahrzeit: 50 % ist die Nennzeit, 100 % doppelt so schnell.","Beginne mit den langen Bewegungen, die nicht ohnehin in einer Wartezeit liegen (z. B. Verschieben −MM3, Heben und Senken −MM2). Öffne schrittweise, z. B. 50, 65, 80 %, und miss nach jeder Änderung. Über 80 % gehst du nur mit schriftlicher Begründung. Die Ereignisliste darf keine Kollision und keine Laufzeitstörung melden."], 5:["Welche zwei Bewegungen brauchen das Ergebnis der jeweils anderen nicht und kommen sich räumlich nicht in die Quere?","Frage bei jedem Kandidaten: Braucht B das Ergebnis von A? Können A und B kollidieren? Was passiert, wenn eine der beiden stehen bleibt? Nur wenn alle drei Antworten unkritisch sind, ist er geeignet. Abgesichert wird über Endlagen, nicht über Zeiten.","Beispiel: In Schritt 8 laufen „Bad abdecken“ (−MM4) und „zurück zum Band“ (−MM3) schon parallel, weiter erst mit beiden Endlagen. Ein Kandidat ist „Bad öffnen“ (−MM4) während der Fahrt zum Bad. Dann muss −BG7 vor dem Tauchen als Bedingung stehen."]},
 lf:[["Welcher Prüfschritt grenzt einen Fehler vermutlich am schnellsten ein: Signalmonitor, Beobachtungstabelle oder Weg-Zeit-Diagramm? Begründe deine Vermutung an einem Beispiel aus den bisherigen Übungen.",[0]],["Welcher Anteil deiner Taktzeit lässt sich überhaupt verkürzen, wenn Tauch- und Abtropfzeit fest bleiben? Schätze ihn vor der Messung.",[2]]],
 lfk:["Welcher Prüfschritt hat in deinen fünf Störfällen tatsächlich am schnellsten eingegrenzt? Stimmt das mit deiner Vermutung überein?","Wie groß war die Einsparung tatsächlich, verglichen mit deiner Schätzung? Was hat den Unterschied ausgemacht?"],
 pr:[["Fünf Störfälle mit vollständigem Fehlerprotokoll, jede Ursache mit einem Prüfschritt belegt",[0]],["Zu jedem Störfall notiert, ob dein Programm ihn gemeldet hat; fehlende Meldungen als Verbesserung aufgeschrieben",[0,1]],["Taktzeit vorher und nachher über mehrere Zyklen mit Messlinien gemessen, Einsparung in % angegeben",[1,2]],["Keine Drossel über 80 % ohne schriftliche Begründung, jede Abweichung von 50 % begründet, Überwachungszeiten neu gemessen und angepasst",[2]],["Mehrere Zyklen nach der Optimierung ohne Störmeldung in der Ereignisliste, jeder Korb „verzinnt“ mit unveränderter Tauch- und Abtropfzeit",[1,2]],["Jeder Parallelisierungskandidat mit Begründung bewertet",[2]]],
 ergebnis:[{n:"Fehlerprotokoll mit Verbesserungsvorschlägen", a:"neu", h:"Grundlage für das Meldekonzept in L37"},{n:"Drosseleinstellung und Messprotokoll Taktzeit", a:"neu", h:"vorher, nachher, Einsparung"},{n:"Fahrzeitentabelle", a:"erweitert", h:"nach der Optimierung neu gemessen"},{n:"FB Tinning", a:"übernommen", h:"wird nur geändert, wenn du eine Parallelisierung umsetzt (Plus)"}],
 plus:"Setze den besten Parallelisierungskandidaten in deiner Schrittkette als Simultanverzweigung um (Absicherung über Endlagen) und miss die neue Taktzeit. Oder als gegenseitige Fehlersuche im Team: Baut euch gegenseitig einen verdeckten Fehler ein und protokolliert die Suche.",
 tpls:[
 {id:"zerlegung", cap:"Zyklus zerlegen", phase:2, head:["Anteil","Zeit (s)","verkürzbar? (ja oder nein, warum)"], muster:["Beispiel: eine einzelne Bewegung, −MM1 einhängen","Fahrzeit aus L22","ja, über die Drossel, solange nichts kollidiert"], rows:[["Bewegungszeiten (Summe aus L22)"],["Wartezeiten"],["Tauch- und Abtropfzeit"],["Zyklus gesamt (geschätzt)"],["geschätzte Einsparung"]], inputs:2},
 {id:"fehler", cap:"Fehlerprotokoll", phase:4, head:["Nr.","Symptom","Vermutung","Prüfschritt","Ursache","Behebung","min","Programm hat gemeldet (ja oder nein, Verbesserung)"], muster:["Beispiel","Portal steht in Schritt 5, keine Bewegung","Endlage −BG7 kommt nicht","−BG7 im Signalmonitor: bleibt 0, obwohl die Abdeckung offen ist","−BG7 war auf 0 geforct","Force mit A zurückgenommen","4","ja, „−MM4 öffnen: Endlage −BG7 nicht erreicht“"], rows:[["1"],["2"],["3"],["4"],["5"]], inputs:7},
 {id:"takt", cap:"Messprotokoll Taktzeit", phase:4, head:["Messung","Taktzeit (s)","Drosseleinstellungen","Bemerkung"], muster:["Beispiel vorher, Zyklus 1","von −BG1 bis −BG1 im nächsten Zyklus, z. B. 38,0","alle 50 %","Tauch- und Abtropfzeit je 10 s (Voreinstellung)"], rows:[["vorher, Zyklus 1"],["vorher, Zyklus 2"],["vorher, Zyklus 3"],["vorher, Mittelwert"],["nachher, Zyklus 1"],["nachher, Zyklus 2"],["nachher, Zyklus 3"],["nachher, Mittelwert"],["Einsparung in %"]], inputs:3},
 {id:"parallel", cap:"Parallelisierungskandidaten", phase:4, head:["Kandidat","möglich? (ja oder nein)","Begründung (Kollision, Endlage)"], muster:["Schritt 8: abdecken und zurück zum Band","ja, steht schon so im Soll-Ablauf","Der Korb ist oben (−BG3), die Abdeckung stößt nicht an"], rows:[["Schritt 4 zum Bad und Schritt 5 Bad öffnen"],["Schritt 3 anheben und Schritt 4 zum Bad"],["Schritt 8 zurück und Schritt 9 absenken"],["Schritt 10 lösen und nächster Korb läuft ein"]], inputs:2, leer:2},
 {id:"fahrzeiten", erweitert:"L22:fahrzeiten", cap:"Fahrzeiten und Überwachungszeiten", phase:4, head:["Zylinder","Richtung","Fahrzeit (s), größter Wert","Faktor","Überwachungszeit (s)","Zuschlag (s)","Begründung","Drossel (%)"], muster:["Beispiel","ausfahren","1,6 (größter Wert aus mehreren Messungen)","1,5","2,4","0","lange Bewegung, kleine Streuung, Faktor 1,5 reicht","50"], rows:[["−MM1","einhängen (L36)"],["−MM1","lösen (L36)"],["−MM2","senken (L36)"],["−MM2","anheben (L36)"],["−MM3","zum Bad (L36)"],["−MM3","zum Band (L36)"],["−MM4","abdecken (L36)"],["−MM4","öffnen (L36)"]], inputs:6}
]
,
 bezug:[
 {von:"L22", id:"fahrzeiten", phase:2, wozu:"Deine Fahrzeiten aus L22 sind der Ausgangswert für die Taktzeit."}
]
}
