// Stammdaten der Übung L31 (Felder siehe uebungVorlage.md). Langtexte in texte.json, Kurz-Checks in quiz.js.
{id:"L31",
 st:4,
 t:"Stellglied und Zulauf überwachen",
 sub:"Prozessstörungen aus dem Verlauf erkennen",
 ue:3,
 vor:"L30",
 repo:"24",
 bild:null,
 typ:"programmieren",
 einst:"Übungsumfang wie in L30: <i>Kühlwassertank: Nachspeisung = SPS regelt</i>. Alles andere läuft von selbst: <i>Verzinnen: Portal −MM1…−MM4 = Portal automatisch</i>, <i>Band, Anschlag, Vereinzeler = Bandmodul automatisch</i>, <i>Zinnbad: Temperatur und Füllstand = Regler automatisch</i>.",
 ziele:["ein Stellglied über die Stellungsrückmeldung überwachen","Prozessstörungen aus dem Verlauf des Istwerts erkennen","Überwachungszeiten und Gültigkeitsbedingungen so festlegen, dass im Normalbetrieb kein Fehlalarm entsteht"],
 sig:"MB18 MB17 BL2 SF4 KF2",
 sit:"Ein klemmendes Regelventil oder eine abgesperrte Frischwasserleitung fällt erst auf, wenn der Tank leer ist. Dein Programm soll das früher merken.",
 plan:["Leite in der Vorlage „Überwachungen herleiten“ die Überwachungszeit für „Regelventil klemmt“ aus der Stellzeit des Ventils her (8 s für 0 bis 100 %).","Lege in derselben Vorlage die Gültigkeitsbedingung für „Frischwasser fehlt“ fest und rechne nach, dass der eingeschwungene Regelbetrieb sie nicht erfüllt, auch mit offenem Ablasshahn und Sprühkühlung."],
 auf:["Lies in deinem FB <code>TankLevel</code> den Stellwert des Reglers in Prozent (<code>tankOutput</code> aus L30, über <code>PlantData</code> als Input) und rechne die Stellungsrückmeldung %IW74 in Prozent um. Auch %IW74 bekommt <code>TankLevel</code> als Input, verschaltet im OB1.","Baue zwei Testumschaltungen in <code>TankLevel</code> ein: einen festen Ersatzwert statt %IW74 und das Einfrieren des Pegelwerts −BL2.","Programmiere die Stellungsüberwachung: Abweichung über 10 % länger als deine hergeleitete Zeit (15 s) → Meldung „Regelventil klemmt“.","Programmiere die Zulaufüberwachung: −MB17 offen, Rückmeldung −MB18 über 90 %, deine Gültigkeitsbedingung erfüllt und der Pegel steigt in 20 s nicht um 1 % → Meldung „Frischwasser fehlt“, Nachspeisung abschalten. Trage die zusätzliche Sperre von −MB17 in deine „Ausgangsliste“ ein.","Speichere beide Meldungen rücksetzdominant und quittiere sie mit einer Flanke von −SF4, erst wenn die Ursache behoben ist. Setze um, wie der Regler nach dem Abschalten der Nachspeisung wieder anfährt.","Teste beide Störungen, eine normale Stellbewegung von 0 auf 100 % und den eingeschwungenen Regelbetrieb mit offenem Ablasshahn. Die Ergebnisse hältst du im Prüfprotokoll dieser Übung fest."],
 hilfe:{1:["Was soll deine Überwachung sehen, wenn das Ventil klemmt, und wie erzeugst du genau das, obwohl sich Analogwerte nicht forcen lassen?","Nimm die Testumschaltung aus L11 als Muster: eine Bool-Variable schaltet zwischen echtem Wert und Ersatzwert um. Für das Einfrieren merkst du dir den letzten echten Pegel.","<code>IF #statTestMode THEN #tempFeedback := #statTestRaw; ELSE #tempFeedback := #rawFeedback; END_IF;</code> (<code>#rawFeedback</code> ist ein Input von <code>TankLevel</code>, im OB1 mit \"MB18_Stellung\" verschaltet) und <code>IF #statTestFreeze THEN #tempLevel := #statFrozenLevel; ELSE #tempLevel := #levelPercent; #statFrozenLevel := #levelPercent; END_IF;</code> Beide Tests schaltest du nur in der Beobachtungstabelle ein."], 2:["Wann ist eine große Abweichung zwischen Stellwert und Rückmeldung ganz normal?","Während das Ventil fährt, hinkt die Rückmeldung hinterher. Ein Sprung von 0 auf 100 % dauert 8 s. Die Zeit startet nur, solange die Abweichung über 10 % liegt.","TON als Multiinstanz: <code>IN := ABS(#tempSetpointPct - #tempFeedbackPct) &gt; #TOLERANCE</code>, <code>PT := #VALVE_TIMEOUT</code> mit den lokalen Konstanten <code>#TOLERANCE</code> = 10.0 und <code>#VALVE_TIMEOUT</code> = T#15s. Q setzt die Meldung. 15 s liegen rund 1,9-mal über der Stellzeit, wie bei den Überwachungszeiten aus L22."], 3:["Warum steigt der Pegel im eingeschwungenen Betrieb nicht, obwohl −MB17 offen ist?","Prüfe nur, wenn der Regler wirklich mehr Wasser will: Ventil fast ganz offen und Pegel deutlich unter dem Sollwert. Merke dir zu Beginn eines 20-s-Fensters den Pegel und vergleiche am Ende.","Gültig, wenn −MB17 offen UND Rückmeldung über 90 % UND Pegel mindestens 3 % unter dem Sollwert. Dann läuft ein TON mit 20 s. Am Fensterende: Pegel jetzt minus Pegel am Anfang kleiner als 1 % → Meldung. Im Regelbetrieb ist die Abweichung fast null, die Bedingung ist also nie gültig."], 4:["Was darf nicht passieren, wenn jemand quittiert, obwohl das Ventil noch klemmt?","Die Meldung bleibt gesetzt, solange die Ursache besteht. Quittieren wirkt nur mit Flanke (R_TRIG als Multiinstanz) und nur ohne Ursache. Bei „Frischwasser fehlt“ kann dein Programm die Ursache nach dem Abschalten nicht sehen. Hier entscheidet der Bediener; nach dem Quittieren prüft die Überwachung beim nächsten Fenster erneut. Den Regler hältst du wie in L30 an, solange die Nachspeisung abgeschaltet ist.","Setzen bei Bedingung, Rücksetzen bei Flanke −SF4 UND NICHT Bedingung, Rücksetzen nach dem Setzen geschrieben (rücksetzdominant wie in L03). Freigabe −MB17 zusätzlich UND NICHT „Frischwasser fehlt“. Der Reset von <code>PID_Tank</code> folgt der Freigabe wie in L30."]},
 lf:[["Warum darf die Stellungsüberwachung nicht anschlagen, während das Ventil normal von 0 auf 100 % fährt?",[0,2]],["Woran erkennt dein Programm eine abgesperrte Zuleitung, obwohl −MB17 und −MB18 genau das tun, was sie sollen?",[1]],["Was passiert mit dem PI-Regler aus L30, wenn die Nachspeisung abgeschaltet wird, und wie fährt er nach dem Quittieren wieder an?",[1,2]]],
 lfk:["Wie lange dauerte im Versuch eine Stellbewegung von 0 auf 100 %, bis die Abweichung unter 10 % lag? Passt deine Überwachungszeit dazu?"],
 pr:[["Testwert für die Stellungsrückmeldung aufgeschaltet → nach 15 s „Regelventil klemmt“",[0]],["Normale Stellbewegung von 0 auf 100 % (Sollwertsprung) → kein Fehlalarm",[0,2]],["Ablasshahn offen, Testumschaltung friert −BL2 bei 60 % ein, −MB17 offen, Rückmeldung über 90 % → nach 20 s „Frischwasser fehlt“, −MB17 schließt. Den Hahn brauchst du, damit der echte Pegel während des Tests nicht bis −BG39 steigt.",[1]],["Eingeschwungener Regelbetrieb mit offenem Ablasshahn über 10 min → kein Fehlalarm",[2]],["Quittieren mit −SF4, solange die Ursache besteht (Testwert noch aktiv) → die Meldung bleibt",[1,2]]],
 ergebnis:[{n:"FB TankLevel", a:"erweitert", h:"Stellungs- und Zulaufüberwachung, zwei Testumschaltungen"},{n:"globaler DB PlantData", a:"übernommen", h:"tankOutput aus L30, jetzt auch für die Stellungsüberwachung"},{n:"Herleitung der Überwachungszeit, Prüfprotokoll", a:"neu", h:"Muster für die Überwachung weiterer Stellglieder"}, {n:"Ausgangsliste", a:"erweitert", h:"neue Zeilen: −MB17"}],
 plus:"Erkenne zusätzlich ein Ventil, das zwar folgt, aber immer langsamer wird: Miss bei jedem großen Sprung die Stellzeit und melde eine Warnung, wenn sie deutlich über 8 s steigt (vorbeugende Instandhaltung).",
 tpls:[
 {id:"herleitung", cap:"Überwachungen herleiten", phase:2, head:["Festlegung","Wert bzw. Bedingung","Herleitung"], muster:["Beispiel L22: Überwachungszeit einer Bewegung","Fahrzeit × Faktor","größter gemessener Wert mal 1,5 bis 2"], rows:[["Überwachungszeit „Regelventil klemmt“"],["Gültigkeitsbedingung „Frischwasser fehlt“"],["Nachrechnung: Regelbetrieb mit Ablasshahn und Sprühkühlung"]], inputs:2},
 {id:"schreib", erweitert:"L02:schreib", cap:"Ausgangsliste", phase:4, head:["Ausgang","Bedeutung","ab Übung","schreibt (Baustein, einzige Stelle)","Bedingung oder Befehl kommt von","in der Querverweisliste geprüft"], muster:["−PF2","Bad bereit","L02","FB Indication, Aufruf im OB1","−BG9 UND −BG10, ODER Lampentest −SF4","ja, eine Schreibstelle"], rows:[["−MB17","Nachspeisen, zusätzlich gesperrt bei „Frischwasser fehlt“, ersetzt die Zeile aus L30","L31"]], inputs:3}
]
,
 bezug:[
 {von:"L30", id:"messung", phase:2, wozu:"Aus deinem Messprotokoll weißt du, wie weit −MB18 mit offenem Ablasshahn steht."}
]
}
