// Stammdaten der Übung L01 (Felder siehe uebungVorlage.md). Langtexte in texte.json, Kurz-Checks in quiz.js.
{id:"L01", st:1, t:"Signale erkunden", sub:"Schließer, Öffner und Forcen", ue:2, vor:"keine", repo:"–", bild:["08-signalmonitor.jpg","Signalmonitor in der Seitenleiste: jeder Eingang lässt sich forcen"], typ:"erkunden",
 einst:"Übungsumfang: alle Bereiche automatisch (<i>Verzinnen: Portal −MM1…−MM4</i> = <i>Portal automatisch</i>, <i>Band, Anschlag, Vereinzeler</i> = <i>Bandmodul automatisch</i>, <i>Zinnbad: Temperatur und Füllstand</i> = <i>Regler automatisch</i>, <i>Kühlwassertank: Nachspeisung</i> = <i>Niveauregler automatisch</i>). Für die Beobachtungstabelle in TIA steht unter <i>Verbindung</i> die Quelle der Ausgänge auf <i>PLCSIM Advanced</i> (Bridge verbunden). Für die Versuche mit der Demo-SPS (Grundstellung, −BG9) schaltest du auf <i>Demo ohne SPS</i>.",
 ziele:["jedem Bedienelement Adresse und Signalpegel zuordnen","Schließer, Öffner und Meldesignale nach dem Ruhestromprinzip unterscheiden","drahtbruchsichere Verdrahtung begründen"],
 sig:"BG1 BG2 BG3 BG4 BG5 BG6 BG7 BG8 BG9 BG10 BG11 SF1 SF2 SA3 KF2 SF4 SA1 SA2 SF5 SF6 SF7 BG12 BG13 FA1 BG39",
 sit:"Du übernimmst die Inbetriebnahme einer Verzinnungsanlage. Bevor du eine Zeile programmierst, prüfst du die Verdrahtung Signal für Signal. Das ist der klassische Loop-Check.",
 plan:["Fülle in der Vorlage „Wertetabelle der Eingänge %I0.0 bis %I2.7“ die Spalte „erwartet in Ruhe“ aus, bevor du etwas betätigst: Trage für jeden Eingang ein, welchen Pegel du nach seiner Art erwartest. Adresse, Kennzeichen, Gerät und Art stehen schon drin."],
 auf:["Lege das TIA-Projekt an, in dem du bis L36 weiterarbeitest, und füge die CPU 1516-3 PN/DP ein.","Stecke in der Gerätesicht die Stromversorgung und die Signalmodule (4 × DI 32, 2 × DQ 32, AI 8, AQ 4) und stelle ihre Anfangsadressen so ein, dass sie zur Signalliste passen: DI ab %I0.0, DQ ab %Q0.0, AI ab %IW64, AQ ab %QW80. Übersetze danach die Hardwarekonfiguration.","Erlaube die Simulation, importiere die PLC-Variablen aus <code>TIA/PLC_Variablen_Zinnbad.xlsx</code>, übersetze und lade in die PLCSIM-Advanced-Instanz <code>Zinnbad</code> (Anleitung im Repository: docs/01-inbetriebnahme.md, Abschnitte 2 und 3).","Lege eine Beobachtungstabelle für die 24 Eingänge %I0.0 bis %I2.7 an. Ist der Zwilling über die Bridge mit PLCSIM Advanced gekoppelt, liest du die Pegel in der Beobachtungstabelle ab. Ohne SPS liest du sie im Signalmonitor des Zwillings ab.","Betätige jedes Bedienelement im Zwilling (3D-Pult und Seitenleiste). Trage den gemessenen Pegel unbetätigt und betätigt in die Vorlage „Wertetabelle der Eingänge %I0.0 bis %I2.7“ ein und prüfe, ob er zur Art passt.","Schalte unter <i>Verbindung</i> auf <i>Demo ohne SPS</i>. Stelle −SA1 auf AUTO und drücke START −SF1. Die Demo fährt die Grundstellung an und startet dann die Zyklen. Trage in der Vorlage „Grundstellung: welche Endlagen melden 1?“ für jeden Endlagensensor ein, was er in der Grundstellung meldet.","Force im Signalmonitor −BG9 auf 0, während die Demo läuft. Beobachte mindestens einen vollen Automatikzyklus (ein Korb wird einmal verzinnt) und beantworte die Fragen in der Vorlage „Versuch: −BG9 auf 0 geforct“. Gib das Signal danach mit <b>A</b> wieder ans Modell zurück.","Sichere dein Projekt als Projektarchiv mit der Übungsnummer im Namen, zum Beispiel <code>Verzinnung_L01</code>."],
 fw:{0:[2], 1:[14,3], 2:[4,2], 3:[11,3,1], 4:[10,12,5], 5:[9,12], 6:[13,8,7], 7:[2]},
 hilfe:{0:["Wo startest du in TIA Portal ein neues Projekt, und wo fügst du ein Gerät hinzu?","Portalansicht: Start, Neues Projekt erstellen. Danach Geräte & Netze, Neues Gerät hinzufügen.","Start, Neues Projekt erstellen, Name Verzinnung, Erstellen. Geräte & Netze, Neues Gerät hinzufügen, Controller, SIMATIC S7-1500, CPU, CPU 1516-3 PN/DP, Hinzufügen. TIA wechselt in die Projektansicht."], 1:["Welche Ein- und Ausgangsadressen kommen in der Signalliste vor, und wie viele Bytes hat eine DI-32-Baugruppe?","Projektnavigation, CPU, Gerätekonfiguration. Rechts der Hardware-Katalog: PM auf Steckplatz 0, dann viermal DI 32x24VDC HF, zweimal DQ 32x24VDC/0.5A ST, einmal AI 8xU/I/RTD/TC ST, einmal AQ 4xU/I ST. Adressen in der Geräteübersicht prüfen.","DI: E-Adressen 0…3, 4…7, 8…11, 12…15. DQ: A-Adressen 0…3, 4…7. AI: Baugruppe anklicken, Eigenschaften, E/A-Adressen, Anfangsadresse 64. AQ: Anfangsadresse 80. Projekt speichern, CPU markieren, Übersetzen."], 2:["Welche drei Dinge brauchst du noch, damit dein Projekt in PLCSIM Advanced läuft und die Namen der Signale kennt?","In den Projekteigenschaften unter Schutz die Simulation erlauben, danach in der Standard-Variablentabelle die Excel-Datei importieren, übersetzen und laden.","Projekteigenschaften: Schutz, Haken „Simulation bei Kompilierung von Bausteinen unterstützen“. Projektnavigation: CPU, PLC-Variablen, Doppelklick auf Standard-Variablentabelle, in der Symbolleiste der Tabelle Importieren, Datei TIA/PLC_Variablen_Zinnbad.xlsx, OK. Danach übersetzen und in die PLCSIM-Advanced-Instanz „Zinnbad“ laden."], 3:["In welchem Ordner unter deiner CPU findest du Beobachtungstabellen?","Ordner Beobachtungs- und Forcetabellen, Neue Beobachtungstabelle hinzufügen, dann die Adressen oder Namen der PLC-Variablen eintragen und online verbinden.","Trage in der Spalte Adresse %I0.0 bis %I2.7 ein (TIA ergänzt die Namen). Markiere die CPU, klicke auf Online verbinden und in der Beobachtungstabelle auf Alle beobachten. In der Spalte Beobachtungswert siehst du TRUE oder FALSE."]},
 lf:[["Warum ist STOP −SF2 ein Öffner, START −SF1 aber ein Schließer?",[1,2]],["Was meldet −BG39 am Kühlwassertank bei Drahtbruch, und warum ist das die sichere Seite?",[2]],["Worin unterscheidet sich Forcen im Signalmonitor des Zwillings vom Steuern einer Variable in TIA?",[0]]],
 lfk:["Welcher Eingang hat dich beim Betätigen überrascht, weil er schon unbetätigt 1 meldet? Erkläre mit dem Ruhestromprinzip, warum das so gewollt ist."],
 pr:[["Wertetabelle für alle 24 Eingänge %I0.0 bis %I2.7 vollständig: erwarteter Pegel und beide gemessenen Pegel eingetragen",[0]],["Für jeden Eingang ist geprüft, ob der gemessene Pegel zur Art passt (Schließer, Öffner oder Meldesignal mit 1 = in Ordnung), jede Abweichung ist erklärt",[1]],["Grundstellung −BG2, −BG4, −BG5, −BG8 = 1 erkannt",[0]],["Wirkung von −BG9 = 0 richtig beschrieben und mit der sicheren Seite begründet",[2]],["Am Ende ist kein Signal mehr geforct, und das Projektarchiv ist gesichert",[0]]],
 ergebnis:[{n:"TIA-Projekt Verzinnung", a:"neu", h:"Dein Projekt wächst von L01 bis L36. In L37 führt ihr im Team eure Projekte zusammen. Archiv nach jeder Übung."},{n:"Beobachtungstabelle Eingänge", a:"neu", h:"%I0.0 bis %I2.7"},{n:"Wertetabelle der 24 Eingänge", a:"neu", h:"Grundlage für L12 und das Pflichtenheft in L37"}],
 plus:"Erstelle aus <code>signale.csv</code> eine Symboltabelle in Excel mit den Spalten Typ (DI, DQ, AI, AQ), Gerät und Wirkrichtung (was bedeutet 1?). Ergänze für jedes Gerät seinen Ort in der Anlage.",
 tpls:[
 {id:"werte", fw:[10,0,5], felder:["01",{typ:"01",ab:4},{typ:"01",ab:4},{typ:"janein",ab:4},{typ:"notiz",ab:4}], vergleich:[0,1], cap:"Wertetabelle der Eingänge %I0.0 bis %I2.7", phase:2, head:["Adresse","Kennzeichen","Gerät","Art laut Signalliste","erwartet in Ruhe (vorher eintragen)","gemessen unbetätigt bzw. in Ruhe","gemessen betätigt bzw. belegt","passt zur Art (ja oder nein)","Bemerkung"], muster:["%I1.3","−SF1","Taster START, Bedienpult","Schließer","0","0","1","ja","rastet nicht, nur solange gedrückt"], rows:[["%I0.0","−BG1","Endlage −MM1 eingehängt","Sensor, 1 = Endlage erreicht"],["%I0.1","−BG2","Endlage −MM1 gelöst","Sensor, 1 = Endlage erreicht"],["%I0.2","−BG3","Endlage −MM2 oben","Sensor, 1 = Endlage erreicht"],["%I0.3","−BG4","Endlage −MM2 unten","Sensor, 1 = Endlage erreicht"],["%I0.4","−BG5","Endlage −MM3 über dem Band","Sensor, 1 = Endlage erreicht"],["%I0.5","−BG6","Endlage −MM3 über dem Zinnbad","Sensor, 1 = Endlage erreicht"],["%I0.6","−BG7","Endlage −MM4 Bad offen","Sensor, 1 = Endlage erreicht"],["%I0.7","−BG8","Endlage −MM4 Bad abgedeckt","Sensor, 1 = Endlage erreicht"],["%I1.0","−BG9","Temperatur Zinnbad erreicht (ab 250 °C)","Meldesignal, 1 = in Ordnung"],["%I1.1","−BG10","Füllhöhe Zinnbad ausreichend (ab 40 %)","Meldesignal, 1 = in Ordnung"],["%I1.2","−BG11","Lichtschranke Einlauf Übergabeplatz","Sensor, 1 = Korb erkannt"],["%I1.3","−SF1","Taster START, Bedienpult","Schließer"],["%I1.4","−SF2","Taster STOP, Bedienpult","Öffner"],["%I1.5","−SA3","Wahlschalter HAND/AUTO, Schaltschranktür","rastender Schalter, 1 = HAND"],["%I1.6","−KF2","Rückmeldung Sicherheitsrelais","Meldesignal, 1 = Freigabe"],["%I1.7","−SF4","Taster Quittieren, Bedienpult","Schließer"],["%I2.0","−SA1","Wahlschalter AUTO/EINZEL (Dauerbetrieb/Einzelzyklus), Bedienpult","rastender Schalter, 1 = AUTO (Dauerbetrieb)"],["%I2.1","−SA2","Schlüsselschalter Vor-Ort-Steuerstelle −S10","rastender Schalter, 1 = aktiv"],["%I2.2","−SF5","Taster Band rechts, −S10","Schließer"],["%I2.3","−SF6","Taster Band links, −S10","Schließer"],["%I2.4","−SF7","Taster Band Halt, −S10","Öffner"],["%I2.5","−BG12","Lichtschranke Bandanfang","Sensor, 1 = Korb erkannt"],["%I2.6","−BG13","Lichtschranke Ende Band 1","Sensor, 1 = Korb erkannt"],["%I2.7","−FA1","Motorschutzschalter Band 1, Hilfskontakt","Meldesignal, 1 = in Ordnung"]], inputs:5},
 {id:"grundst", fw:[9,12], felder:["01","text"], cap:"Grundstellung: welche Endlagen melden 1?", phase:4, head:["Kennzeichen","Endlage","meldet in Grundstellung (0 oder 1)","Zylinder steht damit …"], muster:["Beispiel: −BG14","−MM5 Anschlag geschlossen","1","Anschlag zu, ein Korb auf Band 1 wird am Anschlag angehalten"], rows:[["−BG1","−MM1 eingehängt"],["−BG2","−MM1 gelöst"],["−BG3","−MM2 oben"],["−BG4","−MM2 unten"],["−BG5","−MM3 über dem Band"],["−BG6","−MM3 über dem Zinnbad"],["−BG7","−MM4 Bad offen"],["−BG8","−MM4 Bad abgedeckt"]], inputs:2},
 {id:"bg9", fw:[13,8,7], felder:["text","text"], cap:"Versuch: −BG9 auf 0 geforct", phase:4, head:["Frage","Beobachtung","Begründung"], muster:["Wie zeigt der Signalmonitor den Force?","−BG9 ist markiert und zeigt 0, obwohl das Bad heiß ist","Forcen überschreibt das Signal des Modells"], rows:[["Welcher Schritt startet nicht mehr?"],["Welche Meldeleuchte reagiert, und wie?"],["Warum ist das die sichere Seite?"],["Was passiert, nachdem du den Force mit A zurückgibst?"]], inputs:2}
]
}
