// Stammdaten der Übung L15 (Felder siehe uebungVorlage.md). Langtexte in texte.json, Kurz-Checks in quiz.js.
{id:"L15", st:2, t:"Betriebsarten HAND und AUTO", sub:"Betriebsartenteil: umschalten, ohne dass sich etwas bewegt", ue:3, vor:"L14", repo:"3, 4", bild:["03-schaltschrank.jpg","Wahlschalter −SA3 Hand / Auto und Leuchte −PF7 an der Schaltschranktür"],
 typ:"programmieren",
 einst:"Übungsumfang: <i>Verzinnen: Portal −MM1…−MM4</i> = <i>SPS steuert</i>, <i>Band, Anschlag, Vereinzeler</i> = <i>SPS steuert</i>, <i>Zinnbad: Temperatur und Füllstand</i> = <i>Regler automatisch</i>, <i>Kühlwassertank: Nachspeisung</i> = <i>Niveauregler automatisch</i>. Dein Programm schaltet die Ventile −MB1 bis −MB9, die Leuchten −PF1 und −PF7 und über Indication weiter −PF2 bis −PF4. Band und Vereinzeler (−MB10) schaltet es noch nicht, deshalb steht das Band. Das ist im Handbetrieb gewollt.",
 ziele:["einen Betriebsartenteil mit sich gegenseitig ausschließenden Betriebsarten programmieren und die Betriebsart über Bausteinausgänge weitergeben","Betriebsarten stoßfrei wechseln: der Wechsel selbst löst keine Bewegung aus","Bedingungen für AUTO festlegen: Grundstellung, Freigabe, kein Not-Halt"],
 sig:"SA3 PF7 PF1 KF2 SF4 BG2 BG4 BG5 BG8 SF19 SF20 MB9",
 sit:"Neben den Handbetrieb aus L13 kommt bald eine Automatik. Bevor der erste Automatikschritt programmiert wird, legst du fest, wer die Anlage wann führt: −SA3 an der Schaltschranktür wählt HAND oder AUTO. Es darf nie beides zugleich aktiv sein, und das Umschalten selbst darf nichts bewegen.",
 tab:{cap:"Betriebsarten der Verzinnungsanlage", ...T(["Betriebsart","aktiv, wenn","Wirkung"],[["HAND","−SA3 = 1 und −KF2 gibt frei","Handtaster wirken über die Verriegelungen, die Automatik ruht, −PF7 leuchtet (geschrieben in Manual)"],["AUTO","−SA3 = 0 und −KF2 gibt frei","Handtaster wirkungslos; ab L17 arbeitet die Automatik auf START hin; ohne Grundstellung blinkt −PF1 (geschrieben in ModeSelect)"],["keine","−KF2 = 0 (Not-Halt, Schutzfeld)","alle Befehle gelöscht; nach dem Quittieren bewegt sich nichts von selbst"]])},
 plan:["Zeichne die Betriebsarten HAND, AUTO und „keine“ als Zustandsdiagramm mit allen Übergängen und ihren Bedingungen.","Skizziere die Programmstruktur nach der Karte „Programmstruktur der Anlage“: welche Bausteine es nach dieser Übung gibt, in welcher Reihenfolge der OB1 sie aufruft und welches Signal von welchem Baustein zu welchem fließt."],
 auf:["Lege einen FB <code>ModeSelect</code> mit Bausteinkopf an und rufe ihn im OB1 direkt nach <code>StartRelease</code> auf. Er bekommt −SA3, −KF2 und <code>homePosition</code> (aus <code>PlantData</code>) über seine Eingänge, bildet intern <code>#statModeManual</code> und <code>#statModeAuto</code> und gibt sie über die Ausgänge <code>modeManual</code> und <code>modeAuto</code> weiter. Nie dürfen beide 1 sein.","Programmiere: Bei −KF2 = 0 sind beide Betriebsarten 0. Prüfe mit einem Not-Halt, dass nach dem Quittieren die gewählte Betriebsart wieder aktiv ist und sich nichts bewegt.","Baue die Verschaltung von <code>Manual</code> um: Verschalte seinen Eingang <code>manualMode</code> im OB1 mit dem Ausgang <code>modeManual</code> von <code>ModeSelect</code> statt mit −SA3. −PF7 schreibt weiterhin nur <code>Manual</code>.","Bilde den Ausgang <code>autoReady</code> (AUTO und Grundstellung). Fehlt in AUTO die Grundstellung, blinkt −PF1 mit 1 Hz über deinen FB <code>Clock</code> aus L04 als Multiinstanz. Prüfe in der Querverweisliste und in der Vorlage „Ausgangsliste“, dass −PF1 nur noch in <code>ModeSelect</code> geschrieben wird. Gültig ist immer die jüngste Zeile eines Ausgangs. Lege <code>modeManual</code>, <code>modeAuto</code> und <code>autoReady</code> im OB1 in <code>PlantData</code> ab und trage sie in die Vorlage „Variablenliste PlantData“ ein.","Entscheide, was mit der gespeicherten Handstellung des Anschlags −MM5 beim Wechsel nach AUTO geschieht. Trage deine Entscheidung in die Vorlage „Entscheidung: Anschlag −MM5 beim Betriebsartenwechsel“ ein, setze sie um und begründe sie im Bausteinkopf.","Gleiche dein Zustandsdiagramm aus der Planung mit dem fertigen Programm ab und korrigiere, was nicht übereinstimmt."],
 hilfe:{0:["Welcher Eingang hat Vorrang: −SA3 oder −KF2? Was muss gelten, damit überhaupt eine Betriebsart aktiv ist?","Bilde zuerst, ob −KF2 freigibt. Nur dann entscheidet −SA3 zwischen HAND und AUTO. Schreibe beide Ergebnisse in die statischen Variablen und weise sie am Ende des FB den Ausgängen zu. Prüfe in der Beobachtungstabelle beide Ausgänge gleichzeitig.","<pre class=\"code\"><code>#statModeManual := #safetyOk AND #manualSelected;\n#statModeAuto := #safetyOk AND NOT #manualSelected;\n#modeManual := #statModeManual;\n#modeAuto := #statModeAuto;</code></pre>Weil beide aus demselben Eingang −SA3 gebildet werden, einmal mit und einmal ohne NICHT, können sie nie gleichzeitig 1 sein."],4:["Was macht ein 5/2-Ventil mit Federrückstellung, wenn sein Ausgang 0 wird? Kann in diesem Moment ein Korb unter dem Hebel liegen?","Spiele beide Möglichkeiten durch: a) Die Handstellung fällt beim Wechsel weg, der Anschlag schließt. b) Die Stellung bleibt gehalten, bis ein neuer Befehl kommt. Prüfe für beide, was mit einem Korb an −BG40 oder unter −BG11 geschieht.","Eine vertretbare Lösung: <code>#statStopperOpen</code> bleibt beim Wechsel nach AUTO erhalten, −MB9 bleibt 1, bis ein neuer Befehl kommt (in HAND −SF20, ab L21 aus der Übergabeplatz-Kette). In <code>Manual</code> heißt die Zuweisung dann <code>#valveStopperOpen := #statStopperOpen AND #safetyOk;</code> statt mit <code>manualMode</code>. Bei −KF2 = 0 fällt −MB9 ohnehin ab, denn −KF2 macht die Ventile spannungslos. Gib <code>Manual</code> dafür den Eingang <code>safetyOk</code> (im OB1 mit −KF2 verschaltet), damit es −KF2 = 0 vom Wechsel nach AUTO unterscheiden kann, und lösche <code>#statStopperOpen</code> bei <code>safetyOk</code> = 0. Schreibe die Begründung in den Bausteinkopf."]},
 lf:[["Warum müssen sich Betriebsarten gegenseitig ausschließen? Was könnte sonst passieren?",[0]],["Warum darf ein Betriebsartenwechsel keine Bewegung auslösen, und warum ist das beim Anschlag −MM5 schwieriger als bei −MM1 bis −MM4?",[1]],["Warum gehört die Grundstellung in die Bedingung für AUTO, aber nicht für HAND?",[2]],["Warum fragt nur ModeSelect den Schalter −SA3 ab, während alle anderen Bausteine modeManual und modeAuto als Eingang bekommen?",[0]],["Warum sitzt der Wahlschalter HAND / AUTO an der Schaltschranktür und nicht am Bedienpult?",[0]]],
 lfk:["Du hast −SA3 umgeschaltet, während ein Handtaster im Signalmonitor geforct war. Was ist passiert, und passt das zu deiner Regel „ein Umschalten löst keine Bewegung aus“?"],
 pr:[["−SA3 auf HAND → modeManual = 1, modeAuto = 0, −PF7 an",[0]],["In allen Tests sind modeManual und modeAuto nie gleichzeitig 1 (Beobachtungstabelle)",[0]],["Umschalten in jeder Lage, auch mit geforctem Handtaster → keine unbefohlene Bewegung, −MM5 verhält sich wie festgelegt",[1]],["AUTO ohne Grundstellung (−BG2 im Signalmonitor auf 0 forcen) → −PF1 blinkt mit 1 Hz, autoReady bleibt 0",[2]],["Not-Halt → beide Betriebsarten 0; nach dem Quittieren mit −SF4 bewegt sich nichts",[2]],["Zustandsdiagramm stimmt mit dem Programm überein",[0,1]]],
 ergebnis:[{n:"FB ModeSelect",a:"neu",h:"Betriebsartenteil; Ausgänge modeManual, modeAuto, autoReady; einzige Schreibstelle von −PF1"},{n:"FB Manual",a:"umgebaut",h:"bekommt modeManual statt −SA3; schreibt bis L15 noch −MB1 bis −MB9 und weiter −PF7"},{n:"FB Clock",a:"übernommen",h:"als Multiinstanz in ModeSelect für das 1-Hz-Blinken"},{n:"Zustandsdiagramm Betriebsarten",a:"neu",h:"wird in L18 erweitert"},{n:"Entscheidung −MM5 beim Wechsel",a:"neu",h:"gilt weiter in L16 und L21"},{n:"Skizze Programmstruktur",a:"neu",h:"wird in L16 und L17 ergänzt"}, {n:"globaler DB PlantData", a:"erweitert", h:"neue Einträge in der Variablenliste PlantData: Betriebsart HAND, Betriebsart AUTO, AUTO bereit (AUTO und Grundstellung)"}, {n:"Ausgangsliste", a:"erweitert", h:"neue Zeilen: −PF1"}],
 plus:"Zähle in <code>ModeSelect</code> jeden Wechsel nach HAND und jeden Not-Halt in AUTO und gib beide Zähler als Ausgänge aus (Beobachtungstabelle). So sieht der Schichtleiter, wie oft die Automatik unterbrochen wurde. Wer schon ein eigenes HMI-Projekt hat, zeigt die aktive Betriebsart zusätzlich dort an.",
 tpls:[
 {id:"mm5", cap:"Entscheidung: Anschlag −MM5 beim Betriebsartenwechsel", phase:4, head:["Situation","Was passiert mit #statStopperOpen?","Was macht −MB9?","Begründung"], muster:["Beispiel −MM1 bis −MM4 (5/2 bistabil)","keine Speicherung nötig","Ventil bleibt in seiner Stellung, der Zylinder bewegt sich nicht","Ein bistabiles Ventil hält seine Lage auch ohne Signal"], rows:[["Wechsel HAND → AUTO, Anschlag offen"],["Wechsel HAND → AUTO, Anschlag zu"],["Wechsel AUTO → HAND"],["Not-Halt in HAND, danach quittiert"]], inputs:3},
 {id:"schreib", erweitert:"L02:schreib", cap:"Ausgangsliste", phase:4, head:["Ausgang","Bedeutung","ab Übung","schreibt (Baustein, einzige Stelle)","Bedingung oder Befehl kommt von","in der Querverweisliste geprüft"], muster:["−PF2","Bad bereit","L02","FB Indication (bis L03 FC), Aufruf im OB1","−BG9 UND −BG10, ODER Lampentest −SF4","ja, eine Schreibstelle"], rows:[["−PF1","AUTO bereit, blinkt ohne Grundstellung","L15"]], inputs:3},
 {id:"plantdata", erweitert:"L05:plantdata", cap:"Variablenliste PlantData", phase:4, head:["Inhalt","ab Übung","Variablenname","Datentyp","remanent (ja oder nein, warum)","schreibt (Baustein, über den OB1)","liest"], muster:["Betriebsbereitschaft","L05","ready","Bool","nein, nach dem Neustart muss neu gestartet werden","Operation (Output ready)","Indication"], rows:[["Betriebsart HAND","L15"],["Betriebsart AUTO","L15"],["AUTO bereit (AUTO und Grundstellung)","L15"]], inputs:5}
]
}
