// Kurz-Checks der Übung L05: ein = Eingangs-Check in Phase 1 (nur Vorwissen aus den vor-Übungen), aus = Abschluss-Check in Phase 6.
// Frage: [Frage, [Antwort 0, Antwort 1, Antwort 2], Index der richtigen Antwort, Begründung]
{ein:[
  ["Welche Zeit nimmst du, damit ein Signal erst nach 3 s ununterbrochenem Anstehen wirkt?",["TON","TOF","TP"],0,"TON verzögert das Einschalten (L04)."],
  ["Wo liegen die Daten einer Multiinstanz #instClock?",["im Instanz-DB des FB, der sie aufruft","in einem eigenen globalen DB","in Merkern"],0,"So hast du Zeiten und Clock in L04 angelegt."]],
 aus:[
  ["Du zählst Körbe selbst: #statBasketCount := #statBasketCount + 1. Warum brauchst du dafür eine Flanke an −BG40?",["Sonst zählt das Programm in jedem Zyklus weiter, solange der Korb anliegt.","Weil −BG40 ein Öffner ist.","Weil Int-Variablen nur Flanken zählen."],0,"Ohne Flanke wird die Addition jeden Zyklus ausgeführt. CTU wertet CU selbst flankengesteuert aus."],
  ["Welcher Zähler eignet sich für die Zahl der Körbe im Puffer?",["CTU","CTD","CTUD"],2,"Körbe kommen hinzu und gehen ab: Es wird vorwärts und rückwärts gezählt."],
  ["Neue Stilregel: Wie legst du den Tageszähler an?",["als CTU-Multiinstanz im FB Counting","als CTU mit eigenem Einzel-DB","als Merkerwort"],0,"Zähler gehören wie Zeiten als Multiinstanz in den FB, der sie benutzt."],
  ["Neue Stilregel: Indication braucht den Wartungshinweis. Wie kommt er dorthin?",["Der OB1 legt den Output von Counting in PlantData ab und verschaltet ihn mit dem Input von Indication.","Indication liest \"InstCounting\".maintenanceDue im Baustein.","Indication liest \"PlantData\".maintenanceDue im Baustein."],0,"Bausteine kennen nur ihre Schnittstelle, verschaltet wird im OB1."],
  ["Der Tageszähler soll einen Neustart überleben. Wo stellst du die Remanenz ein?",["in der Schnittstelle von Counting an der CTU-Multiinstanz","nur in PlantData","in der Beobachtungstabelle"],0,"Remanent muss der Speicher sein, in dem gezählt wird."],
  ["Ein CTU vom Datentyp Int steht auf 32767. Was passiert beim nächsten Korb?",["Der Zählwert bleibt bei 32767 stehen.","Er springt auf −32768.","Die CPU geht in STOP."],0,"An der Grenze des Datentyps hat CU keine Wirkung mehr. Deshalb zählst du Teile mit DInt."],
  ["Am CTUD kommen im selben Zyklus eine Flanke an CU und eine an CD. Was macht CV?",["CV bleibt unverändert.","CV wird erst um 1 erhöht und dann verringert, also zwei Änderungen im Programmstatus.","CV wird auf 0 gesetzt."],0,"So steht es in der TIA-Hilfe zu CTUD: Hinein und heraus heben sich auf."],
  ["Neue Stilregel: Welche Einstellung wählst du in der Spalte Remanenz eines FB nicht?",["Im IDB setzen","Remanent","Nicht remanent"],0,"Siemens empfiehlt, die Remanenz immer im FB einzustellen. „Im IDB setzen“ erhöht die Abarbeitungszeit."],
  ["Du ergänzt in Counting eine Variable und lädst ohne aktivierte Speicherreserve. Was passiert mit dem remanenten Tageszähler?",["Er wird auf den Startwert zurückgesetzt, weil InstCounting reinitialisiert wird.","Er bleibt erhalten, weil er remanent ist.","Er wird verdoppelt."],0,"Eine geänderte Schnittstelle reinitialisiert den Instanz-DB. Mit „Aktualwerte behalten“ bleiben die Werte erhalten."]]}
