// Stammdaten der Übung L35 (Felder siehe uebungVorlage.md). Langtexte in texte.json, Kurz-Checks in quiz.js.
{id:"L35",
 st:4,
 t:"Antriebsstörungen beherrschen",
 sub:"Melden, quittieren, sperren",
 ue:3,
 vor:"L32 oder L33, L34",
 repo:"19",
 bild:["11-umrichter.jpg","Störungen auslösen im Fenster Umrichter"],
 typ:"programmieren",
 einst:"Übungsumfang wie in L34: <i>Band, Anschlag, Vereinzeler = SPS steuert</i>, unter <i>Antriebe</i> Band 1 −MA1, Band 2 −MA2 und Rollenkurve −MA6 auf <i>Umrichter</i>, Prüfband −MA5 auf <i>Umrichter −TA5</i>. <i>Verzinnen: Portal −MM1…−MM4 = Portal automatisch</i>, <i>Zinnbad: Temperatur und Füllstand = Regler automatisch</i>, <i>Kühlwassertank: Nachspeisung = Niveauregler automatisch</i>.",
 ziele:["Stör-, Sperr- und Führungsbits im Zustandswort auswerten und vier Störfälle unterscheiden","regelgerecht quittieren, ohne dass ein Antrieb von selbst wieder anläuft","quittierbare von zeitlich gesperrten Störungen unterscheiden und dem Bediener verständlich melden"],
 sig:"TA2 TA3 TA4 KF2 SF4 SF41 SF42 SF43",
 sit:"Ein Umrichter meldet Überlast, ein Bandmotor überhitzt. Das Bedienpersonal braucht klare Meldungen und einen sicheren Weg zurück in den Betrieb.",
 plan:["Fülle die Vorlage „Meldetexttabelle Antriebsstörungen“ aus und trage als Vermutung ein, an welchen ZSW1-Bits du jeden Fall erkennst (Karte Zustandswort aus L33). In den Schritten 1 bis 3 prüfst du deine Vermutung und ergänzt Meldetext, Quittierbarkeit und Reaktion der Anlage."],
 auf:["Löse im Fenster <i>Umrichter</i> nacheinander <i>Störung Überlast</i> (F30005) und <i>Motor überhitzt</i> (F07011) aus und trage jeweils ZSW1 hex und bitweise in die Vorlage „ZSW1 in den vier Fällen“ ein. Das Abkühlen stellst du nach, indem du <i>Motor überhitzt</i> erneut drückst.","Drücke einen Not-Halt (STO) und trage ZSW1 in die Vorlage „ZSW1 in den vier Fällen“ ein.","Schalte am Bedienpanel des Umrichters auf HAND und trage ZSW1 in dieselbe Vorlage ein. Achte besonders auf ZSW1.9.","Programmiere je Antrieb einen Diagnosebaustein (Multiinstanz im Antriebsbaustein), der Störung (ZSW1.3), Einschaltsperre (ZSW1.6) und fehlende Führung (ZSW1.9) im Klartext meldet. Überlast und Motorübertemperatur unterscheidest du über ZSW1.13 (0 = Motorübertemperatur), Not-Halt über −KF2. Mit Technologieobjekt bekommt <code>DriveAxis</code> dafür zusätzlich einen Eingang <code>zsw1</code>, den du im OB1 mit dem Eingangswort (z. B. \"TA2_ZSW1\") verschaltest, denn der Technologie-DB meldet beide Störungen nur als Fehler im Antrieb.","Sperre bei einer Störung die betroffene Förderstrecke: Vorgelagerte Förderer schieben keinen Korb auf ein stehendes Band.","Quittiere mit −SF4 bzw. dem Quittiertaster der zugehörigen Vor-Ort-Steuerstelle: Dein Programm setzt daraus <code>MC_Reset</code> bzw. eine Flanke an STW1.7 ab. Solange F07011 nicht quittierbar ist, bleibt die Meldung mit dem Hinweis „abkühlen lassen“ stehen.","Sorge dafür, dass nach dem Quittieren nichts von selbst anläuft, und teste alle vier Fälle an mindestens einem Umrichter. Trage die Ergebnisse in die Vorlage „Testprotokoll Antriebsstörungen“ ein."],
 hilfe:{3:["Welche Bits ändern sich in welchem Fall, und welcher Fall setzt dasselbe Bit wie ein anderer?","Nimm deine Notizen aus den Schritten 1 bis 3. Störung: ZSW1.3. Darunter: ZSW1.13 = 0 nur bei Motorübertemperatur. Einschaltsperre ZSW1.6 zusammen mit −KF2 = 0 heißt Not-Halt. ZSW1.9 = 0 heißt HAND am Panel.","<code>#overload := #zsw1.%X3 AND #zsw1.%X13;</code> <code>#motorHot := #zsw1.%X3 AND NOT #zsw1.%X13;</code> <code>#eStop := #zsw1.%X6 AND NOT #kf2Ok;</code> <code>#localControl := NOT #zsw1.%X9;</code> <code>#zsw1</code> und <code>#kf2Ok</code> sind Inputs deines Antriebsbausteins. Mit Technologieobjekt verschaltest du beim Aufruf im OB1 das Eingangswort \"TA2_ZSW1\" mit dem Eingang zsw1 (über <code>ConveyorLine</code> und <code>Conveyor</code> durchgereicht). Dein Programm darf das Eingangswort lesen, nur die Beobachtungstabelle zeigt es wegen „TPA OB Servo“ nicht an."], 4:["Wie erfährt der vorgelagerte Förderer, dass der nächste nicht übernehmen kann?","Dein Übergabe-Handshake aus L23 hat schon das Signal „bereit zur Übernahme“. Eine Antriebsstörung nimmt es einfach weg.","Im FB <code>Conveyor</code>: <code>#readyToTake := … AND NOT #instDrive.fault;</code> Weil alle Instanzen denselben FB nutzen, gilt das für Band 1, Rollenkurve und Band 2 zugleich. Der vorgelagerte Förderer gibt dann keinen Korb mehr ab, ohne dass du seine Logik änderst."], 5:["Was darf ein Quittierversuch bei noch heißem Motor auslösen, und was nicht?","Quittieren wirkt nur mit Flanke. Der Umrichter nimmt die Störung erst an, wenn die Ursache weg ist. Ein Impuls über nur einen Zyklus kann im Zwilling verloren gehen, weil die Ausgänge nicht in jedem Zyklus übertragen werden. Halte das Quittierbit deshalb, bis die Störung weg ist, aber nicht unbegrenzt.","Flanke −SF4 → bei Telegramm setzt du STW1.7 und hältst es, bis ZSW1.3 auf 0 fällt, höchstens aber 500 ms (TON als Multiinstanz, <code>#ACK_TIME</code> = T#500ms), dann setzt du es zurück. Bei TO gibst du eine Flanke an <code>MC_Reset.Execute</code>. Steht nach dem Quittierversuch ZSW1.3 weiter auf 1 und ZSW1.13 auf 0, zeigst du „Band 1 (−TA2): Motor überhitzt, abkühlen lassen, dann quittieren“."], 6:["Wo in deinem Programm könnte nach dem Quittieren ein neuer Fahrbefehl von selbst entstehen?","Prüfe beide Wege: <code>MC_Power.Enable</code> bleibt 1, und deine Logik erzeugt eine neue Flanke an <code>MC_MoveVelocity.Execute</code>; bzw. dein Telegramm-Baustein schreibt nach dem Quittieren selbst wieder das Betriebs-Steuerwort.","Jede Störung, jeder Not-Halt (−KF2 = 0) und HAND am Panel setzen den Laufbefehl <code>#statRun</code> in deinem FB <code>Conveyor</code> zurück. Gesetzt wird er nur durch eine neue START-Flanke. So entsteht nach dem Quittieren keine neue Bewegung."]},
 lf:[["Warum lässt sich F07011 nicht sofort quittieren, F30005 aber schon?",[2]],["Woran unterscheidet dein Programm eine Einschaltsperre durch Not-Halt von einer Einschaltsperre aus anderem Grund?",[0]],["Warum ist ein dauerhaft gesetztes Quittierbit keine Lösung?",[1]]],
 lfk:["Welche Bits von ZSW1 haben sich in den vier Fällen tatsächlich geändert? Stimmt das mit deiner Meldetexttabelle aus der Planung überein?"],
 pr:[["Alle vier Fälle mit eigener Meldung (Ort, Ursache, Abhilfe) gemeldet; Überlast und Motorübertemperatur unterscheiden sich",[0,2]],["F07011 vor dem Abkühlen quittieren → die Meldung bleibt stehen, mit dem Hinweis „abkühlen lassen“",[1,2]],["F30005 quittieren → Meldung weg, das Band steht und läuft erst nach einem neuen Startbefehl",[1]],["Not-Halt und Quittieren an −KF2 → kein Band läuft ohne neuen Startbefehl",[1]],["Störung an Band 2 → Rollenkurve und Band 1 geben keinen Korb an das stehende Band ab",[0]],["HAND am Bedienpanel → eigene Meldung „Vor-Ort-Führung“ statt einer Übergabestörung",[0]]],
 ergebnis:[{n:"Diagnosebaustein je Antrieb", a:"neu", h:"Multiinstanz, vier Fälle im Klartext"},{n:"Antriebsbaustein (DriveAxis oder DriveTelegram)", a:"erweitert", h:"Diagnose als Multiinstanz, Quittieren mit gehaltenem Impuls, kein Wiederanlauf ohne Start"},{n:"FB Conveyor (L23)", a:"erweitert", h:"sperrt die Übernahme bei Antriebsstörung"},{n:"Meldetexttabelle und Testprotokoll", a:"neu", h:"Grundlage für das Meldekonzept in L37"}],
 plus:"Erweitere die Diagnose um einen Störungszähler je Antrieb und die Dauer der letzten Störung (Zeit von der Meldung bis zum erfolgreichen Quittieren). Werte nach einer Testreihe aus, welcher Antrieb am häufigsten und am längsten stand.",
 tpls:[
 {id:"meldetexte", cap:"Meldetexttabelle Antriebsstörungen", phase:2, head:["Fall","Erkennung (Vermutung, dann geprüft)","Meldetext mit Ort, Ursache, Abhilfe","quittierbar","Reaktion der Anlage"], muster:["Beispiel L23: Motorschutz Band 1","−FA1 = 0","Band 1: Motorschutz −FA1 ausgelöst. Ursache prüfen, Schalter einschalten, quittieren","ja, nach dem Einschalten von −FA1","Band 1 steht, Vorgänger gibt keinen Korb ab"], rows:[["Überlast Umrichter F30005"],["Motor überhitzt F07011"],["Not-Halt (STO)"],["HAND am Bedienpanel"]], inputs:4},
 {id:"zsw", cap:"ZSW1 in den vier Fällen", phase:4, head:["Fall","ZSW1 hex","ZSW1 Bits 15 bis 0","geänderte Bits gegenüber Betrieb"], muster:["So trägst du ein","Wert aus der Beobachtungstabelle","Bit 15 links, Bit 0 rechts","z. B. Bit 3 = 1 (Störung wirksam)"], rows:[["Betrieb ohne Störung (Vergleich)"],["Überlast F30005"],["Motor überhitzt F07011"],["Not-Halt (STO)"],["HAND am Bedienpanel"]], inputs:3},
 {id:"test", cap:"Testprotokoll Antriebsstörungen", phase:4, head:["Fall","Meldung erschienen (Text)","Quittieren sofort möglich?","läuft ohne neuen Start an? (soll: nein)","i.O."], muster:["Beispiel L23: Motorschutz Band 1","Band 1: Motorschutz −FA1 ausgelöst. Ursache prüfen, Schalter einschalten, quittieren","nein, erst nach dem Einschalten von −FA1","nein","ja"], rows:[["Überlast F30005"],["Motor überhitzt F07011"],["Not-Halt (STO)"],["HAND am Bedienpanel"]], inputs:4}
]
,
 bezug:[
 {von:"L33", id:"zustand", phase:2, wozu:"Dein Zustandsprotokoll aus L33 zeigt ZSW1 im Normalbetrieb. Damit vergleichst du die Störfälle."}
]
}
