// Einstieg für esbuild. Die Importe legen die Ladereihenfolge fest (Schichten): Ein Modul darf nur aus Modulen
// importieren, die hier vor ihm stehen. Danach starten die Seiteneffekte (Listener, Migrationen, route()).
import './app/daten.js';
import './app/basis.js';
import './app/fortschritt.js';
import './editor/svg.js';
import './editor/status.js';
import './editor/registry.js';
import './editor/vorlagen-svg.js';
import './editor/bauteile.js';
import './editor/bausteine.js';
import './editor/vorlagen/alt.js';
import './editor/zeichnen.js';
import './editor/blaetter.js';
import './app/start.js';
import './app/skizzen-kacheln.js';
import './app/variablen.js';
import './app/uebung.js';
import './editor/editor.js';
import './app/druck.js';
import './app/seiten.js';
import './symbole/grund.js';
import './symbole/iec60617.js';
import './schaltplan/daten.js';
import './schaltplan/querverweise.js';
import './schaltplan/klemmen.js';
import './schaltplan/modell.js';
import './schaltplan/blatt.js';
import './schaltplan/tabellen.js';
import './schaltplan/seiten.js';
import './schaltplan/elemente.js';
import './schaltplan/kontaktspiegel.js';
import './schaltplan/analog.js';
import './schaltplan/pfade.js';
import './schaltplan/leistung.js';
import './schaltplan/liste.js';
import './schaltplan/deckblatt.js';
import './schaltplan/bloecke.js';
import './schaltplan/plan.js';
import { init as init_schaltplan_ansicht } from './schaltplan/ansicht.js';
import { init as init_app_tooltip } from './app/tooltip.js';
import { init as init_app_router } from './app/router.js';
import { init as init_app_ereignisse } from './app/ereignisse.js';
import { init as init_editor_ereignisse } from './editor/ereignisse.js';

init_editor_ereignisse();
init_app_ereignisse();
init_app_tooltip();
init_schaltplan_ansicht();
init_app_router();
