// Einstieg für esbuild. Die Importe legen die Ladereihenfolge fest (Schichten): Ein Modul darf nur aus Modulen
// importieren, die hier vor ihm stehen. Danach starten die Seiteneffekte (Listener, Migrationen, route()).
import './app/daten.js';
import './app/basis.js';
import './app/fortschritt.js';
// Schaltzeichen (reine Funktionen, gemeinsam mit dem Schaltplan)
import './symbole/grund.js';
import './symbole/iec60617.js';
import './editor/svg.js';
import './editor/datenpruefung.js';
import './editor/status.js';
import './editor/registry.js';
import './editor/spuren.js';
import './editor/vorlagen-svg.js';
import './editor/bauteile.js';
import './editor/bausteine.js';
import './editor/auswahl.js';
import './editor/kette.js';
import './editor/zeichnen.js';
import './editor/blaetter.js';
import './app/start.js';
import './app/skizzen-kacheln.js';
import './app/variablen.js';
import './app/vorlagen-basis.js';
import './app/vorlage-stand.js';
// init steht hier: Eine zweite Importzeile weiter unten würde die Ladereihenfolge (Schicht) verschieben
import { init as init_app_nachschlagen } from './app/nachschlagen.js';
import './app/uebung.js';
import { init as init_app_vorlage_popup } from './app/vorlage-popup.js';
import './editor/signalfeld.js';
import './editor/eigenschaften.js';
import './editor/anzeige.js';
import './editor/pruefung.js';
import './editor/verlauf.js';
import './editor/beschriften.js';
import './editor/werkzeuge.js';
import './editor/bearbeiten.js';
import './editor/andocken.js';
import './editor/zeiger.js';
import './editor/oeffnen.js';
import './editor/tastatur.js';
import './app/druck.js';
import './app/seiten.js';
import './app/unterlagen.js';
import './app/projekt.js';
// Vorlagen zuletzt: Sie melden sich nur in der Registry an und dürfen dafür alles aus dem Kern benutzen.
import './editor/vorlagen/grafcet-aktion.js';
import './editor/vorlagen/grafcet-kette.js';
import './editor/vorlagen/grafcet-schnipsel.js';
import './editor/vorlagen/grafcet-knoepfe.js';
import './editor/vorlagen/grafcet-pruefen.js';
import './editor/vorlagen/grafcet-spiel.js';
import './editor/vorlagen/grafcet.js';
import './editor/vorlagen/zustand.js';
import './editor/vorlagen/anlage-antriebe.js';
import './editor/vorlagen/wegschritt-striche.js';
import './editor/vorlagen/wegschritt-eingabe.js';
import './editor/vorlagen/wegschritt.js';
import './editor/vorlagen/elektro-kennzeichen.js';
import './editor/vorlagen/elektro-pfade.js';
import './editor/vorlagen/elektro-spiegel.js';
import './editor/vorlagen/elektro-simulation.js';
import './editor/vorlagen/elektro-pruefen.js';
import './editor/vorlagen/elektro-klemmen.js';
import './editor/vorlagen/elektro.js';
import './editor/vorlagen/elektro-geraete.js';
import './editor/vorlagen/leistung-pole.js';
import './editor/vorlagen/leistung.js';
import './editor/vorlagen/pneumatik-symbole.js';
import './editor/vorlagen/pneumatik-geraete.js';
import './editor/vorlagen/pneumatik-simstatus.js';
import './editor/vorlagen/pneumatik-simulation.js';
import './editor/vorlagen/pneumatik-antriebe.js';
import './editor/vorlagen/pneumatik-pruefen.js';
import './editor/vorlagen/pneumatik.js';
import './editor/vorlagen/regelkreis-glieder.js';
import './editor/vorlagen/regelkreis-bausteine.js';
import './editor/vorlagen/regelkreis-wege.js';
import './editor/vorlagen/regelkreis-simulation.js';
import './editor/vorlagen/regelkreis-pruefen.js';
import './editor/vorlagen/regelkreis.js';
import './editor/vorlagen/trend-striche.js';
import './editor/vorlagen/trend.js';
import './editor/vorlagen/raster.js';
import './schaltplan/daten.js';
import './schaltplan/querverweise.js';
import './schaltplan/klemmen.js';
import './schaltplan/modell.js';
import './schaltplan/blatt.js';
import './schaltplan/tabellen.js';
import './schaltplan/seiten.js';
import './schaltplan/elemente.js';
import './schaltplan/kontaktspiegel.js';
import './schaltplan/analog.js';
import './schaltplan/pfade.js';
import './schaltplan/leistung.js';
import './schaltplan/liste.js';
import './schaltplan/deckblatt.js';
import './schaltplan/bloecke.js';
import './schaltplan/plan.js';
import './schaltplan/zoom.js';
import { init as init_schaltplan_ansicht } from './schaltplan/ansicht.js';
import { init as init_app_tooltip } from './app/tooltip.js';
import { init as init_app_router } from './app/router.js';
import { init as init_app_ereignisse } from './app/ereignisse.js';
import { init as init_editor_ereignisse } from './editor/ereignisse.js';

init_editor_ereignisse();
init_app_ereignisse();
init_app_vorlage_popup();
init_app_nachschlagen();
init_app_tooltip();
init_schaltplan_ansicht();
init_app_router();
