// Stammdaten der Übung L13 (Felder siehe uebungVorlage.md). Langtexte in texte.json, Kurz-Checks in quiz.js.
{id:"L13", st:1, t:"Handbetrieb", sub:"Zylinder einzeln verfahren: Tippen und gespeicherte Stellung", ue:3, vor:"L12", repo:"4", bild:["03-schaltschrank.jpg","Tableau Handbetrieb an der Schaltschranktür"], typ:"programmieren",
 einst:"Übungsumfang: <i>Verzinnen: Portal −MM1…−MM4</i> = <i>SPS steuert</i>, <i>Band, Anschlag, Vereinzeler</i> = <i>Bandmodul automatisch</i>, <i>Zinnbad: Temperatur und Füllstand</i> = <i>Regler automatisch</i>, <i>Kühlwassertank: Nachspeisung</i> = <i>Niveauregler automatisch</i>. Quelle der Ausgänge unter <i>Verbindung</i>: <i>PLCSIM Advanced</i>. Jetzt schreibt dein Programm die Ventile −MB1 bis −MB8 des Portals. Steht −SA3 auf HAND, überlässt das Bandmodul den Anschlag −MM5 (−MB9) und den Vereinzeler −MM6 (−MB10) deinem Programm und hält Rollenkurve, Band 2 und Prüfstation an. Schreibst du −MB10 nicht, öffnet die Feder den Vereinzeler, und die Körbe stauen sich am Anschlag. Die Handtaster findest du auf dem Tableau an der Schaltschranktür (Seitenleiste: <i>Schaltschranktür −A1: Handbetrieb</i>).",
 ziele:["jeden Handtaster seinem Ventil und seiner Endlage zuordnen","bistabile und monostabile Ventile im Handbetrieb richtig ansteuern","Gefahren eines Handbetriebs ohne Verriegelung erkennen"],
 sig:"SA3 PF7 MB10 SF11 SF12 SF13 SF14 SF15 SF16 SF17 SF18 SF19 SF20 MB1 MB2 MB3 MB4 MB5 MB6 MB7 MB8 MB9 BG1 BG2 BG3 BG4 BG5 BG6 BG7 BG8 BG14 BG15",
 sit:"Bevor es einen Automatikablauf gibt, will der Inbetriebnehmer jede Bewegung einzeln fahren: Schaltet das richtige Ventil, kommt die richtige Endlage, sind die Drosseln sinnvoll eingestellt? Dafür bekommt die Anlage einen Handbetrieb. Mit dem Wahlschalter −SA3 an der Schaltschranktür auf HAND wirken die Handtaster des Tableaus.",
 tab:{cap:"Handtaster, Ventile, Endlagen", ...T(["Bewegung","Taster","Ventil","Endlage","Ventiltyp"],[["−MM1 einhängen / lösen","−SF11 / −SF12","−MB1 / −MB2","−BG1 / −BG2","5/2 bistabil"],["−MM2 senken / anheben","−SF13 / −SF14","−MB3 / −MB4","−BG4 / −BG3","5/2 bistabil"],["−MM3 zum Bad / zum Band","−SF15 / −SF16","−MB5 / −MB6","−BG6 / −BG5","5/2 bistabil"],["−MM4 abdecken / öffnen","−SF17 / −SF18","−MB7 / −MB8","−BG8 / −BG7","5/2 bistabil"],["−MM5 Anschlag öffnen / schließen","−SF19 / −SF20","−MB9","−BG15 / −BG14","5/2 monostabil, Feder schließt"]])},
 plan:["Lege die Schnittstelle des FB Manual in der Vorlage „Schnittstelle FB Manual“ fest: Die PLC-Variablen stehen schon drin, du vergibst Parameternamen, Datentyp und Bedeutung, auch für die statische Variable des Anschlags.","Ergänze die Vorlage „Ausgangsliste“ um −MB1 bis −MB9 und −PF7."],
 auf:["Lege einen FB <code>Manual</code> (Handbetrieb) mit Bausteinkopf an und rufe ihn im OB1 auf (Instanz-DB <code>InstManual</code>). Taster, −SA3, Ventile und −PF7 schließt du über die Schnittstelle an. Er wirkt nur, solange −SA3 auf HAND steht, −PF7 zeigt den Handbetrieb an.","Programmiere die bistabilen Ventile −MM1 bis −MM4 im Tippbetrieb: Die Spule ist nur angesteuert, solange der Taster gedrückt ist.","Monostabiles Ventil −MB9 (Anschlag −MM5): −SF19 öffnet, −SF20 schließt. Speichere die gewünschte Stellung als statische Variable <code>#statStopperOpen</code>, denn ohne Signal schließt die Feder sofort.","Programmiere die Gegentaster-Sperre: Werden beide Taster einer Bewegung zugleich gedrückt, wird keine Spule dieser Bewegung angesteuert.","Fahre jede Bewegung mit ihrem Taster und hake in der Vorlage „Tabelle Taster, Ventil, Endlage am Zwilling geprüft“ für jede Zeile ab, ob Ventil, Endlage und Richtung stimmen.","Prüfe in der Querverweisliste, dass jeder Ausgang −MB1 bis −MB9 und −PF7 genau eine schreibende Stelle hat.","Fahre bewusst eine gefährliche Kombination, z. B. −MM2 über dem Bad senken, während die Abdeckung geschlossen ist. Beobachte die 3D-Ansicht und die Ereignisse, trage das Ergebnis in die Vorlage „Liste gefährlicher Kombinationen (Vorarbeit für L14)“ ein. Sammle dort auch weitere Kombinationen, die dir auffallen, und setze danach die Anlage unter <i>Verbindung</i> zurück."],
 hilfe:{0:["Welche Signale braucht Manual, und welche liefert es? Woran erkennt Manual, dass es wirken darf?","Inputs: manualMode (−SA3) und je Taster ein Bool. Outputs: je Ventil ein Bool und lampManual. Jede Ventilbedingung beginnt mit manualMode UND.","Beispiel −MM2: <code>#valveLower := #manualMode AND #btnLower AND NOT #btnRaise; #valveRaise := #manualMode AND #btnRaise AND NOT #btnLower; #lampManual := #manualMode;</code> Im OB1: manualMode := \"SA3_Handbetrieb\", btnLower := \"SF13_MM2_Senken\", valveLower => \"MB3_Senken\" usw."], 2:["Was passiert mit −MB9, sobald du −SF19 loslässt, wenn du nur tippst?","Eine Flanke oder der Pegel von −SF19 setzt #statStopperOpen, −SF20 setzt zurück. Der Output folgt der statischen Variable, solange HAND aktiv ist.","<code>IF #btnStopperOpen AND NOT #btnStopperClose THEN #statStopperOpen := TRUE; ELSIF #btnStopperClose THEN #statStopperOpen := FALSE; END_IF; #valveStopperOpen := #manualMode AND #statStopperOpen;</code> Was beim Wechsel nach AUTO mit #statStopperOpen geschieht, entscheidest du in L15."], 3:["Wie verhinderst du, dass beide Spulen eines bistabilen Ventils gleichzeitig Strom bekommen?","Jede Spule bekommt die Bedingung „eigener Taster UND NICHT Gegentaster“.","Siehe −MM2 in Hilfe 3 zum ersten Schritt. Test: einen Taster im Signalmonitor auf 1 forcen, den anderen drücken, im Signalmonitor beide Ventilausgänge beobachten."]},
 lf:[["Warum genügt bei einem bistabilen Ventil Tippen, beim monostabilen −MB9 aber nicht?",[1]],["Was passiert mit einem bistabilen Ventil, wenn beide Spulen gleichzeitig angesteuert werden?",[1]],["Ein bistabiles Ventil wird nur angetippt. Warum fährt der Zylinder trotzdem bis in die Endlage, und was bedeutet das für den Handbetrieb?",[1,2]]],
 lfk:["Welche Bewegungen dürfen in welcher Lage nicht gefahren werden? Sammle deine Beobachtungen aus dem letzten Arbeitsschritt als Liste für L14. Welche Kombination hat der Zwilling selbst gestoppt, welche nicht?"],
 pr:[["Jede Bewegung fährt mit ihrem Taster und meldet die richtige Endlage",[0]],["−SA3 auf AUTO → Handtaster wirkungslos, −PF7 aus",[0]],["Einen Gegentaster im Signalmonitor auf 1 forcen, den anderen drücken → keine Spule angesteuert",[1]],["−MM5 bleibt nach −SF19 offen, schließt mit −SF20",[1]],["Tabelle Taster, Ventil, Endlage am Zwilling geprüft",[0]],["Querverweisliste: −MB1 bis −MB9 und −PF7 je genau eine schreibende Stelle",[2]],["Liste gefährlicher Kombinationen mit Beobachtung aus 3D-Ansicht und Ereignissen",[2]]],
 ergebnis:[{n:"FB Manual (InstManual)", a:"neu", h:"schreibt −MB1 bis −MB9 und −PF7, merkt sich die Stellung des Anschlags"},{n:"Liste gefährlicher Kombinationen", a:"neu", h:"Grundlage der Gefährdungsmatrix in L14"},{n:"Indication, BathMonitor, Counting, StartRelease, PlantData", a:"übernommen", h:"laufen unverändert weiter"}, {n:"Ausgangsliste", a:"erweitert", h:"neue Zeilen: −MB1, −MB2, −MB3, −MB4, −MB5 …"}],
 plus:"Miss die Fahrzeit jeder Bewegung im Handbetrieb mit ET eines TON wie im Plus von L04: Start mit dem Tastendruck, Ende mit der gemeldeten Endlage. Trage sie in deine Tabelle ein. Vergleiche Hin- und Rückweg und überlege, woran ein Unterschied liegen kann.",
 tpls:[
 {id:"schnitt", cap:"Schnittstelle FB Manual", phase:2, head:["Bereich","PLC-Variable","Parametername (deine Wahl)","Datentyp","Bedeutung"], muster:["Input","SF13_MM2_Senken","btnLower","Bool","Handtaster −MM2 senken, 1 = gedrückt"], rows:[["Input","SA3_Handbetrieb"],["Input","SF11_MM1_Einhaengen"],["Input","SF12_MM1_Loesen"],["Input","SF13_MM2_Senken"],["Input","SF14_MM2_Anheben"],["Input","SF15_MM3_Zinnbad"],["Input","SF16_MM3_Band"],["Input","SF17_MM4_Schliessen"],["Input","SF18_MM4_Oeffnen"],["Input","SF19_MM5_Oeffnen"],["Input","SF20_MM5_Schliessen"],["Output","MB1_Einhaengen"],["Output","MB2_Loesen"],["Output","MB3_Senken"],["Output","MB4_Anheben"],["Output","MB5_Zinnbad"],["Output","MB6_Foerderband"],["Output","MB7_Schliessen"],["Output","MB8_Oeffnen"],["Output","MB9_Anschlag_auf"],["Output","PF7_Handbetrieb"],["Static","keine (statStopperOpen)"]], inputs:3},
 {id:"schreib", erweitert:"L02:schreib", cap:"Ausgangsliste", phase:2, head:["Ausgang","Bedeutung","ab Übung","schreibt (Baustein, einzige Stelle)","Bedingung oder Befehl kommt von","in der Querverweisliste geprüft"], muster:["−PF2","Bad bereit","L02","FB Indication (bis L03 FC), Aufruf im OB1","−BG9 UND −BG10, ODER Lampentest −SF4","ja, eine Schreibstelle"], rows:[["−MB1","−MM1 einhängen","L13"],["−MB2","−MM1 lösen","L13"],["−MB3","−MM2 senken","L13"],["−MB4","−MM2 anheben","L13"],["−MB5","−MM3 zum Zinnbad","L13"],["−MB6","−MM3 zum Band","L13"],["−MB7","−MM4 abdecken","L13"],["−MB8","−MM4 öffnen","L13"],["−MB9","−MM5 Anschlag öffnen","L13"],["−PF7","Handbetrieb","L13"]], inputs:3},
 {id:"handtest", cap:"Tabelle Taster, Ventil, Endlage am Zwilling geprüft", phase:4, head:["Bewegung","Taster","Ventil","Endlage erwartet","Ventil schaltet (ja oder nein)","Endlage gemeldet (ja oder nein)","Richtung stimmt (ja oder nein)","Fahrzeit in s (nur im Plus)"], muster:["−MM3 zum Bad","−SF15","−MB5","−BG6","ja","ja","ja","Wert aus ET, z. B. 2,6"], rows:[["−MM1 einhängen","−SF11","−MB1","−BG1"],["−MM1 lösen","−SF12","−MB2","−BG2"],["−MM2 senken","−SF13","−MB3","−BG4"],["−MM2 anheben","−SF14","−MB4","−BG3"],["−MM3 zum Bad","−SF15","−MB5","−BG6"],["−MM3 zum Band","−SF16","−MB6","−BG5"],["−MM4 abdecken","−SF17","−MB7","−BG8"],["−MM4 öffnen","−SF18","−MB8","−BG7"],["−MM5 Anschlag öffnen","−SF19","−MB9 = 1","−BG15"],["−MM5 Anschlag schließen","−SF20","−MB9 = 0","−BG14"]], inputs:4},
 {id:"kombis", cap:"Liste gefährlicher Kombinationen (Vorarbeit für L14)", phase:4, head:["Bewegung (Taster)","Lage vorher (welche Endlagen melden)","Beobachtung in der 3D-Ansicht","Meldung unter Ereignisse (wörtlich)","stoppt der Zwilling selbst? (ja oder nein)"], muster:["−MM2 senken (−SF13)","über dem Bad (−BG6), Abdeckung geschlossen (−BG8)","Korb senkt bis auf die Abdeckung und bleibt dort stehen","Kollision: −MM2 senkt auf die geschlossene Badabdeckung (−BG7 fehlt)","ja"], rows:[], inputs:5, leer:8}
]
}
