// Englische Texte – 3D-Anlage: Beschriftungen in der Szene, Schilder, HMI-Bild im Schaltschrank.
// Schlüssel = deutscher Text wie im Quelltext (Leerraum egal), Werte in Vorlagen als {0}, {1} …
export default {
  // ---- 3D-Beschriftungen: Portal, Bad, Bänder ----
  '−MM1 Einhängen': '−MM1 Hook in',
  '−MM2 Tauchen': '−MM2 Dip',
  '−MM3 Verschieben': '−MM3 Traverse',
  '−MM4 Abstreifen': '−MM4 Cover',
  '−MM5 Anschlag': '−MM5 Stop',
  '−MM6 Vereinzeler': '−MM6 Separator',
  '−MM8 Kippen': '−MM8 Tip',
  'Energiekette Hub −MM2': 'Cable carrier lift −MM2',
  'Randabsaugung': 'Rim extraction',
  '−BG9 Temperatur': '−BG9 Temperature',
  '−BG10 Füllhöhe': '−BG10 Fill level',
  'Sn 99,3 · max. 300 °C': 'Sn 99.3 · max. 300 °C',
  'Lötbad 25 kg · 3,5 kW · 400 V 3~': 'Solder bath 25 kg · 3.5 kW · 400 V 3~',
  'Antrieb Band 1 −MA1': 'Drive conveyor 1 −MA1',
  'Antrieb Band 2 −MA2': 'Drive conveyor 2 −MA2',
  'Antrieb Rollenkurve −MA6': 'Drive roller curve −MA6',
  '−BG12 Bandanfang': '−BG12 Conveyor start',
  '−BG13 Band 1 Ende': '−BG13 Conveyor 1 end',
  '−BG18 Inkrementalgeber 10 Imp/U': '−BG18 Incremental encoder 10 ppr',
  '−BG27 Inkrementalgeber Band 2': '−BG27 Incremental encoder conveyor 2',
  '−BG21 Band 2 Anfang': '−BG21 Conveyor 2 start',
  '−BG22 Kühlplatz': '−BG22 Cooling position',
  '−BG24 Band 2 Ende': '−BG24 Conveyor 2 end',
  '−BG35 Kurve Anfang': '−BG35 Curve start',
  '−BG36 Kurve Ende': '−BG36 Curve end',
  'Ventilinsel Band −QM2': 'Valve terminal conveyor −QM2',
  'Ventilinsel −QM1': 'Valve terminal −QM1',
  'Ventilinsel −QM4': 'Valve terminal −QM4',
  'Wartungseinheit 6 bar': 'Air service unit 6 bar',
  'Wartungseinheit −AZ2': 'Air service unit −AZ2',
  'Einschaltventil': 'On/off valve',
  'Spule 14': 'Coil 14',
  'Spule 12': 'Coil 12',
  'Rollenkurve −MA6 (90°, konische Rollen, Rundriemen)': 'Roller curve −MA6 (90°, tapered rollers, round belts)',
  'Sprühkühlung (Abschrecken)': 'Spray cooling (quenching)',
  'Sprühventil −MB13': 'Spray valve −MB13',
  'Tank, Umwälzpumpe −MA3': 'Tank, circulation pump −MA3',
  '−BT2 Pyrometer Korbtemperatur': '−BT2 Pyrometer basket temperature',
  'Luftmesser −MB14': 'Air knife −MB14',
  'Kabelbrücke': 'Cable bridge',
  'Y-Verteiler BG1/BG2': 'Y-splitter BG1/BG2',
  '−XD1 Feldverteiler Portal': '−XD1 Field distributor gantry',
  '−XD2 Feldverteiler Bad': '−XD2 Field distributor bath',
  '−XD3 Feldverteiler Band': '−XD3 Field distributor conveyor',
  '−XD5 Feldverteiler Prüfstation': '−XD5 Field distributor inspection station',
  'Lichtvorhang −BG20 (anklicken = Person geht durch)': 'Light curtain −BG20 (click = person walks through)',
  'Signalsäule (PF1 · PF4 · PF3)': 'Signal tower (PF1 · PF4 · PF3)',
  'Ein Werker geht durch den Lichtvorhang in die Anlage': 'A worker walks through the light curtain into the plant',

  // ---- Prüfstation ----
  'Korbkipper −MM8': 'Basket tipper −MM8',
  'Muldenantrieb −MA7': 'Trough drive −MA7',
  '−BG37 Einlauf Mulde': '−BG37 Trough infeed',
  'Trichter': 'Hopper',
  'Vibrorinne −MA4': 'Vibratory chute −MA4',
  'Linearförderer': 'Linear feeder',
  '230 V · 50 Hz · 100 Hz Schwingung': '230 V · 50 Hz · 100 Hz vibration',
  'Schwingförderer': 'Vibratory feeder',
  'Steuergerät Vibrorinne −MA4': 'Controller vibratory chute −MA4',
  'Prüfband −MA5': 'Inspection conveyor −MA5',
  'Keyence CV-X Kamera −KF10': 'Keyence CV-X camera −KF10',
  'Ausblasdüse −MB16': 'Blow-off nozzle −MB16',
  'Ausschuss n.i.O.': 'Reject NOK',
  'KLT i.O.-Teile': 'KLT bin OK parts',
  '−BG34 KLT voll': '−BG34 KLT bin full',
  'Kabelkanal Prüfstation': 'Cable duct inspection station',
  'Druckluft 6 bar (Hallennetz)': 'Compressed air 6 bar (hall supply)',
  '−MB15 5/2 Kippen': '−MB15 5/2 tip',
  '−MB16 3/2 Düse': '−MB16 3/2 nozzle',

  // ---- Bedienpult und Vor-Ort-Steuerstellen ----
  'Bedienpult Rittal CP (Taster anklickbar)': 'Operator panel Rittal CP (pushbuttons clickable)',
  'Vor-Ort-Steuerstelle −S10': 'Local control station −S10',
  'Vor-Ort-Steuerstelle −S20': 'Local control station −S20',
  'Vor-Ort-Steuerstelle −S30': 'Local control station −S30',
  'Vor-Ort-Steuerstelle −S40': 'Local control station −S40',
  'EINZEL        AUTO': 'SINGLE        AUTO',
  'NOT-HALT': 'E-STOP',
  'BETRIEBSART': 'MODE',
  'QUITTIEREN': 'ACKNOWLEDGE',
  'BETRIEB': 'OPERATION',
  'Anlage läuft': 'Plant running',
  'MELDUNGEN': 'STATUS',
  'Temperatur': 'Temperature',
  'Füllhöhe unterschr.': 'Low fill level',
  'Korb vorhanden': 'Basket present',
  'Handbetrieb': 'Manual mode',
  'VOR-ORT': 'LOCAL',
  'Schlüssel': 'Key',
  'aktiv': 'active',
  '◀ LINKS': '◀ LEFT',
  'HALT': 'STOP',
  'RECHTS ▶': 'RIGHT ▶',
  'PRÜFUNG EIN': 'INSPECTION ON',
  'PRÜFUNG AUS': 'INSPECTION OFF',
  '◀ MULDE ZURÜCK': '◀ TROUGH BACK',
  'MULDE VOR ▶': 'TROUGH FWD ▶',
  'KIPPEN': 'TIP',
  'KIPPER ZURÜCK': 'TIPPER BACK',
  'QUITT.': 'ACK.',
  'Rückstellen': 'Reset',

  // ---- Schaltschrank −A1: Beschriftungen ----
  'Schaltschrank −A1': 'Control cabinet −A1',
  'Schaltschrank Zinnbad': 'Control cabinet tin bath',
  '−X0 Einspeisung 400 V': '−X0 Power supply 400 V',
  '−QB1 Hauptschalter': '−QB1 Main switch',
  '−FA1 Motorschutz Band': '−FA1 Motor protection conveyor',
  '−FA5 Motorschutz Band 2': '−FA5 Motor protection conveyor 2',
  '−FA6 Motorschutz Pumpe': '−FA6 Motor protection pump',
  '−FA7 Motorschutz Rollenkurve': '−FA7 Motor protection roller curve',
  '−FA8 Motorschutz Mulde': '−FA8 Motor protection trough',
  '−FA2 LS C16 Heizung': '−FA2 MCB C16 heater',
  '−FA3 LS B6': '−FA3 MCB B6',
  '−FA4 LS B6': '−FA4 MCB B6',
  '−TA1 Netzteil 24 V DC / 10 A': '−TA1 Power supply 24 V DC / 10 A',
  '−XD9 Servicesteckdose': '−XD9 Service socket',
  'PM 1507 Laststromversorgung': 'PM 1507 Load power supply',
  'Reserve 20 %': 'Spare 20 %',
  '−QA3 Heizung': '−QA3 Heater',
  '−QA7 Pumpe Sprühkühlung': '−QA7 Pump spray cooling',
  '−QA1/−QA2 Wendekombination Band (rechts | links)': '−QA1/−QA2 Reversing contactor conveyor (right | left)',
  '−QA5/−QA6 Wendekombination Band 2': '−QA5/−QA6 Reversing contactor conveyor 2',
  '−QA10/−QA11 Wendekombination Rollenkurve': '−QA10/−QA11 Reversing contactor roller curve',
  '−QA12/−QA13 Wendekombination Mulde': '−QA12/−QA13 Reversing contactor trough',
  '−KF10 Keyence CV-X Controller': '−KF10 Keyence CV-X controller',
  '−TB1 Halbleiterrelais Heizung': '−TB1 Solid-state relay heater',
  '−KF2 Sicherheitsrelais': '−KF2 Safety relay',
  '−KF3…−KF6 Koppelrelais': '−KF3…−KF6 Interface relays',
  '−X3 Eingänge': '−X3 Inputs',
  '−X4 Ausgänge': '−X4 Outputs',
  '−X5 Feld': '−X5 Field',
  '−XPE Schutzleiterschiene': '−XPE PE busbar',
  'Schirmauflage / Zugentlastung': 'Shield clamp / strain relief',
  'Tableau Handbetrieb (anklickbar)': 'Manual-mode panel (clickable)',
  'HMI TP1200 Comfort −PF10 (PROFINET)': 'HMI TP1200 Comfort −PF10 (PROFINET)',

  // ---- Tableau Handbetrieb (Schaltschranktür) ----
  'HANDBETRIEB': 'MANUAL MODE',
  'AUTO        HAND': 'AUTO      MANUAL',
  'Hand aktiv': 'Manual active',
  'einhängen': 'hook in',
  'lösen': 'release',
  'senken': 'lower',
  'anheben': 'lift',
  'zum Bad': 'to bath',
  'zum Band': 'to conveyor',
  'Bad zu': 'close bath',
  'Bad auf': 'open bath',
  'öffnen': 'open',
  'schließen': 'close',
  'kippen': 'tip',
  'zurück': 'back',

  // ---- HMI TP1200 (Prozessbild) ----
  'Zinnbad – Übersicht': 'Tin bath – Overview',
  'Betrieb': 'Operation',
  'HAND (Schaltschrank)': 'MANUAL (cabinet)',
  'AUTOMATIK': 'AUTOMATIC',
  'EINZELZYKLUS': 'SINGLE CYCLE',
  'Korb am Übergabeplatz': 'Basket at transfer point',
  'Schritt {0}: {1}': 'Step {0}: {1}',
  'Schritt: siehe SPS': 'Step: see PLC',
  'Grundstellung': 'Home position',
  'MM1 einhängen': 'MM1 hook in',
  'MM2 anheben': 'MM2 lift',
  'MM3 zum Bad': 'MM3 to bath',
  'Bad öffnen': 'Open bath',
  'Tauchen': 'Dip',
  'Abtropfen': 'Drip off',
  'Zum Band / Bad zu': 'To conv. / close bath',
  'Absenken': 'Lower',
  'Korb lösen': 'Release basket',
  'Verzinnt: {0}': 'Tinned: {0}',
  'Zinnbad': 'Tin bath',
  'Füllstand {0} %': 'Fill level {0} %',
  'Heizung −TB1': 'Heater −TB1',
  'SPS regelt': 'PLC controls',
  'Endlagen': 'End positions',
  'ein': 'in',
  'gelöst': 'released',
  'oben': 'up',
  'unten': 'down',
  'Band': 'conveyor',
  'Bad': 'bath',
  'auf': 'open',
  'zu': 'closed',
  'Förderband': 'Conveyor',
  '→  vorwärts': '→  forward',
  '←  rückwärts': '←  reverse',
  'Halt': 'Stop',
  'Band: {0} {1} mm/s Weg {2} m': 'Conveyor: {0}   {1} mm/s   Travel {2} m',
  'Vor-Ort aktiv': 'Local active',
  'SPS steuert': 'PLC controls',
  'EIN': 'ON',
  'AUS': 'OFF',
  'Kurve: {0} {1} · Band 2: {2} {3} · Mulde: {4} · Kühlplatz {5} · Sprühen {6} · KLT {7}/{8} · Ausschuss {9}':
    'Curve: {0} {1} · Conveyor 2: {2} {3} · Trough: {4} · Cooling pos. {5} · Spray {6} · KLT {7}/{8} · Reject {9}',
  'NOT-HALT {0} – entriegeln und quittieren ({1})': 'E-STOP {0} – release and acknowledge ({1})',
  'Lichtvorhang −BG20 unterbrochen – Schutzfeld räumen und quittieren (−SF4)': 'Light curtain −BG20 interrupted – clear the protective field and acknowledge (−SF4)',
  'NOT-HALT entriegelt – quittieren (−SF4 oder Vor-Ort −SF41…−SF44)': 'E-STOP released – acknowledge (−SF4 or local −SF41…−SF44)',
  'Keine Störung': 'No fault',

  // ---- Display CPU 1516 ----
  'Demo: Steuerung im Browser': 'Demo: control in browser',
  'Übersicht': 'Overview',
  'Diagnose': 'Diagnost.',
  'Einstell.': 'Settings',
  'Module': 'Modules',
};
