// Englische Texte – Kommentare der Signalliste (signale.csv / signale.js).
// Schlüssel = deutscher Text wie im Quelltext (Leerraum egal), Werte in Vorlagen als {0}, {1} …
export default {
  // --- nur in TIA/PLC_Variablen_Zinnbad.xlsx anders formuliert ---
  'Lichtschranke Korb am Bandende': 'Light barrier basket at conveyor end',
  'Lichtschranke Band 2 Anfang (Uebergabe)': 'Light barrier conveyor 2 start (transfer)',
  'Lichtschranke Band 2 Ende (Entnahme)': 'Light barrier conveyor 2 end (removal)',
  // --- signale.csv, Excel-feste Fassung (kein - am Anfang, kein ; im Kommentar) ---
  'Einhaengezylinder -MM1: Korb einhaengen (faehrt ein, Haken schwenkt unter den Buegel)': '-MM1 hook-in cylinder: hook in basket (retracts, hook swings under the bail)',
  'Einhaengezylinder -MM1: Korb loesen (faehrt aus, Haken schwenkt frei)': '-MM1 hook-in cylinder: release basket (extends, hook swings clear)',
  'Tauchzylinder -MM2: senken (faehrt aus)': '-MM2 dip cylinder: lower (extends)',
  'Tauchzylinder -MM2: anheben (faehrt ein)': '-MM2 dip cylinder: lift (retracts)',
  'Verschiebezylinder -MM3: zum Zinnbad (faehrt aus)': '-MM3 traverse cylinder: to tin bath (extends)',
  'Verschiebezylinder -MM3: zum Foerderband (faehrt ein)': '-MM3 traverse cylinder: to conveyor (retracts)',
  'Abstreifzylinder -MM4: Bad abdecken (faehrt aus)': '-MM4 cover cylinder: cover bath (extends)',
  'Abstreifzylinder -MM4: Bad oeffnen (faehrt ein)': '-MM4 cover cylinder: open bath (retracts)',
  'Anschlag -MM5 Uebergabeplatz oeffnen (5/2 monostabil, Feder schliesst)': '-MM5 open stop at transfer position (5/2 monostable, spring closes)',
  'Vereinzeler -MM6 sperren (5/2 monostabil, Feder oeffnet)': '-MM6 block separator (5/2 monostable, spring opens)',
  'Korbkipper -MM8 kippen (5/2 monostabil)': '-MM8 tip basket tipper (5/2 monostable)',
  'Endlage -MM1 eingefahren = Korb eingehaengt': '-MM1 retracted = basket hooked in',
  'Endlage -MM1 ausgefahren = Haken geloest (Grundstellung)': '-MM1 extended = hook released (home position)',
  'Endlage -MM2 eingefahren = angehoben': '-MM2 retracted = lifted',
  'Endlage -MM2 ausgefahren = abgesenkt (Grundstellung)': '-MM2 extended = lowered (home position)',
  'Endlage -MM3 eingefahren = ueber Foerderband (Grundstellung)': '-MM3 retracted = above conveyor (home position)',
  'Endlage -MM3 ausgefahren = ueber Zinnbad': '-MM3 extended = above tin bath',
  'Endlage -MM4 eingefahren = Bad offen': '-MM4 retracted = bath open',
  'Endlage -MM4 ausgefahren = Bad abgedeckt (Grundstellung)': '-MM4 extended = bath covered (home position)',
  'Anschlag -MM5 geschlossen (Finger ueber dem Band)': '-MM5 stop closed (finger above the conveyor)',
  'Anschlag -MM5 offen': '-MM5 stop open',
  'Vereinzeler -MM6 geschlossen (sperrt)': '-MM6 separator closed (blocking)',
  'Vereinzeler -MM6 offen': '-MM6 separator open',
  'Inkrementalgeber Band Spur B (90 Grad versetzt, vorwaerts: B = 1 bei steigender Flanke A)': 'Incremental encoder conveyor track B (offset by 90 deg, forward: B = 1 on rising edge of A)',
  'Sicherheitslichtvorhang -BG20 Schutzfeld frei (1 = frei, Abschaltung ueber -KF2)': 'Safety light curtain -BG20 protective field clear (1 = clear, shutdown via -KF2)',
  'Kipper -MM8 unten (Grundstellung)': '-MM8 tipper down (home position)',
  'Kipper -MM8 gekippt': '-MM8 tipper tipped',
  // --- signale.csv (ASCII, kommt über die Bridge) ---
  '-MM1 Einhaengezylinder: Korb einhaengen (faehrt ein, Haken schwenkt unter den Buegel)': '-MM1 hook-in cylinder: hook in basket (retracts, hook swings under the bail)',
  '-MM1 Einhaengezylinder: Korb loesen (faehrt aus, Haken schwenkt frei)': '-MM1 hook-in cylinder: release basket (extends, hook swings clear)',
  '-MM2 Tauchzylinder: senken (faehrt aus)': '-MM2 dip cylinder: lower (extends)',
  '-MM2 Tauchzylinder: anheben (faehrt ein)': '-MM2 dip cylinder: lift (retracts)',
  '-MM3 Verschiebezylinder: zum Zinnbad (faehrt aus)': '-MM3 traverse cylinder: to tin bath (extends)',
  '-MM3 Verschiebezylinder: zum Foerderband (faehrt ein)': '-MM3 traverse cylinder: to conveyor (retracts)',
  '-MM4 Abstreifzylinder: Bad abdecken (faehrt aus)': '-MM4 cover cylinder: cover bath (extends)',
  '-MM4 Abstreifzylinder: Bad oeffnen (faehrt ein)': '-MM4 cover cylinder: open bath (retracts)',
  'Meldeleuchte Anlage laeuft (Automatik-Dauerbetrieb aktiv)': 'Indicator lamp plant running (automatic continuous mode active)',
  'Meldeleuchte Zinnbad Betriebstemperatur erreicht': 'Indicator lamp tin bath operating temperature reached',
  'Meldeleuchte Fuellhoehe unterschritten': 'Indicator lamp fill level below minimum',
  'Meldeleuchte Materialkorb vorhanden': 'Indicator lamp material basket present',
  'Leuchttaster Quittieren -SF4 Bedienpult (blinkt: Not-Halt quittieren)': 'Illuminated acknowledge button -SF4 operator panel (flashing: acknowledge E-stop)',
  'Leuchte Vor-Ort-Steuerstelle aktiv': 'Indicator lamp local control station active',
  'Leuchte Handbetrieb aktiv (Schaltschranktuer)': 'Indicator lamp manual mode active (control cabinet door)',
  'Schuetz Bandmotor Rechtslauf (Foerderrichtung)': 'Contactor conveyor motor forward (conveying direction)',
  'Schuetz Bandmotor Linkslauf (Wendeschuetz, mech. verriegelt)': 'Contactor conveyor motor reverse (reversing contactor, mech. interlocked)',
  '-MM5 Anschlag Uebergabeplatz oeffnen (5/2 monostabil, Feder schliesst)': '-MM5 open stop at transfer position (5/2 monostable, spring closes)',
  '-MM6 Vereinzeler sperren (5/2 monostabil, Feder oeffnet)': '-MM6 block separator (5/2 monostable, spring opens)',
  'Heizung Zinnbad ueber Halbleiterrelais (2-Punkt oder Impuls/PWM)': 'Tin bath heater via solid-state relay (on/off or pulse/PWM)',
  'Zinn-Nachfuelleinrichtung oeffnen (ca. 2 %/s)': 'Open tin refill unit (approx. 2 %/s)',
  'Schuetz Band 2 Rechtslauf (Foerderrichtung)': 'Contactor conveyor 2 forward (conveying direction)',
  'Schuetz Band 2 Linkslauf (Wendeschuetz, mech. verriegelt)': 'Contactor conveyor 2 reverse (reversing contactor, mech. interlocked)',
  'Schuetz Rollenkurve -MA6 Rechtslauf (Foerderrichtung)': 'Contactor roller curve -MA6 forward (conveying direction)',
  'Schuetz Umwaelzpumpe Spruehkuehlung -MA3': 'Contactor spray cooling circulation pump -MA3',
  'Keyence CV-X Trigger je Teil (Flanke)': 'Keyence CV-X trigger per part (edge)',
  'Leuchte Vor-Ort-Steuerstelle Band 2 aktiv': 'Indicator lamp local control station conveyor 2 active',
  'Spruehventil Abschrecken (wirkt nur bei laufender Pumpe -QA7)': 'Quenching spray valve (only effective while pump -QA7 is running)',
  'Luftmesser am Tunnelauslauf (blaest das Wasser ab)': 'Air knife at tunnel exit (blows off the water)',
  '-MM8 Korbkipper kippen (5/2 monostabil)': '-MM8 tip basket tipper (5/2 monostable)',
  'Vibrorinne -MA4 (vereinzelt die Teile)': 'Vibratory chute -MA4 (separates the parts)',
  'Pruefband -MA5': 'Inspection conveyor -MA5',
  'Ausblasduese n.i.O.-Teile in den Ausschussbehaelter': 'Blow-off nozzle for NOK parts into the reject bin',
  'Schuetz Rollenkurve -MA6 Linkslauf (Wendeschuetz, mech. verriegelt)': 'Contactor roller curve -MA6 reverse (reversing contactor, mech. interlocked)',
  'Leuchte Vor-Ort-Steuerstelle -S30 Rollenkurve aktiv': 'Indicator lamp local control station -S30 roller curve active',
  'Schuetz Muldenrollen -MA7 vorwaerts zum Endanschlag (Wendeschuetz, mech. verriegelt)': 'Contactor trough rollers -MA7 forward to end stop (reversing contactor, mech. interlocked)',
  'Schuetz Muldenrollen -MA7 zurueck (Wendeschuetz, mech. verriegelt)': 'Contactor trough rollers -MA7 backward (reversing contactor, mech. interlocked)',
  'Leuchte Vor-Ort-Steuerstelle -S40 Pruefstation aktiv': 'Indicator lamp local control station -S40 inspection station active',
  'Leuchttaster Quittieren -SF41 an -S10 (blinkt: Not-Halt quittieren)': 'Illuminated acknowledge button -SF41 at -S10 (flashing: acknowledge E-stop)',
  'Leuchttaster Quittieren -SF42 an -S20 (blinkt: Not-Halt quittieren)': 'Illuminated acknowledge button -SF42 at -S20 (flashing: acknowledge E-stop)',
  'Leuchttaster Quittieren -SF43 an -S30 (blinkt: Not-Halt quittieren)': 'Illuminated acknowledge button -SF43 at -S30 (flashing: acknowledge E-stop)',
  'Leuchttaster Quittieren -SF44 an -S40 (blinkt: Not-Halt quittieren)': 'Illuminated acknowledge button -SF44 at -S40 (flashing: acknowledge E-stop)',
  '-MM1 eingefahren = Korb eingehaengt': '-MM1 retracted = basket hooked in',
  '-MM1 ausgefahren = Haken geloest (Grundstellung)': '-MM1 extended = hook released (home position)',
  '-MM2 eingefahren = angehoben': '-MM2 retracted = lifted',
  '-MM2 ausgefahren = abgesenkt (Grundstellung)': '-MM2 extended = lowered (home position)',
  '-MM3 eingefahren = ueber Foerderband (Grundstellung)': '-MM3 retracted = above conveyor (home position)',
  '-MM3 ausgefahren = ueber Zinnbad': '-MM3 extended = above tin bath',
  '-MM4 eingefahren = Bad offen': '-MM4 retracted = bath open',
  '-MM4 ausgefahren = Bad abgedeckt (Grundstellung)': '-MM4 extended = bath covered (home position)',
  'Betriebstemperatur Zinn erreicht (1 = ok, ab 250 Grad C)': 'Tin operating temperature reached (1 = ok, from 250 deg C)',
  'Fuellhoehe Zinnbad ausreichend (1 = ok, ab 40 %)': 'Tin bath fill level sufficient (1 = ok, from 40 %)',
  'Lichtschranke Einlauf Uebergabeplatz (Korb kommt, liegt aber noch nicht am Anschlag)': 'Light barrier transfer point inlet (basket arriving, not yet resting against the stop)',
  'Korb liegt am Anschlag -MM5 an (induktiver Sensor M12 buendig in der Anschlagleiste)': 'Basket resting against stop -MM5 (inductive M12 sensor flush in the stop bar)',
  'Anschlag -MM5 offen (90 Grad, erst dann Korb anheben oder absenken)': 'Stop -MM5 open (90 deg, only then lift or lower the basket)',
  'Taster START (Schliesser)': 'START button (NO contact)',
  'Taster STOP (Oeffner: 1 = nicht betaetigt)': 'STOP button (NC contact: 1 = not pressed)',
  'Wahlschalter Schaltschranktuer (1 = Hand, 0 = Auto)': 'Selector switch control cabinet door (1 = manual, 0 = auto)',
  'Sicherheitsrelais -KF2 Rueckmeldung (1 = Freigabe, 0 = Not-Halt)': 'Safety relay -KF2 feedback (1 = enabled, 0 = E-stop)',
  'Taster Quittieren Bedienpult (Schliesser, parallel auf -KF2 Start)': 'Acknowledge button operator panel (NO contact, parallel to -KF2 start)',
  'Wahlschalter Betriebsart (1 = Automatik/Dauer, 0 = Einzelzyklus)': 'Mode selector switch (1 = automatic/continuous, 0 = single cycle)',
  'Schluesselschalter Vor-Ort-Steuerstelle -S10 (1 = aktiv)': 'Key switch local control station -S10 (1 = active)',
  'Vor-Ort Taster Band Rechtslauf (Schliesser)': 'Local button conveyor forward (NO contact)',
  'Vor-Ort Taster Band Linkslauf (Schliesser)': 'Local button conveyor reverse (NO contact)',
  'Vor-Ort Taster Band Halt (Oeffner: 1 = nicht betaetigt)': 'Local button conveyor stop (NC contact: 1 = not pressed)',
  'Lichtschranke Korb am Bandanfang': 'Light barrier basket at conveyor start',
  'Lichtschranke Korb am Ende von Band 1 (Uebergabe an die Rollenkurve)': 'Light barrier basket at end of conveyor 1 (transfer to roller curve)',
  'Motorschutzschalter Band Hilfskontakt (1 = OK)': 'Motor protection switch conveyor, auxiliary contact (1 = OK)',
  'Handtaster -MM1 einhaengen': 'Manual button -MM1 hook in',
  'Handtaster -MM1 loesen': 'Manual button -MM1 release',
  'Handtaster -MM2 senken': 'Manual button -MM2 lower',
  'Handtaster -MM2 anheben': 'Manual button -MM2 lift',
  'Handtaster -MM3 zum Zinnbad': 'Manual button -MM3 to tin bath',
  'Handtaster -MM3 zum Band': 'Manual button -MM3 to conveyor',
  'Handtaster -MM4 Bad abdecken': 'Manual button -MM4 cover bath',
  'Handtaster -MM4 Bad oeffnen': 'Manual button -MM4 open bath',
  '-MM5 Anschlag geschlossen (Finger ueber dem Band)': '-MM5 stop closed (finger above the conveyor)',
  '-MM5 Anschlag offen': '-MM5 stop open',
  '-MM6 Vereinzeler geschlossen (sperrt)': '-MM6 separator closed (blocking)',
  '-MM6 Vereinzeler offen': '-MM6 separator open',
  'Inkrementalgeber Band Spur A (10 Imp/U, 24,5 mm Bandweg je Impuls)': 'Incremental encoder conveyor track A (10 pulses/rev, 24.5 mm conveyor travel per pulse)',
  'Inkrementalgeber Band Spur B (90 Grad versetzt; vorwaerts: B = 1 bei steigender Flanke A)': 'Incremental encoder conveyor track B (offset by 90 deg; forward: B = 1 on rising edge of A)',
  'Inkrementalgeber Band Nullimpuls (1 je Umdrehung = 245 mm)': 'Incremental encoder conveyor zero pulse (1 per revolution = 245 mm)',
  'Handtaster -MM5 Anschlag oeffnen': 'Manual button -MM5 open stop',
  'Handtaster -MM5 Anschlag schliessen': 'Manual button -MM5 close stop',
  'Handtaster -MM6 Vereinzeler schliessen': 'Manual button -MM6 close separator',
  'Handtaster -MM6 Vereinzeler oeffnen': 'Manual button -MM6 open separator',
  'Sicherheitslichtvorhang -BG20 Schutzfeld frei (1 = frei; Abschaltung ueber -KF2)': 'Safety light curtain -BG20 protective field clear (1 = clear; shutdown via -KF2)',
  'Lichtschranke Band 2 Anfang (Korb von der Rollenkurve uebernommen)': 'Light barrier conveyor 2 start (basket taken over from roller curve)',
  'Lichtschranke Kuehlplatz': 'Light barrier cooling station',
  'Lichtschranke Teil am Kameraplatz (Pruefband)': 'Light barrier part at camera position (inspection conveyor)',
  'Lichtschranke Band 2 Ende (Korb an der Uebergabe zur Kippmulde)': 'Light barrier conveyor 2 end (basket at transfer to tipping trough)',
  'Lichtschranke Rollenkurve Anfang (Korb von Band 1 uebernommen)': 'Light barrier roller curve start (basket taken over from conveyor 1)',
  'Lichtschranke Rollenkurve Ende (Korb vor der Uebergabe auf Band 2)': 'Light barrier roller curve end (basket before transfer to conveyor 2)',
  'Inkrementalgeber Band 2 Spur A (10 Imp/U)': 'Incremental encoder conveyor 2 track A (10 pulses/rev)',
  'Inkrementalgeber Band 2 Spur B (90 Grad versetzt)': 'Incremental encoder conveyor 2 track B (offset by 90 deg)',
  'Inkrementalgeber Band 2 Nullimpuls': 'Incremental encoder conveyor 2 zero pulse',
  'Keyence CV-X Ergebnis Teil i.O. (0,3 s gueltig)': 'Keyence CV-X result part OK (valid for 0.3 s)',
  'Keyence CV-X Ergebnis Teil n.i.O. (0,3 s gueltig)': 'Keyence CV-X result part NOK (valid for 0.3 s)',
  'Schluesselschalter Vor-Ort-Steuerstelle -S20 (1 = aktiv)': 'Key switch local control station -S20 (1 = active)',
  'Vor-Ort Band 2 Rechtslauf (Schliesser)': 'Local conveyor 2 forward (NO contact)',
  'Vor-Ort Band 2 Linkslauf (Schliesser)': 'Local conveyor 2 reverse (NO contact)',
  'Vor-Ort Band 2 Halt (Oeffner: 1 = nicht betaetigt)': 'Local conveyor 2 stop (NC contact: 1 = not pressed)',
  'Motorschutzschalter Band 2 Hilfskontakt (1 = OK)': 'Motor protection switch conveyor 2, auxiliary contact (1 = OK)',
  '-MM8 Kipper unten (Grundstellung)': '-MM8 tipper down (home position)',
  '-MM8 Kipper gekippt': '-MM8 tipper tipped',
  'Korb am Endanschlag der Kippmulde': 'Basket at end stop of tipping trough',
  'KLT i.O.-Teile voll (144 Teile)': 'KLT bin for OK parts full (144 parts)',
  'Handtaster -MM8 Kipper kippen': 'Manual button -MM8 tip tipper',
  'Handtaster -MM8 Kipper zurueck': 'Manual button -MM8 tipper back',
  'Schluesselschalter Vor-Ort-Steuerstelle -S30 (1 = aktiv)': 'Key switch local control station -S30 (1 = active)',
  'Vor-Ort Rollenkurve Rechtslauf (Schliesser)': 'Local roller curve forward (NO contact)',
  'Vor-Ort Rollenkurve Linkslauf (Schliesser)': 'Local roller curve reverse (NO contact)',
  'Vor-Ort Rollenkurve Halt (Oeffner: 1 = nicht betaetigt)': 'Local roller curve stop (NC contact: 1 = not pressed)',
  'Motorschutzschalter Rollenkurve -FA7 Hilfskontakt (1 = OK)': 'Motor protection switch roller curve -FA7, auxiliary contact (1 = OK)',
  'Not-Halt -SF0 Bedienpult Meldekontakt (Oeffner: 1 = entriegelt, 0 = betaetigt)': 'E-stop -SF0 operator panel, signaling contact (NC contact: 1 = released, 0 = pressed)',
  'Not-Halt -SF8 Vor-Ort -S10 Band 1 Meldekontakt (Oeffner: 1 = entriegelt, 0 = betaetigt)': 'E-stop -SF8 local -S10 conveyor 1, signaling contact (NC contact: 1 = released, 0 = pressed)',
  'Not-Halt -SF9 Vor-Ort -S20 Band 2 Meldekontakt (Oeffner: 1 = entriegelt, 0 = betaetigt)': 'E-stop -SF9 local -S20 conveyor 2, signaling contact (NC contact: 1 = released, 0 = pressed)',
  'Not-Halt -SF10 Vor-Ort -S30 Rollenkurve Meldekontakt (Oeffner: 1 = entriegelt, 0 = betaetigt)': 'E-stop -SF10 local -S30 roller curve, signaling contact (NC contact: 1 = released, 0 = pressed)',
  'Not-Halt -SF33 Vor-Ort -S40 Pruefstation Meldekontakt (Oeffner: 1 = entriegelt, 0 = betaetigt)': 'E-stop -SF33 local -S40 inspection station, signaling contact (NC contact: 1 = released, 0 = pressed)',
  'Schluesselschalter Vor-Ort-Steuerstelle -S40 (1 = aktiv, Automatik der Station ruht)': 'Key switch local control station -S40 (1 = active, station automatic paused)',
  'Vor-Ort -S40 Vibrorinne + Pruefband EIN (Schliesser, Selbsthaltung in der SPS)': 'Local -S40 vibratory chute + inspection conveyor ON (NO contact, latching in the PLC)',
  'Vor-Ort -S40 Vibrorinne + Pruefband AUS (Oeffner: 1 = nicht betaetigt)': 'Local -S40 vibratory chute + inspection conveyor OFF (NC contact: 1 = not pressed)',
  'Vor-Ort -S40 Muldenrollen vorwaerts tippen (Schliesser)': 'Local -S40 jog trough rollers forward (NO contact)',
  'Vor-Ort -S40 Muldenrollen zurueck tippen (Schliesser)': 'Local -S40 jog trough rollers backward (NO contact)',
  'Vor-Ort -S40 Kipper kippen (Schliesser, nur mit Korb an -BG33 oder leerer Mulde)': 'Local -S40 tip tipper (NO contact, only with basket at -BG33 or empty trough)',
  'Vor-Ort -S40 Kipper zurueck (Schliesser)': 'Local -S40 tipper back (NO contact)',
  'Motorschutzschalter Muldenantrieb -MA7 -FA8 Hilfskontakt (1 = OK)': 'Motor protection switch trough drive -MA7 -FA8, auxiliary contact (1 = OK)',
  'Taster Quittieren Vor-Ort -S10 Band 1 (Schliesser, parallel zu -SF4 an -KF2)': 'Acknowledge button local -S10 conveyor 1 (NO contact, parallel to -SF4 on -KF2)',
  'Taster Quittieren Vor-Ort -S20 Band 2 (Schliesser, parallel zu -SF4 an -KF2)': 'Acknowledge button local -S20 conveyor 2 (NO contact, parallel to -SF4 on -KF2)',
  'Taster Quittieren Vor-Ort -S30 Rollenkurve (Schliesser, parallel zu -SF4 an -KF2)': 'Acknowledge button local -S30 roller curve (NO contact, parallel to -SF4 on -KF2)',
  'Taster Quittieren Vor-Ort -S40 Pruefstation (Schliesser, parallel zu -SF4 an -KF2)': 'Acknowledge button local -S40 inspection station (NO contact, parallel to -SF4 on -KF2)',
  'Lichtschranke Einlauf Kippmulde (Korb in der Mulde, schwenkt mit)': 'Light barrier tipping trough inlet (basket in trough, swivels with it)',
  'Zinntemperatur analog 0...27648 = 0...400 Grad C': 'Tin temperature analog 0...27648 = 0...400 deg C',
  'Fuellstand analog 0...27648 = 0...100 %': 'Fill level analog 0...27648 = 0...100 %',
  'Pyrometer Kuehlplatz: Korbtemperatur 0...27648 = 0...400 Grad C': 'Pyrometer cooling station: basket temperature 0...27648 = 0...400 deg C',

  // --- signale.js (Standardliste ohne Bridge) ---
  '−MM1 Korb einhängen': '−MM1 hook in basket',
  '−MM1 Korb lösen': '−MM1 release basket',
  '−MM2 senken': '−MM2 lower',
  '−MM2 anheben': '−MM2 lift',
  '−MM3 zum Zinnbad': '−MM3 to tin bath',
  '−MM3 zum Förderband': '−MM3 to conveyor',
  '−MM4 Bad abdecken': '−MM4 cover bath',
  '−MM4 Bad öffnen': '−MM4 open bath',
  'Leuchte Automatik EIN': 'Indicator lamp automatic ON',
  'Leuchte Betriebstemperatur': 'Indicator lamp operating temperature',
  'Leuchte Füllhöhe unterschritten': 'Indicator lamp fill level below minimum',
  'Leuchte Materialkorb vorhanden': 'Indicator lamp material basket present',
  'Leuchttaster Quittieren': 'Illuminated acknowledge button',
  'Leuchte Handbetrieb aktiv (Schaltschranktür)': 'Indicator lamp manual mode active (control cabinet door)',
  'Schütz Bandmotor Rechtslauf (Förderrichtung)': 'Contactor conveyor motor forward (conveying direction)',
  'Schütz Bandmotor Linkslauf': 'Contactor conveyor motor reverse',
  'Anschlag Übergabeplatz öffnen (Feder schließt)': 'Open stop at transfer position (spring closes)',
  'Vereinzeler sperren (Feder öffnet)': 'Block separator (spring opens)',
  'Heizung Zinnbad (Halbleiterrelais)': 'Tin bath heater (solid-state relay)',
  'Zinn-Nachfülleinrichtung öffnen': 'Open tin refill unit',
  'Schütz Band 2 Rechtslauf (Förderrichtung)': 'Contactor conveyor 2 forward (conveying direction)',
  'Schütz Band 2 Linkslauf': 'Contactor conveyor 2 reverse',
  'Schütz Rollenkurve −MA6 Rechtslauf (Förderrichtung)': 'Contactor roller curve −MA6 forward (conveying direction)',
  'Schütz Rollenkurve −MA6 Linkslauf': 'Contactor roller curve −MA6 reverse',
  'Leuchte Vor-Ort-Steuerstelle Rollenkurve aktiv': 'Indicator lamp local control station roller curve active',
  'Schütz Muldenrollen −MA7 vorwärts (zum Endanschlag)': 'Contactor trough rollers −MA7 forward (to end stop)',
  'Schütz Muldenrollen −MA7 zurück': 'Contactor trough rollers −MA7 backward',
  'Leuchte Vor-Ort-Steuerstelle Prüfstation −S40 aktiv': 'Indicator lamp local control station inspection station −S40 active',
  'Leuchttaster Quittieren −SF41 an −S10 (blinkt: quittieren)': 'Illuminated acknowledge button −SF41 at −S10 (flashing: acknowledge)',
  'Leuchttaster Quittieren −SF42 an −S20 (blinkt: quittieren)': 'Illuminated acknowledge button −SF42 at −S20 (flashing: acknowledge)',
  'Leuchttaster Quittieren −SF43 an −S30 (blinkt: quittieren)': 'Illuminated acknowledge button −SF43 at −S30 (flashing: acknowledge)',
  'Leuchttaster Quittieren −SF44 an −S40 (blinkt: quittieren)': 'Illuminated acknowledge button −SF44 at −S40 (flashing: acknowledge)',
  'Umwälzpumpe Sprühkühlung −MA3': 'Spray cooling circulation pump −MA3',
  'Sprühventil Abschrecken (nur mit laufender Pumpe)': 'Quenching spray valve (only with pump running)',
  'Luftmesser abblasen am Tunnelauslauf': 'Air knife blow-off at tunnel exit',
  '−MM8 Korbkipper kippen (5/2 monostabil)': '−MM8 tip basket tipper (5/2 monostable)',
  'Vibrorinne −MA4': 'Vibratory chute −MA4',
  'Prüfband −MA5': 'Inspection conveyor −MA5',
  'Ausblasdüse n.i.O.-Teile': 'Blow-off nozzle for NOK parts',
  'Kamera Prüfplatz auslösen': 'Trigger inspection camera',
  '−MM1 eingehängt': '−MM1 hooked in',
  '−MM1 gelöst': '−MM1 released',
  '−MM2 oben': '−MM2 up',
  '−MM2 unten': '−MM2 down',
  '−MM3 über Band': '−MM3 above conveyor',
  '−MM3 über Zinnbad': '−MM3 above tin bath',
  '−MM4 Bad offen': '−MM4 bath open',
  '−MM4 Bad abgedeckt': '−MM4 bath covered',
  'Betriebstemperatur erreicht': 'Operating temperature reached',
  'Füllhöhe ausreichend': 'Fill level sufficient',
  'Lichtschranke Einlauf Übergabeplatz (Korb kommt)': 'Light barrier transfer point inlet (basket arriving)',
  'Korb liegt am Anschlag −MM5 an (induktiv M12 in der Anschlagleiste)': 'Basket resting against stop −MM5 (inductive M12 in the stop bar)',
  '−MM5 Anschlag offen (90°, erst dann Korb anheben oder absenken)': '−MM5 stop open (90°, only then lift or lower the basket)',
  'Taster START': 'START button',
  'Taster STOP (Öffner)': 'STOP button (NC contact)',
  'Wahlschalter Schaltschranktür 1 = Hand, 0 = Auto': 'Selector switch control cabinet door 1 = manual, 0 = auto',
  'Sicherheitsrelais Freigabe (1 = kein Not-Halt)': 'Safety relay enable (1 = no E-stop)',
  'Taster Quittieren Bedienpult': 'Acknowledge button operator panel',
  'Wahlschalter 1 = Automatik (Dauer), 0 = Einzelzyklus': 'Selector switch 1 = automatic (continuous), 0 = single cycle',
  'Schlüsselschalter Vor-Ort-Steuerstelle': 'Key switch local control station',
  'Vor-Ort Taster Rechtslauf': 'Local button forward',
  'Vor-Ort Taster Linkslauf': 'Local button reverse',
  'Vor-Ort Taster Halt (Öffner)': 'Local button stop (NC contact)',
  'Lichtschranke Bandanfang': 'Light barrier conveyor start',
  'Lichtschranke Ende Band 1 (Übergabe an die Rollenkurve)': 'Light barrier end of conveyor 1 (transfer to roller curve)',
  'Motorschutzschalter Band ausgelöst = 0': 'Motor protection switch conveyor tripped = 0',
  'Handtaster −MM1 einhängen': 'Manual button −MM1 hook in',
  'Handtaster −MM1 lösen': 'Manual button −MM1 release',
  'Handtaster −MM2 senken': 'Manual button −MM2 lower',
  'Handtaster −MM2 anheben': 'Manual button −MM2 lift',
  'Handtaster −MM3 zum Bad': 'Manual button −MM3 to bath',
  'Handtaster −MM3 zum Band': 'Manual button −MM3 to conveyor',
  'Handtaster −MM4 Bad zu': 'Manual button −MM4 close bath',
  'Handtaster −MM4 Bad auf': 'Manual button −MM4 open bath',
  '−MM5 Anschlag geschlossen (Korb wird gehalten)': '−MM5 stop closed (basket is held)',
  '−MM5 Anschlag offen': '−MM5 stop open',
  '−MM6 Vereinzeler geschlossen (sperrt)': '−MM6 separator closed (blocking)',
  '−MM6 Vereinzeler offen': '−MM6 separator open',
  'Inkrementalgeber Band Spur A (10 Imp/U)': 'Incremental encoder conveyor track A (10 pulses/rev)',
  'Inkrementalgeber Band Spur B (90° versetzt)': 'Incremental encoder conveyor track B (offset by 90°)',
  'Inkrementalgeber Band Nullimpuls (1 je Umdrehung)': 'Incremental encoder conveyor zero pulse (1 per revolution)',
  'Handtaster −MM5 Anschlag öffnen': 'Manual button −MM5 open stop',
  'Handtaster −MM5 Anschlag schließen': 'Manual button −MM5 close stop',
  'Handtaster −MM6 Vereinzeler schließen': 'Manual button −MM6 close separator',
  'Handtaster −MM6 Vereinzeler öffnen': 'Manual button −MM6 open separator',
  'Handtaster −MM8 Kipper kippen': 'Manual button −MM8 tip tipper',
  'Handtaster −MM8 Kipper zurück': 'Manual button −MM8 tipper back',
  'Sicherheitslichtvorhang Schutzfeld frei': 'Safety light curtain protective field clear',
  'Lichtschranke Band 2 Anfang (Korb übernommen)': 'Light barrier conveyor 2 start (basket taken over)',
  'Lichtschranke Kühlplatz': 'Light barrier cooling station',
  '−MM8 Kipper unten (Grundstellung)': '−MM8 tipper down (home position)',
  '−MM8 Kipper gekippt': '−MM8 tipper tipped',
  'Lichtschranke Teil am Kameraplatz (Prüfband)': 'Light barrier part at camera position (inspection conveyor)',
  'Lichtschranke Band 2 Ende (Übergabe zur Kippmulde)': 'Light barrier conveyor 2 end (transfer to tipping trough)',
  'Lichtschranke Rollenkurve Anfang': 'Light barrier roller curve start',
  'Lichtschranke Rollenkurve Ende': 'Light barrier roller curve end',
  'Inkrementalgeber Band 2 Spur A': 'Incremental encoder conveyor 2 track A',
  'Inkrementalgeber Band 2 Spur B': 'Incremental encoder conveyor 2 track B',
  'Kamera: Korb i.O.': 'Camera: basket OK',
  'Kamera: Korb n.i.O.': 'Camera: basket NOK',
  'Schlüsselschalter Vor-Ort-Steuerstelle Band 2': 'Key switch local control station conveyor 2',
  'Vor-Ort Band 2 Rechtslauf': 'Local conveyor 2 forward',
  'Vor-Ort Band 2 Linkslauf': 'Local conveyor 2 reverse',
  'Vor-Ort Band 2 Halt (Öffner)': 'Local conveyor 2 stop (NC contact)',
  'Motorschutz Band 2 (1 = OK)': 'Motor protection conveyor 2 (1 = OK)',
  'KLT i.O.-Teile voll': 'KLT bin for OK parts full',
  'Lichtschranke Einlauf Kippmulde (Korb in der Mulde)': 'Light barrier tipping trough inlet (basket in trough)',
  'Schlüsselschalter Vor-Ort-Steuerstelle Rollenkurve': 'Key switch local control station roller curve',
  'Vor-Ort Rollenkurve Rechtslauf': 'Local roller curve forward',
  'Vor-Ort Rollenkurve Linkslauf': 'Local roller curve reverse',
  'Vor-Ort Rollenkurve Halt (Öffner)': 'Local roller curve stop (NC contact)',
  'Motorschutz Rollenkurve (1 = OK)': 'Motor protection roller curve (1 = OK)',
  'Not-Halt −SF0 Bedienpult Meldekontakt (Öffner: 1 = entriegelt)': 'E-stop −SF0 operator panel, signaling contact (NC contact: 1 = released)',
  'Not-Halt −SF8 Vor-Ort −S10 Meldekontakt (Öffner: 1 = entriegelt)': 'E-stop −SF8 local −S10, signaling contact (NC contact: 1 = released)',
  'Not-Halt −SF9 Vor-Ort −S20 Meldekontakt (Öffner: 1 = entriegelt)': 'E-stop −SF9 local −S20, signaling contact (NC contact: 1 = released)',
  'Not-Halt −SF10 Vor-Ort −S30 Meldekontakt (Öffner: 1 = entriegelt)': 'E-stop −SF10 local −S30, signaling contact (NC contact: 1 = released)',
  'Not-Halt −SF33 Vor-Ort −S40 Meldekontakt (Öffner: 1 = entriegelt)': 'E-stop −SF33 local −S40, signaling contact (NC contact: 1 = released)',
  'Schlüsselschalter Vor-Ort-Steuerstelle Prüfstation −S40': 'Key switch local control station inspection station −S40',
  'Vor-Ort −S40 Vibrorinne + Prüfband EIN': 'Local −S40 vibratory chute + inspection conveyor ON',
  'Vor-Ort −S40 Vibrorinne + Prüfband AUS (Öffner)': 'Local −S40 vibratory chute + inspection conveyor OFF (NC contact)',
  'Vor-Ort −S40 Muldenrollen vorwärts tippen': 'Local −S40 jog trough rollers forward',
  'Vor-Ort −S40 Muldenrollen zurück tippen': 'Local −S40 jog trough rollers backward',
  'Vor-Ort −S40 Kipper kippen': 'Local −S40 tip tipper',
  'Vor-Ort −S40 Kipper zurück': 'Local −S40 tipper back',
  'Motorschutz Muldenantrieb −MA7 (1 = OK)': 'Motor protection trough drive −MA7 (1 = OK)',
  'Taster Quittieren Vor-Ort −S10 (parallel zu −SF4 an −KF2)': 'Acknowledge button local −S10 (parallel to −SF4 on −KF2)',
  'Taster Quittieren Vor-Ort −S20 (parallel zu −SF4 an −KF2)': 'Acknowledge button local −S20 (parallel to −SF4 on −KF2)',
  'Taster Quittieren Vor-Ort −S30 (parallel zu −SF4 an −KF2)': 'Acknowledge button local −S30 (parallel to −SF4 on −KF2)',
  'Taster Quittieren Vor-Ort −S40 (parallel zu −SF4 an −KF2)': 'Acknowledge button local −S40 (parallel to −SF4 on −KF2)',
  'Korbtemperatur Kühlplatz 0…27648 = 0…400 °C': 'Basket temperature cooling station 0…27648 = 0…400 °C',
  'Zinntemperatur 0…27648 = 0…400 °C': 'Tin temperature 0…27648 = 0…400 °C',
  'Füllstand 0…27648 = 0…100 %': 'Fill level 0…27648 = 0…100 %',
  'Umrichter −TA2 Steuerwort 1 (STW1)': 'Drive −TA2 control word 1 (STW1)',
  'Umrichter −TA2 Drehzahlsollwert NSOLL_A (16#4000 = 1500 1/min = 100 mm/s)': 'Drive −TA2 speed setpoint NSOLL_A (16#4000 = 1500 rpm = 100 mm/s)',
  'Umrichter −TA2 Zustandswort 1 (ZSW1)': 'Drive −TA2 status word 1 (ZSW1)',
  'Umrichter −TA2 Drehzahlistwert NIST_A (16#4000 = 1500 1/min = 100 mm/s)': 'Drive −TA2 actual speed NIST_A (16#4000 = 1500 rpm = 100 mm/s)',
  'Umrichter -TA2 Steuerwort 1 (STW1)': 'Drive -TA2 control word 1 (STW1)',
  'Umrichter -TA2 Drehzahlsollwert NSOLL_A (16#4000 = 1500 1/min = 100 mm/s)': 'Drive -TA2 speed setpoint NSOLL_A (16#4000 = 1500 rpm = 100 mm/s)',
  'Umrichter -TA2 Zustandswort 1 (ZSW1)': 'Drive -TA2 status word 1 (ZSW1)',
  'Umrichter -TA2 Drehzahlistwert NIST_A (16#4000 = 1500 1/min = 100 mm/s)': 'Drive -TA2 actual speed NIST_A (16#4000 = 1500 rpm = 100 mm/s)',
  'Umrichter −TA3 Steuerwort 1 (STW1)': 'Drive −TA3 control word 1 (STW1)',
  'Umrichter −TA3 Drehzahlsollwert NSOLL_A (16#4000 = 1500 1/min = 120 mm/s)': 'Drive −TA3 speed setpoint NSOLL_A (16#4000 = 1500 rpm = 120 mm/s)',
  'Umrichter −TA3 Zustandswort 1 (ZSW1)': 'Drive −TA3 status word 1 (ZSW1)',
  'Umrichter −TA3 Drehzahlistwert NIST_A (16#4000 = 1500 1/min = 120 mm/s)': 'Drive −TA3 actual speed NIST_A (16#4000 = 1500 rpm = 120 mm/s)',
  'Umrichter -TA3 Steuerwort 1 (STW1)': 'Drive -TA3 control word 1 (STW1)',
  'Umrichter -TA3 Drehzahlsollwert NSOLL_A (16#4000 = 1500 1/min = 120 mm/s)': 'Drive -TA3 speed setpoint NSOLL_A (16#4000 = 1500 rpm = 120 mm/s)',
  'Umrichter -TA3 Zustandswort 1 (ZSW1)': 'Drive -TA3 status word 1 (ZSW1)',
  'Umrichter -TA3 Drehzahlistwert NIST_A (16#4000 = 1500 1/min = 120 mm/s)': 'Drive -TA3 actual speed NIST_A (16#4000 = 1500 rpm = 120 mm/s)',
  'Umrichter −TA4 Steuerwort 1 (STW1)': 'Drive −TA4 control word 1 (STW1)',
  'Umrichter −TA4 Drehzahlsollwert NSOLL_A (16#4000 = 1500 1/min = 110 mm/s)': 'Drive −TA4 speed setpoint NSOLL_A (16#4000 = 1500 rpm = 110 mm/s)',
  'Umrichter −TA4 Zustandswort 1 (ZSW1)': 'Drive −TA4 status word 1 (ZSW1)',
  'Umrichter −TA4 Drehzahlistwert NIST_A (16#4000 = 1500 1/min = 110 mm/s)': 'Drive −TA4 actual speed NIST_A (16#4000 = 1500 rpm = 110 mm/s)',
  'Umrichter -TA4 Steuerwort 1 (STW1)': 'Drive -TA4 control word 1 (STW1)',
  'Umrichter -TA4 Drehzahlsollwert NSOLL_A (16#4000 = 1500 1/min = 110 mm/s)': 'Drive -TA4 speed setpoint NSOLL_A (16#4000 = 1500 rpm = 110 mm/s)',
  'Umrichter -TA4 Zustandswort 1 (ZSW1)': 'Drive -TA4 status word 1 (ZSW1)',
  'Umrichter -TA4 Drehzahlistwert NIST_A (16#4000 = 1500 1/min = 110 mm/s)': 'Drive -TA4 actual speed NIST_A (16#4000 = 1500 rpm = 110 mm/s)',
  'Umrichter −TA5 Steuerwort 1 (STW1)': 'Drive −TA5 control word 1 (STW1)',
  'Umrichter −TA5 Drehzahlsollwert NSOLL_A (16#4000 = 1500 1/min = 150 mm/s)': 'Drive −TA5 speed setpoint NSOLL_A (16#4000 = 1500 rpm = 150 mm/s)',
  'Umrichter −TA5 Zustandswort 1 (ZSW1)': 'Drive −TA5 status word 1 (ZSW1)',
  'Umrichter −TA5 Drehzahlistwert NIST_A (16#4000 = 1500 1/min = 150 mm/s)': 'Drive −TA5 actual speed NIST_A (16#4000 = 1500 rpm = 150 mm/s)',
  'Umrichter -TA5 Steuerwort 1 (STW1)': 'Drive -TA5 control word 1 (STW1)',
  'Umrichter -TA5 Drehzahlsollwert NSOLL_A (16#4000 = 1500 1/min = 150 mm/s)': 'Drive -TA5 speed setpoint NSOLL_A (16#4000 = 1500 rpm = 150 mm/s)',
  'Umrichter -TA5 Zustandswort 1 (ZSW1)': 'Drive -TA5 status word 1 (ZSW1)',
  'Umrichter -TA5 Drehzahlistwert NIST_A (16#4000 = 1500 1/min = 150 mm/s)': 'Drive -TA5 actual speed NIST_A (16#4000 = 1500 rpm = 150 mm/s)',
  'Schluesselschalter Vor-Ort-Steuerstelle Pruefband -S50 (1 = Vor-Ort)': 'Key switch local control station inspection conveyor -S50 (1 = local)',
  'Vor-Ort -S50 Pruefband EIN (Schliesser)': 'Local -S50 inspection conveyor ON (NO contact)',
  'Vor-Ort -S50 Pruefband AUS (Oeffner: 1 = nicht betaetigt)': 'Local -S50 inspection conveyor OFF (NC contact: 1 = not pressed)',
  'Vor-Ort -S50 Drehzahlpotentiometer Pruefband 0...27648 = 0...100 %': 'Local -S50 speed potentiometer inspection conveyor 0...27648 = 0...100 %',
  'Leuchte Vor-Ort-Steuerstelle Pruefband -S50 aktiv': 'Lamp local control station inspection conveyor -S50 active',
  'Schlüsselschalter Vor-Ort-Steuerstelle Prüfband −S50': 'Key switch local control station inspection conveyor −S50',
  'Vor-Ort −S50 Prüfband EIN': 'Local −S50 inspection conveyor ON',
  'Vor-Ort −S50 Prüfband AUS (Öffner)': 'Local −S50 inspection conveyor OFF (NC contact)',
  'Vor-Ort −S50 Drehzahlpotentiometer 0…27648 = 0…100 %': 'Local −S50 speed potentiometer 0…27648 = 0…100 %',
  'Leuchte Vor-Ort-Steuerstelle Prüfband −S50 aktiv': 'Lamp local control station inspection conveyor −S50 active',
  // Kühlwassertank
  'Magnetventil Frischwasser -MB17 Nachspeisen (2/2 NC, in Reihe mit Regelventil -MB18)': 'Fresh water solenoid valve -MB17 refill (2/2 NC, in series with control valve -MB18)',
  'Regelventil Frischwasser -MB18 Stellwert 0...27648 = 0...100 % (AQ 4 Kanal 0, Stellzeit 8 s)': 'Fresh water control valve -MB18 setpoint 0...27648 = 0...100 % (AQ 4 channel 0, stroke time 8 s)',
  'Regelventil -MB18 Stellungsrueckmeldung 0...27648 = 0...100 %': 'Control valve -MB18 position feedback 0...27648 = 0...100 %',
  'Fuellstand Kuehlwassertank Radar Micropilot FMR20B analog 0...27648 = 0...100 %': 'Cooling water tank level radar Micropilot FMR20B analog 0...27648 = 0...100 %',
  'Grenzschalter Liquiphant FTL31 Kuehlwassertank MIN (1 = Gabel bedeckt ueber 25 %, Trockenlaufschutz Pumpe -MA3)': 'Point level switch Liquiphant FTL31 cooling water tank MIN (1 = fork covered above 25 %, dry-run protection pump -MA3)',
  'Grenzschalter Liquiphant FTL31 Kuehlwassertank MAX (1 = Gabel frei unter 90 %, 0 = voll oder Drahtbruch)': 'Point level switch Liquiphant FTL31 cooling water tank MAX (1 = fork free below 90 %, 0 = full or wire break)',
  'Magnetventil Frischwasser −MB17 Nachspeisen (in Reihe mit −MB18)': 'Fresh water solenoid valve −MB17 refill (in series with −MB18)',
  'Regelventil Frischwasser −MB18 Stellwert 0…27648 = 0…100 %': 'Fresh water control valve −MB18 setpoint 0…27648 = 0…100 %',
  'Regelventil −MB18 Stellungsrückmeldung 0…27648 = 0…100 %': 'Control valve −MB18 position feedback 0…27648 = 0…100 %',
  'Füllstand Kühlwassertank (Radar) 0…27648 = 0…100 %': 'Cooling water tank level (radar) 0…27648 = 0…100 %',
  'Liquiphant Kühlwassertank Minimum (1 = bedeckt, über 25 %)': 'Liquiphant cooling water tank minimum (1 = covered, above 25 %)',
  'Liquiphant Kühlwassertank Maximum (1 = frei, unter 90 %)': 'Liquiphant cooling water tank maximum (1 = free, below 90 %)',
  'Daumenradschalter −SF48 Tauchzeit, Einer, Wertigkeit 1': 'Thumbwheel switch −SF48 dip time, units, weight 1',
  'Daumenradschalter −SF48 Tauchzeit, Einer, Wertigkeit 2': 'Thumbwheel switch −SF48 dip time, units, weight 2',
  'Daumenradschalter −SF48 Tauchzeit, Einer, Wertigkeit 4': 'Thumbwheel switch −SF48 dip time, units, weight 4',
  'Daumenradschalter −SF48 Tauchzeit, Einer, Wertigkeit 8': 'Thumbwheel switch −SF48 dip time, units, weight 8',
  'Daumenradschalter −SF48 Tauchzeit, Zehner, Wertigkeit 1': 'Thumbwheel switch −SF48 dip time, tens, weight 1',
  'Daumenradschalter −SF48 Tauchzeit, Zehner, Wertigkeit 2': 'Thumbwheel switch −SF48 dip time, tens, weight 2',
  'Daumenradschalter −SF48 Tauchzeit, Zehner, Wertigkeit 4': 'Thumbwheel switch −SF48 dip time, tens, weight 4',
  'Daumenradschalter −SF48 Tauchzeit, Zehner, Wertigkeit 8': 'Thumbwheel switch −SF48 dip time, tens, weight 8',
  'Daumenradschalter −SF48 Tauchzeit, Hunderter, Wertigkeit 1': 'Thumbwheel switch −SF48 dip time, hundreds, weight 1',
  'Daumenradschalter −SF48 Tauchzeit, Hunderter, Wertigkeit 2': 'Thumbwheel switch −SF48 dip time, hundreds, weight 2',
  'Daumenradschalter −SF48 Tauchzeit, Hunderter, Wertigkeit 4': 'Thumbwheel switch −SF48 dip time, hundreds, weight 4',
  'Daumenradschalter −SF48 Tauchzeit, Hunderter, Wertigkeit 8': 'Thumbwheel switch −SF48 dip time, hundreds, weight 8',
  'BCD-Anzeige −PG1 Bedienpult, Einer, Wertigkeit 1': 'BCD display −PG1 operator panel, units, weight 1',
  'BCD-Anzeige −PG1 Bedienpult, Einer, Wertigkeit 2': 'BCD display −PG1 operator panel, units, weight 2',
  'BCD-Anzeige −PG1 Bedienpult, Einer, Wertigkeit 4': 'BCD display −PG1 operator panel, units, weight 4',
  'BCD-Anzeige −PG1 Bedienpult, Einer, Wertigkeit 8': 'BCD display −PG1 operator panel, units, weight 8',
  'BCD-Anzeige −PG1 Bedienpult, Zehner, Wertigkeit 1': 'BCD display −PG1 operator panel, tens, weight 1',
  'BCD-Anzeige −PG1 Bedienpult, Zehner, Wertigkeit 2': 'BCD display −PG1 operator panel, tens, weight 2',
  'BCD-Anzeige −PG1 Bedienpult, Zehner, Wertigkeit 4': 'BCD display −PG1 operator panel, tens, weight 4',
  'BCD-Anzeige −PG1 Bedienpult, Zehner, Wertigkeit 8': 'BCD display −PG1 operator panel, tens, weight 8',
  'BCD-Anzeige −PG1 Bedienpult, Hunderter, Wertigkeit 1': 'BCD display −PG1 operator panel, hundreds, weight 1',
  'BCD-Anzeige −PG1 Bedienpult, Hunderter, Wertigkeit 2': 'BCD display −PG1 operator panel, hundreds, weight 2',
  'BCD-Anzeige −PG1 Bedienpult, Hunderter, Wertigkeit 4': 'BCD display −PG1 operator panel, hundreds, weight 4',
  'BCD-Anzeige −PG1 Bedienpult, Hunderter, Wertigkeit 8': 'BCD display −PG1 operator panel, hundreds, weight 8',
};
