// Englische Texte – Oberfläche: index.html, Seitenleiste, Fenster, Status, Bedienung, Signalmonitor, Diagramm, Startmeldungen.
// Schlüssel = deutscher Text wie im Quelltext (Leerraum egal), Werte in Vorlagen als {0}, {1} …
export default {
  // ---------------------------------------------------------------- Kopf, 3D-Ansicht
  'Zinnbad-Zwilling': 'Tin Bath Twin',
  'Zinnbad': 'Tin bath',
  'Verzinnen von Kleinteilen im Materialkorb · Einhängen −MM1, Tauchen −MM2, Verschieben −MM3, Abstreifen −MM4': 'Tinning small parts in a basket · hook in −MM1, dip −MM2, traverse −MM3, cover −MM4',
  'Schritt': 'Step',
  'Zinn': 'Tin',
  'Füllhöhe': 'Fill level',
  'Verzinnt': 'Tinned',
  'Achtung': 'Warning',
  'Beschriftung': 'Labels',
  'Grafik: Auto': 'Graphics: Auto',
  'Grafik: Auto ({0})': 'Graphics: Auto ({0})',
  'Grafik: {0}': 'Graphics: {0}',
  'Hoch': 'High',
  'Hoch−': 'High−',
  'Mittel': 'Medium',
  'Niedrig': 'Low',
  'Minimal': 'Minimal',
  'Grafikqualität: Auto regelt nach Bildrate': 'Graphics quality: Auto adapts to the frame rate',
  'Ansicht zurücksetzen': 'Reset view',
  'Ansicht': 'View',
  'Feste Ansicht wählen': 'Choose a preset view',
  'Steuerung': 'Controls',
  'Maussteuerung anzeigen': 'Show mouse controls',
  'Maussteuerung': 'Mouse controls',
  'Legende ausblenden': 'Hide legend',
  'Schaltschrank öffnen': 'Open control cabinet',
  'Schaltschrank schließen': 'Close control cabinet',
  'Seitenleiste': 'Sidebar',
  'Seitenleiste ein- und ausblenden': 'Show or hide the sidebar',
  '3D-Ansicht': '3D view',
  'Linke Taste ziehen': 'Left-drag',
  'Drehen um den Drehpunkt': 'Orbit around the pivot',
  'Rechte Taste ziehen': 'Right-drag',
  'Ansicht verschieben': 'Pan',
  'Mausrad': 'Mouse wheel',
  'Zoomen': 'Zoom',
  'Doppelklick': 'Double-click',
  'Drehpunkt auf Bauteil setzen': 'Set pivot on component',
  'Klick auf Taster': 'Click a pushbutton',
  'Bedienen (Taster, Not-Halt, Schalter)': 'Operate (pushbuttons, E-stop, switches)',
  'Shift': 'Shift',
  '+ Linke Taste': '+ left button',
  'Verschieben (Touchpad)': 'Pan (touchpad)',
  'Touch': 'Touch',
  '1 Finger drehen · 2 Finger zoomen/schieben': '1 finger: orbit · 2 fingers: zoom/pan',
  'Keine Verbindung zur SPS': 'No connection to the PLC',
  '3D-Darstellung nicht möglich': '3D view not available',
  'Browser oder Grafiktreiber stellen kein WebGL 2 bereit. Aktuellen Chrome, Edge oder Firefox verwenden, den Grafiktreiber aktualisieren und in den Browsereinstellungen die Hardwarebeschleunigung einschalten.': 'The browser or graphics driver does not provide WebGL 2. Use a current Chrome, Edge or Firefox, update the graphics driver and enable hardware acceleration in the browser settings.',
  '3D-Darstellung unterbrochen': '3D view interrupted',
  'Der Grafiktreiber hat die Darstellung zurückgesetzt. Sie wird wiederhergestellt, die Anlage läuft weiter.': 'The graphics driver has reset the display. It is being restored; the line keeps running.',
  'Der Grafiktreiber stellt die Darstellung nicht wieder her. Bitte die Seite neu laden (F5).': 'The graphics driver does not restore the display. Please reload the page (F5).',

  // Feste Ansichten (Auswahlliste)
  'Übersicht': 'Overview',
  'Gesamtanlage': 'Entire line',
  'Linie von oben': 'Line from above',
  'Schaltschrank −A1': 'Control cabinet −A1',
  'Teilprozesse': 'Subprocesses',
  'Band 1 · Übergabeplatz': 'Conveyor 1 · transfer point',
  'Portal · Haken −MM1/−MM2/−MM3': 'Gantry · hook −MM1/−MM2/−MM3',
  'Zinnbad (Blick ins Bad)': 'Tin bath (view into the bath)',
  'Pneumatik · Ventilinsel −QM1': 'Pneumatics · valve terminal −QM1',
  'Rollenkurve −MA6': 'Roller curve −MA6',
  'Band 2 · Sprühkühlung': 'Conveyor 2 · spray cooling',
  'Korbkipper −MM8': 'Basket tipper −MM8',
  'Vibrorinne · Prüfband · Kamera': 'Vibratory chute · inspection conveyor · camera',
  'Ausschleusen · KLT': 'Discharge · KLT bin',
  'Steuerstellen': 'Control stations',
  'Bedienpult (START/STOP/NOT-HALT)': 'Operator panel (START/STOP/E-STOP)',
  'Vor-Ort −S10 Band 1 (Antrieb)': 'Local −S10 conveyor 1 (drive)',
  'Vor-Ort −S30 Rollenkurve': 'Local −S30 roller curve',
  'Vor-Ort −S20 Band 2': 'Local −S20 conveyor 2',
  'Vor-Ort −S40 Prüfstation': 'Local −S40 inspection station',

  // ---------------------------------------------------------------- Seitenleiste oben, Verbindung
  'Bedienen & Beobachten': 'Operate & Monitor',
  'Version des Zwillings': 'Twin version',
  'DE': 'DE',
  'Auf Deutsch umschalten (lädt die Seite neu)': 'Auf Deutsch umschalten (lädt die Seite neu)',
  'Alle Bereiche auf- oder zuklappen': 'Expand or collapse all sections',
  'Alle zuklappen': 'Collapse all',
  'Alle aufklappen': 'Expand all',
  'Seitenleiste ausblenden': 'Hide sidebar',
  'Verbindung': 'Connection',
  'Bridge: wird gesucht …': 'Bridge: searching …',
  'PLCSIM Advanced: –': 'PLCSIM Advanced: –',
  'PLCSIM Advanced': 'PLCSIM Advanced',
  'Quelle der Ausgänge': 'Source of the outputs',
  'Demo ohne SPS': 'Demo without PLC',
  'Anlage zurücksetzen': 'Reset line',
  'PLCSIM Advanced: Die Ventile und Leuchten schaltet dein TIA-Programm. Endlagen, BG9–BG11 und die Taster gehen in die Eingänge der virtuellen CPU.': 'PLCSIM Advanced: your TIA program switches the valves and lamps. End positions, BG9–BG11 and the pushbuttons go to the inputs of the virtual CPU.',
  'Demo: Eine Schrittkette im Browser steuert die Anlage. SA1 auf AUTO: START −SF1 fährt Zyklen, bis STOP −SF2. SA1 auf EINZEL: jedes START ein Zyklus. Handbetrieb über die Schaltschranktür.': 'Demo: a step sequence in the browser controls the line. SA1 on AUTO: START −SF1 runs cycles until STOP −SF2. SA1 on SINGLE: one cycle per START. Manual mode via the cabinet door.',
  'Bridge nicht erreichbar': 'Bridge not reachable',
  'Bridge verbunden · nur Beobachten': 'Bridge connected · monitoring only',
  'Bridge verbunden': 'Bridge connected',
  'nicht verbunden': 'not connected',
  'getrennt': 'disconnected',
  'Run': 'Run',
  'start.bat ausführen, dann verbindet sich die Seite automatisch.': 'Run start.bat; the page then connects automatically.',
  'Bridge nicht erreichbar. Ausgänge bleiben auf dem letzten Stand.': 'Bridge not reachable. Outputs keep their last state.',
  'Nur Beobachten: Diese Seite ist {0}× geöffnet, gesteuert wird von der zuletzt geöffneten Registerkarte im Modus PLCSIM. Schließe die anderen oder lade diese Seite neu, um hier zu steuern.': 'Monitoring only: this page is open {0}×; control lies with the most recently opened tab in PLCSIM mode. Close the others or reload this page to control from here.',
  'Instanz nicht verbunden.': 'Instance not connected.',
  // Statustexte der Bridge (status.js übersetzt sie nach Muster)
  "Instanz '{0}' - {1}": "Instance '{0}' - {1}",
  "Instanz '{0}' ist ausgeschaltet": "Instance '{0}' is switched off",
  "Instanz '{0}' nicht gefunden ({1})": "Instance '{0}' not found ({1})",
  'PLCSIM-Advanced-Runtime-Manager laeuft nicht (Control Panel starten)': 'PLCSIM Advanced Runtime Manager is not running (start the Control Panel)',
  'Noch keine Verbindung': 'Not connected yet',
  'Bridge {0} passt nicht zum Zwilling v{1}: Bridge\\build.bat ausführen und die Bridge neu starten.': 'Bridge {0} does not match twin v{1}: run Bridge\\build.bat and restart the Bridge.',
  '(alte Version)': '(old version)',
  'signale.csv: Namen nicht gefunden: {0}': 'signale.csv: names not found: {0}',
  'Diese Registerkarte steuert die Anlage.': 'This tab controls the line.',
  'Nur Beobachten: eine andere Registerkarte im Modus PLCSIM steuert die Anlage. Diese hier sendet keine Eingänge mehr.': 'Monitoring only: another tab in PLCSIM mode controls the line. This one no longer sends inputs.',

  // ---------------------------------------------------------------- Übungsumfang
  'Übungsumfang': 'Exercise scope',
  'Band, Anschlag, Vereinzeler': 'Conveyor, stop, separator',
  'Steuerung des Bandes': 'Conveyor control',
  'Bandmodul automatisch': 'Conveyor module automatic',
  'SPS steuert': 'PLC controls',
  'Zinnbad: Temperatur und Füllstand': 'Tin bath: temperature and fill level',
  'Regelung des Zinnbads': 'Tin bath control',
  'Regler automatisch': 'Controller automatic',
  'SPS regelt': 'PLC controls',
  'Band: −QA1/−QA2 (Rechts/Links), −MB9 Anschlag, −MB10 Vereinzeler, Rollenkurve −QA10/−QA11, Band 2, Muldenrollen −QA12/−QA13 und Prüfstation aus deinem Programm; −BG11…−BG13, −BG35/−BG36, −BG21…−BG24, −BG37/−BG33 (Einlauf/Endanschlag Kippmulde) und die Vor-Ort-Steuerstellen sind Eingänge.': 'Conveyor: −QA1/−QA2 (right/left), −MB9 stop, −MB10 separator, roller curve −QA10/−QA11, conveyor 2, trough rollers −QA12/−QA13 and inspection station from your program; −BG11…−BG13, −BG35/−BG36, −BG21…−BG24, −BG37/−BG33 (tipping trough infeed/end stop) and the local control stations are inputs.',
  'Band: Das Bandmodul fördert, stoppt, vereinzelt und übergibt über die Rollenkurve selbstständig.': 'Conveyor: the conveyor module conveys, stops, separates and transfers via the roller curve on its own.',
  'Zinnbad: −TB1 Heizung (2-Punkt, Impuls/PWM oder PID) und −MB11 Nachfüllen aus deinem Programm, Istwerte −BT1/−BL1 analog.': 'Tin bath: −TB1 heater (on/off, pulse/PWM or PID) and −MB11 refill from your program, actual values −BT1/−BL1 analog.',
  'Zinnbad: Der Regler am Bad hält 280 °C, nachfüllen per Knopf.': 'Tin bath: the controller on the bath holds 280 °C, refill by button.',
  'Übungsumfang: Band, Anschlag und Vereinzeler steuert jetzt die SPS': 'Exercise scope: conveyor, stop and separator are now controlled by the PLC',
  'Übungsumfang: Bandmodul läuft wieder automatisch': 'Exercise scope: conveyor module runs automatically again',
  'Übungsumfang: Zinnbad-Temperatur und Nachfüllen regelt jetzt die SPS': 'Exercise scope: tin bath temperature and refilling are now controlled by the PLC',
  'Übungsumfang: Zinnbad wird wieder vom Regler am Bad geregelt': 'Exercise scope: tin bath is controlled by the bath controller again',

  // ---------------------------------------------------------------- Bedienfeld, Vor-Ort-Steuerstellen, Schaltschranktür
  'Bedienfeld der Anlage': 'Line operator panel',
  'NOT-HALT': 'E-STOP',
  'NOT-HALT (SF0)': 'E-STOP (SF0)',
  'Quittieren': 'Acknowledge',
  'Quittieren (SF4)': 'Acknowledge (SF4)',
  'Wahlschalter Einzel/Automatik (SA1)': 'Selector switch single/automatic (SA1)',
  'EINZEL': 'SINGLE',
  'AUTO': 'AUTO',
  'HAND': 'MANUAL',
  'Betrieb': 'Operation',
  'START': 'START',
  'STOP': 'STOP',
  'START (SF1)': 'START (SF1)',
  'STOP (SF2)': 'STOP (SF2)',
  'Anlage läuft': 'Plant running',
  'Meldungen': 'Indicators',
  'Zinnbad Betriebs­temperatur': 'Tin bath at operating temp­erature',
  'Füllhöhe unter­schritten': 'Fill level too low',
  'Materialkorb vorhanden': 'Material basket present',
  'Person durch den Lichtvorhang −BG20 gehen lassen': 'Let a person walk through light curtain −BG20',
  'STOP −SF2 als Öffner verdrahtet (unbetätigt = 1)': 'STOP −SF2 wired as NC contact (not pressed = 1)',
  'Vor-Ort-Steuerstellen': 'Local control stations',
  'Vor-Ort-Steuerstelle Band (−S10)': 'Local control station conveyor (−S10)',
  'Vor-Ort-Steuerstelle Band 2 (−S20)': 'Local control station conveyor 2 (−S20)',
  'Vor-Ort-Steuerstelle Rollenkurve (−S30)': 'Local control station roller curve (−S30)',
  'Vor-Ort-Steuerstelle Prüfstation (−S40)': 'Local control station inspection station (−S40)',
  'Links': 'Left',
  'Halt': 'Stop',
  'Rechts': 'Right',
  'Vor-Ort aktiv': 'Local active',
  'Schlüsselschalter Vor-Ort (SA2)': 'Local key switch (SA2)',
  'Schlüsselschalter Vor-Ort Band 2 (SA4)': 'Local key switch conveyor 2 (SA4)',
  'Schlüsselschalter Vor-Ort Rollenkurve (SA5)': 'Local key switch roller curve (SA5)',
  'Schlüsselschalter Vor-Ort Prüfstation (SA6)': 'Local key switch inspection station (SA6)',
  'Band Linkslauf (SF6)': 'Conveyor run left (SF6)',
  'Band Halt (SF7)': 'Conveyor stop (SF7)',
  'Band Rechtslauf (SF5)': 'Conveyor run right (SF5)',
  'Band 2 Linkslauf (SF24)': 'Conveyor 2 run left (SF24)',
  'Band 2 Halt (SF25)': 'Conveyor 2 stop (SF25)',
  'Band 2 Rechtslauf (SF23)': 'Conveyor 2 run right (SF23)',
  'Rollenkurve Linkslauf (SF31)': 'Roller curve run left (SF31)',
  'Rollenkurve Halt (SF32)': 'Roller curve stop (SF32)',
  'Rollenkurve Rechtslauf (SF30)': 'Roller curve run right (SF30)',
  'NOT-HALT Vor-Ort (SF8)': 'Local E-STOP (SF8)',
  'NOT-HALT Vor-Ort Band 2 (SF9)': 'Local E-STOP conveyor 2 (SF9)',
  'NOT-HALT Vor-Ort Rollenkurve (SF10)': 'Local E-STOP roller curve (SF10)',
  'NOT-HALT Vor-Ort Prüfstation (SF33)': 'Local E-STOP inspection station (SF33)',
  'Quittieren Vor-Ort S10 (SF41)': 'Local acknowledge S10 (SF41)',
  'Quittieren Vor-Ort S20 (SF42)': 'Local acknowledge S20 (SF42)',
  'Quittieren Vor-Ort S30 (SF43)': 'Local acknowledge S30 (SF43)',
  'Quittieren Vor-Ort S40 (SF44)': 'Local acknowledge S40 (SF44)',
  'Prüfung EIN': 'Inspection ON',
  'Prüfung AUS': 'Inspection OFF',
  'Vibrorinne und Prüfband EIN (SF34)': 'Vibratory chute and inspection conveyor ON (SF34)',
  'Vibrorinne und Prüfband AUS (SF35)': 'Vibratory chute and inspection conveyor OFF (SF35)',
  'Mulde zurück': 'Trough back',
  'Mulde vor': 'Trough fwd',
  'Muldenrollen zurück tippen (SF37)': 'Jog trough rollers back (SF37)',
  'Muldenrollen vor tippen (SF36)': 'Jog trough rollers forward (SF36)',
  'Kippen': 'Tip',
  'Kipper zurück': 'Tipper back',
  'Kipper kippen (SF38)': 'Tip the tipper (SF38)',
  'Kipper zurück (SF39)': 'Tipper back (SF39)',
  'Schaltschranktür −A1: Handbetrieb': 'Cabinet door −A1: manual mode',
  'Wahlschalter Auto/Hand (SA3)': 'Selector switch auto/manual (SA3)',
  'Hand aktiv': 'Manual active',
  '−MM1 einhängen': '−MM1 hook in',
  '−MM1 lösen': '−MM1 release',
  '−MM2 senken': '−MM2 lower',
  '−MM2 anheben': '−MM2 lift',
  '−MM3 zum Bad': '−MM3 to bath',
  '−MM3 zum Band': '−MM3 to conveyor',
  '−MM4 Bad zu': '−MM4 close bath',
  '−MM4 Bad auf': '−MM4 open bath',
  '−MM5 Anschlag öffnen': '−MM5 open stop',
  '−MM5 Anschlag schließen': '−MM5 close stop',
  '−MM6 Vereinzeler schließen': '−MM6 close separator',
  '−MM6 Vereinzeler öffnen': '−MM6 open separator',
  '−MM8 Kipper kippen': '−MM8 tip tipper',
  '−MM8 Kipper zurück': '−MM8 tipper back',
  'Hand: MM1…MM4 im Tippbetrieb (Spule nur solange gedrückt, mit Verriegelungen). MM5, MM6 und MM8 hängen an monostabilen Ventilen: Selbsthaltung in der SPS („öffnen/kippen“ setzt, „zurück/schließen“ setzt zurück). Die Rollenkurve −MA6 wird nur über die Vor-Ort-Steuerstelle −S30 bedient. Taster-Eingänge %I3.0…%I3.7, %I5.0…%I5.3, %I8.2/%I8.3.': 'Manual: MM1…MM4 in jog mode (coil energized only while pressed, with interlocks). MM5, MM6 and MM8 are on monostable valves: latching in the PLC (“open/tip” sets, “back/close” resets). The roller curve −MA6 is operated only from local control station −S30. Pushbutton inputs %I3.0…%I3.7, %I5.0…%I5.3, %I8.2/%I8.3.',

  // ---------------------------------------------------------------- Prozess
  'Prozess': 'Process',
  'Zinn −BT1': 'Tin −BT1',
  'Füllhöhe −BL1': 'Fill level −BL1',
  'Heizung ein': 'Heater on',
  'Heizung aus': 'Heater off',
  'Zinn nachfüllen': 'Refill tin',
  'Korb auflegen': 'Place basket',
  'Körbe automatisch zuführen': 'Feed baskets automatically',
  'Geschwindigkeit aller Zylinder': 'Speed of all cylinders',
  'Jeden Zylinder einzeln stellen die Drosselrückschlagventile an seinen Anschlüssen: Klick auf ein Ventil in der 3D-Ansicht oder „Groß öffnen“ im Weg-Zeit-Diagramm.': 'Each cylinder is set individually with the one-way flow control valves at its ports: click a valve in the 3D view or “Open large” in the displacement-time diagram.',
  'Jedes Tauchen verbraucht Zinn. Unter 40 % meldet −BG10 „Füllhöhe unterschritten“, unter 250 °C fällt −BG9 ab. Temperatur (−BT1, 0…400 °C) und Füllstand (−BL1, 0…100 %) liegen zusätzlich als Analogwerte 0…27648 an.': 'Every dip consumes tin. Below 40 % −BG10 reports “fill level too low”, below 250 °C −BG9 drops out. Temperature (−BT1, 0…400 °C) and fill level (−BL1, 0…100 %) are also available as analog values 0…27648.',
  'Heizung −TB1: {0} · Heizelement {1} % · BT1 = {2} · BL1 = {3}': 'Heater −TB1: {0} · heating element {1} % · BT1 = {2} · BL1 = {3}',
  'EIN': 'ON',
  'AUS': 'OFF',
  'NOT-HALT aktiv': 'E-STOP active',
  'SPS': 'PLC',
  'Zinn nachgefüllt (85 %)': 'Tin refilled (85 %)',
  'Anlage in Grundstellung zurückgesetzt · das CPU-Programm läuft weiter, Ausgänge greifen sofort wieder': 'Line reset to home position · the CPU program keeps running, outputs take effect again immediately',
  'Anlage in Grundstellung zurückgesetzt · SF1 startet die Automatik': 'Line reset to home position · SF1 starts automatic mode',
  'Demo: Automatik EIN': 'Demo: automatic ON',

  // ---------------------------------------------------------------- Weg-Zeit-Diagramm, Drosseln
  'Weg-Zeit-Diagramm (live, 60 s)': 'Displacement-time diagram (live, 60 s)',
  'Weg-Zeit-Diagramm aller Zylinder': 'Displacement-time diagram of all cylinders',
  'Weg-Zeit-Diagramm aller Zylinder mit Messlinien': 'Displacement-time diagram of all cylinders with cursors',
  'Schrittnummern der Demo-SPS oben': 'Demo PLC step numbers at the top',
  'jetzt': 'now',
  'Groß öffnen · Messlinien · Drosseln': 'Open large · cursors · throttles',
  'Weg-Zeit-Diagramm · Drosseln': 'Displacement-time diagram · throttles',
  'Zeitfenster': 'Time window',
  'Anhalten': 'Pause',
  'Weiter': 'Resume',
  'Messlinien löschen': 'Clear cursors',
  'Schließen (Esc)': 'Close (Esc)',
  'Fenster schließen': 'Close window',
  'Drosselrückschlagventile': 'One-way flow control valves',
  'Abluftdrosselung · 50 % = Nennzeit, 100 % = doppelt so schnell, 0 % = zu': 'Exhaust-air throttling · 50 % = nominal time, 100 % = twice as fast, 0 % = closed',
  'Alle auf 50 %': 'All to 50 %',
  'Einhängen': 'Hook in',
  'eingehängt': 'hooked in',
  'gelöst': 'released',
  'Tauchen': 'Dip',
  'oben': 'up',
  'unten': 'down',
  'Verschieben': 'Traverse',
  'Band': 'conveyor',
  'Bad': 'bath',
  'Abstreifen': 'Cover',
  'offen': 'open',
  'zu': 'closed',
  'Anschlag': 'Stop',
  'Vereinzeler': 'Separator',
  'gekippt': 'tipped',
  'Klick ins Diagramm setzt Messlinie 1, ein zweiter Klick Messlinie 2. Sie rasten an den Flanken der Endlagensensoren ein (Alt-Taste: frei). Ziehen verschiebt, Mausrad blättert im angehaltenen Diagramm.': 'Click in the diagram to set cursor 1, a second click sets cursor 2. They snap to the edges of the end-position sensors (Alt key: free). Drag to move; the mouse wheel scrolls through the paused diagram.',
  'Linie {0}: <b>{1}</b>': 'Cursor {0}: <b>{1}</b>',
  'Ausfahren': 'Extend',
  'Einfahren': 'Retract',
  'Endlagen {0} / {1}': 'End positions {0} / {1}',
  'Drosselrückschlagventil an Anschluss {0} (drosselt die Abluft beim Ausfahren)': 'One-way flow control valve at port {0} (throttles the exhaust air when extending)',
  'Drosselrückschlagventil an Anschluss {0} (drosselt die Abluft beim Einfahren)': 'One-way flow control valve at port {0} (throttles the exhaust air when retracting)',
  '−{0} Drossel {1}': '−{0} throttle {1}',
  'zu – Zylinder steht': 'closed – cylinder stopped',
  '{0} · gemessen {1}': '{0} · measured {1}',

  // ---------------------------------------------------------------- Ereignisse, Signalmonitor
  'Ereignisse': 'Events',
  'Noch keine Ereignisse.': 'No events yet.',
  'Signalmonitor': 'Signal monitor',
  'Signale filtern': 'Filter signals',
  'Filtern …': 'Filter …',
  'Signal': 'Signal',
  'Adresse': 'Address',
  'Forcen': 'Force',
  'Ausgänge SPS → Zwilling': 'Outputs PLC → twin',
  'Eingänge Zwilling → SPS': 'Inputs twin → PLC',
  '{0} forcen': 'Force {0}',
  'Wert aus dem Modell': 'Value from the model',
  'Auf 0 forcen': 'Force to 0',
  'Auf 1 forcen': 'Force to 1',
};
