// Englische Texte – Oberfläche: index.html, Seitenleiste, Fenster, Status, Bedienung, Signalmonitor, Diagramm, Startmeldungen.
// Schlüssel = deutscher Text wie im Quelltext (Leerraum egal), Werte in Vorlagen als {0}, {1} …
export default {
  // ---------------------------------------------------------------- Kopf, 3D-Ansicht
  'Zinnbad-Zwilling': 'Tin Bath Twin',
  'Zinnbad': 'Tin bath',
  'Verzinnen von Kleinteilen im Materialkorb · Einhängen −MM1, Tauchen −MM2, Verschieben −MM3, Abstreifen −MM4': 'Tinning small parts in a basket · hook in −MM1, dip −MM2, traverse −MM3, cover −MM4',
  'Schritt': 'Step',
  'Zinn': 'Tin',
  'Füllhöhe': 'Fill level',
  'Verzinnt': 'Tinned',
  'Achtung': 'Warning',
  'Beschriftung': 'Labels',
  'Grafik: Auto': 'Graphics: Auto',
  'Grafik: Auto ({0})': 'Graphics: Auto ({0})',
  'Grafik: {0}': 'Graphics: {0}',
  'Hoch': 'High',
  'Hoch−': 'High−',
  'Mittel': 'Medium',
  'Niedrig': 'Low',
  'Minimal': 'Minimal',
  'Grafikqualität: Auto regelt nach Bildrate': 'Graphics quality: Auto adapts to the frame rate',
  'Ansicht zurücksetzen': 'Reset view',
  'Ansicht': 'View',
  'Feste Ansicht wählen': 'Choose a preset view',
  'Steuerung': 'Controls',
  'Maussteuerung anzeigen': 'Show mouse controls',
  'Maussteuerung': 'Mouse controls',
  'Legende ausblenden': 'Hide legend',
  'Schaltschrank öffnen': 'Open control cabinet',
  'Schaltschrank schließen': 'Close control cabinet',
  'Übungshandbuch': 'Exercise handbook',
  'Übungshandbuch in einem neuen Tab öffnen': 'Open the exercise handbook in a new tab (German)',
  'Seitenleiste': 'Sidebar',
  'Seitenleiste ein- und ausblenden': 'Show or hide the sidebar',
  '3D-Ansicht': '3D view',
  'Linke Taste ziehen': 'Left-drag',
  'Drehen um den Drehpunkt': 'Orbit around the pivot',
  'Rechte Taste ziehen': 'Right-drag',
  'Ansicht verschieben': 'Pan',
  'Mausrad': 'Mouse wheel',
  'Zoomen': 'Zoom',
  'Doppelklick': 'Double-click',
  'Drehpunkt auf Bauteil setzen': 'Set pivot on component',
  'Klick auf Taster': 'Click a pushbutton',
  'Bedienen (Taster, Not-Halt, Schalter)': 'Operate (pushbuttons, E-stop, switches)',
  'Shift': 'Shift',
  '+ Linke Taste': '+ left button',
  'Verschieben (Touchpad)': 'Pan (touchpad)',
  'Touch': 'Touch',
  '1 Finger drehen · 2 Finger zoomen/schieben': '1 finger: orbit · 2 fingers: zoom/pan',
  'Keine Verbindung zur SPS': 'No connection to the PLC',
  '3D-Darstellung nicht möglich': '3D view not available',
  'Browser oder Grafiktreiber stellen kein WebGL 2 bereit. Aktuellen Chrome, Edge oder Firefox verwenden, den Grafiktreiber aktualisieren und in den Browsereinstellungen die Hardwarebeschleunigung einschalten.': 'The browser or graphics driver does not provide WebGL 2. Use a current Chrome, Edge or Firefox, update the graphics driver and enable hardware acceleration in the browser settings.',
  '3D-Darstellung unterbrochen': '3D view interrupted',
  'Der Grafiktreiber hat die Darstellung zurückgesetzt. Sie wird wiederhergestellt, die Anlage läuft weiter.': 'The graphics driver has reset the display. It is being restored; the line keeps running.',
  'Der Grafiktreiber stellt die Darstellung nicht wieder her. Bitte die Seite neu laden (F5).': 'The graphics driver does not restore the display. Please reload the page (F5).',

  // Feste Ansichten (Auswahlliste)
  'Übersicht': 'Overview',
  'Gesamtanlage': 'Entire line',
  'Linie von oben': 'Line from above',
  'Schaltschrank −A1': 'Control cabinet −A1',
  'Teilprozesse': 'Subprocesses',
  'Band 1 · Übergabeplatz': 'Conveyor 1 · transfer point',
  'Portal · Haken −MM1/−MM2/−MM3': 'Gantry · hook −MM1/−MM2/−MM3',
  'Zinnbad (Blick ins Bad)': 'Tin bath (view into the bath)',
  'Pneumatik · Ventilinsel −QM1': 'Pneumatics · valve terminal −QM1',
  'Rollenkurve −MA6': 'Roller curve −MA6',
  'Band 2 · Sprühkühlung': 'Conveyor 2 · spray cooling',
  'Korbkipper −MM8': 'Basket tipper −MM8',
  'Vibrorinne · Prüfband · Kamera': 'Vibratory chute · inspection conveyor · camera',
  'Ausschleusen · KLT': 'Discharge · KLT bin',
  'Steuerstellen': 'Control stations',
  'Bedienpult (START/STOP/NOT-HALT)': 'Operator panel (START/STOP/E-STOP)',
  'Vor-Ort −S10 Band 1 (Antrieb)': 'Local −S10 conveyor 1 (drive)',
  'Vor-Ort −S30 Rollenkurve': 'Local −S30 roller curve',
  'Vor-Ort −S20 Band 2': 'Local −S20 conveyor 2',
  'Vor-Ort −S40 Prüfstation': 'Local −S40 inspection station',

  // ---------------------------------------------------------------- Seitenleiste oben, Verbindung
  'Bedienen & Beobachten': 'Operate & Monitor',
  'Version des Zwillings': 'Twin version',
  'DE': 'DE',
  'Auf Deutsch umschalten (lädt die Seite neu)': 'Auf Deutsch umschalten (lädt die Seite neu)',
  'Alle Bereiche auf- oder zuklappen': 'Expand or collapse all sections',
  'Alle zuklappen': 'Collapse all',
  'Alle aufklappen': 'Expand all',
  'Seitenleiste ausblenden': 'Hide sidebar',
  'Verbindung': 'Connection',
  'Bridge: wird gesucht …': 'Bridge: searching …',
  'PLCSIM Advanced: –': 'PLCSIM Advanced: –',
  'PLCSIM Advanced': 'PLCSIM Advanced',
  'Quelle der Ausgänge': 'Source of the outputs',
  'Demo ohne SPS': 'Demo without PLC',
  'Anlage zurücksetzen': 'Reset line',
  'PLCSIM Advanced: Die Ventile und Leuchten schaltet dein TIA-Programm. Endlagen, BG9–BG11 und die Taster gehen in die Eingänge der virtuellen CPU.': 'PLCSIM Advanced: your TIA program switches the valves and lamps. End positions, BG9–BG11 and the pushbuttons go to the inputs of the virtual CPU.',
  'Demo: Eine Schrittkette im Browser steuert die Anlage. SA1 auf AUTO: START −SF1 fährt Zyklen, bis STOP −SF2. SA1 auf EINZEL: jedes START ein Zyklus. Handbetrieb über die Schaltschranktür.': 'Demo: a step sequence in the browser controls the line. SA1 on AUTO: START −SF1 runs cycles until STOP −SF2. SA1 on SINGLE: one cycle per START. Manual mode via the cabinet door.',
  'Bridge nicht erreichbar': 'Bridge not reachable',
  'Bridge verbunden · nur Beobachten': 'Bridge connected · monitoring only',
  'Bridge verbunden': 'Bridge connected',
  'nicht verbunden': 'not connected',
  'getrennt': 'disconnected',
  'Run': 'Run',
  'start.bat ausführen, dann verbindet sich die Seite automatisch.': 'Run start.bat; the page then connects automatically.',
  'Bridge nicht erreichbar. Ausgänge bleiben auf dem letzten Stand.': 'Bridge not reachable. Outputs keep their last state.',
  'Nur Beobachten: Diese Seite ist {0}× geöffnet, gesteuert wird von der zuletzt geöffneten Registerkarte im Modus PLCSIM. Schließe die anderen oder lade diese Seite neu, um hier zu steuern.': 'Monitoring only: this page is open {0}×; control lies with the most recently opened tab in PLCSIM mode. Close the others or reload this page to control from here.',
  'Instanz nicht verbunden.': 'Instance not connected.',
  // Statustexte der Bridge (status.js übersetzt sie nach Muster)
  "Instanz '{0}' - {1}": "Instance '{0}' - {1}",
  "Instanz '{0}' ist ausgeschaltet": "Instance '{0}' is switched off",
  "Instanz '{0}' nicht gefunden ({1})": "Instance '{0}' not found ({1})",
  'PLCSIM-Advanced-Runtime-Manager laeuft nicht (Control Panel starten)': 'PLCSIM Advanced Runtime Manager is not running (start the Control Panel)',
  'Noch keine Verbindung': 'Not connected yet',
  'Bridge {0} passt nicht zum Zwilling v{1}: Bridge\\build.bat ausführen und die Bridge neu starten.': 'Bridge {0} does not match twin v{1}: run Bridge\\build.bat and restart the Bridge.',
  '(alte Version)': '(old version)',
  'signale.csv: Namen nicht gefunden: {0}': 'signale.csv: names not found: {0}',
  'Diese Registerkarte steuert die Anlage.': 'This tab controls the line.',
  'Nur Beobachten: eine andere Registerkarte im Modus PLCSIM steuert die Anlage. Diese hier sendet keine Eingänge mehr.': 'Monitoring only: another tab in PLCSIM mode controls the line. This one no longer sends inputs.',

  // ---------------------------------------------------------------- Übungsumfang
  'Übungsumfang': 'Exercise scope',
  'Band, Anschlag, Vereinzeler': 'Conveyor, stop, separator',
  'Steuerung des Bandes': 'Conveyor control',
  'Bandmodul automatisch': 'Conveyor module automatic',
  'SPS steuert': 'PLC controls',
  'Zinnbad: Temperatur und Füllstand': 'Tin bath: temperature and fill level',
  'Regelung des Zinnbads': 'Tin bath control',
  'Regler automatisch': 'Controller automatic',
  'SPS regelt': 'PLC controls',
  'Band: −QA1/−QA2 (Rechts/Links), −MB9 Anschlag, −MB10 Vereinzeler, Rollenkurve −QA10/−QA11, Band 2, Muldenrollen −QA12/−QA13 und Prüfstation aus deinem Programm; −BG11…−BG13, −BG40 (Korb liegt am Anschlag an), −BG35/−BG36, −BG21…−BG24, −BG37/−BG33 (Einlauf/Endanschlag Kippmulde) und die Vor-Ort-Steuerstellen sind Eingänge.': 'Conveyor: −QA1/−QA2 (right/left), −MB9 stop, −MB10 separator, roller curve −QA10/−QA11, conveyor 2, trough rollers −QA12/−QA13 and inspection station from your program; −BG11…−BG13, −BG40 (basket resting against the stop), −BG35/−BG36, −BG21…−BG24, −BG37/−BG33 (tipping trough infeed/end stop) and the local control stations are inputs.',
  'Band: Das Bandmodul fördert, stoppt, vereinzelt und übergibt über die Rollenkurve selbstständig. Nach einem Not-Halt läuft es erst nach dem Quittieren mit START −SF1 wieder an.': 'Conveyor: the conveyor module conveys, stops, separates and transfers via the roller curve on its own. After an E-stop it only restarts after acknowledging and pressing START −SF1.',
  'Zinnbad: −TB1 Heizung (2-Punkt, Impuls/PWM oder PID) und −MB11 Nachfüllen aus deinem Programm, Istwerte −BT1/−BL1 analog.': 'Tin bath: −TB1 heater (on/off, pulse/PWM or PID) and −MB11 refill from your program, actual values −BT1/−BL1 analog.',
  'Zinnbad: Der Regler am Bad hält 280 °C, nachfüllen per Knopf.': 'Tin bath: the controller on the bath holds 280 °C, refill by button.',
  'Übungsumfang: Band, Anschlag und Vereinzeler steuert jetzt die SPS': 'Exercise scope: conveyor, stop and separator are now controlled by the PLC',
  'Übungsumfang: Bandmodul läuft wieder automatisch': 'Exercise scope: conveyor module runs automatically again',
  'Übungsumfang: Zinnbad-Temperatur und Nachfüllen regelt jetzt die SPS': 'Exercise scope: tin bath temperature and refilling are now controlled by the PLC',
  'Übungsumfang: Zinnbad wird wieder vom Regler am Bad geregelt': 'Exercise scope: tin bath is controlled by the bath controller again',

  // ---------------------------------------------------------------- Bedienfeld, Vor-Ort-Steuerstellen, Schaltschranktür
  'Bedienfeld der Anlage': 'Line operator panel',
  'NOT-HALT': 'E-STOP',
  'NOT-HALT (SF0)': 'E-STOP (SF0)',
  'Quittieren': 'Acknowledge',
  'Quittieren (SF4)': 'Acknowledge (SF4)',
  'Wahlschalter Einzel/Automatik (SA1)': 'Selector switch single/automatic (SA1)',
  'EINZEL': 'SINGLE',
  'AUTO': 'AUTO',
  'HAND': 'MANUAL',
  'Betrieb': 'Operation',
  'START': 'START',
  'STOP': 'STOP',
  'START (SF1)': 'START (SF1)',
  'STOP (SF2)': 'STOP (SF2)',
  'Anlage läuft': 'Plant running',
  'Meldungen': 'Indicators',
  'Zinnbad Betriebs­temperatur': 'Tin bath at operating temp­erature',
  'Füllhöhe unter­schritten': 'Fill level too low',
  'Materialkorb vorhanden': 'Material basket present',
  'Person durch den Lichtvorhang −BG20 gehen lassen': 'Let a person walk through light curtain −BG20',
  'STOP −SF2 als Öffner verdrahtet (unbetätigt = 1)': 'STOP −SF2 wired as NC contact (not pressed = 1)',
  'Vor-Ort-Steuerstellen': 'Local control stations',
  'Vor-Ort-Steuerstelle Band (−S10)': 'Local control station conveyor (−S10)',
  'Vor-Ort-Steuerstelle Band 2 (−S20)': 'Local control station conveyor 2 (−S20)',
  'Vor-Ort-Steuerstelle Rollenkurve (−S30)': 'Local control station roller curve (−S30)',
  'Vor-Ort-Steuerstelle Prüfstation (−S40)': 'Local control station inspection station (−S40)',
  'Links': 'Left',
  'Halt': 'Stop',
  'Rechts': 'Right',
  'Vor-Ort aktiv': 'Local active',
  'Schlüsselschalter Vor-Ort (SA2)': 'Local key switch (SA2)',
  'Schlüsselschalter Vor-Ort Band 2 (SA4)': 'Local key switch conveyor 2 (SA4)',
  'Schlüsselschalter Vor-Ort Rollenkurve (SA5)': 'Local key switch roller curve (SA5)',
  'Schlüsselschalter Vor-Ort Prüfstation (SA6)': 'Local key switch inspection station (SA6)',
  'Band Linkslauf (SF6)': 'Conveyor run left (SF6)',
  'Band Halt (SF7)': 'Conveyor stop (SF7)',
  'Band Rechtslauf (SF5)': 'Conveyor run right (SF5)',
  'Band 2 Linkslauf (SF24)': 'Conveyor 2 run left (SF24)',
  'Band 2 Halt (SF25)': 'Conveyor 2 stop (SF25)',
  'Band 2 Rechtslauf (SF23)': 'Conveyor 2 run right (SF23)',
  'Rollenkurve Linkslauf (SF31)': 'Roller curve run left (SF31)',
  'Rollenkurve Halt (SF32)': 'Roller curve stop (SF32)',
  'Rollenkurve Rechtslauf (SF30)': 'Roller curve run right (SF30)',
  'NOT-HALT Vor-Ort (SF8)': 'Local E-STOP (SF8)',
  'NOT-HALT Vor-Ort Band 2 (SF9)': 'Local E-STOP conveyor 2 (SF9)',
  'NOT-HALT Vor-Ort Rollenkurve (SF10)': 'Local E-STOP roller curve (SF10)',
  'NOT-HALT Vor-Ort Prüfstation (SF33)': 'Local E-STOP inspection station (SF33)',
  'Quittieren Vor-Ort S10 (SF41)': 'Local acknowledge S10 (SF41)',
  'Quittieren Vor-Ort S20 (SF42)': 'Local acknowledge S20 (SF42)',
  'Quittieren Vor-Ort S30 (SF43)': 'Local acknowledge S30 (SF43)',
  'Quittieren Vor-Ort S40 (SF44)': 'Local acknowledge S40 (SF44)',
  'Prüfung EIN': 'Inspection ON',
  'Prüfung AUS': 'Inspection OFF',
  'Vibrorinne und Prüfband EIN (SF34)': 'Vibratory chute and inspection conveyor ON (SF34)',
  'Vibrorinne und Prüfband AUS (SF35)': 'Vibratory chute and inspection conveyor OFF (SF35)',
  'Mulde zurück': 'Trough back',
  'Mulde vor': 'Trough fwd',
  'Muldenrollen zurück tippen (SF37)': 'Jog trough rollers back (SF37)',
  'Muldenrollen vor tippen (SF36)': 'Jog trough rollers forward (SF36)',
  'Kippen': 'Tip',
  'Kipper zurück': 'Tipper back',
  'Kipper kippen (SF38)': 'Tip the tipper (SF38)',
  'Kipper zurück (SF39)': 'Tipper back (SF39)',
  'Schaltschranktür −A1: Handbetrieb': 'Cabinet door −A1: manual mode',
  'Wahlschalter Auto/Hand (SA3)': 'Selector switch auto/manual (SA3)',
  'Hand aktiv': 'Manual active',
  '−MM1 einhängen': '−MM1 hook in',
  '−MM1 lösen': '−MM1 release',
  '−MM2 senken': '−MM2 lower',
  '−MM2 anheben': '−MM2 lift',
  '−MM3 zum Bad': '−MM3 to bath',
  '−MM3 zum Band': '−MM3 to conveyor',
  '−MM4 Bad zu': '−MM4 close bath',
  '−MM4 Bad auf': '−MM4 open bath',
  '−MM5 Anschlag öffnen': '−MM5 open stop',
  '−MM5 Anschlag schließen': '−MM5 close stop',
  '−MM6 Vereinzeler schließen': '−MM6 close separator',
  '−MM6 Vereinzeler öffnen': '−MM6 open separator',
  '−MM8 Kipper kippen': '−MM8 tip tipper',
  '−MM8 Kipper zurück': '−MM8 tipper back',
  'Hand: MM1…MM4 im Tippbetrieb (Spule nur solange gedrückt, mit Verriegelungen). MM5, MM6 und MM8 hängen an monostabilen Ventilen: Selbsthaltung in der SPS („öffnen/kippen“ setzt, „zurück/schließen“ setzt zurück). Die Rollenkurve −MA6 wird nur über die Vor-Ort-Steuerstelle −S30 bedient. Taster-Eingänge %I3.0…%I3.7, %I5.0…%I5.3, %I8.2/%I8.3.': 'Manual: MM1…MM4 in jog mode (coil energized only while pressed, with interlocks). MM5, MM6 and MM8 are on monostable valves: latching in the PLC (“open/tip” sets, “back/close” resets). The roller curve −MA6 is operated only from local control station −S30. Pushbutton inputs %I3.0…%I3.7, %I5.0…%I5.3, %I8.2/%I8.3.',

  // ---------------------------------------------------------------- Prozess
  'Prozess': 'Process',
  'Zinn −BT1': 'Tin −BT1',
  'Füllhöhe −BL1': 'Fill level −BL1',
  'Heizung ein': 'Heater on',
  'Heizung aus': 'Heater off',
  'Zinn nachfüllen': 'Refill tin',
  'Korb auflegen': 'Place basket',
  'Körbe automatisch zuführen': 'Feed baskets automatically',
  'Geschwindigkeit aller Zylinder': 'Speed of all cylinders',
  'Jeden Zylinder einzeln stellen die Drosselrückschlagventile an seinen Anschlüssen: Klick auf ein Ventil in der 3D-Ansicht oder „Groß öffnen“ im Weg-Zeit-Diagramm.': 'Each cylinder is set individually with the one-way flow control valves at its ports: click a valve in the 3D view or “Open large” in the displacement-time diagram.',
  'Jedes Tauchen verbraucht Zinn. Unter 40 % meldet −BG10 „Füllhöhe unterschritten“, unter 250 °C fällt −BG9 ab. Temperatur (−BT1, 0…400 °C) und Füllstand (−BL1, 0…100 %) liegen zusätzlich als Analogwerte 0…27648 an.': 'Every dip consumes tin. Below 40 % −BG10 reports “fill level too low”, below 250 °C −BG9 drops out. Temperature (−BT1, 0…400 °C) and fill level (−BL1, 0…100 %) are also available as analog values 0…27648.',
  'Heizung −TB1: {0} · Heizelement {1} % · BT1 = {2} · BL1 = {3}': 'Heater −TB1: {0} · heating element {1} % · BT1 = {2} · BL1 = {3}',
  'EIN': 'ON',
  'AUS': 'OFF',
  'NOT-HALT aktiv': 'E-STOP active',
  'SPS': 'PLC',
  'Zinn nachgefüllt (85 %)': 'Tin refilled (85 %)',
  'Anlage in Grundstellung zurückgesetzt · das CPU-Programm läuft weiter, Ausgänge greifen sofort wieder': 'Line reset to home position · the CPU program keeps running, outputs take effect again immediately',
  'Anlage in Grundstellung zurückgesetzt · SF1 startet die Automatik': 'Line reset to home position · SF1 starts automatic mode',
  'Demo: Automatik EIN': 'Demo: automatic ON',

  // ---------------------------------------------------------------- Weg-Zeit-Diagramm, Drosseln
  'Weg-Zeit-Diagramm (live, 60 s)': 'Displacement-time diagram (live, 60 s)',
  'Weg-Zeit-Diagramm aller Zylinder': 'Displacement-time diagram of all cylinders',
  'Weg-Zeit-Diagramm aller Zylinder mit Messlinien': 'Displacement-time diagram of all cylinders with cursors',
  'Schrittnummern der Demo-SPS oben': 'Demo PLC step numbers at the top',
  'jetzt': 'now',
  'Groß öffnen · Messlinien · Drosseln': 'Open large · cursors · throttles',
  'Weg-Zeit-Diagramm · Drosseln': 'Displacement-time diagram · throttles',
  'Zeitfenster': 'Time window',
  'Anhalten': 'Pause',
  'Weiter': 'Resume',
  'Messlinien löschen': 'Clear cursors',
  'Schließen (Esc)': 'Close (Esc)',
  'Fenster schließen': 'Close window',
  'Drosselrückschlagventile': 'One-way flow control valves',
  'Abluftdrosselung · 50 % = Nennzeit, 100 % = doppelt so schnell, 0 % = zu': 'Exhaust-air throttling · 50 % = nominal time, 100 % = twice as fast, 0 % = closed',
  'Alle auf 50 %': 'All to 50 %',
  'Einhängen': 'Hook in',
  'eingehängt': 'hooked in',
  'gelöst': 'released',
  'Tauchen': 'Dip',
  'oben': 'up',
  'unten': 'down',
  'Verschieben': 'Traverse',
  'Band': 'conveyor',
  'Bad': 'bath',
  'Abstreifen': 'Cover',
  'offen': 'open',
  'zu': 'closed',
  'Anschlag': 'Stop',
  'Vereinzeler': 'Separator',
  'gekippt': 'tipped',
  'Klick ins Diagramm setzt Messlinie 1, ein zweiter Klick Messlinie 2. Sie rasten an den Flanken der Endlagensensoren ein (Alt-Taste: frei). Ziehen verschiebt, Mausrad blättert im angehaltenen Diagramm.': 'Click in the diagram to set cursor 1, a second click sets cursor 2. They snap to the edges of the end-position sensors (Alt key: free). Drag to move; the mouse wheel scrolls through the paused diagram.',
  'Linie {0}: <b>{1}</b>': 'Cursor {0}: <b>{1}</b>',
  'Ausfahren': 'Extend',
  'Einfahren': 'Retract',
  'Endlagen {0} / {1}': 'End positions {0} / {1}',
  'Drosselrückschlagventil an Anschluss {0} (drosselt die Abluft beim Ausfahren)': 'One-way flow control valve at port {0} (throttles the exhaust air when extending)',
  'Drosselrückschlagventil an Anschluss {0} (drosselt die Abluft beim Einfahren)': 'One-way flow control valve at port {0} (throttles the exhaust air when retracting)',
  '−{0} Drossel {1}': '−{0} throttle {1}',
  'zu – Zylinder steht': 'closed – cylinder stopped',
  '{0} · gemessen {1}': '{0} · measured {1}',

  // ---------------------------------------------------------------- Ereignisse, Signalmonitor
  'Ereignisse': 'Events',
  'Noch keine Ereignisse.': 'No events yet.',
  'Signalmonitor': 'Signal monitor',
  'Signale filtern': 'Filter signals',
  'Filtern …': 'Filter …',
  'Signal': 'Signal',
  'Adresse': 'Address',
  'Forcen': 'Force',
  'Ausgänge SPS → Zwilling': 'Outputs PLC → twin',
  'Eingänge Zwilling → SPS': 'Inputs twin → PLC',
  '{0} forcen': 'Force {0}',
  'Wert aus dem Modell': 'Value from the model',
  'Auf 0 forcen': 'Force to 0',
  'Auf 1 forcen': 'Force to 1',
  'Name in signale.csv: {0}': 'Name in signale.csv (internal): {0}',
  // ---------------------------------------------------------------- Umrichter −TA2…−TA5 (ui/umrichter.js, anlage/g120.js)
  'Störung Überlast': 'Overload fault',
  'Motor überhitzt': 'Motor overheated',
  'Störung F30005 im Umrichter auslösen (sofort quittierbar)': 'Trigger fault F30005 in the drive (can be acknowledged at once)',
  'Kaltleiter im Motor spricht an: F07011, quittierbar erst nach dem Abkühlen': 'PTC in the motor responds: F07011, can only be acknowledged after cooling down',
  'SPS → Umrichter ·': 'PLC → drive ·',
  'Umrichter → SPS ·': 'Drive → PLC ·',
  'Drehzahlsollwert ·': 'Speed setpoint ·',
  'Drehzahlistwert ·': 'Actual speed ·',
  'Wort': 'word',
  'EIN / AUS1': 'ON / OFF1',
  'Kein AUS2 (Austrudeln)': 'No OFF2 (coast down)',
  'Kein AUS3 (Schnellhalt)': 'No OFF3 (quick stop)',
  'Betrieb freigeben': 'Enable operation',
  'Hochlaufgeber freigeben': 'Enable ramp-function generator',
  'Hochlaufgeber fortsetzen': 'Continue ramp-function generator',
  'Drehzahlsollwert freigeben': 'Enable speed setpoint',
  'Störung quittieren (Flanke 0 → 1)': 'Acknowledge fault (edge 0 → 1)',
  'nicht verwendet': 'not used',
  'Führung durch SPS': 'Control by PLC',
  'Drehrichtungsumkehr (Sollwert invertieren)': 'Direction reversal (invert setpoint)',
  'Motorpotenziometer höher (nicht verwendet)': 'Motorized potentiometer raise (not used)',
  'Motorpotenziometer tiefer (nicht verwendet)': 'Motorized potentiometer lower (not used)',
  'reserviert': 'reserved',
  'Einschaltbereit': 'Ready to switch on',
  'Betriebsbereit': 'Ready for operation',
  'Betrieb freigegeben': 'Operation enabled',
  'Störung wirksam': 'Fault active',
  'Kein AUS2 aktiv': 'No OFF2 active',
  'Kein AUS3 aktiv': 'No OFF3 active',
  'Einschaltsperre aktiv': 'Switching on inhibited',
  'Warnung wirksam': 'Alarm active',
  'Drehzahl-Soll-Ist-Abweichung im Toleranzbereich': 'Speed setpoint/actual deviation within tolerance',
  'Führung gefordert': 'Control requested',
  'Vergleichsdrehzahl erreicht': 'Comparison speed reached',
  'I-, M- oder P-Grenze nicht erreicht': 'I, M or P limit not reached',
  'Haltebremse offen': 'Holding brake open',
  'Keine Warnung Motorübertemperatur': 'No motor overtemperature alarm',
  'Motor dreht rechts': 'Motor rotates clockwise',
  'Keine Warnung Umrichterüberlast': 'No drive overload alarm',
  'S1 Einschaltsperre': 'S1 Switching on inhibited',
  'S2 Einschaltbereit': 'S2 Ready to switch on',
  'S3 Betriebsbereit': 'S3 Ready for operation',
  'S4 Betrieb': 'S4 Operation',
  'S5 Ausschalten': 'S5 Switching off',
  'S5 Ausschalten (AUS1)': 'S5 Switching off (OFF1)',
  'S5 Schnellhalt (AUS3)': 'S5 Quick stop (OFF3)',
  'Störung': 'Fault',
  'Leistungsteil Überlast I2t': 'Power unit overload I2t',
  'Motorübertemperatur': 'Motor overtemperature',
  'Feldbus: Sollwert-Timeout': 'Fieldbus: setpoint timeout',
  'Display Bedienpanel IOP-2': 'Display of operator panel IOP-2',
  'Drehrad': 'Jog wheel',
  'ESC: zurück zur Statusanzeige': 'ESC: back to the status display',
  'INFO: Diagnose (Störungen und Warnungen)': 'INFO: diagnostics (faults and alarms)',
  'Drehrad: Mausrad, Pfeiltasten oder Klick auf den linken/rechten Rand drehen, Mitte drücken = OK': 'Jog wheel: turn with the mouse wheel, arrow keys or a click on the left/right edge, press the centre = OK',
  'EIN (nur in HAND)': 'ON (HAND only)',
  'AUS (AUS1, nur in HAND)': 'OFF (OFF1, HAND only)',
  'Umschalten HAND / AUTO': 'Switch HAND / AUTO',
  'Tasten bedienbar · Mausrad am Drehrad': 'Keys can be operated · mouse wheel on the jog wheel',
  'FSA · 0,37 kW · 3 AC 400 V': 'FSA · 0.37 kW · 3 AC 400 V',
  'EIN nur in HAND': 'ON only in HAND',
  'AUS nur in HAND': 'OFF only in HAND',
  'Quittieren …': 'Acknowledging …',
  'Störungen und Warnungen': 'Faults and alarms',
  'Warnung': 'Alarm',
  'Safe Torque Off angewählt (−KF2)': 'Safe Torque Off selected (−KF2)',
  'Keine Störungen oder Warnungen': 'No faults or alarms',
  'OK = Quittieren': 'OK = acknowledge',
  'ESC = zurück': 'ESC = back',
  'Drehzahl': 'Speed',
  'Sollwert': 'Setpoint',
  'Strom': 'Current',
  'Istwerte': 'Actual values',
  'Ausgangsfrequenz': 'Output frequency',
  'Ausgangsspannung': 'Output voltage',
  'Ausgangsstrom': 'Output current',
  'Bandgeschwindigkeit': 'Conveyor speed',
  'Telegramm 1': 'Telegram 1',
  'HAND: Das Bedienpanel führt den Umrichter (I/O, Drehrad = Sollwert). Das Telegramm der SPS ist ohne Wirkung, ZSW1.9 = 0.': 'HAND: the operator panel controls the drive (I/O, jog wheel = setpoint). The PLC telegram has no effect, ZSW1.9 = 0.',
  'Frontansicht Umrichter (SINAMICS G120)': 'Front view of the drive (SINAMICS G120)',
  'Antriebe: Schütz oder Umrichter (SINAMICS G120, Telegramm 1)': 'Drives: contactor or frequency converter (SINAMICS G120, telegram 1)',
  'Band 1 −MA1': 'Conveyor 1 −MA1',
  'Band 2 −MA2': 'Conveyor 2 −MA2',
  'Prüfband −MA5': 'Inspection conveyor −MA5',
  'Antrieb Band 1 −MA1': 'Drive of conveyor 1 −MA1',
  'Antrieb Band 2 −MA2': 'Drive of conveyor 2 −MA2',
  'Antrieb Rollenkurve −MA6': 'Drive of roller curve −MA6',
  'Antrieb Prüfband −MA5': 'Drive of inspection conveyor −MA5',
  'Schütz −QA1/−QA2': 'Contactor −QA1/−QA2',
  'Schütz −QA5/−QA6': 'Contactor −QA5/−QA6',
  'Schütz −QA10/−QA11': 'Contactor −QA10/−QA11',
  'Schütz −QA9': 'Contactor −QA9',
  'Umrichter −TA2': 'Drive −TA2',
  'Umrichter −TA3': 'Drive −TA3',
  'Umrichter −TA4': 'Drive −TA4',
  'Umrichter −TA5': 'Drive −TA5',
  'Umrichter und Telegramme öffnen': 'Open drives and telegrams',
  'Umrichter · SINAMICS G120 · Standardtelegramm 1': 'Drive · SINAMICS G120 · standard telegram 1',
  'Umrichter wählen': 'Select drive',
  'Umrichter': 'Drive',
  'Standardtelegramm 1': 'standard telegram 1',
  'Prüfband': 'Inspection conveyor',
  'Rampen live': 'Ramps live',
  'Sollwert NSOLL_A': 'Setpoint NSOLL_A',
  'wirksamer Sollwert (Hochlaufgeber-Eingang)': 'effective setpoint (ramp-function generator input)',
  'Istdrehzahl NIST_A': 'Actual speed NIST_A',
  'Verlauf von Sollwert und Istdrehzahl des Umrichters': 'Trend of setpoint and actual speed of the drive',
  'Am Umrichter: {0}. {1}': 'On a drive: {0}. {1}',
  'Das Bandmodul führt sie selbst. Mit „SPS steuert“ übernimmt dein Programm die Telegramme.': 'The conveyor module controls them itself. With “PLC controls” your program takes over the telegrams.',
  'Dein Programm führt sie über Standardtelegramm 1 (STW1/NSOLL_A → ZSW1/NIST_A), z. B. mit TO_SpeedAxis; die zugehörigen Schütze sind ohne Wirkung.': 'Your program controls them via standard telegram 1 (STW1/NSOLL_A → ZSW1/NIST_A), e.g. with TO_SpeedAxis; the associated contactors have no effect.',
  'Der Umrichter ist nicht gewählt: im Übungsumfang {0} auf „Umrichter −{1}“ stellen.': 'The drive is not selected: in the exercise scope set {0} to “Drive −{1}”.',
  'Der Umrichter treibt {0}. Das Bandmodul (Übungsumfang „automatisch“) führt ihn über dasselbe Telegramm. Not-Halt wählt STO an.': 'The drive runs {0}. The conveyor module (exercise scope “automatic”) controls it via the same telegram. Emergency stop selects STO.',
  'Der Umrichter treibt {0}. Fahrbefehle kommen aus dem Telegramm der SPS, die Schützansteuerung {1} ist ohne Wirkung. Not-Halt wählt STO an.': 'The drive runs {0}. Commands come from the PLC telegram, contactor control {1} has no effect. Emergency stop selects STO.',
  // ---------------------------------------------------------------- Vor-Ort-Steuerstelle Prüfband −S50
  'Vor-Ort-Steuerstelle Prüfband (−S50)': 'Local control station inspection conveyor (−S50)',
  'Prüfband EIN': 'Conveyor ON',
  'Prüfband AUS': 'Conveyor OFF',
  'Schlüsselschalter Vor-Ort Prüfband (SA7)': 'Key switch local inspection conveyor (SA7)',
  'Prüfband EIN (SF45)': 'Inspection conveyor ON (SF45)',
  'Prüfband AUS (SF46)': 'Inspection conveyor OFF (SF46)',
  'Drehzahl Prüfband (SF47)': 'Speed of inspection conveyor (SF47)',
  'Hat Vorrang vor −S40. Die Drehzahl wirkt nur am Umrichter −TA5, am Schütz −QA9 läuft das Prüfband mit Nenngeschwindigkeit. Not-Halt und Quittieren an −S40.': 'Takes priority over −S40. The speed only acts on drive −TA5; on contactor −QA9 the inspection conveyor runs at rated speed. Emergency stop and acknowledge at −S40.',
  'Drehzahl {0} %': 'Speed {0} %',
  'Vor-Ort −S50 Prüfband': 'Local −S50 inspection conveyor',
  'Tiefenschatten': 'Ambient occlusion',
  'Tiefenschatten (Ambient Occlusion): Verschattung in Ecken, Nuten und Spalten – realistischer, kostet Grafikleistung': 'Ambient occlusion: shading in corners, grooves and gaps – more realistic, costs graphics performance',
  // Kühlwassertank
  'Kühlwassertank: Nachspeisung': 'Cooling water tank: refill',
  'Niveauregler automatisch': 'Level controller automatic',
  'Nachspeisung des Kühlwassertanks': 'Refilling of the cooling water tank',
  'Kühlwasser −BL2': 'Cooling water −BL2',
  'Ablasshahn Kühlwasser': 'Cooling water drain valve',
  'Ablasshahn öffnen': 'Open drain valve',
  'Ablasshahn schließen': 'Close drain valve',
  'Motorschutz {0} auslösen': 'Trip motor protection {0}',
  'Motorschutz {0} zurücksetzen': 'Reset motor protection {0}',
  'Drahtbruch {0}': 'Wire break {0}',
  'Bytes zeigen': 'Show bytes',
  'BCD-Geräte': 'BCD devices',
  'Körbe': 'Baskets',
  'Tauchzeit s': 'Dip time s',
  'KÖRBE': 'BASKETS',
  'TAUCHZEIT s': 'DIP TIME s',
  'Daumenradschalter Tauchzeit −SF48': 'Thumbwheel switch dip time −SF48',
  'Hunderter': 'Hundreds',
  'Zehner': 'Tens',
  'Einer': 'Units',
  'Anzeigeformat für Byte und Wort': 'Display format for byte and word',
  'Byte aus den Bits darunter': 'Byte made up of the bits below',
  'Dez': 'Dec',
  'Drahtbruch {0} beheben': 'Repair wire break {0}',
  'Störgröße: Leitung zum Analogsensor unterbrochen, die Analogbaugruppe meldet 7FFF (32767) statt des Messwerts': 'Disturbance: line to the analog sensor interrupted, the analog module reports 7FFF (32767) instead of the measured value',
  'Störgröße: Motorschutzschalter löst aus, sein Hilfskontakt meldet 0 und der Motor steht, bis du ihn zurücksetzt': 'Disturbance: the motor protection switch trips, its auxiliary contact reports 0 and the motor stops until you reset it',
  'Störgröße: Handventil am Kühlwassertank öffnen (ca. 1 %/s)': 'Disturbance: open the manual valve on the cooling water tank (approx. 1 %/s)',
  'Jedes Abschrecken verbraucht Kühlwasser, heiße Körbe verdampfen zusätzlich. Grenzschalter Liquiphant: −BG38 = 1, solange Wasser über Minimum (25 %) steht, −BG39 = 1, solange Maximum (90 %) nicht erreicht ist (Ruhestrom: Drahtbruch meldet wie leer bzw. voll); den Füllstand misst der Radar −BL2 stetig; unter 8 % läuft die Pumpe −MA3 trocken. Der Ablasshahn ist eine Störgröße zum Testen der Regelung.': 'Every quench consumes cooling water, hot baskets evaporate extra. Liquiphant point level switches: −BG38 = 1 while the water is above minimum (25 %), −BG39 = 1 while maximum (90 %) is not reached (closed-circuit principle: a wire break reports empty or full); the radar −BL2 measures the level continuously; below 8 % the pump −MA3 runs dry. The drain valve is a disturbance for testing the control.',
  'Kühlwasser: Der Niveauregler am Tank speist zwischen 55 und 75 % nach und sperrt die Pumpe unter −BG38.': 'Cooling water: the level controller on the tank refills between 55 and 75 % and locks the pump below −BG38.',
  'Kühlwasser: −MB17 Magnetventil und −MB18 Regelventil (%QW80, 0…27648) aus deinem Programm – Zweipunkt mit den Grenzschaltern −BG38/−BG39, mit Hysterese auf den Radar −BL2 (%IW72) oder stetig mit PID_Compact. Den Trockenlaufschutz der Pumpe −MA3 übernimmt dein Programm.': 'Cooling water: −MB17 solenoid valve and −MB18 control valve (%QW80, 0…27648) from your program – on/off with the point level switches −BG38/−BG39, with hysteresis on the radar −BL2 (%IW72) or continuously with PID_Compact. Your program also handles the dry-run protection of pump −MA3.',
  'ZU': 'CLOSED',
  'AUF': 'OPEN',
  'Nachspeisen −MB17: {0} · Regelventil −MB18: {1} % · Zulauf {2} %/s · Verbrauch {3} %/s · BL2 = {4}': 'Refill −MB17: {0} · control valve −MB18: {1} % · inflow {2} %/s · consumption {3} %/s · BL2 = {4}',
  'Pumpe gesperrt (−BG38)': 'pump locked (−BG38)',
  'Kühlwassertank · Nachspeisung': 'Cooling water tank · refill',
  // Übungsumfang Verzinnen (Portal) und Rezept
  'Verzinnen: Portal −MM1…−MM4': 'Tinning: gantry −MM1…−MM4',
  'Portal automatisch': 'Gantry automatic',
  'Steuerung des Portals': 'Control of the gantry',
  'Portal': 'Gantry',
  'Portal auto': 'Gantry auto',
  'Übungsumfang Verzinnen: Portal automatisch. Das Ventil schaltet die Portalsteuerung, dieser SPS-Ausgang ist ohne Wirkung.': 'Exercise scope tinning: gantry automatic. The gantry control switches this valve, the PLC output has no effect.',
  'Übungsumfang: Portal −MM1…−MM4 fährt jetzt automatisch, die Ventilausgänge −MB1…−MB8 der SPS sind ohne Wirkung': 'Exercise scope: gantry −MM1…−MM4 now runs automatically, the PLC valve outputs −MB1…−MB8 have no effect',
  'Übungsumfang: Portal automatisch (wirkt mit PLCSIM Advanced, in der Demo fährt die Demo-SPS ohnehin)': 'Exercise scope: gantry automatic (takes effect with PLCSIM Advanced, in the demo the demo PLC runs it anyway)',
  'Übungsumfang: Portal −MM1…−MM4 steuert jetzt die SPS': 'Exercise scope: gantry −MM1…−MM4 is now controlled by the PLC',
  'Portal: Die Portalsteuerung fährt die Schrittkette selbst (einhängen, anheben, zum Bad, tauchen, abtropfen, zurück, absetzen, lösen), sobald −KF2 frei ist. Nach einem Not-Halt läuft sie erst nach dem Quittieren mit START −SF1 wieder an; −SA3 Hand schaltet auf die Tipptaster am Türtableau. Sie beginnt, wenn ein Korb an −BG40 anliegt, und hebt und senkt nur bei offenem Anschlag −BG15. Dein Programm stoppt also das Band an −BG40, öffnet −MB9, sobald −BG1 eingehängt meldet, und lässt den fertigen Korb nach −BG2 gelöst abfahren.': 'Gantry: the gantry control runs the sequence itself (hook in, lift, to the bath, dip, drain, back, set down, release) as soon as −KF2 is enabled. After an E-stop it only restarts after acknowledging and pressing START −SF1; −SA3 manual switches to the jog buttons on the door panel. It starts when a basket rests against −BG40 and only lifts and lowers with the stop open (−BG15). So your program stops the conveyor at −BG40, opens −MB9 as soon as −BG1 reports hooked in, and lets the finished basket leave after −BG2 released.',
  'Portal: −MB1…−MB8 (Einhängen/Lösen, Senken/Anheben, Bad/Band, Abdeckung) aus deinem Programm; Endlagen −BG1…−BG8.': 'Gantry: −MB1…−MB8 (hook in/release, lower/lift, bath/conveyor, cover) from your program; end positions −BG1…−BG8.',
  'Tauchzeit (Rezept)': 'Dipping time (recipe)',
  'Abtropfzeit (Rezept)': 'Draining time (recipe)',
  'Tauchzeit': 'dipping time',
  'Abtropfzeit': 'draining time',
  'Rezept: {0} {1} s': 'Recipe: {0} {1} s',
  'Die Demo-SPS und das Portal „automatisch“ tauchen und tropfen so lange. Steuert dein Programm das Portal, prüft der Zwilling, ob es die Zeiten einhält: Ist ein Korb kürzer getaucht oder abgetropft (0,5 s Toleranz), ist er mangelhaft.': 'The demo PLC and the gantry “automatic” dip and drain for this long. If your program controls the gantry, the twin checks whether it keeps these times: a basket dipped or drained for less (0.5 s tolerance) is defective.',
  // Grafik-Fenster
  'Grafik': 'Graphics',
  'Grafikeinstellungen': 'Graphics settings',
  'Qualität': 'Quality',
  'Auto passt die Stufe an die Bildrate an': 'Auto adapts the level to the frame rate',
  'Auto': 'Auto',
  'Spiegelungen': 'Reflections',
  'Metall spiegelt die Halle (wirkt in Stufe Hoch)': 'Metal reflects the hall (applies at level High)',
  'Verschattung in Ecken, Nuten und Spalten – kostet Grafikleistung': 'Shading in corners, grooves and gaps – costs graphics performance',
  'Grafikkarte: {0}': 'Graphics card: {0}',
  'unbekannt': 'unknown',
  'Das ist die Onboard-Grafik. Hat der Rechner zusätzlich eine NVIDIA- oder AMD-Karte: Windows-Einstellungen → System → Anzeige → Grafik → Browser auf „Hohe Leistung“ stellen und den Browser neu starten.': 'This is the integrated graphics. If the computer also has an NVIDIA or AMD card: Windows Settings → System → Display → Graphics → set the browser to “High performance” and restart the browser.',
  'Schließen': 'Close',
  // Seitenleiste lösen
  'Lösen': 'Detach',
  'Andocken': 'Dock',
  'Zurück in das Hauptfenster': 'Back into the main window',
  'In eigenem Fenster öffnen, z. B. auf einem zweiten Bildschirm': 'Open in a separate window, e.g. on a second screen',
  'Fenster blockiert': 'Window blocked',
  'Der Browser hat das neue Fenster blockiert. Bitte Pop-ups für diese Seite erlauben.': 'The browser blocked the new window. Please allow pop-ups for this page.',
};
