// Stammdaten der Übung L19 (Felder siehe uebungVorlage.md). Langtexte in texte.json, Kurz-Checks in quiz.js.
{id:"L19", st:2, t:"Not-Halt-Diagnose und Erstwert", sub:"Sicherheitsfunktion und Diagnose trennen", ue:3, vor:"L12, L15", repo:"5", bild:["02-bedienpult.jpg","Not-Halt −SF0 und Quittiertaster −SF4 am Bedienpult"],
 typ:"programmieren",
 einst:"Übungsumfang: <i>Verzinnen: Portal −MM1…−MM4</i> = <i>Portal automatisch</i>, <i>Band, Anschlag, Vereinzeler</i> = <i>Bandmodul automatisch</i>, <i>Zinnbad: Temperatur und Füllstand</i> = <i>Regler automatisch</i>, <i>Kühlwassertank: Nachspeisung</i> = <i>Niveauregler automatisch</i>, −SA3 auf AUTO. Portal und Band laufen von selbst, damit du siehst, dass −KF2 alles anhält. Portalsteuerung und Bandmodul des Zwillings laufen nach dem Quittieren erst mit START −SF1 wieder an, wie an einer realen Anlage mit neuem Startbefehl. Deine Wiederanlaufsperre prüfst du an deinen eigenen Ausgängen. Dein Programm schaltet in dieser Übung nur die Leuchtmelder −PF5 und −PF12 bis −PF15. Alle fünf Not-Halt-Taster sind in der 3D-Ansicht unter <i>Ansicht → Steuerstellen</i> erreichbar.",
 ziele:["begründen, warum Meldekontakte nur melden und nicht abschalten (Sicherheitsfunktion und Diagnose trennen)","eine Erstwertmeldung bilden","Lichtvorhang und Not-Halt in der Diagnose unterscheiden und den Quittierort erkennen"],
 sig:"KF2 SF0 SF8 SF9 SF10 SF33 SF4 SF41 SF42 SF43 SF44 PF5 PF12 PF13 PF14 PF15 BG20",
 sit:"Die Anlage hat fünf Not-Halt-Taster. Nach einem Stillstand fragt der Schichtleiter: Welcher Taster hat ausgelöst, und wo wurde quittiert?",
 plan:["Fülle die Vorlage „Not-Halt-Zuordnung und Erstwert“ aus: Taster, Steuerstelle, Meldekontakt, Quittiertaster und Leuchtmelder stehen schon drin. Du legst je Taster die Erstwert-Nummer 1 bis 5 und den Meldetext für den Quittierort fest."],
 auf:["Lege einen FB <code>EStopDiag</code> mit Bausteinkopf an und rufe ihn im OB1 auf. Er bekommt Meldekontakte, Quittiertaster, −BG20 und −KF2 über seine Eingänge und schreibt nur Anzeigen. Prüfe in der Querverweisliste, dass −PF5 seit L12 keine Schreibstelle hat. <code>EStopDiag</code> wird die einzige. Trage −PF5 und −PF12 bis −PF15 in die Vorlage „Ausgangsliste“ ein.","Speichere den <b>ersten</b> ausgelösten Taster in <code>#statFirstEStop</code> (Int 0 bis 5) nach deiner Tabelle. Weitere Taster überschreiben ihn nicht. Lege fest, wann er gelöscht wird.","Programmiere die Meldung Lichtvorhang: Schaltet −KF2 ab, ohne dass ein Meldekontakt gefallen ist, und war −BG20 unterbrochen, gib eine eigene Meldung „Lichtvorhang“ aus.","Erkenne beim Wiederanlauf von −KF2 (positive Flanke), an welchem Quittiertaster quittiert wurde.","Lasse alle Quittier-Leuchttaster mit 2 Hz blinken, sobald quittiert werden kann: −KF2 gibt nicht frei, alle Not-Halt-Taster sind entriegelt und −BG20 ist frei. Nimm dafür deinen FB <code>Clock</code> aus L04 als Multiinstanz.","Bilde Erstwert und Quittierort als Meldetext in einer <code>WString</code>-Variablen und zeige ihn in einer Beobachtungstabelle an."],
 hilfe:{1:["Woran erkennst du, dass ein Taster gerade erst gedrückt wurde, und wann darf er den Erstwert noch eintragen?","Werte je Meldekontakt die fallende Flanke aus (<code>F_TRIG</code>, denn gedrückt heißt 0). Trage nur ein, solange <code>#statFirstEStop</code> noch 0 ist. Frage die Taster in einer festen Reihenfolge ab.","<pre class=\"code\"><code>#instEdgeSF0(CLK := #eStopSF0);   // F_TRIG\n#instEdgeSF8(CLK := #eStopSF8);\nIF #statFirstEStop = 0 THEN\n  IF #instEdgeSF0.Q THEN #statFirstEStop := #ESTOP_PULT;\n  ELSIF #instEdgeSF8.Q THEN #statFirstEStop := #ESTOP_S10;\n  END_IF;   // ... weitere Taster\nEND_IF;</code></pre>Die Nummern aus deiner Tabelle legst du als lokale Konstanten an (z. B. <code>ESTOP_PULT</code> = 1, <code>ESTOP_S10</code> = 2). Fallen zwei im selben Zyklus, gewinnt der zuerst abgefragte. Das schreibst du in den Kommentar."],3:["Ist der Quittiertaster noch gedrückt, wenn −KF2 wieder 1 meldet? Bei einem Relais mit überwachtem Start nicht.","Merke dir bei jeder steigenden Flanke eines Quittiertasters, welcher es war (<code>#statLastAck</code>). Bei der steigenden Flanke von −KF2 übernimmst du diesen Wert als Quittierort.","<pre class=\"code\"><code>IF #instAckSF4.Q THEN #statLastAck := #ACK_PULT; END_IF;\nIF #instAckSF43.Q THEN #statLastAck := #ACK_S30; END_IF;\n// ... weitere Taster\n#instSafetyOkEdge(CLK := #safetyOk);   // R_TRIG\nIF #instSafetyOkEdge.Q THEN\n  #statAckPlace := #statLastAck;\nEND_IF;</code></pre>Die Konstanten <code>ACK_PULT</code> = 1 bis <code>ACK_S40</code> = 5 legst du lokal an, in der Reihenfolge −SF4, −SF41, −SF42, −SF43, −SF44."]},
 lf:[["Warum werden die Meldekontakte nur gemeldet und nicht zum Abschalten benutzt?",[0]],["Wie unterscheidest du Not-Halt und Lichtvorhang, obwohl beide über −KF2 abschalten? Bedenke: Das Schutzfeld meldet nach dem Durchgriff sofort wieder frei.",[2]],["Ein Sicherheitsrelais mit überwachtem Start gibt erst beim Loslassen des Quittiertasters frei. Was musst du dir merken, um den Quittierort trotzdem zu erkennen?",[2]],["Zwei Taster werden im selben CPU-Zyklus gedrückt. Welchen Erstwert meldet dein Programm, und warum kann es das nicht genauer?",[1]]],
 lfk:["Du hast den Meldekontakt eines Not-Halt-Tasters im Signalmonitor auf 0 geforct (Drahtbruch). Was hat deine Diagnose angezeigt, und was hat −KF2 getan?"],
 pr:[["−SF9 drücken, dann −SF0 → Erstwert = −SF9 (Nummer laut Tabelle)",[1]],["Beide entriegeln, an −S30 quittieren (−SF43) → Meldetext „quittiert an −S30“",[2]],["Person durch den Lichtvorhang gehen lassen → eigene Meldung „Lichtvorhang“, kein Not-Halt-Erstwert",[2]],["Leuchttaster: bei gedrücktem Not-Halt aus, nach dem Entriegeln Blinken mit 2 Hz, nach dem Quittieren aus",[0,2]],["Querverweisliste: −PF5 und −PF12 bis −PF15 haben je genau eine Schreibstelle; kein Ausgang von EStopDiag geht an ModeSelect, Interlock oder CommandOutput",[0]]],
 ergebnis:[{n:"FB EStopDiag",a:"neu",h:"Erstwert, Lichtvorhang, Quittierort, einzige Schreibstelle von −PF5 und −PF12 bis −PF15"},{n:"FB Clock",a:"übernommen",h:"als Multiinstanz für 2 Hz"},{n:"Tabelle Not-Halt-Taster",a:"neu",h:"Grundlage für das Meldekonzept in L37"}, {n:"Ausgangsliste", a:"erweitert", h:"neue Zeilen: −PF5, −PF12, −PF13, −PF14, −PF15"}],
 plus:"Erkenne „Meldekontakt gestört“: Ein Meldekontakt meldet betätigt, aber −KF2 gibt frei. Gib dafür einen eigenen Meldetext aus. Wer ein eigenes HMI-Projekt hat, zeigt Erstwert und Quittierort zusätzlich dort als Meldung an.",
 tpls:[
 {id:"nothalt", cap:"Not-Halt-Zuordnung und Erstwert", phase:2, head:["Not-Halt","Steuerstelle","Meldekontakt","Quittiertaster","Leuchtmelder","Erstwert-Nummer (1 bis 5)","Meldetext beim Quittieren hier"], muster:["−SF10","−S30 Rollenkurve","%I9.4","−SF43","−PF14","deine Nummer, z. B. nach Lage von links nach rechts","Text, den der Bediener am Quittierort lesen soll"], rows:[["−SF0","Bedienpult","%I9.1","−SF4","−PF5"],["−SF8","−S10 Band 1","%I9.2","−SF41","−PF12"],["−SF9","−S20 Band 2","%I9.3","−SF42","−PF13"],["−SF10","−S30 Rollenkurve","%I9.4","−SF43","−PF14"],["−SF33","−S40 Prüfstation","%I9.5","−SF44","−PF15"]], inputs:2},
 {id:"schreib", erweitert:"L02:schreib", cap:"Ausgangsliste", phase:4, head:["Ausgang","Bedeutung","ab Übung","schreibt (Baustein, einzige Stelle)","Bedingung oder Befehl kommt von","in der Querverweisliste geprüft"], muster:["−PF2","Bad bereit","L02","FB Indication (bis L03 FC), Aufruf im OB1","−BG9 UND −BG10, ODER Lampentest −SF4","ja, eine Schreibstelle"], rows:[["−PF5","Quittieraufforderung Bedienpult","L19"],["−PF12","Quittieraufforderung −S10","L19"],["−PF13","Quittieraufforderung −S20","L19"],["−PF14","Quittieraufforderung −S30","L19"],["−PF15","Quittieraufforderung −S40","L19"]], inputs:3}
]
}
