// Stammdaten der Übung L17 (Felder siehe uebungVorlage.md). Langtexte in texte.json, Kurz-Checks in quiz.js.
{id:"L17", st:2, t:"Schrittkette Verzinnen", sub:"Automatik als GRAFCET entwerfen und umsetzen", ue:6, vor:"L16", repo:"2", bild:["04-zinnbad.jpg","Portal über dem Zinnbad mit −MM1 bis −MM4"],
 typ:"programmieren",
 einst:"Übungsumfang: <i>Verzinnen: Portal −MM1…−MM4</i> = <i>SPS steuert</i>, <i>Band, Anschlag, Vereinzeler</i> = <i>Bandmodul automatisch</i>, <i>Zinnbad: Temperatur und Füllstand</i> = <i>Regler automatisch</i>, <i>Kühlwassertank: Nachspeisung</i> = <i>Niveauregler automatisch</i>. Dein Programm fährt das Portal (−MB1 bis −MB8). In AUTO bringt das Bandmodul die Körbe, hält sie am Anschlag an und öffnet den Anschlag −MM5 selbst, sobald dein Portal den Korb eingehängt hat. In AUTO wirkt deine Zeile für −MB9 erst ab L21. Schaltest du −SA3 auf HAND, schalten −MB9 und −MB10 wieder nach deinem Programm. Schreibst du −MB10 nicht, öffnet die Feder den Vereinzeler, und die Körbe stauen sich am Anschlag.",
 ziele:["eine Ablaufsteuerung als GRAFCET nach DIN EN 60848 entwerfen und dabei Schritt, Transition und Aktion unterscheiden","die Schrittkette im FB als statische Bool-Variablen oder als CASE-Anweisung mit ELSE-Zweig umsetzen","die Kette so einbinden, dass sie nur Auto-Befehle an die Befehlsausgabe liefert und die Prozesszeiten ab Endlage einhält"],
 sig:"SF1 SA3 KF2 MB1 MB2 MB3 MB4 MB5 MB6 MB7 MB8 BG1 BG2 BG3 BG4 BG5 BG6 BG7 BG8 BG15 BG40",
 sit:"Ein Korb liegt am Anschlag (−BG40). Das Portal soll ihn auf START einmal komplett verzinnen. Tauch- und Abtropfzeit betragen je 10 s; einstellbar sind sie unter <i>Prozess</i> von 2 bis 30 s.",
 tab:{cap:"Soll-Ablauf", ...T(["Schritt","Aktion","Ventil","Weiter, wenn"],[
  ["1","Initialschritt, warten","–","AUTO, startbereit und START"],["2","Korb einhängen","−MB1","−BG1 und Anschlag offen −BG15"],["3","Anheben","−MB4","−BG3"],["4","Zum Zinnbad","−MB5","−BG6"],["5","Bad öffnen","−MB8","−BG7"],["6","Tauchen","−MB3","−BG4 und Tauchzeit abgelaufen"],["7","Anheben, abtropfen","−MB4","−BG3 und Abtropfzeit abgelaufen"],["8","Bad abdecken, zurück zum Band","−MB7 und −MB6","−BG8, −BG5 und −BG15"],["9","Absenken","−MB3","−BG4"],["10","Korb lösen","−MB2","−BG2, zurück zu Schritt 1"]])},
 plan:["Entwirf aus der Tabelle „Soll-Ablauf“ einen GRAFCET mit Schritten, Transitionen und Aktionen und lasse ihn freigeben. Schreibe an die Transition 1 → 2, was „startbereit“ bei dir umfasst.","Ergänze deine Skizze der Programmstruktur um Tinning: Platz im OB1, Eingänge, Auto-Befehle an CommandOutput."],
 auf:["Lege einen FB <code>Tinning</code> mit Bausteinkopf an und rufe ihn im OB1 vor <code>CommandOutput</code> auf. Verschalte seine Auto-Befehle über <code>PlantData</code> mit <code>CommandOutput</code> und nimm die Steuerwerte aus der Beobachtungstabelle von L16 heraus.","Übertrage deinen freigegebenen GRAFCET: Variante A (statische Bool-Variable je Schritt, Setzen und Rücksetzen in FUP) oder Variante B (<code>CASE #statStep OF</code> in SCL mit ELSE-Zweig).","Programmiere den Initialschritt 1: Die Kette verlässt ihn nur bei <code>modeAuto</code>, Startbereitschaft und START. Setze dafür deine Transition aus dem GRAFCET um.","Programmiere die Schritte 2 bis 5 und 8 bis 10 so, dass jeder nur den Auto-Befehl seiner Bewegung setzt und auf die gemeldete Endlage weiterschaltet.","Programmiere die Schritte 6 und 7: Tauch- und Abtropfzeit laufen erst ab Endlage (<code>TON</code> mit Eingang Schritt aktiv UND Endlage). Lege die Sollwerte als <code>Time</code>-Variablen in <code>PlantData</code> an, passend zu den Rezeptzeiten im Zwilling, und trage sie in die Vorlage „Variablenliste PlantData“ ein.","Lege fest, was die Kette bei einem Wechsel nach HAND und bei Not-Halt mitten im Zyklus tut, trage es in die Vorlage „Festlegung: Unterbrechung der Kette mitten im Zyklus“ ein, setze es um und dokumentiere es im Bausteinkopf. Danach darf sie nicht von selbst weiterlaufen.","Fahre einen vollständigen Zyklus und sichere das Weg-Zeit-Diagramm als Bildschirmfoto (Karte „Weg-Zeit-Diagramm im Zwilling“)."],
 hilfe:{1:["Wie viele Schritte dürfen in deiner Kette gleichzeitig aktiv sein, und wie stellst du das im Programm sicher?","Variante B: Lege <code>#statStep</code> (Int, Startwert 1) an. Schreibe je Schritt einen CASE-Zweig, der nur seine Transition prüft und dann <code>#statStep</code> auf den nächsten Wert setzt. Die Auto-Befehle bildest du nach dem <code>END_CASE</code> aus der Schrittnummer.","<pre class=\"code\"><code>CASE #statStep OF\n  1: IF #modeAuto AND #autoReady AND #readyToStart\n        AND #basketAtStopper AND #start THEN\n       #statStep := 2;\n     END_IF;\n  2: IF #mm1Hooked AND #stopperOpen THEN\n       #statStep := 3;\n     END_IF;\n  // ... Schritte 3 bis 10\n  ELSE\n    #statStep := 1;\nEND_CASE;\n#autoHook := #statStep = 2;\n#autoRaise := (#statStep = 3) OR (#statStep = 7);</code></pre>"],4:["Was passiert mit der Tauchzeit, wenn die Drossel von −MM2 halb zu ist und die Zeit schon beim Schrittwechsel startet?","Rufe den <code>TON</code> als Multiinstanz in jedem Zyklus auf, außerhalb des CASE. Sein Eingang IN ist „Schritt 6 aktiv UND −BG4“, PT ist der Sollwert <code>dipTime</code>. Die Transition 6 → 7 fragt seinen Ausgang Q ab.","<pre class=\"code\"><code>#instTimerDip(IN := (#statStep = 6) AND #mm2Down,\n              PT := #dipTime);\n// im CASE, Schritt 6:\n//   IF #instTimerDip.Q THEN #statStep := 7; END_IF;</code></pre>"],5:["Was passiert mit den Auto-Befehlen in HAND? Was mit der Schrittnummer?","Zwei vertretbare Wege: a) Die Kette behält ihren Schritt, ihre Befehle wirken in HAND nicht, und sie läuft erst nach einem neuen START weiter. b) Die Kette springt in den Initialschritt zurück, und die Anlage wird von Hand in Grundstellung gebracht. Prüfe für beide, was ein Korb im Zinn bedeutet.","Beispiel für b): Bei <code>modeAuto</code> = 0 setzt du <code>#statStep := 1</code>. Nach der Rückkehr in AUTO verlangt Schritt 1 Grundstellung und START, also läuft nichts von selbst. Hängt der Korb noch im Bad, fährst du ihn in HAND heraus."]},
 lf:[["Warum starten die Zeiten in Schritt 6 und 7 erst ab Endlage und nicht beim Schrittwechsel?",[2]],["Warum darf in Schritt 8 gleichzeitig abgedeckt und zurückgefahren werden? Sieh dir dazu in der 3D-Ansicht an, wo Korb und Abdeckung in Schritt 8 stehen.",[0]],["Was passiert mit dem Korb, wenn das Portal in Schritt 2 anhebt, bevor −BG15 meldet?",[0]],["Warum braucht eine CASE-Anweisung für die Schrittkette einen ELSE-Zweig?",[1]]],
 pr:[["Ein Zyklus läuft vollständig, die Ereignisliste meldet „Korb … verzinnt“ und keinen „Korb mangelhaft“",[0,2]],["Weg-Zeit-Diagramm zeigt die Bewegungen in der Reihenfolge des GRAFCET",[0]],["Tauchzeit im Zwilling unter Prozess (Schieber Tauchzeit (Rezept)) und als Sollwert in der Beobachtungstabelle auf 5 s geändert → Kette taucht 5 s, keine Meldung „Korb mangelhaft“",[2]],["−BG7 im Signalmonitor auf 0 forcen → Kette bleibt in Schritt 5 stehen, keine weitere Bewegung",[0,1]],["Not-Halt oder Wechsel auf HAND in Schritt 6, danach quittieren bzw. zurück auf AUTO → Kette läuft nicht selbsttätig weiter",[1,2]],["Variante B: #statStep in der Beobachtungstabelle auf 99 gesteuert → der ELSE-Zweig greift wie festgelegt",[1]],["Querverweisliste: Ventile weiterhin nur beim Aufruf von CommandOutput geschrieben",[2]]],
 ergebnis:[{n:"FB Tinning",a:"neu",h:"Schrittkette des Portals, liefert nur Auto-Befehle; wird in L18 und L22 erweitert"},{n:"GRAFCET Verzinnen",a:"neu",h:"wird in L18 und L22 erweitert, Grundlage für L36"},{n:"DB PlantData",a:"erweitert",h:"Sollzeiten dipTime, dripTime; Auto-Befehle jetzt von Tinning geschrieben"},{n:"FB CommandOutput",a:"übernommen",h:"bekommt die Auto-Befehle von Tinning"},{n:"Skizze Programmstruktur",a:"erweitert",h:"mit Tinning"}],
 plus:"Setze dieselbe Kette in S7-GRAPH um (eigener FB, nicht aufgerufen, oder an Stelle von <code>Tinning</code>) und vergleiche: Wie zeigt GRAPH den aktiven Schritt und eine wartende Transition im Programmstatus, und wo würdest du dort Verriegelungen eintragen?",
 tpls:[
 {id:"unterbrechung", cap:"Festlegung: Unterbrechung der Kette mitten im Zyklus", phase:4, head:["Ereignis mitten im Zyklus","Was tut die Kette?","Wie wird sie zurückgesetzt?","Wie geht es danach weiter?"], muster:["Beispiel: CPU STOP und wieder RUN","Schrittnummer bekommt ihren Startwert, die Kette steht im Initialschritt","von selbst beim Anlauf (nicht remanent)","erst nach Grundstellung und START"], rows:[["Wechsel nach HAND in Schritt 6"],["Not-Halt in Schritt 4, danach quittiert"],["Not-Halt in Schritt 6, danach quittiert"],["zurück auf AUTO nach einem Eingriff in HAND"]], inputs:3},
 {id:"plantdata", erweitert:"L05:plantdata", cap:"Variablenliste PlantData", phase:4, head:["Inhalt","ab Übung","Variablenname","Datentyp","remanent (ja oder nein, warum)","schreibt (Baustein, über den OB1)","liest"], muster:["Betriebsbereitschaft","L05","ready","Bool","nein, nach dem Neustart muss neu gestartet werden","Operation (Output ready)","Indication"], rows:[["Sollwert Tauchzeit","L17"],["Sollwert Abtropfzeit","L17"]], inputs:5}
]
,
 bezug:[
 {von:"L16", id:"querverweis", phase:5, wozu:"Vergleiche die Querverweisliste mit deinem Stand nach L16: Die Ventile schreibt weiter nur CommandOutput."}
]
}
