// Stammdaten der Übung L20 (Felder siehe uebungVorlage.md). Langtexte in texte.json, Kurz-Checks in quiz.js.
{id:"L20", st:2, t:"Band 1 mit Vor-Ort-Steuerstelle", sub:"Wendeschütz, Selbsthaltung, Motorschutz", ue:3, vor:"L16", repo:"6", bild:null,
 typ:"programmieren",
 einst:"Übungsumfang: <i>Verzinnen: Portal −MM1…−MM4</i> = <i>SPS steuert</i>, <i>Band, Anschlag, Vereinzeler</i> = <i>SPS steuert</i>, Antrieb Band 1 −MA1 = <i>Schütz −QA1/−QA2</i>, <i>Zinnbad: Temperatur und Füllstand</i> = <i>Regler automatisch</i>, <i>Kühlwassertank: Nachspeisung</i> = <i>Niveauregler automatisch</i>; −SA3 auf HAND, kein START. Dein Programm schaltet −QA1, −QA2 und −PF6. Portal, Rollenkurve, Band 2 und Prüfstation stehen, weil dein Programm sie in dieser Übung nicht fährt.",
 ziele:["eine Wendeschützsteuerung mit Selbsthaltung und gegenseitiger Verriegelung aus dem Stromlaufplan in KOP umsetzen","den Motorschutz auswerten und melden","Steuerstellen per Schlüsselschalter umschalten und von Betriebsarten unterscheiden"],
 sig:"SA2 SF5 SF6 SF7 SF8 KF2 FA1 QA1 QA2 PF6",
 sit:"Für Reinigung und Wartung soll Band 1 direkt an der Vor-Ort-Steuerstelle −S10 gefahren werden, in beide Richtungen.",
 plan:["Zeichne den Stromlaufplan der Wendeschützschaltung in konventioneller Schütztechnik: Hauptstromkreis und Steuerstromkreis mit Selbsthaltung und Schützverriegelung (Richtungswechsel nur über Halt), Halt −SF7 und Motorschutz −FA1. Begründe, warum du hier keine Tasterverriegelung einsetzt. Lasse ihn freigeben."],
 auf:["Lege einen FB <code>ConveyorLocal</code> in KOP mit Bausteinkopf an und rufe ihn im OB1 vor <code>CommandOutput</code> auf. Übertrage deinen Stromlaufplan Strompfad für Strompfad und trage zu jedem Bauteil das KOP-Element in die Vorlage „Gegenüberstellung Stromlaufplan und KOP“ ein.","Programmiere den Schlüsselschalter: −SA2 = 1: Die Vor-Ort-Steuerstelle hat Vorrang, −PF6 leuchtet. −SA2 = 0: −SF5 und −SF6 sind wirkungslos. Lege in der Vorlage „Festlegungen Band 1 vor Ort“ fest und begründe, ob ein laufendes Band beim Abziehen des Schlüssels stehen bleibt.","Programmiere Rechts und Links mit Selbsthaltung in statischen Variablen. Halt −SF7 (Öffner), ausgelöster Motorschutz −FA1 oder −KF2 = 0 löschen beide; danach läuft das Band erst nach einem neuen Tastendruck.","Programmiere die gegenseitige Verriegelung: Die Richtung wechselt nur über Halt.","Gib <code>localRight</code> und <code>localLeft</code> über <code>PlantData</code> an <code>CommandOutput</code> und schreibe dort −QA1 und −QA2 in je einer Zeile, so wie die Ventile in L16. Ergänze die Vorlagen „Ausgangsliste“ und „Variablenliste PlantData“.","Melde einen ausgelösten Motorschutz: −PF6 blinkt mit 1 Hz (dein FB <code>Clock</code> als Multiinstanz), solange −FA1 = 0 ist."],
 hilfe:{0:["Welche Kontakte liegen im Strompfad von −QA1 in Reihe, welcher parallel zum Taster Rechts?","Ein Strompfad wird ein Netzwerk. Reihenschaltung heißt Kontakte hintereinander, Parallelschaltung ein Zweig. Der Hilfsschließer von −QA1 wird zur statischen Variablen <code>#statRight</code>, der Öffner von −QA2 zur Abfrage „<code>#statLeft</code> ist 0“.","Netzwerk Rechts in KOP: Schließer Taster Rechts parallel zu Schließer <code>#statRight</code>; dahinter in Reihe Schließer Halt (Öffner im Feld, hier Schließer, weil du den Signalzustand abfragst), Schließer Motorschutz, Schließer −KF2, Schließer Schlüssel −SA2, Öffnerkontakt <code>#statLeft</code>; am Ende die Spule <code>#statRight</code>. Netzwerk Links entsprechend. Ein weiteres Netzwerk gibt <code>#statRight</code> an den Ausgang <code>localRight</code>."]},
 lf:[["Die Schütze sind mechanisch verriegelt. Warum programmierst du trotzdem eine Verriegelung?",[0]],["Warum wird −SF7 als Öffner verdrahtet, warum steht im KOP dafür trotzdem ein Schließerkontakt, und was passiert bei Drahtbruch?",[0]],["Warum ist −SA2 eine Steuerstelle und keine Betriebsart?",[2]]],
 pr:[["Rechts drücken und loslassen → Band läuft weiter",[0]],["Links während Rechtslauf → keine Reaktion",[0]],["−SF5 im Signalmonitor auf 1 forcen, −SF6 drücken → nur eine Richtung, −QA1 und −QA2 nie gleichzeitig 1",[0]],["−FA1 im Signalmonitor auf 0 forcen (simuliert nur den Hilfskontakt) → dein Programm schaltet −QA1 ab, Band steht, −PF6 blinkt",[1]],["Nach Halt, Motorschutz oder Not-Halt läuft das Band erst nach neuem Tastendruck",[0,1]],["−SA2 = 0 → Vor-Ort-Befehle wirkungslos, −PF6 aus",[2]],["Querverweisliste: −QA1 und −QA2 haben je eine Schreibstelle beim Aufruf von CommandOutput",[0]]],
 ergebnis:[{n:"FB ConveyorLocal",a:"neu",h:"Vor-Ort-Steuerstelle −S10 in KOP, liefert localRight, localLeft, localActive; schreibt −PF6"},{n:"FB CommandOutput",a:"erweitert",h:"Zeilen für −QA1 und −QA2; in L21 kommt die Automatik dazu"},{n:"Stromlaufplan Wendeschütz",a:"neu",h:"mit Gegenüberstellung Bauteil → KOP-Element"}, {n:"globaler DB PlantData", a:"erweitert", h:"neue Einträge in der Variablenliste PlantData: Vor-Ort-Befehl Rechts, Vor-Ort-Befehl Links"}, {n:"Ausgangsliste", a:"erweitert", h:"neue Zeilen: −QA1, −QA2, −PF6"}],
 plus:"Zähle in <code>ConveyorLocal</code>, wie oft das Band vor Ort gestartet wurde, und miss die gesamte Laufzeit in Sekunden. Lege beide Werte remanent in <code>PlantData</code> ab (wie die Zähler in L05) und prüfe mit STOP und RUN, dass sie erhalten bleiben.",
 tpls:[
 {id:"kop", cap:"Gegenüberstellung Stromlaufplan und KOP", phase:4, head:["Bauteil im Stromlaufplan","Kontakt im Stromlaufplan","Element im KOP","Operand im KOP","Begründung"], muster:["−SF5 Rechts","Schließer","Schließerkontakt","Input des FB, im OB1 an SF5_Band_Rechts","Der Taster liefert beim Drücken 1"], rows:[["−SF6 Links","Schließer"],["−SF7 Halt","Öffner"],["−FA1 Hilfskontakt","Öffner (1 = in Ordnung)"],["Selbsthaltung Rechtslauf","Schließer von −QA1"],["Selbsthaltung Linkslauf","Schließer von −QA2"],["Verriegelung im Pfad Rechts","Öffner von −QA2"],["Verriegelung im Pfad Links","Öffner von −QA1"],["Spule Rechtslauf","Spule −QA1"],["Spule Linkslauf","Spule −QA2"]], inputs:3},
 {id:"entscheid", cap:"Festlegungen Band 1 vor Ort", phase:4, head:["Fall","Reaktion des Bandes","Begründung"], muster:["Beispiel: Not-Halt (−KF2 = 0)","beide Richtungen gelöscht, Band steht, Anlauf nur mit neuem Tastendruck","So verlangt es das Soll-Verhalten"], rows:[["Schlüssel −SA2 wird bei laufendem Band abgezogen"],["−FA1 fällt während der Fahrt"],["Drahtbruch an −SF7 (auf 0 geforct)"],["Rechts läuft, Links wird gedrückt"],["−FA1 ausgelöst, Schlüssel −SA2 abgezogen: Was zeigt −PF6?"]], inputs:2},
 {id:"schreib", erweitert:"L02:schreib", cap:"Ausgangsliste", phase:4, head:["Ausgang","Bedeutung","ab Übung","schreibt (Baustein, einzige Stelle)","Bedingung oder Befehl kommt von","in der Querverweisliste geprüft"], muster:["−PF2","Bad bereit","L02","FB Indication (bis L03 FC), Aufruf im OB1","−BG9 UND −BG10, ODER Lampentest −SF4","ja, eine Schreibstelle"], rows:[["−QA1","Band 1 Rechtslauf","L20"],["−QA2","Band 1 Linkslauf","L20"],["−PF6","Vor-Ort-Steuerstelle −S10 aktiv","L20"]], inputs:3},
 {id:"plantdata", erweitert:"L05:plantdata", cap:"Variablenliste PlantData", phase:4, head:["Inhalt","ab Übung","Variablenname","Datentyp","remanent (ja oder nein, warum)","schreibt (Baustein, über den OB1)","liest"], muster:["Betriebsbereitschaft","L05","ready","Bool","nein, nach dem Neustart muss neu gestartet werden","Operation (Output ready)","Indication"], rows:[["Vor-Ort-Befehl Rechts","L20"],["Vor-Ort-Befehl Links","L20"]], inputs:5}
]
}
