// Stammdaten der Übung L22 (Felder siehe uebungVorlage.md). Langtexte in texte.json, Kurz-Checks in quiz.js.
{id:"L22", st:2, t:"Überwachungszeiten auslegen", sub:"Messen, begründen, Störungen melden", ue:4, vor:"L18", repo:"13, 14", bild:["09-weg-zeit-diagramm.jpg","Weg-Zeit-Diagramm mit Messlinien und Drosseln"],
 typ:"auslegen",
 einst:"Übungsumfang wie in L17: <i>Verzinnen: Portal −MM1…−MM4</i> = <i>SPS steuert</i>, <i>Band, Anschlag, Vereinzeler</i> = <i>Bandmodul automatisch</i>, <i>Zinnbad: Temperatur und Füllstand</i> = <i>Regler automatisch</i>, <i>Kühlwassertank: Nachspeisung</i> = <i>Niveauregler automatisch</i>. Dein Programm fährt das Portal, das Bandmodul bringt die Körbe und öffnet den Anschlag. <i>Geschwindigkeit aller Zylinder</i> unter <i>Prozess</i> = 100 %.",
 ziele:["Fahrzeiten messen und Überwachungszeiten begründet ableiten","Störungen mit Zylinder und Richtung melden und nach dem Quittieren im selben Schritt weiterlaufen","Warten und Störung unterscheiden"],
 sig:"BG1 BG2 BG3 BG4 BG5 BG6 BG7 BG8 SF4",
 sit:"Ein Zylinder klemmt, und die Anlage steht ohne Meldung. Künftig soll jede Bewegung überwacht werden, mit Zeiten, die zur Anlage passen.",
 plan:["Markiere in deinem GRAFCET aus L17, welche Schritte eine Bewegung befehlen und überwacht werden und welche nur warten (Initialschritt, Tauchzeit, Abtropfzeit).","Lege in der Vorlage „Meldetexte der Laufzeitüberwachung“ den Text jeder Meldung fest: Zylinder, Richtung, fehlende Endlage."],
 auf:["Miss im Weg-Zeit-Diagramm (Karte in L17, „Groß öffnen“, Messlinien) die Fahrzeit jedes Zylinders in beiden Richtungen bei Drossel 50 %, über mehrere Zyklen. Trage je Bewegung den größten Wert und die Drosselstellung in die Vorlage „Fahrzeiten und Überwachungszeiten“ ein.","Lege die Überwachungszeiten fest: Fahrzeit × Faktor (Vorschlag 1,5 bis 2), bei kurzen Bewegungen mit festem Zuschlag. Begründe Faktor und Zuschlag je Bewegung in der Vorlage „Fahrzeiten und Überwachungszeiten“.","Ergänze jeden Bewegungsschritt um eine Laufzeitüberwachung (<code>TON</code>-Multiinstanz, Zeit als <code>Time</code>-Variable aus <code>PlantData</code>). Bei Ablauf hält die Kette im Schritt. Schreibe dann den passenden Meldetext aus deiner Vorlage „Meldetexte der Laufzeitüberwachung“, z. B. „−MM2 senken: Endlage −BG4 nicht erreicht“, in eine Textvariable vom Typ <code>WString</code> (Karte in L19) und zeige sie in einer Beobachtungstabelle an. Trage die Überwachungszeiten in die Vorlage „Variablenliste PlantData“ ein.","Programmiere das Quittieren mit einer Flanke an −SF4: Ist die Ursache behoben, läuft die Kette im selben Schritt weiter, die Überwachungszeit beginnt neu.","Prüfe, dass Warteschritte keine Überwachung haben: In Schritt 6 und 7 überwachst du nur die Bewegung bis −BG4 bzw. −BG3, nicht die Tauch- oder Abtropfzeit.","Teste die Überwachung: Stelle jede der 8 Drosseln von −MM1 bis −MM4 einzeln auf 0 % und force −BG7 im Signalmonitor auf 0. Stelle danach alle Drosseln auf 50 % und fahre mehrere Zyklen ohne Fehlmeldung."],
 hilfe:{2:["Wann soll die Zeit laufen, und wann nicht? Was passiert mit dem TON, wenn der Schritt wechselt?","Ein <code>TON</code> je Bewegungsschritt: IN = Schritt aktiv UND Endlage noch nicht erreicht, PT = Überwachungszeit. Bei Q setzt du eine statische Störung dieses Schritts; die Transition schaltet nur ohne Störung weiter. Rufe den TON in jedem Zyklus auf, nicht innerhalb des CASE-Zweigs.","<pre class=\"code\"><code>#instSupLower(IN := (#statStep = 6) AND NOT #mm2Down,\n              PT := #supTimeLower);\nIF #instSupLower.Q THEN\n  #statFaultLower := TRUE;   // Meldung: MM2 senken, BG4 fehlt\nEND_IF;\n// im CASE, Schritt 6:\n//   IF #mm2Down AND NOT #statFaultLower AND #instTimerDip.Q THEN ...</code></pre>"],3:["Woran merkt die Kette, dass die Ursache behoben ist, und was passiert mit dem abgelaufenen TON?","Quittieren löscht die Störung. Damit die Zeit neu beginnt, muss der TON einmal mit IN = 0 aufgerufen werden, z. B. indem die Störung selbst in die IN-Bedingung eingeht.","<pre class=\"code\"><code>#instAckEdge(CLK := #ackButton);   // R_TRIG an SF4\nIF #instAckEdge.Q THEN\n  #statFaultLower := FALSE;\nEND_IF;\n#instSupLower(IN := (#statStep = 6) AND NOT #mm2Down\n                    AND NOT #statFaultLower,\n              PT := #supTimeLower);</code></pre>Solange die Störung ansteht, ist IN = 0, und der TON setzt sich zurück. Nach dem Quittieren läuft er von vorn."]},
 lf:[["Was unterscheidet „Schritt wartet auf Bedingung“ von „Störung“?",[2]],["Welche Folgen hat eine zu kurze, welche eine zu lange Überwachungszeit?",[0]],["Warum reicht bei einer sehr kurzen Bewegung wie −MM1 der Faktor allein nicht?",[0]]],
 pr:[["Fahrzeitentabelle für 4 Zylinder × 2 Richtungen vollständig, Faktor je Bewegung begründet",[0]],["Jede der 8 Drosseln von −MM1 bis −MM4 einzeln auf 0 % → richtige Meldung mit Zylinder und Richtung",[1]],["−BG7 im Signalmonitor auf 0 forcen → Meldung mit −MM4 öffnen und fehlender Endlage −BG7",[1]],["Nach Beheben und Quittieren mit −SF4 läuft die Kette im selben Schritt weiter",[1]],["Initialschritt 5 min ohne START und Tauchzeit 30 s → keine Laufzeitstörung",[2]],["Alle Drosseln 50 %, mehrere Zyklen → keine Fehlmeldung",[0]]],
 ergebnis:[{n:"FB Tinning",a:"erweitert",h:"Laufzeitüberwachung je Bewegungsschritt, Meldungen, Quittieren"},{n:"Fahrzeitentabelle",a:"neu",h:"Ausgangswert für die Taktzeitoptimierung in L36"},{n:"DB PlantData",a:"erweitert",h:"Überwachungszeiten als Time-Variablen"}],
 plus:"Verschleiß früh erkennen: Miss in der Kette mit <code>ET</code> laufend die Fahrzeit jeder Bewegung und gib eine Warnung (keine Störung) aus, sobald sie 80 % der Überwachungszeit erreicht. Wer ein eigenes HMI-Projekt hat, kann die Meldungen zusätzlich mit <code>Program_Alarm</code> im HMI-Meldefenster mit Zeitstempel anzeigen.",
 tpls:[
 {id:"fahrzeiten", cap:"Fahrzeiten und Überwachungszeiten", phase:4, head:["Zylinder","Richtung","Fahrzeit (s), größter Wert","Faktor","Überwachungszeit (s)","Zuschlag (s)","Begründung","Drossel (%)"], muster:["Beispiel","ausfahren","1,6 (größter Wert aus mehreren Messungen)","1,5","2,4","0","lange Bewegung, kleine Streuung, Faktor 1,5 reicht","50"], rows:[["−MM1","einhängen"],["−MM1","lösen"],["−MM2","senken"],["−MM2","anheben"],["−MM3","zum Bad"],["−MM3","zum Band"],["−MM4","abdecken"],["−MM4","öffnen"]], inputs:6},
 {id:"meldungen", cap:"Meldetexte der Laufzeitüberwachung", phase:2, head:["Bewegung","fehlende Endlage","Meldetext"], muster:["−MM2 senken","−BG4","−MM2 senken: Endlage −BG4 nicht erreicht"], rows:[["−MM1 einhängen","−BG1"],["−MM1 lösen","−BG2"],["−MM2 senken","−BG4"],["−MM2 anheben","−BG3"],["−MM3 zum Bad","−BG6"],["−MM3 zum Band","−BG5"],["−MM4 abdecken","−BG8"],["−MM4 öffnen","−BG7"]], inputs:1},
 {id:"plantdata", erweitert:"L05:plantdata", cap:"Variablenliste PlantData", phase:4, head:["Inhalt","ab Übung","Variablenname","Datentyp","remanent (ja oder nein, warum)","schreibt (Baustein, über den OB1)","liest"], muster:["Betriebsbereitschaft","L05","ready","Bool","nein, nach dem Neustart muss neu gestartet werden","Operation (Output ready)","Indication"], rows:[["Überwachungszeiten der 8 Bewegungen","L22"]], inputs:5}
]
}
