
// ----------------------------------------------------------------------------
// Signale (Standard = signale.csv; wird beim Verbinden von der Bridge ersetzt)
// ----------------------------------------------------------------------------
export const SIGNALE = [
  ['MB1_Einhaengen', '%Q0.0', 'ausgang', '−MM1 Korb einhängen'],
  ['MB2_Loesen', '%Q0.1', 'ausgang', '−MM1 Korb lösen'],
  ['MB3_Senken', '%Q0.2', 'ausgang', '−MM2 senken'],
  ['MB4_Anheben', '%Q0.3', 'ausgang', '−MM2 anheben'],
  ['MB5_Zinnbad', '%Q0.4', 'ausgang', '−MM3 zum Zinnbad'],
  ['MB6_Foerderband', '%Q0.5', 'ausgang', '−MM3 zum Förderband'],
  ['MB7_Schliessen', '%Q0.6', 'ausgang', '−MM4 Bad abdecken'],
  ['MB8_Oeffnen', '%Q0.7', 'ausgang', '−MM4 Bad öffnen'],
  ['PF1_Automatik', '%Q1.0', 'ausgang', 'Leuchte Automatik EIN'],
  ['PF2_Temperatur', '%Q1.1', 'ausgang', 'Leuchte Betriebstemperatur'],
  ['PF3_Fuellhoehe', '%Q1.2', 'ausgang', 'Leuchte Füllhöhe unterschritten'],
  ['PF4_Korb', '%Q1.3', 'ausgang', 'Leuchte Materialkorb vorhanden'],
  ['PF5_Quittieren', '%Q1.4', 'ausgang', 'Leuchttaster Quittieren'],
  ['PF6_VorOrt', '%Q1.5', 'ausgang', 'Leuchte Vor-Ort-Steuerstelle aktiv'],
  ['PF7_Handbetrieb', '%Q1.6', 'ausgang', 'Leuchte Handbetrieb aktiv (Schaltschranktür)'],
  ['QA1_Band_Rechts', '%Q2.0', 'ausgang', 'Schütz Bandmotor Rechtslauf (Förderrichtung)'],
  ['QA2_Band_Links', '%Q2.1', 'ausgang', 'Schütz Bandmotor Linkslauf'],
  ['MB9_Anschlag_auf', '%Q2.2', 'ausgang', 'Anschlag Übergabeplatz öffnen (Feder schließt)'],
  ['MB10_Vereinzeler_zu', '%Q2.3', 'ausgang', 'Vereinzeler sperren (Feder öffnet)'],
  ['TB1_Heizung', '%Q2.4', 'ausgang', 'Heizung Zinnbad (Halbleiterrelais)'],
  ['MB11_Nachfuellen', '%Q2.5', 'ausgang', 'Zinn-Nachfülleinrichtung öffnen'],
  ['QA5_B2_Rechts', '%Q2.6', 'ausgang', 'Schütz Band 2 Rechtslauf (Förderrichtung)'],
  ['QA6_B2_Links', '%Q2.7', 'ausgang', 'Schütz Band 2 Linkslauf'],
  ['QA10_Kurve_Rechts', '%Q3.0', 'ausgang', 'Schütz Rollenkurve −MA6 Rechtslauf (Förderrichtung)'],
  ['QA11_Kurve_Links', '%Q4.2', 'ausgang', 'Schütz Rollenkurve −MA6 Linkslauf'],
  ['PF9_VorOrt3', '%Q4.3', 'ausgang', 'Leuchte Vor-Ort-Steuerstelle Rollenkurve aktiv'],
  ['QA12_Mulde_Vor', '%Q4.4', 'ausgang', 'Schütz Muldenrollen −MA7 vorwärts (zum Endanschlag)'],
  ['QA13_Mulde_Zurueck', '%Q4.5', 'ausgang', 'Schütz Muldenrollen −MA7 zurück'],
  ['PF11_VorOrt4', '%Q4.6', 'ausgang', 'Leuchte Vor-Ort-Steuerstelle Prüfstation −S40 aktiv'],
  ['PF12_Quitt_S10', '%Q4.7', 'ausgang', 'Leuchttaster Quittieren −SF41 an −S10 (blinkt: quittieren)'],
  ['PF13_Quitt_S20', '%Q5.0', 'ausgang', 'Leuchttaster Quittieren −SF42 an −S20 (blinkt: quittieren)'],
  ['PF14_Quitt_S30', '%Q5.1', 'ausgang', 'Leuchttaster Quittieren −SF43 an −S30 (blinkt: quittieren)'],
  ['PF15_Quitt_S40', '%Q5.2', 'ausgang', 'Leuchttaster Quittieren −SF44 an −S40 (blinkt: quittieren)'],
  ['QA7_Pumpe', '%Q3.1', 'ausgang', 'Umwälzpumpe Sprühkühlung −MA3'],
  ['MB13_Spruehwasser', '%Q3.4', 'ausgang', 'Sprühventil Abschrecken (nur mit laufender Pumpe)'],
  ['MB14_Luftmesser', '%Q3.5', 'ausgang', 'Luftmesser abblasen am Tunnelauslauf'],
  ['MB15_Kippen', '%Q3.6', 'ausgang', '−MM8 Korbkipper kippen (5/2 monostabil)'],
  ['QA8_Vibro', '%Q3.7', 'ausgang', 'Vibrorinne −MA4'],
  ['QA9_Pruefband', '%Q4.0', 'ausgang', 'Prüfband −MA5'],
  ['MB16_Ausblasen', '%Q4.1', 'ausgang', 'Ausblasdüse n.i.O.-Teile'],
  ['KF10_Kamera_Trigger', '%Q3.2', 'ausgang', 'Kamera Prüfplatz auslösen'],
  ['PF8_VorOrt2', '%Q3.3', 'ausgang', 'Leuchte Vor-Ort-Steuerstelle Band 2 aktiv'],
  ['BG1_MM1_eingehaengt', '%I0.0', 'eingang', '−MM1 eingehängt'],
  ['BG2_MM1_geloest', '%I0.1', 'eingang', '−MM1 gelöst'],
  ['BG3_MM2_oben', '%I0.2', 'eingang', '−MM2 oben'],
  ['BG4_MM2_unten', '%I0.3', 'eingang', '−MM2 unten'],
  ['BG5_MM3_Band', '%I0.4', 'eingang', '−MM3 über Band'],
  ['BG6_MM3_Bad', '%I0.5', 'eingang', '−MM3 über Zinnbad'],
  ['BG7_MM4_offen', '%I0.6', 'eingang', '−MM4 Bad offen'],
  ['BG8_MM4_zu', '%I0.7', 'eingang', '−MM4 Bad abgedeckt'],
  ['BG9_Temperatur', '%I1.0', 'eingang', 'Betriebstemperatur erreicht'],
  ['BG10_Fuellhoehe', '%I1.1', 'eingang', 'Füllhöhe ausreichend'],
  ['BG11_Korb', '%I1.2', 'eingang', 'Lichtschranke Einlauf Übergabeplatz (Korb kommt)'],
  ['SF1_Start', '%I1.3', 'eingang', 'Taster START'],
  ['SF2_Stop', '%I1.4', 'eingang', 'Taster STOP (Öffner)'],
  ['SA3_Handbetrieb', '%I1.5', 'eingang', 'Wahlschalter Schaltschranktür 1 = Hand, 0 = Auto'],
  ['KF2_NotHalt_OK', '%I1.6', 'eingang', 'Sicherheitsrelais Freigabe (1 = kein Not-Halt)'],
  ['SF4_Quittieren', '%I1.7', 'eingang', 'Taster Quittieren Bedienpult'],
  ['SA1_Dauerbetrieb', '%I2.0', 'eingang', 'Wahlschalter 1 = Automatik (Dauer), 0 = Einzelzyklus'],
  ['SA2_VorOrt', '%I2.1', 'eingang', 'Schlüsselschalter Vor-Ort-Steuerstelle'],
  ['SF5_Band_Rechts', '%I2.2', 'eingang', 'Vor-Ort Taster Rechtslauf'],
  ['SF6_Band_Links', '%I2.3', 'eingang', 'Vor-Ort Taster Linkslauf'],
  ['SF7_Band_Halt', '%I2.4', 'eingang', 'Vor-Ort Taster Halt (Öffner)'],
  ['BG12_Bandanfang', '%I2.5', 'eingang', 'Lichtschranke Bandanfang'],
  ['BG13_Bandende', '%I2.6', 'eingang', 'Lichtschranke Ende Band 1 (Übergabe an die Rollenkurve)'],
  ['BG40_Korb_am_Anschlag', '%I8.0', 'eingang', 'Korb liegt am Anschlag −MM5 an (Anschlagleiste eingedrückt)'],
  ['FA1_Motorschutz', '%I2.7', 'eingang', 'Motorschutzschalter Band ausgelöst = 0'],
  ['SF11_MM1_Einhaengen', '%I3.0', 'eingang', 'Handtaster −MM1 einhängen'],
  ['SF12_MM1_Loesen', '%I3.1', 'eingang', 'Handtaster −MM1 lösen'],
  ['SF13_MM2_Senken', '%I3.2', 'eingang', 'Handtaster −MM2 senken'],
  ['SF14_MM2_Anheben', '%I3.3', 'eingang', 'Handtaster −MM2 anheben'],
  ['SF15_MM3_Zinnbad', '%I3.4', 'eingang', 'Handtaster −MM3 zum Bad'],
  ['SF16_MM3_Band', '%I3.5', 'eingang', 'Handtaster −MM3 zum Band'],
  ['SF17_MM4_Schliessen', '%I3.6', 'eingang', 'Handtaster −MM4 Bad zu'],
  ['SF18_MM4_Oeffnen', '%I3.7', 'eingang', 'Handtaster −MM4 Bad auf'],
  ['BG14_MM5_zu', '%I4.0', 'eingang', '−MM5 Anschlag geschlossen (Korb wird gehalten)'],
  ['BG15_MM5_offen', '%I4.1', 'eingang', '−MM5 Anschlag offen'],
  ['BG16_MM6_zu', '%I4.2', 'eingang', '−MM6 Vereinzeler geschlossen (sperrt)'],
  ['BG17_MM6_offen', '%I4.3', 'eingang', '−MM6 Vereinzeler offen'],
  ['BG18_Geber_A', '%I4.4', 'eingang', 'Inkrementalgeber Band Spur A (10 Imp/U)'],
  ['BG18_Geber_B', '%I4.5', 'eingang', 'Inkrementalgeber Band Spur B (90° versetzt)'],
  ['BG18_Geber_N', '%I4.6', 'eingang', 'Inkrementalgeber Band Nullimpuls (1 je Umdrehung)'],
  ['SF19_MM5_Oeffnen', '%I5.0', 'eingang', 'Handtaster −MM5 Anschlag öffnen'],
  ['SF20_MM5_Schliessen', '%I5.1', 'eingang', 'Handtaster −MM5 Anschlag schließen'],
  ['SF21_MM6_Schliessen', '%I5.2', 'eingang', 'Handtaster −MM6 Vereinzeler schließen'],
  ['SF22_MM6_Oeffnen', '%I5.3', 'eingang', 'Handtaster −MM6 Vereinzeler öffnen'],
  ['SF28_MM8_Kippen', '%I8.2', 'eingang', 'Handtaster −MM8 Kipper kippen'],
  ['SF29_MM8_Zurueck', '%I8.3', 'eingang', 'Handtaster −MM8 Kipper zurück'],
  ['BG20_Lichtvorhang_frei', '%I4.7', 'eingang', 'Sicherheitslichtvorhang Schutzfeld frei'],
  ['BG21_B2_Anfang', '%I5.4', 'eingang', 'Lichtschranke Band 2 Anfang (Korb übernommen)'],
  ['BG22_B2_Kuehlung', '%I5.5', 'eingang', 'Lichtschranke Kühlplatz'],
  ['BG32_Teil_Pruefplatz', '%I5.6', 'eingang', 'Lichtschranke Teil am Kameraplatz (Prüfband)'],
  ['BG24_B2_Ende', '%I5.7', 'eingang', 'Lichtschranke Band 2 Ende (Übergabe zur Kippmulde)'],
  ['BG35_Kurve_Anfang', '%I6.0', 'eingang', 'Lichtschranke Rollenkurve Anfang'],
  ['BG36_Kurve_Ende', '%I6.1', 'eingang', 'Lichtschranke Rollenkurve Ende'],
  ['BG27_Geber2_A', '%I6.2', 'eingang', 'Inkrementalgeber Band 2 Spur A'],
  ['BG27_Geber2_B', '%I6.3', 'eingang', 'Inkrementalgeber Band 2 Spur B'],
  ['BG27_Geber2_N', '%I6.4', 'eingang', 'Inkrementalgeber Band 2 Nullimpuls'],
  ['BG28_Pruefung_iO', '%I6.5', 'eingang', 'Kamera: Korb i.O.'],
  ['BG29_Pruefung_niO', '%I6.6', 'eingang', 'Kamera: Korb n.i.O.'],
  ['SA4_VorOrt2', '%I6.7', 'eingang', 'Schlüsselschalter Vor-Ort-Steuerstelle Band 2'],
  ['SF23_B2_Rechts', '%I7.0', 'eingang', 'Vor-Ort Band 2 Rechtslauf'],
  ['SF24_B2_Links', '%I7.1', 'eingang', 'Vor-Ort Band 2 Linkslauf'],
  ['SF25_B2_Halt', '%I7.2', 'eingang', 'Vor-Ort Band 2 Halt (Öffner)'],
  ['FA5_Motorschutz2', '%I7.3', 'eingang', 'Motorschutz Band 2 (1 = OK)'],
  ['BG30_MM8_unten', '%I7.4', 'eingang', '−MM8 Kipper unten (Grundstellung)'],
  ['BG31_MM8_gekippt', '%I7.5', 'eingang', '−MM8 Kipper gekippt'],
  ['BG33_Kipper_Korb', '%I7.6', 'eingang', 'Korb am Endanschlag der Kippmulde'],
  ['BG34_KLT_voll', '%I7.7', 'eingang', 'KLT i.O.-Teile voll'],
  ['BG37_Kipper_Einlauf', '%I11.7', 'eingang', 'Lichtschranke Einlauf Kippmulde (Korb in der Mulde)'],
  ['SA5_VorOrt3', '%I8.4', 'eingang', 'Schlüsselschalter Vor-Ort-Steuerstelle Rollenkurve'],
  ['SF30_Kurve_Rechts', '%I8.5', 'eingang', 'Vor-Ort Rollenkurve Rechtslauf'],
  ['SF31_Kurve_Links', '%I8.6', 'eingang', 'Vor-Ort Rollenkurve Linkslauf'],
  ['SF32_Kurve_Halt', '%I8.7', 'eingang', 'Vor-Ort Rollenkurve Halt (Öffner)'],
  ['FA7_Motorschutz3', '%I9.0', 'eingang', 'Motorschutz Rollenkurve (1 = OK)'],
  ['SF0_NotHalt_frei', '%I9.1', 'eingang', 'Not-Halt −SF0 Bedienpult Meldekontakt (Öffner: 1 = entriegelt)'],
  ['SF8_NotHalt_frei', '%I9.2', 'eingang', 'Not-Halt −SF8 Vor-Ort −S10 Meldekontakt (Öffner: 1 = entriegelt)'],
  ['SF9_NotHalt_frei', '%I9.3', 'eingang', 'Not-Halt −SF9 Vor-Ort −S20 Meldekontakt (Öffner: 1 = entriegelt)'],
  ['SF10_NotHalt_frei', '%I9.4', 'eingang', 'Not-Halt −SF10 Vor-Ort −S30 Meldekontakt (Öffner: 1 = entriegelt)'],
  ['SF33_NotHalt_frei', '%I9.5', 'eingang', 'Not-Halt −SF33 Vor-Ort −S40 Meldekontakt (Öffner: 1 = entriegelt)'],
  ['SA6_VorOrt4', '%I9.6', 'eingang', 'Schlüsselschalter Vor-Ort-Steuerstelle Prüfstation −S40'],
  ['SF34_Pruef_Ein', '%I9.7', 'eingang', 'Vor-Ort −S40 Vibrorinne + Prüfband EIN'],
  ['SF35_Pruef_Halt', '%I10.0', 'eingang', 'Vor-Ort −S40 Vibrorinne + Prüfband AUS (Öffner)'],
  ['SF36_Mulde_Vor', '%I10.1', 'eingang', 'Vor-Ort −S40 Muldenrollen vorwärts tippen'],
  ['SF37_Mulde_Zurueck', '%I10.2', 'eingang', 'Vor-Ort −S40 Muldenrollen zurück tippen'],
  ['SF38_Kipper_Kippen', '%I10.3', 'eingang', 'Vor-Ort −S40 Kipper kippen'],
  ['SF39_Kipper_Zurueck', '%I10.4', 'eingang', 'Vor-Ort −S40 Kipper zurück'],
  ['FA8_Motorschutz4', '%I10.5', 'eingang', 'Motorschutz Muldenantrieb −MA7 (1 = OK)'],
  ['SF41_Quittieren_S10', '%I10.6', 'eingang', 'Taster Quittieren Vor-Ort −S10 (parallel zu −SF4 an −KF2)'],
  ['SF42_Quittieren_S20', '%I10.7', 'eingang', 'Taster Quittieren Vor-Ort −S20 (parallel zu −SF4 an −KF2)'],
  ['SF43_Quittieren_S30', '%I11.0', 'eingang', 'Taster Quittieren Vor-Ort −S30 (parallel zu −SF4 an −KF2)'],
  ['SF44_Quittieren_S40', '%I11.1', 'eingang', 'Taster Quittieren Vor-Ort −S40 (parallel zu −SF4 an −KF2)'],
  ['BT2_Korbtemperatur', '%IW68', 'eingang', 'Korbtemperatur Kühlplatz 0…27648 = 0…400 °C'],
  ['BT1_Temperatur', '%IW64', 'eingang', 'Zinntemperatur 0…27648 = 0…400 °C'],
  ['BL1_Fuellstand', '%IW66', 'eingang', 'Füllstand 0…27648 = 0…100 %'],
  ['TA2_STW1', '%QW256', 'ausgang', 'Umrichter −TA2 Steuerwort 1 (STW1)'],
  ['TA2_NSOLL_A', '%QW258', 'ausgang', 'Umrichter −TA2 Drehzahlsollwert NSOLL_A (16#4000 = 1500 1/min = 100 mm/s)'],
  ['TA2_ZSW1', '%IW256', 'eingang', 'Umrichter −TA2 Zustandswort 1 (ZSW1)'],
  ['TA2_NIST_A', '%IW258', 'eingang', 'Umrichter −TA2 Drehzahlistwert NIST_A (16#4000 = 1500 1/min = 100 mm/s)'],
  ['TA3_STW1', '%QW260', 'ausgang', 'Umrichter −TA3 Steuerwort 1 (STW1)'],
  ['TA3_NSOLL_A', '%QW262', 'ausgang', 'Umrichter −TA3 Drehzahlsollwert NSOLL_A (16#4000 = 1500 1/min = 120 mm/s)'],
  ['TA3_ZSW1', '%IW260', 'eingang', 'Umrichter −TA3 Zustandswort 1 (ZSW1)'],
  ['TA3_NIST_A', '%IW262', 'eingang', 'Umrichter −TA3 Drehzahlistwert NIST_A (16#4000 = 1500 1/min = 120 mm/s)'],
  ['TA4_STW1', '%QW264', 'ausgang', 'Umrichter −TA4 Steuerwort 1 (STW1)'],
  ['TA4_NSOLL_A', '%QW266', 'ausgang', 'Umrichter −TA4 Drehzahlsollwert NSOLL_A (16#4000 = 1500 1/min = 110 mm/s)'],
  ['TA4_ZSW1', '%IW264', 'eingang', 'Umrichter −TA4 Zustandswort 1 (ZSW1)'],
  ['TA4_NIST_A', '%IW266', 'eingang', 'Umrichter −TA4 Drehzahlistwert NIST_A (16#4000 = 1500 1/min = 110 mm/s)'],
  ['TA5_STW1', '%QW268', 'ausgang', 'Umrichter −TA5 Steuerwort 1 (STW1)'],
  ['TA5_NSOLL_A', '%QW270', 'ausgang', 'Umrichter −TA5 Drehzahlsollwert NSOLL_A (16#4000 = 1500 1/min = 150 mm/s)'],
  ['TA5_ZSW1', '%IW268', 'eingang', 'Umrichter −TA5 Zustandswort 1 (ZSW1)'],
  ['TA5_NIST_A', '%IW270', 'eingang', 'Umrichter −TA5 Drehzahlistwert NIST_A (16#4000 = 1500 1/min = 150 mm/s)'],
  ['SA7_VorOrt5', '%I11.2', 'eingang', 'Schlüsselschalter Vor-Ort-Steuerstelle Prüfband −S50'],
  ['SF45_Pruefband_Ein', '%I11.3', 'eingang', 'Vor-Ort −S50 Prüfband EIN'],
  ['SF46_Pruefband_Aus', '%I11.4', 'eingang', 'Vor-Ort −S50 Prüfband AUS (Öffner)'],
  ['SF47_Pruefband_Drehzahl', '%IW70', 'eingang', 'Vor-Ort −S50 Drehzahlpotentiometer 0…27648 = 0…100 %'],
  ['PF16_VorOrt5', '%Q5.3', 'ausgang', 'Leuchte Vor-Ort-Steuerstelle Prüfband −S50 aktiv'],
  ['MB17_Nachspeisen', '%Q5.4', 'ausgang', 'Magnetventil Frischwasser −MB17 Nachspeisen (in Reihe mit −MB18)'],
  ['MB18_Regelventil', '%QW80', 'ausgang', 'Regelventil Frischwasser −MB18 Stellwert 0…27648 = 0…100 %'],
  ['MB18_Stellung', '%IW74', 'eingang', 'Regelventil −MB18 Stellungsrückmeldung 0…27648 = 0…100 %'],
  ['BL2_Wasserstand', '%IW72', 'eingang', 'Füllstand Kühlwassertank (Radar) 0…27648 = 0…100 %'],
  ['BG38_Wasser_Min', '%I11.5', 'eingang', 'Liquiphant Kühlwassertank Minimum (1 = bedeckt, über 25 %)'],
  ['BG39_Wasser_Max_frei', '%I11.6', 'eingang', 'Liquiphant Kühlwassertank Maximum (1 = frei, unter 90 %)'],
].map(([name, adresse, richtung, kommentar]) => ({ name, adresse, richtung, kommentar }));

