// Stammdaten der Übung L18 (Felder siehe uebungVorlage.md). Langtexte in texte.json, Kurz-Checks in quiz.js.
{id:"L18", st:2, t:"Dauer- und Einzelzyklus", sub:"Zyklusende abwarten, START als Flanke", ue:3, vor:"L17", repo:"3", bild:["02-bedienpult.jpg","Wahlschalter −SA1 Dauerbetrieb / Einzelzyklus am Bedienpult"],
 typ:"programmieren",
 einst:"Übungsumfang wie in L17: <i>Verzinnen: Portal −MM1…−MM4</i> = <i>SPS steuert</i>, <i>Band, Anschlag, Vereinzeler</i> = <i>Bandmodul automatisch</i>, <i>Zinnbad: Temperatur und Füllstand</i> = <i>Regler automatisch</i>, <i>Kühlwassertank: Nachspeisung</i> = <i>Niveauregler automatisch</i>. Dein Programm fährt das Portal und schreibt −PF1, das Bandmodul bringt die Körbe und öffnet den Anschlag. Lasse <i>Körbe automatisch zuführen</i> eingeschaltet, damit der Dauerbetrieb Nachschub hat.",
 ziele:["Dauer- und Einzelzyklus im Betriebsartenteil umsetzen und als Ausgänge an die Kette weitergeben","START als Flanke auswerten","„Zyklusende abwarten“ und „kein Wiederanlauf nach Not-Halt“ umsetzen"],
 sig:"SA1 SF1 SF2 PF1 KF2 SA3 BG2",
 sit:"Die Automatik aus L17 läuft genau einen Zyklus. Der Betreiber will in AUTO zwei Ablaufarten, gewählt mit −SA1 am Bedienpult. Dauerbetrieb: Zyklus um Zyklus, bis STOP gedrückt wird; der laufende Korb wird fertig. Einzelzyklus: genau ein Zyklus je START.",
 plan:["Ergänze dein Zustandsdiagramm aus L15: Teile AUTO in die Ablaufarten Dauerbetrieb und Einzelzyklus und trage alle Übergänge mit ihren Bedingungen ein (START, STOP, −SA1, HAND, Not-Halt)."],
 auf:["Erweitere <code>ModeSelect</code> um die START-Flanke: <code>R_TRIG</code> als Multiinstanz an −SF1. Rufe den R_TRIG in jedem Zyklus auf und verknüpfe erst seinen Ausgang Q mit AUTO und −KF2. Rufst du ihn nur in AUTO auf, wertet er ein START, das vor dem Quittieren gedrückt war, danach als neue Flanke. Die gültige Flanke im Einzelzyklus gibst du als Ausgang <code>startPulse</code> aus.","Programmiere das Setzen: Lege <code>#statContinuous</code> an und setze sie mit einer gültigen START-Flanke bei −SA1 = Dauerbetrieb.","Programmiere das Rücksetzen: STOP −SF2 (Öffner), Wechsel auf Einzelzyklus, Wechsel auf HAND und Not-Halt setzen <code>#statContinuous</code> zurück, Rücksetzen hat Vorrang. Gib den Wert als Ausgang <code>continuous</code> aus. Lege <code>continuous</code> und <code>startPulse</code> im OB1 in <code>PlantData</code> ab und trage beide in die Vorlage „Variablenliste PlantData“ ein.","Formuliere die Transition 1 → 2 in <code>Tinning</code> so, dass sie Dauerbetrieb und Einzelzyklus abdeckt. Schreibe sie an deinen GRAFCET aus L17 und setze sie um.","Programmiere −PF1: Dauerlicht im Dauerbetrieb, 1-Hz-Blinken aus L15 bei fehlender Grundstellung. Lege die Rangfolge in der Vorlage „Rangfolge der Anzeigen an −PF1“ fest und baue beides in die eine Zuweisung von −PF1 in <code>ModeSelect</code> ein. Ergänze die neue Bedingung von −PF1 in der Vorlage „Ausgangsliste“."],
 hilfe:{2:["Was muss gelten, wenn Setzen und Rücksetzen im selben Zyklus anstehen?","In SCL schreibst du zuerst die Setzbedingung, danach die Rücksetzbedingung: Die zuletzt bearbeitete Zuweisung gewinnt. In FUP nimmst du ein <code>SR</code>, dort hat R1 Vorrang. Denke daran: −SF2 ist ein Öffner, gedrückt heißt 0.","<pre class=\"code\"><code>IF #tempEdgeValid AND #continuousSelected THEN\n  #statContinuous := TRUE;\nEND_IF;\nIF NOT #stopButton OR NOT #continuousSelected\n   OR NOT #statModeAuto THEN  // HAND oder Not-Halt\n  #statContinuous := FALSE;\nEND_IF;\n#continuous := #statContinuous;</code></pre><code>#statModeAuto</code> ist bei HAND und bei −KF2 = 0 ohnehin 0, deshalb deckt eine Abfrage beide Fälle ab."],3:["Was unterscheidet Dauerbetrieb und Einzelzyklus an der Transition 1 → 2? Was gilt für beide gleich?","Bilde zuerst den Teil, der immer gilt (AUTO und startbereit wie in L17). Verknüpfe ihn mit UND mit einer ODER-Verknüpfung der beiden Startquellen.","AUTO UND startbereit UND (Dauerbetrieb ODER START-Flanke im Einzelzyklus), in SCL:<pre class=\"code\"><code>IF #modeAuto AND #autoReady AND #readyToStart\n   AND #basketAtStopper\n   AND (#continuous OR #startPulse) THEN\n  #statStep := 2;\nEND_IF;</code></pre>"]},
 lf:[["Warum braucht START eine Flankenauswertung? Was passiert ohne, wenn jemand die Taste hält?",[1]],["Wie wird sich deine Anlage verhalten, wenn im laufenden Zyklus von Dauerbetrieb auf Einzelzyklus umgeschaltet wird? Begründe deine Vorhersage.",[0]],["Warum hält STOP die Kette erst am Zyklusende an und nicht sofort?",[2]]],
 lfk:["Wie hat sich deine Anlage verhalten, als du im laufenden Zyklus von Dauerbetrieb auf Einzelzyklus umgeschaltet hast? Stimmt das mit deiner Vorhersage aus Leitfrage 2 überein?"],
 pr:[["Dauerbetrieb + START → mehrere Zyklen hintereinander, −PF1 leuchtet dauernd",[0]],["STOP in Schritt 6 → Korb wird fertig, dann Halt in Schritt 1",[2]],["Einzelzyklus, START gedrückt halten → nur ein Zyklus",[1]],["Not-Halt auslösen, START im Signalmonitor auf 1 forcen, quittieren → nichts läuft an; erst nach Zurücknehmen des Force und neuem Tastendruck startet die Kette",[1,2]],["Not-Halt während Dauerbetrieb, quittieren → kein selbstständiger Wiederanlauf, −PF1 zeigt keinen Dauerbetrieb mehr",[2]],["AUTO ohne Grundstellung → −PF1 blinkt; Querverweisliste: −PF1 hat genau eine Schreibstelle",[0]]],
 ergebnis:[{n:"FB ModeSelect",a:"erweitert",h:"START-Flanke, #statContinuous, Ausgänge continuous und startPulse, Rangfolge für −PF1"},{n:"FB Tinning",a:"erweitert",h:"Transition 1 → 2 für Dauer- und Einzelzyklus"},{n:"Zustandsdiagramm Betriebsarten",a:"erweitert",h:"mit Dauerbetrieb und Einzelzyklus"}, {n:"globaler DB PlantData", a:"erweitert", h:"neue Einträge in der Variablenliste PlantData: Dauerbetrieb aktiv, Startimpuls Einzelzyklus"}, {n:"Ausgangsliste", a:"erweitert", h:"neue Zeilen: −PF1"}],
 plus:"Programmiere die Grundstellungsfahrt als eigene Schrittfolge in <code>Tinning</code> (anheben → zurück und abdecken → senken → lösen) mit den Schrittnummern 11 bis 14. Sie startet in AUTO auf START, wenn die Anlage nicht in Grundstellung steht. Spätere Übungen setzen sie nicht voraus; im Abschlussprojekt L37 sparst du damit Zeit.",
 tpls:[
 {id:"pf1", cap:"Rangfolge der Anzeigen an −PF1", phase:4, head:["Zustand","−PF1 zeigt","Rang (1 = gewinnt)","Begründung"], muster:["Beispiel −PF3 (L05): Füllhöhe fehlt und Wartung fällig","schnelles Blinken 1 Hz","1","Eine Prozessstörung ist wichtiger als ein Wartungshinweis"], rows:[["Dauerbetrieb aktiv"],["AUTO, Grundstellung fehlt"],["AUTO, Einzelzyklus, Grundstellung vorhanden"],["HAND"]], inputs:3},
 {id:"randfaelle", cap:"Randfälle: Vorhersage und Beobachtung", phase:5, head:["Randfall","Vorhersage","Beobachtung am Zwilling","passt (ja oder nein)"], muster:["Einzelzyklus, START gedrückt halten","genau ein Zyklus","Kette fährt einen Zyklus und bleibt in Schritt 1","ja"], rows:[["Dauerbetrieb, mitten im Zyklus auf Einzelzyklus umschalten"],["START, während die Kette schon läuft"],["STOP, während START gedrückt ist (START auf 1 geforct)"],["Not-Halt in AUTO, START vor dem Quittieren gedrückt"]], inputs:3},
 {id:"schreib", erweitert:"L02:schreib", cap:"Ausgangsliste", phase:4, head:["Ausgang","Bedeutung","ab Übung","schreibt (Baustein, einzige Stelle)","Bedingung oder Befehl kommt von","in der Querverweisliste geprüft"], muster:["−PF2","Bad bereit","L02","FB Indication (bis L03 FC), Aufruf im OB1","−BG9 UND −BG10, ODER Lampentest −SF4","ja, eine Schreibstelle"], rows:[["−PF1","Dauerlicht im Dauerbetrieb, blinkt ohne Grundstellung","L18"]], inputs:3},
 {id:"plantdata", erweitert:"L05:plantdata", cap:"Variablenliste PlantData", phase:4, head:["Inhalt","ab Übung","Variablenname","Datentyp","remanent (ja oder nein, warum)","schreibt (Baustein, über den OB1)","liest"], muster:["Betriebsbereitschaft","L05","ready","Bool","nein, nach dem Neustart muss neu gestartet werden","Operation (Output ready)","Indication"], rows:[["Dauerbetrieb aktiv","L18"],["Startimpuls Einzelzyklus","L18"]], inputs:5}
]
}
