// Kurz-Checks je Übung. Wird von build.mjs in vorlage.html eingesetzt (Platzhalter __QUIZ__).
// ein = Eingangs-Check in Phase 1 (nur Vorwissen aus den vor-Übungen), aus = Abschluss-Check in Phase 6 (Transfer, darf Stoff der Übung abfragen)
// Frage: [Frage, [Antwort 0, Antwort 1, Antwort 2], Index der richtigen Antwort, Begründung]
({
 L01:{ein:[
  ["Wie viele Bits hat ein Byte?",["4","8","16"],1,"Ein Byte hat acht Bits. %I0.0 bis %I0.7 sind die acht Bits von Byte 0."],
  ["Ein Schließer ist nicht betätigt. Ist sein Kontakt offen oder geschlossen?",["offen","geschlossen","das hängt von der Spannung ab"],0,"Schließer schließen erst beim Betätigen. Unbetätigt sind sie offen."]],
 aus:[
  ["STOP −SF2 ist als Öffner verdrahtet. Welchen Pegel sieht die SPS, solange niemand drückt?",["0","1","hängt von der Betriebsart ab"],1,"Öffner sind unbetätigt geschlossen: 1 = nicht betätigt. Ein Drahtbruch wirkt wie Drücken, das ist die sichere Seite."],
  ["Was bewirkt das Forcen eines Eingangs im Signalmonitor des Zwillings?",["Der Eingang wird unabhängig vom Prozess fest auf 0 oder 1 gesetzt.","Die SPS geht in STOP.","Der zugehörige Ausgang wird gesperrt."],0,"Der Wert bleibt, bis du ihn mit A zurückgibst."],
  ["Was bedeutet die Adresse %I1.3?",["Eingang, Byte 1, Bit 3","Ausgang, Bit 13","Eingang Nummer 13"],0,"I = Eingang, dann Byte und Bit. Bei dieser Anlage ist %I1.3 der Taster START −SF1."]]},
 L02:{ein:[
  ["Was bedeutet die Adresse %I1.0?",["Eingang, Byte 1, Bit 0","Ausgang 10","Eingang Nummer 10"],0,"I steht für Eingang, dann folgen Byte und Bit (L01). %I1.0 ist −BG9."],
  ["Wo legst du fest, dass %I1.0 den Namen BG9_Temperatur trägt?",["in der PLC-Variablentabelle","im Signalmonitor des Zwillings","in der Forcetabelle"],0,"Die PLC-Variablentabelle ordnet jeder Adresse Namen, Datentyp und Kommentar zu (L01)."]],
 aus:[
  ["−PF2 soll leuchten, wenn −BG9 UND −BG10 melden. Welche Schaltung in KOP?",["zwei Schließer in Reihe","zwei Schließer parallel","ein Öffner und ein Schließer parallel"],0,"Reihenschaltung = UND, Parallelschaltung = ODER."],
  ["−BG14 und −BG15 melden beide 1. Was liefert XOR?",["1: alles in Ordnung","0: unplausibel, ein Sensor stimmt nicht","1: Zylinder fährt"],1,"Ein Zylinder kann nicht gleichzeitig in beiden Endlagen stehen."],
  ["Neue Stilregel: Ein Ausgang wird an zwei Stellen geschrieben. Was erreicht die Leuchte?",["der Wert der letzten Zuweisung im Zyklus","der Wert der ersten Zuweisung","das ODER beider Zuweisungen"],0,"Am Zyklusende zählt nur, was zuletzt im Prozessabbild steht. Deshalb gehört alles in eine Zuweisung."],
  ["Neue Stilregel: Warum schreibst du \"BG9_Temperatur\" statt %I1.0?",["Der Name sagt, was das Signal bedeutet, und eine geänderte Adresse änderst du nur in der Variablentabelle.","Adressen sind in TIA verboten.","Namen werden schneller bearbeitet."],0,"Symbolische Namen machen das Programm lesbar und wartbar."],
  ["Neue Stilregel: Was gehört in den Bausteinkopf?",["Zweck, Autor, Version und Änderungen","die Zykluszeit der CPU","die Adressen aller Eingänge"],0,"Der Kopf beschreibt den Baustein für den nächsten Leser."]]},
 L03:{ein:[
  ["Ein FC wird im OB1 aufgerufen. Woher bekommt er seine Signale?",["über seine Inputs, verschaltet beim Aufruf im OB1","er liest sie selbst aus dem Signalmonitor","aus einem Merker"],0,"So hast du Indication in L02 angeschlossen."],
  ["Ein Ausgang wird an zwei Stellen im Programm geschrieben. Welcher Wert erreicht die Leuchte?",["der Wert der letzten Zuweisung im Zyklus","der Wert der ersten Zuweisung","beide abwechselnd"],0,"Am Zyklusende wird das Prozessabbild der Ausgänge ausgegeben (L02)."]],
 aus:[
  ["START und STOP wirken gleichzeitig. Was muss die Anlage tun?",["einschalten","ausgeschaltet bleiben (rücksetzdominant)","den letzten Zustand halten"],1,"Bei Maschinen hat Aus Vorrang: in TIA die Box SR mit R1 bzw. STOP in Reihe vor der Selbsthaltung."],
  ["Neue Stilregel: Wo speicherst du die Betriebsbereitschaft?",["als statische Variable im FB (Instanz-DB)","in einem globalen Merker","in einer temporären Variable"],0,"Statische Variablen liegen im Instanz-DB und behalten ihren Wert über Zyklen. Temporäre Variablen liegen nur während des Aufrufs im Lokaldatenstack."],
  ["Neue Stilregel: Welcher Name passt zu einer R_TRIG-Multiinstanz für den START-Taster?",["#instStartTrig","#Start_Flanke","#statStart"],0,"Präfix inst für Instanzen im FB, englisch, camelCase."],
  ["Neue Stilregel: Warum rufst du R_TRIG als Multiinstanz auf?",["Seine Daten liegen dann im Instanz-DB deines FB, es entstehen keine verstreuten DBs.","Weil R_TRIG sonst nicht flankengesteuert ist.","Weil Multiinstanzen schneller sind."],0,"Der FB trägt alles in sich, was er braucht."],
  ["Neue Stilregel: Im FB Operation steht #instStartTrig(CLK := \"SF1_Start\"). Was ist falsch?",["Der FB greift direkt auf eine PLC-Variable zu, statt sie über einen Input zu bekommen.","Nichts, das ist richtig.","R_TRIG braucht einen Merker."],0,"Richtig ist ein Input start, der im OB1 mit \"SF1_Start\" verschaltet wird."]]},
 L04:{ein:[
  ["Wie lange liefert R_TRIG am Ausgang Q eine 1?",["einen Zyklus lang je steigender Flanke","solange CLK = 1 ist","bis zum Rücksetzen"],0,"R_TRIG meldet nur den Wechsel von 0 auf 1 (L03)."],
  ["Was bedeutet das Präfix inst in #instStartTrig?",["eine Instanz eines aufgerufenen FB im eigenen FB (Multiinstanz)","eine Eingangsvariable","eine globale Konstante"],0,"So hast du die Flanken in L03 benannt."]],
 aus:[
  ["Welche Zeit verzögert das Einschalten, z. B. für die Tauchzeit?",["TON","TOF","TP"],0,"TON: Q wird erst nach PT 1, solange IN 1 bleibt."],
  ["−SF4 wird 5 s gehalten, der TP für den Lampentest hat PT = 2 s. Wie lange ist Q = 1?",["5 s","2 s","7 s"],1,"Der Impuls ist immer PT lang, unabhängig von der Dauer des Eingangs."],
  ["Ein TON läuft, IN wechselt auf 0. Was zeigt ET danach?",["0","den letzten Wert","PT"],0,"ET wird sofort zurückgesetzt. Wer messen will, kopiert ET vorher in eine statische Variable."],
  ["Neue Stilregel: Warum steht der Aufruf einer Zeit nicht in einer IF-Bedingung?",["Die Zeit bemerkt Änderungen an IN nur beim Aufruf und verpasst sonst Start oder Abbruch.","Weil IF in FUP nicht erlaubt ist.","Weil Zeiten sonst doppelt so schnell laufen."],0,"Rufe jede Zeit in jedem Zyklus auf und lege die Bedingung an IN."]]},
 L05:{ein:[
  ["Welche Zeit nimmst du, damit ein Signal erst nach 3 s ununterbrochenem Anstehen wirkt?",["TON","TOF","TP"],0,"TON verzögert das Einschalten (L04)."],
  ["Wo liegen die Daten einer Multiinstanz #instClock?",["im Instanz-DB des FB, der sie aufruft","in einem eigenen globalen DB","in Merkern"],0,"So hast du Zeiten und Clock in L04 angelegt."]],
 aus:[
  ["Du zählst Körbe selbst: #statBasketCount := #statBasketCount + 1. Warum brauchst du dafür eine Flanke an −BG40?",["Sonst zählt das Programm in jedem Zyklus weiter, solange der Korb anliegt.","Weil −BG40 ein Öffner ist.","Weil Int-Variablen nur Flanken zählen."],0,"Ohne Flanke wird die Addition jeden Zyklus ausgeführt. CTU wertet CU selbst flankengesteuert aus."],
  ["Welcher Zähler eignet sich für die Zahl der Körbe im Puffer?",["CTU","CTD","CTUD"],2,"Körbe kommen hinzu und gehen ab: Es wird vorwärts und rückwärts gezählt."],
  ["Neue Stilregel: Wie legst du den Tageszähler an?",["als CTU-Multiinstanz im FB Counting","als CTU mit eigenem Einzel-DB","als Merkerwort"],0,"Zähler gehören wie Zeiten als Multiinstanz in den FB, der sie benutzt."],
  ["Neue Stilregel: Indication braucht den Wartungshinweis. Wie kommt er dorthin?",["Der OB1 legt den Output von Counting in PlantData ab und verschaltet ihn mit dem Input von Indication.","Indication liest \"InstCounting\".maintenanceDue im Baustein.","Indication liest \"PlantData\".maintenanceDue im Baustein."],0,"Bausteine kennen nur ihre Schnittstelle, verschaltet wird im OB1."],
  ["Der Tageszähler soll einen Neustart überleben. Wo stellst du die Remanenz ein?",["in der Schnittstelle von Counting an der CTU-Multiinstanz","nur in PlantData","in der Beobachtungstabelle"],0,"Remanent muss der Speicher sein, in dem gezählt wird."]]},
 L06:{ein:[
  ["Was bedeutet die Adresse %I3.5?",["Eingang, Byte 3, Bit 5","Eingang Nummer 35","Ausgang, Byte 3, Bit 5"],0,"I steht für Eingang, dann folgen Byte und Bit. Bei dieser Anlage ist %I3.5 der Handtaster −SF16 (L01)."],
  ["STOP −SF2 ist ein Öffner. Welchen Pegel sieht die SPS, solange niemand drückt?",["0","1","das hängt von der Betriebsart ab"],1,"Ein Öffner ist unbetätigt geschlossen und meldet 1. Das steht in deiner Wertetabelle aus L01."]],
 aus:[
  ["In der Beobachtungstabelle zeigt %IB3 den Wert 16#81. Welche Handtaster sind betätigt?",["−SF11 und −SF18","−SF11, −SF12 und −SF18","−SF12 und −SF17"],0,"16#81 = 2#1000_0001: Bit 7 (%I3.7 = −SF18) und Bit 0 (%I3.0 = −SF11)."],
  ["Welche Bytes enthält das Eingangswort %IW2, und welches steht vorn?",["%IB2 und %IB3, %IB2 vorn","%IB2 und %IB3, %IB3 vorn","%IB1 und %IB2, %IB2 vorn"],0,"Die Zahl hinter IW ist das erste Byte. Bei SIMATIC ist das Byte mit der kleineren Nummer das höherwertige und steht links."],
  ["Was ist 2#1100_1000 dezimal?",["200","192","72"],0,"128 + 64 + 8 = 200. In Hex ist das 16#C8."]]},
 L07:{ein:[
  ["Wie viele Bits hat ein Wort, zum Beispiel %IW2?",["8","16","32"],1,"Ein Wort besteht aus zwei Bytes, also 16 Bit. %IW2 enthält %IB2 und %IB3 (L06)."],
  ["Welchen Wert hat 16#FF dezimal?",["255","256","15"],0,"F = 15, also 15 × 16 + 15 = 255. Das ist der größte Wert eines Bytes (L06)."],
  ["Welche Zeitangabe hast du in L04 für eine Zeit von 3 Sekunden geschrieben?",["T#3S","3","16#3"],0,"Zeiten schreibst du in TIA mit dem Präfix T#."]],
 aus:[
  ["%IW2 zeigt als Word 16#9100. Was zeigt dieselbe Adresse als Int?",["eine negative Zahl","37120","16#9100"],0,"Bit 15 ist gesetzt. Bei Int ist das das Vorzeichen, die Zahl ist negativ (−28416)."],
  ["Ein Übungszähler vom Typ Int steht auf 32767 und zählt mit ADD um 1 weiter. Was gilt?",["Er zeigt 32768.","Die ADD-Box meldet ENO = 0, auf den Wert am Ausgang darfst du dich nicht verlassen.","Er bleibt wie ein CTU bei 32767 stehen."],1,"32768 passt nicht in Int. Die Box meldet den Überlauf über ENO. Nur IEC-Zähler bleiben an der Grenze stehen."],
  ["Neue Stilregel: Welcher Datentyp passt für die Zahl der Körbe im Puffer von Band 1?",["Byte","Word","Int"],2,"Die Zahl der Körbe ist eine Menge, mit der du zählst und vergleichst. Mengen legst du als Int, DInt oder Real an, Bitmuster als Byte, Word oder DWord."],
  ["Warum zählst du Stückzahlen nicht in Real?",["Real kann keine ganzen Zahlen speichern.","Real hat nur etwa 7 gültige Stellen, ab 16777216 gehen Zählschritte verloren.","Real ist langsamer als Int."],1,"16777216.0 + 1.0 ergibt wieder 16777216.0, ohne Fehlermeldung."]]},
 L08:{ein:[
  ["Welche Hex-Zahl hat das Bitmuster 2#0000_1100?",["16#0C","16#12","16#C0"],0,"0000 = 0, 1100 = C. Das hast du in L06 geübt."],
  ["Welcher Datentyp passt für das Bitbild der acht Handtaster?",["Byte","Int","Real"],0,"Bitmuster legst du als Byte oder Word an (Stilregel aus L07)."]],
 aus:[
  ["%IB3 = 16#8D. Was liefert %IB3 AND 16#0C?",["16#0C","16#8D","16#81"],0,"AND lässt nur die Bits durch, die in der Maske 1 sind: Bit 2 und Bit 3 sind in 16#8D gesetzt."],
  ["Was liefert ROL 16#81 um eine Stelle?",["16#03","16#02","16#C0"],0,"Bit 7 fällt links heraus und kommt rechts wieder herein: 2#0000_0011."],
  ["Neue Stilregel: Wie schreibst du die Maske für Bit 0 bis Bit 3 einer Word-Variable?",["15","16#F","16#000F"],2,"Bitmuster schreibst du als Hex-Konstante mit allen Stellen. Ein Word hat vier Hex-Ziffern."]]},
 L09:{ein:[
  ["Welche Hex-Zahl zeigt TIA für die Int-Zahl 37?",["16#0025","16#0037","16#0073"],0,"37 = 2 × 16 + 5. In L06 hast du so umgerechnet."],
  ["Was meldet eine CONV-Box mit ENO = 0?",["Die Umwandlung ist gescheitert, z. B. weil der Wert nicht in den Zieltyp passt.","Die Box ist fertig.","Der Wert ist 0."],0,"Das hast du in L07 mit DInt nach Int ausprobiert."]],
 aus:[
  ["Der Korbzähler steht auf 37. Was zeigt die BCD16-Variable im Anzeigeformat Hex?",["16#0025","16#0037","16#3700"],1,"In BCD bekommt jede Dezimalziffer vier Bits: 3 = 0011, 7 = 0111. Die Hex-Anzeige zeigt deshalb die Ziffern direkt."],
  ["Warum ist 16#001A kein gültiger BCD-Wert?",["Weil A keine Dezimalziffer ist; in BCD gibt es nur 0 bis 9 je Vierergruppe.","Weil BCD-Werte immer mit 16#1 beginnen.","Weil 16#001A größer als 999 ist."],0,"Die Vierergruppen 1010 bis 1111 kommen in BCD nicht vor. CONVERT meldet dann ENO = 0."],
  ["Der Korbzähler steht auf 1000. Was gilt für CONVERT Int nach BCD16?",["Ergebnis 16#1000","ENO = 0, weil nur −999 bis +999 umgewandelt werden","Ergebnis 16#0999 automatisch"],1,"Den Ersatzwert, z. B. 16#0999, legst du selbst fest und gibst ihn bei ENO = 0 aus."]]},
 L10:{ein:[
  ["Ein Übungszähler vom Typ Int steht auf 32767 und wird mit ADD um 1 erhöht. Woran erkennst du den Fehler in FUP?",["ENO der ADD-Box ist 0","Die CPU geht in STOP","Der Zähler bleibt bei 32767 stehen"],0,"Das hast du in L07 mit dem Übungszähler ausprobiert."],
  ["Was zeigt der Ausgang ET einer TON-Zeit?",["die bisher abgelaufene Zeit","die eingestellte Zeit PT","die Uhrzeit"],0,"ET ist die abgelaufene Zeit (L04). ET wird 0, sobald IN 0 wird."]],
 aus:[
  ["Der Tageszähler steht auf 23, ein Wartungshinweis kommt alle 10 Körbe. Was liefert 23 MOD 10?",["2","3","2,3"],1,"MOD liefert den Rest der Ganzzahldivision. Bis zum nächsten Hinweis sind es also noch 7 Körbe."],
  ["Warum rechnest du den Füllgrad als Belegung × 100 / 5 und nicht als Belegung / 5 × 100?",["Weil die Ganzzahldivision den Rest abschneidet und 4 / 5 schon 0 ergibt.","Weil MUL schneller ist als DIV.","Weil TIA die Reihenfolge sonst nicht übersetzt."],0,"Erst multiplizieren, dann teilen, und dafür einen Datentyp wählen, in den das Zwischenergebnis passt."],
  ["ROUND(2.5) ergibt in TIA …",["2","3","2.5"],0,"Genau in der Mitte rundet ROUND zur geraden Zahl."],
  ["Neue Stilregel: Wie schreibst du die Zahl der Plätze auf Band 1 im Code?",["als lokale Konstante #BUFFER_PLACES","als Zahl 5","als globaler Merker"],0,"Ein Name erklärt die Zahl, der Wert steht an einer Stelle im Baustein."]]},
 L11:{ein:[
  ["Welche Bytes belegt das Eingangswort %IW64?",["%IB64 und %IB65","nur %IB64","%IB63 und %IB64"],0,"Die Zahl hinter IW ist das erste Byte, ein Wort belegt zwei Bytes (L06)."],
  ["27648 × 400 wird in einer MUL-Box vom Typ Int gerechnet. Was passiert?",["Das Ergebnis stimmt.","Überlauf: ENO = 0, weil Int bei 32767 endet.","TIA rechnet automatisch in Real."],1,"So hast du es in L10 mit der Int-MUL-Box gesehen. 11 059 200 passt nur in DInt oder Real."]],
 aus:[
  ["Welcher Rohwert entspricht 200 °C bei 0 bis 27648 = 0 bis 400 °C?",["13824","20000","27648"],0,"200 °C ist die Hälfte des Bereichs, also die Hälfte von 27648."],
  ["−BT1 liefert plötzlich 32767. Was ist die wahrscheinlichste Ursache?",["Das Zinn ist 474 °C heiß.","Überlauf oder Drahtbruch, der Wert ist ungültig.","Die Heizung ist aus."],1,"32767 (16#7FFF) meldet die Baugruppe bei Überlauf, mit Diagnose bei 4 bis 20 mA auch bei Drahtbruch."],
  ["Warum brauchst du für −BT1 eine Testumschaltung im FB?",["Weil Analogwerte im Signalmonitor nicht forcebar sind und die Bridge gesteuerte Eingänge überschreibt.","Weil TIA keine Int-Werte steuern kann.","Weil der FB sonst nicht übersetzt wird."],0,"Mit #statTestMode und #statTestRaw testest du jeden Wert, auch außerhalb des Nennbereichs."],
  ["Für −PF2 „Bad bereit“ verknüpfst du −BG9 und bathTempOk mit …",["UND, denn eine Gutmeldung braucht beide Messwege","ODER, denn einer genügt","XOR"],0,"Für Gutmeldungen UND, für Warnungen ODER. So liegt ein Fehler in einem Messweg auf der sicheren Seite."]]},
 L12:{ein:[
  ["−PF3 soll leuchten, wenn …",["die Füllhöhe ausreicht.","die Füllhöhe unterschritten ist.","die Temperatur erreicht ist."],1,"−BG10 meldet 1 = in Ordnung. Die Leuchte zeigt den Mangel, also die Negation (L02)."],
  ["Wie kommt ein Ergebnis von einem Baustein zu einem anderen?",["Der OB1 legt den Output in PlantData ab und verschaltet ihn mit dem Input des anderen Bausteins.","Der andere Baustein liest den Instanz-DB.","Über einen Merker."],0,"So hast du es in L05 eingeführt."]],
 aus:[
  ["StartRelease ist ein FC. Was passiert mit seinen Daten, wenn der Aufruf zu Ende ist, und warum passt das hier?",["Die Daten lagen nur in einem temporären Speicherbereich, der nach dem Aufruf freigegeben wird. StartRelease braucht keine Werte aus dem letzten Zyklus, deshalb passt ein FC.","Die Daten bleiben im Instanz-DB des FC erhalten. Deshalb kann er sich alles bis zum nächsten Zyklus merken.","Die Daten werden in Merkern gesichert und im nächsten Zyklus wieder geladen."],0,"Ein FC hat keinen Instanz-DB und keinen Bereich Static. Beim Aufruf bekommt er nur einen temporären Speicherbereich (Lokaldatenstack), und der wird nach dem Aufruf wieder freigegeben. Für eine reine Verknüpfung der aktuellen Sensorwerte genügt das. Muss sich ein Baustein etwas merken, nimmst du einen FB."],
  ["Welche Endlagen bilden die Grundstellung des Portals?",["−BG1, −BG3, −BG5, −BG7","−BG2, −BG4, −BG5, −BG8","−BG2, −BG3, −BG6, −BG8"],1,"−MM1 gelöst, −MM2 unten, −MM3 über dem Band, −MM4 abgedeckt."],
  ["Ein Endlagensensor der Grundstellung hat Drahtbruch. Was zeigt homePosition?",["0, die Anlage startet nicht","1, der Fehler bleibt unbemerkt","einen zufälligen Wert"],0,"Der Sensor liefert 0, also fehlt eine UND-Bedingung. Das ist die sichere Seite."]]},
 L13:{ein:[
  ["Wo speichert ein FB einen Zustand, der den Zyklus überleben soll?",["als statische Variable im Instanz-DB","in einer Temp-Variable","im Prozessabbild der Ausgänge"],0,"So hast du es in L03 gelernt."],
  ["Was zeigt dir die Querverweisliste zu einem Ausgang?",["jede Stelle, an der er gelesen oder geschrieben wird","seinen aktuellen Wert","seine Verdrahtung im Schaltschrank"],0,"Damit prüfst du, dass jeder Ausgang genau eine Schreibstelle hat (L02)."]],
 aus:[
  ["Warum speichert Manual die Stellung des Anschlags −MM5 in #statStopperOpen?",["Das 5/2-Ventil −MB9 ist monostabil und fällt ohne Signal in die Ruhestellung zurück.","Der Zylinder ist doppeltwirkend.","Wegen des Not-Halts."],0,"Bistabile Ventile (−MM1 bis −MM4) halten ihre Stellung auch ohne Signal."],
  ["−SF13 senken und −SF14 anheben werden gleichzeitig betätigt. Was soll passieren?",["Keine Spule wird angesteuert.","Senken hat Vorrang.","Die zuletzt gedrückte Taste gewinnt."],0,"Gegenbefehle heben sich auf. Ein bistabiles Ventil bleibt dann einfach in seiner Stellung."],
  ["Ein bistabiles Ventil wird kurz angetippt. Was macht der Zylinder?",["Er fährt bis in die Endlage.","Er bleibt sofort stehen, wenn du loslässt.","Er fährt zurück."],0,"Der Schieber bleibt nach dem Impuls in seiner Lage. Anhalten im Hub ginge nur mit einem 5/3-Ventil."]]},
 L14:{ein:[
  ["Was passiert bei einem bistabilen Ventil, wenn du den Taster nach einem kurzen Tippen loslässt?",["Der Zylinder fährt bis in die Endlage weiter.","Der Zylinder bleibt sofort stehen.","Der Zylinder fährt zurück."],0,"Das bistabile Ventil bleibt geschaltet (L13)."],
  ["Welche Leuchte zeigt an, dass der Handbetrieb aktiv ist?",["−PF7","−PF1","−PF5"],0,"Manual schreibt −PF7 seit L13."]],
 aus:[
  ["Wann darf −MM3 verfahren werden?",["nur mit angehobenem Korb (−BG3)","nur bei offenem Bad","in HAND immer"],0,"Ein abgesenkter Korb würde gegen Band oder Badrand fahren."],
  ["Warum verriegelst du auf die Endlage −BG3 statt auf den letzten Befehl „anheben“?",["Der Befehl sagt nur, was gewollt war. Die Endlage meldet, was wirklich ist.","Weil Befehle nur einen Zyklus lang anstehen.","Das ist gleichwertig."],0,"Klemmt der Zylinder oder fehlt Druck, steht der Befehl an, aber der Korb ist nicht oben."],
  ["Die Freigabe für −MM4 abdecken lautet „Korb angehoben (−BG3) oder über dem Band (−BG5)“. Was passiert bei Drahtbruch an −BG3, während der Korb über dem Bad hängt?",["Die Freigabe fehlt, die Abdeckung fährt nicht.","Die Abdeckung fährt gegen den Korb.","Die CPU geht in STOP."],0,"Positiv formulierte Freigaben legen einen Sensorfehler auf die sichere Seite."],
  ["Warum ist Interlock ein FC?",["Er verknüpft nur die aktuellen Endlagen und muss sich nichts merken.","Weil Freigaben in FBs verboten sind.","Weil ein FC Merker nutzen darf."],0,"Faustregel aus L04: Ein FC hat keinen Instanz-DB, seine Daten liegen nur während des Aufrufs im temporären Speicher. Interlock braucht keine Werte aus dem letzten Zyklus, also genügt ein FC. Braucht ein Baustein solche Werte, nimmst du einen FB."]]},
 L15:{ein:[
   ["Was meldet der Ausgang homePosition deines FC StartRelease aus L12?",["Alle Endlagen der Grundstellung sind erreicht.","Die Automatik läuft.","Ein Not-Halt ist gedrückt."],0,"homePosition ist eine reine Verknüpfung der gemeldeten Endlagen. Ein FC hat keinen Instanz-DB, seine Daten gelten nur während des Aufrufs. Für eine reine Verknüpfung genügt das."],
   ["Worauf verriegelst du in L14 eine Bewegung?",["auf die gemeldete Endlage, z. B. −BG3","auf den zuletzt gegebenen Befehl","auf eine feste Wartezeit"],0,"Nur die Endlage meldet, wo der Zylinder wirklich steht."]],
  aus:[
   ["−SA3 steht auf HAND. Wer darf Ventile bewegen?",["nur der Handbetrieb, die Automatik ruht","Handbetrieb und Schrittkette","nur die Schrittkette"],0,"Betriebsarten schließen sich aus. In HAND ruht die Automatik."],
   ["Du schaltest von HAND auf AUTO. Was darf dabei passieren?",["Die Anlage startet sofort den Zyklus.","Nichts bewegt sich. AUTO wartet auf Grundstellung und START.","Alle Zylinder fahren sofort in Grundstellung."],1,"Ein Betriebsartenwechsel ist kein Startbefehl."],
   ["Ein weiterer Baustein soll wissen, ob AUTO aktiv ist. Wie bekommt er das?",["über einen Eingang, den du im OB1 mit dem Ausgang modeAuto von ModeSelect verschaltest","er liest #statModeAuto im Instanz-DB von ModeSelect","er fragt −SA3 selbst ab"],0,"Der Siemens-Styleguide erlaubt den Datenaustausch nur über die Bausteinschnittstellen. So steht die Regel für AUTO an genau einer Stelle."]]},
 L16:{ein:[
   ["Woran erkennst du in der Querverweisliste, dass ein Ausgang an einer Stelle geschrieben wird?",["an der Zugriffsart „schreibend“","am Kommentar des Netzwerks","am Datentyp des Ausgangs"],0,"Die Querverweisliste zeigt je Verwendungsstelle, ob gelesen oder geschrieben wird."],
   ["Was gibt ModeSelect aus L15 an die anderen Bausteine weiter?",["die Ausgänge modeManual und modeAuto","seine statischen Variablen #statModeManual und #statModeAuto","den Schalter −SA3 unverändert"],0,"Daten fließen nur über die Schnittstelle. Statische Variablen bleiben im Baustein."]],
  aus:[
   ["Derselbe Ausgang wird im Handbetrieb und in der Schrittkette zugewiesen. Was passiert?",["TIA meldet beim Übersetzen einen Fehler.","Die letzte Zuweisung im Zyklus gewinnt, die andere ist wirkungslos.","Beide werden ODER-verknüpft."],1,"Die CPU bearbeitet das Programm von oben nach unten. Am Ende des Programmdurchlaufs steht im Prozessabbild der zuletzt geschriebene Wert, und nur der wird an die Ausgangsbaugruppe übertragen."],
   ["Wo gehört die Verriegelung „−MM3 nur mit angehobenem Korb“ hin?",["in die Befehlsausgabe, dann gilt sie für HAND und AUTO","nur in den Handbetrieb","in jeden Schritt der Kette"],0,"An einer Stelle gepflegt, wirkt sie für jede Betriebsart und jede Befehlsquelle."],
   ["Wo steht nach dem Umbau der Schreibzugriff auf %Q0.2 (−MB3) in der Querverweisliste?",["beim Aufruf von InstCommandOutput im OB1","in einem Netzwerk von Manual","in der Beobachtungstabelle"],0,"CommandOutput gibt das Ventil über seinen Ausgang aus. Mit %Q0.2 verschaltet ist er beim Aufruf im OB1."]]},
 L17:{ein:[
   ["Seit L16 liefert Manual nur noch Befehle. Wer schreibt die Ventile −MB1 bis −MB9?",["CommandOutput, als einzige Stelle","Manual und CommandOutput abwechselnd","jeder Baustein, der das Ventil braucht"],0,"Eine Schreibstelle je Ausgang: Alle Befehlsquellen laufen in der Befehlsausgabe zusammen."],
   ["Wann ist der Ausgang Q eines TON (L04) 1?",["wenn IN länger als PT ununterbrochen 1 ist","sofort, wenn IN 1 wird","wenn IN auf 0 fällt"],0,"Der TON ist eine Einschaltverzögerung. Fällt IN vorher ab, beginnt die Zeit von vorn."]],
  aus:[
   ["Neue Stilregel: Was gehört laut Siemens-Styleguide in jede CASE-Anweisung?",["ein ELSE-Zweig für unerwartete Werte","ein EXIT","ein Kommentar in jeder Zeile"],0,"Nur so landet die Kette bei einem ungültigen Schrittwert in einem festgelegten Zustand, statt stumm zu hängen."],
   ["Ab wann läuft die Tauchzeit in Schritt 6?",["mit dem Schrittwechsel","ab Erreichen von −BG4","ab dem Öffnen des Bades"],1,"Sonst frisst die Fahrzeit des Zylinders die Tauchzeit auf, und der Zwilling meldet „Korb mangelhaft“."],
   ["Was ist in GRAFCET eine Transition?",["eine Aktion, die im Schritt ausgeführt wird","die Bedingung für den Übergang zum nächsten Schritt","ein Speicherbaustein"],1,"Schritt, Transition, Schritt: immer im Wechsel."]]},
 L18:{ein:[
   ["Was liefert ein R_TRIG (L03) an seinem Ausgang Q?",["für genau einen Zyklus 1, wenn CLK von 0 auf 1 wechselt","1, solange CLK 1 ist","1, wenn CLK von 1 auf 0 wechselt"],0,"R_TRIG erkennt die steigende Flanke. Für die fallende Flanke gibt es F_TRIG."],
   ["Ein SR-Speicher in TIA (L03): S und R1 sind gleichzeitig 1. Was passiert?",["Er wird zurückgesetzt, R1 hat Vorrang.","Er wird gesetzt.","Er behält seinen bisherigen Wert."],0,"Beim SR ist der Rücksetzeingang dominant."]],
  aus:[
   ["Warum wird START als Flanke ausgewertet?",["Damit ein gehaltenes START im Einzelzyklus nicht mehrere Zyklen auslöst.","Weil START ein Öffner ist.","Damit der Not-Halt schneller wirkt."],0,"Die Flanke ist genau einen Zyklus lang 1, egal wie lange jemand drückt."],
   ["STOP im Dauerbetrieb während Schritt 6: Was soll passieren?",["sofortiger Halt aller Zylinder","Der laufende Korb wird fertig, dann Halt in Schritt 1.","Wechsel in den Handbetrieb"],1,"Ein halb verzinnter Korb wäre Ausschuss. Das sofortige Stillsetzen ist Aufgabe des Not-Halts."],
   ["Warum löschst du #statContinuous bei −KF2 = 0?",["Damit die Anlage nach dem Quittieren nicht von selbst wieder anläuft.","Damit −KF2 schneller freigibt.","Weil −SA1 sonst nicht mehr wirkt."],0,"Das Rücksetzen eines Not-Halts darf keinen Wiederanlauf einleiten. Weiter geht es erst mit einer neuen START-Flanke."]]},
 L19:{ein:[
   ["Was bedeutet −KF2 = 0 für dein Programm aus L15?",["Not-Halt oder Schutzfeld verletzt: beide Betriebsarten sind 0.","Nur HAND ist aktiv.","Die Anlage soll starten."],0,"−KF2 meldet, ob das Sicherheitsrelais freigibt. Ohne Freigabe gibt es keine Betriebsart."],
   ["Wie lässt du eine Leuchte blinken, ohne einen Taktmerker zu verwenden (L04)?",["mit deinem FB Clock als Multiinstanz","mit dem Taktmerkerbyte der CPU","mit einem einzelnen TP-Impuls"],0,"Der Takt entsteht im Programm und wandert mit dem Baustein in jedes Projekt."]],
  aus:[
   ["Was schaltet die Anlage bei Not-Halt ab?",["das SPS-Programm über die Meldekontakte","das Sicherheitsrelais −KF2, unabhängig vom Programm","der Umrichter"],1,"Die Meldekontakte dienen nur der Diagnose. Abgeschaltet wird hart über −KF2."],
   ["Was ist ein Erstwert?",["die zuerst aufgetretene von mehreren Störungen","der erste Wert einer Messreihe","der Startwert eines Zählers"],0,"Folgemeldungen verdecken sonst die eigentliche Ursache."],
   ["Was ist nach DIN EN ISO 13850 das Rücksetzen des Not-Halt-Befehls am Gerät selbst?",["das Entriegeln des Tasters vor Ort","der nächste START","das Quittieren an −SF4"],0,"Entriegeln setzt den Not-Halt-Befehl zurück und darf nichts in Gang setzen. Das Quittieren an −KF2 ist die manuelle Rückstellung, danach braucht es noch einen Startbefehl."]]},
 L20:{ein:[
   ["Was meldet −FA1 = 0?",["Der Motorschutz hat ausgelöst, oder die Leitung ist unterbrochen.","Das Band läuft.","Die Vor-Ort-Steuerstelle ist aktiv."],0,"Hilfskontakte melden 1 = OK, also drahtbruchsicher wie die Öffner aus L01."],
   ["In L16 schreibt CommandOutput die Ventile. Was liefert Manual?",["nur Handbefehle, die CommandOutput zusammenführt","eigene Ventilausgänge","nur Freigaben"],0,"Jeder Ausgang hat genau eine Schreibstelle in der Befehlsausgabe."]],
  aus:[
   ["Warum eine programmierte Verriegelung, obwohl die Schütze mechanisch verriegelt sind?",["Die SPS soll nie beide Richtungen gleichzeitig ansteuern; die Programmverriegelung ergänzt die mechanische.","Die mechanische Verriegelung wirkt nur in HAND.","Die programmierte Verriegelung ist überflüssig."],0,"Die Verriegelung im Programm ersetzt die mechanische und die elektrische Verriegelung (Hilfsöffner) nicht, sie verhindert aber, dass die SPS überhaupt einen widersprüchlichen Befehl ausgibt."],
   ["Halt −SF7 ist ein Öffner. Welchen KOP-Kontakt setzt du für „Halt nicht betätigt“?",["einen Schließerkontakt −| |−","einen Öffnerkontakt −|/|−","eine Spule"],0,"Im KOP fragst du den Signalzustand ab: nicht betätigt heißt Eingang 1, also Schließerkontakt."]]},
 L21:{ein:[
   ["Was meldet −BG15?",["Anschlag −MM5 offen","Korb liegt an","Vereinzeler zu"],0,"−BG14 meldet zu, −BG15 offen (Tabelle in L13)."],
   ["−MB9 ist ein monostabiles 5/2-Ventil mit Federrückstellung. Was passiert, wenn der Ausgang 0 wird?",["Die Feder schließt den Anschlag.","Der Anschlag bleibt, wo er ist.","Der Anschlag öffnet."],0,"Bei monostabilen Ventilen ist der Wegfall des Signals selbst eine Bewegung (L15)."]],
  aus:[
   ["Worauf schaltet die Kette am Übergabeplatz weiter, wenn ein Korb einläuft?",["auf eine Wartezeit nach −BG11","auf −BG40 „Korb liegt an“","auf −BG12"],1,"Eine Wartezeit passt nur für genau eine Bandgeschwindigkeit."],
   ["Wann darf der Vereinzeler den nächsten Korb freigeben?",["sobald −BG11 frei ist","erst wenn der Anschlag geschlossen ist (−BG14)","sofort nach dem Anheben"],1,"Sonst läuft der nächste Korb durch den offenen Anschlag."],
   ["Du öffnest den Anschlag, sobald −BG40 meldet, noch bevor das Portal eingehängt hat. Was passiert?",["−BG40 fällt ab, das Portal sieht keinen Korb mehr und beginnt nie.","Das Portal hängt schneller ein.","Nichts, −BG40 bleibt 1."],0,"−BG40 meldet nur bei geschlossenem Anschlag. Deshalb öffnest du erst nach −BG1."]]},
 L22:{ein:[
   ["Eine Drossel steht auf 0 %. Was passiert mit dem Zylinder?",["Er fährt doppelt so schnell.","Er steht.","Nichts ändert sich."],1,"Ideal, um Überwachungszeiten zu testen. 50 % ist die Nennzeit."],
   ["Was zeigt der Ausgang ET eines TON (L04)?",["die abgelaufene Zeit, solange IN 1 ist","die eingestellte Zeit PT","die Zeit seit dem letzten Zyklus"],0,"Mit ET kannst du die SPS Fahrzeiten selbst messen lassen."]],
  aus:[
   ["Eine zu knapp gewählte Überwachungszeit führt zu …",["Fehlalarmen bei normalen Schwankungen.","späterer Fehlererkennung.","höherer Taktzeit."],0,"Eine zu lange Zeit erkennt Fehler dagegen spät. Deshalb gilt: gemessene Fahrzeit mal Sicherheitsfaktor."],
   ["Welcher Schritt bekommt keine Laufzeitüberwachung?",["der Initialschritt, der auf START wartet","Schritt 4, zum Zinnbad fahren","Schritt 9, absenken"],0,"Warten ist keine Störung. Überwacht wird nur eine befohlene Bewegung."],
   ["Du drückst −SF4, um eine Laufzeitstörung zu quittieren. Was passiert zusätzlich?",["−SF4 setzt auch das Sicherheitsrelais −KF2 zurück, falls es abgeschaltet hatte.","Die Anlage startet sofort neu.","Nichts, −SF4 wirkt nur auf dein Programm."],0,"−SF4 ist parallel auf den Start von −KF2 verdrahtet. Danach läuft trotzdem nichts von selbst an."]]},
 L23:{ein:[["Wie viele Übergaben durchläuft ein Korb von Band 1 bis in die Mulde?",["2","3","4"],1,"Band 1 → Kurve, Kurve → Band 2, Band 2 → Mulde."],["Zwei Bausteine schreiben denselben Ausgang. Was gilt am Ende des Zyklus?",["der Wert der letzten Zuweisung","der Wert der ersten Zuweisung","eine ODER-Verknüpfung beider Werte"],0,"Deshalb schreibt jeden Ausgang nur die Befehlsausgabe (L16)."]], aus:[["Wann bewegt sich ein Korb an einer Übergabe?",["wenn der aufnehmende Förderer läuft","nur wenn beide Förderer in dieselbe Richtung laufen","wenn die Lichtschranke frei ist"],1,"Der Korb liegt an der Stoßstelle auf beiden Förderern."],["Wie überbrückst du die Lücke zwischen zwei Lichtschranken am robustesten?",["mit einem gespeicherten Übergabe-Zustand: gesetzt am abgebenden, zurückgesetzt am aufnehmenden Sensor","mit einer längeren Nachlaufzeit","gar nicht, die Lücke ist zu klein"],0,"Ein gespeicherter Zustand ist unabhängig von Geschwindigkeit und Stillstand."],["Beim nachfolgenden Förderer löst der Motorschutz aus. Was tut der vorgelagerte?",["Er gibt keinen Korb mehr ab.","Er fördert weiter, der Stau löst sich von selbst.","Er läuft rückwärts."],0,"Sonst stauen sich die Körbe an der Stoßstelle und schieben aufeinander."]]},
 L24:{ein:[["Eine INT-Variable steht bei 32767, und du rechnest in SCL #statCount := #statCount + 1. Was steht danach drin?",["−32768 (Überlauf)","32767","32768"],0,"Der Wertebereich ist überschritten (L07). Ein CTU bliebe dagegen bei 32767 stehen. Für große Zählerstände nimmst du DINT."],["Welche Anweisung meldet die steigende Flanke eines Signals für genau einen Zyklus?",["R_TRIG","F_TRIG","TOF"],0,"R_TRIG (L03) als Multiinstanz im FB."]], aus:[["Wie viel Bandweg entspricht ein Impuls von −BG18?",["10 mm","24,5 mm","245 mm"],1,"10 Impulse je Umdrehung, 245 mm je Umdrehung."],["Woran erkennst du die Drehrichtung?",["an der Pulsfrequenz","am Pegel von Spur B bei steigender Flanke von A","am Nullimpuls"],1,"Vorwärts: B = 1 bei steigender Flanke A."],["Wozu dient der Nullimpuls?",["Er korrigiert verpasste oder doppelt gezählte Impulse an einer festen Trommelstellung.","Er zeigt die Position des Korbs.","Er verdoppelt die Auflösung."],0,"Der Geber misst die Trommel. Den Korb erfasst du zusätzlich an einer Lichtschranke."]]},
 L25:{ein:[["Was liefert eine Analogeingabe der S7-1500 bei 100 % des Messbereichs?",["27648","32767","100"],0,"Nennbereich 0 bis 27648 (L11). Darüber liegen Übersteuerung und Überlauf."],["Der Signalmonitor des Zwillings forct …",["nur digitale Eingänge; für Analogwerte baust du eine Testumschaltung im FB.","alle Eingänge und Ausgänge.","nur Analogwerte."],0,"Die Testumschaltung (#statTestMode, #statTestRaw) kennst du aus L11."]], aus:[["Warum läuft die Pumpe vor dem Sprühventil an?",["Das Ventil wirkt nur bei laufender Pumpe. So steht Druck an, wenn es öffnet.","Um Strom zu sparen.","Wegen des Luftmessers."],0,"Reihenfolge der Aggregate: erst Versorgung, dann Verbraucher."],["Rohwert 13824 an −BT2 entspricht …",["100 °C","200 °C","138 °C"],1,"0 bis 27648 = 0 bis 400 °C, 13824 ist die Hälfte."],["Ohne Korb am Kühlplatz meldet −BT2 rund 25 °C. Was folgt daraus?",["Die Messung ist nur mit Korb an −BG22 gültig.","Der Korb ist schon abgekühlt.","Das Pyrometer ist defekt."],0,"Ein Messwert braucht eine Bedingung, die seine Gültigkeit belegt."]]},
 L26:{ein:[["Wie viele Teile liegen in einem Korb?",["12","36","144"],1,"36 Teile je Korb (Anlagenbeschreibung). 144 Teile passen in einen KLT."],["Wie lange braucht ein Teil für 300 mm bei 150 mm/s?",["2 s","0,5 s","45 s"],0,"t = s / v = 300 mm / 150 mm/s."]], aus:[["Wie lange ist das Prüfergebnis −BG28 / −BG29 gültig?",["0,3 s","3 s","bis zum nächsten Trigger"],0,"Wer zu spät liest, verliert das Ergebnis."],["Wozu ein FIFO für die Ausblaszeitpunkte?",["Mehrere Teile können gleichzeitig zwischen Kamera und Düse liegen.","Die Kamera ist langsam.","Die Düse ist monostabil."],0,"Jedes Teil braucht seinen eigenen Ausblaszeitpunkt."],["Was liefert RUNTIME?",["die Zeit seit dem letzten Aufruf mit derselben Speichervariable","die Uhrzeit der CPU","die Zykluszeit des OB1 als Mittelwert"],0,"Aufsummiert ergibt das eine fortlaufende Zeitbasis."]]},
 L27:{ein:[["Was sieht die SPS bei einem Schließer mit Drahtbruch?",["0","1","den letzten Wert"],0,"Ohne Strom kommt am Eingang 0 an (L01)."],["Wo gehört eine Verriegelung hin, die für jeden Befehl an einen Ausgang gelten soll?",["in die Befehlsausgabe, an die einzige Schreibstelle des Ausgangs","in jeden Baustein, der den Ausgang anfordert","in den OB1 vor alle Bausteine"],0,"So gilt sie für Hand, Automatik und spätere Erweiterungen (L16)."]], aus:[["−BG39 meldet 0. Was kann das bedeuten?",["Tank voll oder Drahtbruch","Tank leer","Pumpe läuft"],0,"Ruhestromprinzip: Beides führt zur sicheren Seite, also nicht nachspeisen."],["Wozu gibt −BG38 die Pumpe frei?",["Trockenlaufschutz","Überlaufschutz","Frostschutz"],0,"Ohne Wasser wird die Gleitringdichtung zerstört, und es gibt kein Sprühwasser."],["Was ist am Kühlwassertank die Störgröße?",["Ablasshahn und Sprühverbrauch","das Magnetventil −MB17","der Pegel"],0,"Störgrößen verändern den Istwert von außen. −MB17 ist das Stellglied, der Pegel die Regelgröße."]]},
 L28:{ein:[["Welche Anweisungen rechnen einen Rohwert 0 bis 27648 in eine physikalische Größe um?",["NORM_X und SCALE_X","TON und TOF","MOVE und CONV"],0,"Bekannt aus L25: erst normieren, dann skalieren."],["−BG39 meldet „voll“. Was gilt für die Nachspeisung aus L27?",["Die Nachspeisung bleibt zu, auch bei Drahtbruch.","Die Nachspeisung öffnet, weil der Tank leer sein könnte.","Die Nachspeisung öffnet mit halber Menge."],0,"Ruhestromprinzip: 0 führt zur sicheren Seite."]], aus:[["Was verhindert die Hysterese bei der Zweipunktregelung?",["ständiges Ein- und Ausschalten um einen Schaltpunkt","eine bleibende Regeldifferenz","einen Überlauf"],0,"Ohne Hysterese flattert das Ventil."],["Radar zeigt 98 %, −BG39 meldet „frei“. Was tut dein Programm nach der Verzögerungszeit?",["„Messung gestört“ melden und mit der Grenzschalter-Logik weiterarbeiten","dem Radar glauben und nicht mehr nachspeisen","−BG39 ignorieren"],0,"Ein Widerspruch zeigt, dass eine Messung falsch ist. Die Grenzschalter sind die Sicherheitsebene."],["Warum erkennt eine reine Bereichsprüfung einen eingefrorenen Messwert nicht?",["Er liegt im gültigen Bereich.","Er ist immer 32767.","Er ist negativ."],0,"Erst der Vergleich mit einer zweiten Information deckt ihn auf."]]},
 L29:{ein:[["Was ist bei der Zweipunktregelung die Hysterese?",["der Abstand zwischen Einschalt- und Ausschaltpunkt","die Zeit bis zum Schalten","die Stellgröße in %"],0,"Bekannt aus L27 und L28."],["Wie heißt der Unterschied zwischen Sollwert und Istwert?",["Regeldifferenz e","Störgröße z","Stellgröße y"],0,"Begriffe des Regelkreises aus L27."]], aus:[["Wie viel Heizleistung braucht das Bad ungefähr für 280 °C?",["50 %","76 %","100 %"],1,"100 % ergeben 360 °C im Beharrungszustand."],["Welcher Anteil des PID-Reglers beseitigt die bleibende Regeldifferenz?",["der I-Anteil","der P-Anteil","der D-Anteil"],0,"Der I-Anteil sammelt die Regeldifferenz auf, bis sie verschwunden ist."],["Wann startet die Erstoptimierung bei Sollwert 280 °C und Istwertgrenzen 0 bis 400 °C?",["nur wenn das Bad unter 140 °C liegt","jederzeit","nur bei 280 °C"],0,"Abstand größer als 50 % des Sollwerts und größer als 30 % des Istwertbereichs."],["Wo rufst du PID_Compact auf?",["direkt im Weckalarm-OB als Technologieobjekt","als Multiinstanz im OB1","im Anlauf-OB"],0,"Nur so gibt es Konfiguration, Inbetriebnahmefenster und eine feste Abtastzeit."]]},
 L30:{ein:[["Welchen Ausgang von PID_Compact hast du in L29 für die Heizung −TB1 genutzt?",["Output_PWM","Output_PER","Output"],0,"Die Heizung schaltet nur ein und aus. Output_PWM macht aus dem Stellwert Impulse mit passender Dauer."],["Warum ruft man PID_Compact in einem Weckalarm-OB auf?",["Der Regler rechnet mit festen Zeitabständen zwischen zwei Aufrufen.","Im OB1 darf kein Technologieobjekt stehen.","Der Weckalarm-OB hat Vorrang vor dem Not-Halt."],0,"I- und D-Anteil brauchen eine konstante Abtastzeit. Im OB1 schwankt die Zeit zwischen zwei Aufrufen."]],
 aus:[["Der Kühlwassertank ist eine … Strecke.",["integrierende (ohne Ausgleich)","PT1-","PT2-"],0,"Der Pegel ändert sich, solange Zu- und Abfluss ungleich sind."],["Warum bleibt beim P-Regler mit offenem Ablasshahn eine Regeldifferenz?",["Er braucht eine Regeldifferenz, um die Ventilöffnung für den Abfluss zu liefern.","Der Sensor ist ungenau.","Die Stellzeit ist zu lang."],0,"Der I-Anteil liefert diese Öffnung auch bei Regeldifferenz null."],["Bei welchem Pegel startet die Erstoptimierung für 70 % Sollwert (Istwertgrenzen 0 bis 100 %)?",["unter 35 %","unter 60 %","bei genau 70 %"],0,"Der Abstand muss größer als 50 % des Sollwerts und größer als 30 % der Istwertspanne sein."]]},
 L31:{ein:[["Wie lange braucht −MB18 für 0 bis 100 %?",["1 s","8 s","15 s"],1,"Das steht in der Tabelle der Regelstrecke aus L30."],["Warum lassen sich Analogwerte im Zwilling nicht einfach testen wie Taster?",["Der Signalmonitor kann nur digitale Eingänge forcen.","Analogwerte sind in TIA schreibgeschützt.","Der Zwilling hat keine Analogeingänge."],0,"Deshalb nutzt du eine Testumschaltung im FB, wie in L11."]],
 aus:[["Wozu dient die Stellungsrückmeldung %IW74?",["zum Vergleich mit dem Stellwert, um ein klemmendes Ventil zu erkennen","als Istwert der Regelung","zur Füllstandsmessung"],0,"Stellwert und Rückmeldung müssen nach der Stellzeit übereinstimmen."],["Warum braucht die Zulaufüberwachung eine Gültigkeitsbedingung?",["Im eingeschwungenen Betrieb steht der Pegel absichtlich still.","Weil −MB17 sonst nicht schaltet.","Weil der Regler sonst nicht optimiert."],0,"Ohne Bedingung meldet sie im Normalbetrieb „Frischwasser fehlt“."]]},
 L32:{ein:[["Was entscheidet dein Übergabe-Handshake aus L23?",["wann ein Förderer einen Korb abgibt oder übernimmt","wie schnell der Motor dreht","welche Adresse der Motor hat"],0,"Der Handshake regelt das Wann. In L32 ändert sich nur, wie der Motor angesteuert wird."],["Wie kehrt ein Wendeschütz die Drehrichtung eines Drehstrommotors um?",["Ein zweites Schütz vertauscht zwei Phasen.","Es halbiert die Frequenz.","Es schaltet den Motor auf Gleichstrom."],0,"Deshalb gibt es je Förderer zwei Schütze, die gegeneinander verriegelt sind (L20)."]],
 aus:[["Was darf im TO_SpeedAxis für den Zwilling nicht aktiviert sein?",["Simulation","Rampen","MC_Reset"],0,"Eine Achse in Simulation gibt keine Sollwerte an den Antrieb aus."],["16#4000 im NSOLL_A von −TA2 entspricht …",["100 % = 1500 1/min = 100 mm/s","50 %","der Maximaldrehzahl 2250 1/min"],0,"Bezugsdrehzahl p2000 = 1500 1/min."],["Warum gibt MC_Power im Zwilling nicht frei, wenn die automatische Übernahme der Antriebswerte an ist?",["Das TO wartet auf Werte aus einem echten Umrichter, die nie kommen.","Weil PLCSIM Advanced kein Motion Control kann.","Weil die Bezugsdrehzahl zu klein ist."],0,"MC_Power setzt eine abgeschlossene Datenadaption voraus."]]},
 L33:{ein:[["Welches Wort des Telegramms überträgt den Drehzahlsollwert?",["NSOLL_A","NIST_A","ZSW1"],0,"NSOLL_A geht von der SPS zum Umrichter, NIST_A zurück."],["Wer hat in L32 das Steuerwort STW1 von −TA2 geschrieben?",["das Technologieobjekt","dein OB1 direkt","der Umrichter selbst"],0,"Deshalb musst du es in L33 erst löschen, sonst gäbe es zwei Schreibstellen."]],
 aus:[["Welches Steuerwort holt −TA2 aus der Einschaltsperre?",["16#047E (AUS1 = 0)","16#047F","16#0000"],0,"Erst AUS1, dann führt 16#047F in den Betrieb."],["Was bewirkt AUS2?",["Halt mit Rampe","Impulssperre, der Antrieb trudelt aus","Schnellhalt"],1,"AUS1 = Rampe, AUS3 = Schnellhalt."],["Warum stellst du nach dem Löschen des Technologieobjekts das Prozessabbild des Telegramms zurück?",["Sonst wird es nur im Takt von MC-Servo aktualisiert und ist in der Beobachtungstabelle nicht sichtbar.","Sonst ist der Umrichter nicht mehr im Projekt.","Sonst stimmt die Bezugsdrehzahl nicht."],0,"Motion Control ordnet die Telegramme dem Teilprozessabbild „TPA OB Servo“ zu."]]},
 L34:{ein:[["Wie lange braucht ein Teil für 200 mm bei 100 mm/s?",["2 s","0,5 s","20 s"],0,"t = s / v = 200 mm / 100 mm/s."],["Welcher Telegrammwert entspricht 100 % der Bezugsdrehzahl?",["16#4000","16#7FFF","27648"],0,"Das kennst du aus L32 und L33. 27648 ist dagegen 100 % bei Analogwerten."]],
 aus:[["Das Poti −SF47 steht auf 27648. Welcher NSOLL_A?",["16#2000","16#4000","27648"],1,"27648 = 100 %, und 100 % sind beim Telegramm 16#4000 = 16384."],["Warum NIST_A für die Ausblaszeit?",["Die tatsächliche Geschwindigkeit bestimmt die Laufzeit, auch während der Rampen.","NSOLL_A ist nicht lesbar.","NIST_A ist genauer skaliert."],0,"Sollwert und Istwert unterscheiden sich beim Hoch- und Rücklauf."]]},
 L35:{ein:[["Welches ZSW1-Bit meldet die Einschaltsperre?",["Bit 6","Bit 3","Bit 9"],0,"Das kennst du aus L33: Bit 3 = Störung, Bit 9 = Führung gefordert."],["Womit quittierst du beim Technologieobjekt eine Störung?",["mit einer Flanke an MC_Reset.Execute","mit MC_Power.Enable = 0","mit MC_Halt"],0,"MC_Reset quittiert Alarme des Technologieobjekts, auch Antriebsstörungen (L32)."]],
 aus:[["Ein Bediener quittiert F07011 sofort nach dem Auslösen. Was soll dein Programm zeigen?",["Die Meldung bleibt stehen, mit dem Hinweis „abkühlen lassen, dann quittieren“.","Die Meldung verschwindet, der Antrieb läuft an.","Die CPU geht in STOP."],0,"Quittieren wirkt erst, wenn die Ursache beseitigt ist. Das Programm erklärt dem Bediener, warum."],["Woran unterscheidest du F30005 von F07011 im Telegramm 1?",["an ZSW1.13","an ZSW1.3","an NIST_A"],0,"Beide setzen ZSW1.3. Nur bei Motorübertemperatur fällt ZSW1.13 auf 0."]]},
 L36:{ein:[["Wie hast du in L22 die Überwachungszeit einer Bewegung festgelegt?",["gemessene Fahrzeit mal Faktor bzw. plus Zuschlag","gleich der Nennzeit im Datenblatt","so kurz wie möglich"],0,"Die Fahrzeit streut, deshalb braucht die Überwachung Reserve."],["Was zeigt der Signalmonitor des Zwillings?",["den Zustand jedes Signals auf der Anlagenseite und ob es geforct ist","den Programmstatus in TIA","die CPU-Zykluszeit"],0,"Das kennst du seit L01."]],
 aus:[["Welche Reihenfolge entspricht systematischer Fehlersuche?",["Symptom, Vermutung, Prüfschritt, Ursache","Ursache, Prüfschritt, Symptom","Teile tauschen, bis es geht"],0,"Jeder Prüfschritt soll eine Vermutung bestätigen oder ausschließen."],["Womit belegst du im Zwilling eine kürzere Taktzeit bei eigenem Programm?",["mit den Messlinien von einer Endlagenflanke bis zur selben Flanke im nächsten Zyklus","mit den Schrittmarken im Weg-Zeit-Diagramm","mit der CPU-Zykluszeit"],0,"Schrittmarken zeigt das Diagramm nur bei der Portalautomatik des Zwillings."]]},
 L37:{ein:[["Wohin gehören Daten, die mehrere Anlagenteile brauchen?",["in einen Schnittstellen-DB","als globale Merker quer durchs Programm","in die stat-Variablen eines anderen FB"],0,"So bleiben die Bausteine austauschbar und testbar."],["Wer macht die Anlage sicher?",["das SPS-Programm","die Sicherheitstechnik (−KF2, STO)","das HMI"],1,"Das Programm macht sie bedienbar und diagnostizierbar."]],
 aus:[["Was beschreibt das Pflichtenheft?",["wie der Auftragnehmer die Anforderungen umsetzt","was der Kunde will, ohne Lösungsweg","nur die Kosten"],0,"Das Lastenheft beschreibt das Was, das Pflichtenheft das Wie."],["Eure Vorführung am Zwilling entspricht am ehesten …",["einer Werksabnahme (FAT)","einer Abnahme vor Ort (SAT)","einer Wartung"],0,"Die echte Anlage steht noch nicht; ihr prüft beim Hersteller, also virtuell."]]}
})
