// Stil-Check nach Siemens-Styleguide, wächst mit: Eine Regel erscheint erst ab der Übung, in der sie eingeführt und erklärt wird.
// ab = erste Übung, t = Regel, w = warum (ein Satz), q = Siemens-Beleg. Wird von build.mjs eingesetzt (Platzhalter __STIL__).
[
 {ab:"L02", t:"Jeder Ausgang wird an genau einer Stelle im Programm geschrieben.", w:"Schreiben zwei Stellen denselben Ausgang, gewinnt die letzte, und der Fehler zeigt sich nur manchmal.", q:'<a href="https://support.industry.siemens.com/cs/ww/de/view/109478084">Siemens Programmierstyleguide S7-1200/S7-1500</a>'},
 {ab:"L02", t:"Du verwendest symbolische Namen (z. B. <code>\"BG9_Temperatur\"</code>), keine absoluten Adressen wie <code>%I1.0</code> im Code.", w:"Mit Namen ist das Programm lesbar, und eine geänderte Verdrahtung änderst du nur in der Variablentabelle.", q:'<a href="https://support.industry.siemens.com/cs/ww/de/view/81318674">Siemens Programmierleitfaden S7-1200/S7-1500</a>'},
 {ab:"L02", t:"Der Bausteinkopf ist ausgefüllt (Titel, Kommentar, Autor, Version), jedes Netzwerk hat Titel und Kommentar. In SCL schreibst du Kommentare mit <code>//</code>.", w:"Wer den Baustein später öffnet, sieht sofort, wozu er da ist und welcher Stand vorliegt.", q:'<a href="https://support.industry.siemens.com/cs/ww/de/view/109478084">Siemens Programmierstyleguide S7-1200/S7-1500</a>'},
 {ab:"L03", t:"Zustände speicherst du als statische Variable im FB (<code>#stat…</code>), nicht als Merker.", w:"Statische Variablen gehören zur Instanz, der FB bleibt dadurch mehrfach verwendbar und ohne versteckte Abhängigkeiten.", q:'<a href="https://support.industry.siemens.com/cs/ww/de/view/81318674">Siemens Programmierleitfaden S7-1200/S7-1500</a>'},
 {ab:"L03", t:"Namen nach Styleguide: Bausteine beginnen groß (<code>Operation</code>), Variablen in camelCase. Statische Variablen, temporäre Variablen und Instanzen bekommen das Präfix <code>stat</code>, <code>temp</code> oder <code>inst</code>, Eingänge und Ausgänge bekommen kein Präfix. Keine Umlaute.", w:"Am Präfix erkennst du sofort, wo eine Variable gespeichert ist und wie lange sie lebt.", q:'<a href="https://support.industry.siemens.com/cs/ww/de/view/109478084">Siemens Programmierstyleguide S7-1200/S7-1500</a>'},
 {ab:"L03", t:"Flanken (<code>R_TRIG</code>, <code>F_TRIG</code>) rufst du als Multiinstanz im FB auf (<code>#inst…</code>).", w:"So braucht die Flanke keinen eigenen Datenbaustein und keinen globalen Flankenmerker.", q:'<a href="https://support.industry.siemens.com/cs/ww/de/view/109478084">Siemens Programmierstyleguide S7-1200/S7-1500</a>'},
 {ab:"L04", t:"Zeiten rufst du als Multiinstanz im FB auf (<code>#instTimer…</code>), in jedem Zyklus und nicht innerhalb einer IF-Bedingung.", w:"Eine Zeit sieht ihren Eingang nur, wenn sie aufgerufen wird.", q:'<a href="https://support.industry.siemens.com/cs/ww/de/view/81318674">Siemens Programmierleitfaden S7-1200/S7-1500</a>'},
 {ab:"L05", t:"Zähler rufst du ebenfalls als Multiinstanz im FB auf.", w:"Wie bei den Zeiten liegen die Daten dann beim FB, der sie benutzt.", q:'<a href="https://support.industry.siemens.com/cs/ww/de/view/81318674">Siemens Programmierleitfaden S7-1200/S7-1500</a>'},
 {ab:"L07", t:"Bitmuster (Schalterstellungen, Leuchtenmuster, Masken) legst du als <code>Byte</code>, <code>Word</code> oder <code>DWord</code> an, Mengen und Messwerte als <code>Int</code>, <code>DInt</code> oder <code>Real</code>.", w:"Der Datentyp sagt, ob du mit den Bits arbeitest oder mit der Zahl rechnest. TIA lässt Rechenboxen wie ADD nur mit Zahlen zu und wandelt mit IEC-Prüfung Zahl und Bitmuster nicht still um.", q:'<a href="https://support.industry.siemens.com/cs/ww/de/view/109478084">Siemens Programmierstyleguide S7-1200/S7-1500</a>'},
 {ab:"L08", t:"Bitmuster schreibst du als Hex-Konstante mit allen Stellen (<code>16#0F</code>, <code>16#0001</code>).", w:"So siehst du jedes einzelne Bit auf einen Blick und verwechselst kein Muster mit einer Zahl.", q:'<a href="https://support.industry.siemens.com/cs/ww/de/view/109478084">Siemens Programmierstyleguide S7-1200/S7-1500</a>'},
 {ab:"L10", t:"Feste Zahlenwerte legst du als lokale Konstante in GROSSSCHRIFT an (z. B. <code>MAX_TEMP</code>). Ausnahmen in diesem Handbuch: 0 und 1 sowie Schrittnummern als Marken im <code>CASE</code> (ab L17).", w:"Ein Wert mit Namen erklärt sich selbst und wird nur an einer Stelle geändert.", q:'<a href="https://support.industry.siemens.com/cs/ww/de/view/109478084">Siemens Programmierstyleguide S7-1200/S7-1500</a>'},
 {ab:"L03", t:"Ein Baustein bekommt seine Signale über seine Schnittstelle (Eingänge, Ausgänge). Im Baustein greifst du nicht direkt auf PLC-Variablen oder fremde Instanzen zu, verschaltet wird beim Aufruf im OB1.", w:"So siehst du an der Schnittstelle, was der Baustein braucht und liefert, und kannst ihn wiederverwenden.", q:'<a href="https://support.industry.siemens.com/cs/ww/de/view/109478084">Siemens Programmierstyleguide S7-1200/S7-1500</a>'},
 {ab:"L05", t:"Daten, die mehrere Bausteine gemeinsam brauchen, liegen in einem globalen Schnittstellen-DB (<code>PlantData</code>). Du verschaltest ihn im OB1 mit den Schnittstellen der Bausteine, im Baustein selbst greifst du nicht darauf zu.", w:"Gemeinsame Daten an einer Stelle sind leichter zu finden und zu prüfen als verstreute Einzelvariablen.", q:'<a href="https://support.industry.siemens.com/cs/ww/de/view/81318674">Siemens Programmierleitfaden S7-1200/S7-1500</a>'},
 {ab:"L17", t:"Jede <code>CASE</code>-Anweisung hat einen <code>ELSE</code>-Zweig.", w:"Steht die Variable auf einem unerwarteten Wert, landet das Programm in einem festgelegten Zustand statt nichts zu tun.", q:'<a href="https://support.industry.siemens.com/cs/ww/de/view/109478084">Siemens Programmierstyleguide S7-1200/S7-1500</a>'}
]
