// Stil-Check nach Siemens-Styleguide, wächst mit: Eine Regel erscheint erst ab der Übung, in der sie eingeführt und erklärt wird.
// ab = erste Übung, t = Regel, w = warum (ein Satz), q = Siemens-Beleg. Wird von build.mjs eingesetzt (Platzhalter __STIL__).
[
 {ab:"L02", t:"Jeder Ausgang wird an genau einer Stelle im Programm geschrieben.", w:"Schreiben zwei Stellen denselben Ausgang, gewinnt die letzte, und der Fehler zeigt sich nur manchmal.", q:'<a href="https://support.industry.siemens.com/cs/ww/de/view/109478084">Siemens Programmierstyleguide S7-1200/S7-1500</a>'},
 {ab:"L02", t:"Du verwendest symbolische Namen (z. B. <code>\"BG9_Temperatur\"</code>), keine absoluten Adressen wie <code>%I1.0</code> im Code.", w:"Mit Namen ist das Programm lesbar, und eine geänderte Verdrahtung änderst du nur in der Variablentabelle.", q:'<a href="https://support.industry.siemens.com/cs/ww/de/view/81318674">Siemens Programmierleitfaden S7-1200/S7-1500</a>'},
 {ab:"L02", t:"Der Bausteinkopf ist ausgefüllt (Titel, Kommentar, Autor, Version), jedes Netzwerk hat Titel und Kommentar. In SCL schreibst du Kommentare mit <code>//</code>.", w:"Wer den Baustein später öffnet, sieht sofort, wozu er da ist und welcher Stand vorliegt.", q:'<a href="https://support.industry.siemens.com/cs/ww/de/view/109478084">Siemens Programmierstyleguide S7-1200/S7-1500</a>'},
 {ab:"L03", t:"Zustände speicherst du als statische Variable im FB (<code>#stat…</code>), nicht als Merker.", w:"Statische Variablen gehören zur Instanz, der FB bleibt dadurch mehrfach verwendbar und ohne versteckte Abhängigkeiten.", q:'<a href="https://support.industry.siemens.com/cs/ww/de/view/81318674">Siemens Programmierleitfaden S7-1200/S7-1500</a>'},
 {ab:"L03", t:"Namen nach Styleguide: Bausteine beginnen groß (<code>Operation</code>), Variablen in camelCase. Statische Variablen, temporäre Variablen und Instanzen bekommen das Präfix <code>stat</code>, <code>temp</code> oder <code>inst</code>, Eingänge und Ausgänge bekommen kein Präfix. Keine Umlaute.", w:"Am Präfix erkennst du sofort, wo eine Variable gespeichert ist und wie lange sie lebt.", q:'<a href="https://support.industry.siemens.com/cs/ww/de/view/109478084">Siemens Programmierstyleguide S7-1200/S7-1500</a>'},
 {ab:"L03", t:"Flanken (<code>R_TRIG</code>, <code>F_TRIG</code>) rufst du als Multiinstanz im FB auf (<code>#inst…</code>). Steht in einem Programm eine Flankenanweisung mit Flankenmerker (P, N, P=, N=, P_TRIG, N_TRIG), hat jede ihren eigenen Flankenmerker als statische Variable (<code>#stat…Old</code>), nie als Merker.", w:"So braucht die Flanke keinen eigenen Datenbaustein und keinen globalen Merker, und kein Flankenmerker wird von einer zweiten Flanke überschrieben.", q:'<a href="https://support.industry.siemens.com/cs/ww/de/view/109478084">Siemens Programmierstyleguide S7-1200/S7-1500</a>; <a href="https://docs.tia.siemens.cloud/r/de-de/v21/kop-s7-1200-s7-1500-s7-1200-g2/bitverknupfungen-s7-1200-s7-1500-s7-1200-g2/p-operand-auf-positive-signalflanke-abfragen-s7-1200-s7-1500-s7-1200-g2">TIA Portal Hilfe V21: Hinweis zur Adresse des Flankenmerkers</a>'},
 {ab:"L04", t:"Zeiten (TP, TON, TOF, TONR) sind IEC-Zeiten und rufst du als Multiinstanz im FB auf (<code>#inst…</code>, z. B. <code>#instBathReadyDelay</code>), in jedem Zyklus genau einmal und nicht innerhalb einer IF-Bedingung. Für Blinktakte nimmst du einen programmierten Taktgeber wie <code>Clock</code>, keinen Taktmerker.", w:"Eine Zeit sieht ihren Eingang nur, wenn sie aufgerufen wird. Ein Taktmerker hängt an der Hardware-Konfiguration, ein Taktgeber-FB bringt seinen Takt selbst mit.", q:'<a href="https://support.industry.siemens.com/cs/ww/de/view/81318674">Siemens Programmierleitfaden S7-1200/S7-1500, Kap. 3.2.5 Multiinstanzen, 3.4.2 Globaler Speicher, 4.3 Programmieren von Takt Bits</a>'},
 {ab:"L05", t:"Zähler nimmst du als IEC-Zähler (<code>CTU</code>, <code>CTD</code>, <code>CTUD</code>) und rufst sie als Multiinstanz im FB auf (<code>#inst…</code>), in jedem Zyklus und jede Instanz an genau einer Stelle. Legacy-Zähler wie <code>Z_VORW</code> verwendest du nicht.", w:"Die Daten liegen beim FB, der sie benutzt, und ein zweiter Aufruf derselben Instanz würde falsch zählen.", q:'<a href="https://support.industry.siemens.com/cs/ww/de/view/81318674">Siemens Programmierleitfaden S7-1200/S7-1500, Kap. 3.2.5 Multiinstanzen</a>; <a href="https://docs.tia.siemens.cloud/r/de-de/v21/fup-s7-1200-s7-1500-s7-1200-g2/zahler-s7-1200-s7-1500-s7-1200-g2/ctu-vorwarts-zahlen-s7-1200-s7-1500-s7-1200-g2">TIA Portal Hilfe V21: CTU: Vorwärts zählen</a>'},
 {ab:"L05", t:"Die Remanenz stellst du in der Schnittstelle des FB ein, immer <i>Remanent</i> oder <i>Nicht remanent</i>, nie <i>Im IDB setzen</i>.", w:"So gilt die Einstellung für alle Instanzen sichtbar im FB, und laut Siemens erhöht „Im IDB setzen“ die Abarbeitungszeit.", q:'<a href="https://support.industry.siemens.com/cs/ww/de/view/81318674">Siemens Programmierleitfaden S7-1200/S7-1500, Kap. 3.5 Remanenz</a>'},
 {ab:"L07", t:"Bitmuster (Schalterstellungen, Leuchtenmuster, Masken) legst du als <code>Byte</code>, <code>Word</code> oder <code>DWord</code> an, Mengen und Messwerte als <code>Int</code>, <code>DInt</code> oder <code>Real</code>.", w:"Der Datentyp sagt, ob du mit den Bits arbeitest oder mit der Zahl rechnest. TIA lässt Rechenboxen wie ADD nur mit Zahlen zu, ein Bitmuster vergleichst du sinnvoll nur auf gleich oder ungleich, und mit IEC-Prüfung wandelt TIA Zahl und Bitmuster nicht still ineinander um.", q:'<a href="https://support.industry.siemens.com/cs/ww/de/view/109478084">Siemens Programmierstyleguide S7-1200/S7-1500</a>; <a href="https://docs.tia.siemens.cloud/r/de-de/v21/datentypen/binarzahlen/bitfolgen/word">TIA Portal Hilfe V21: WORD</a>'},
 {ab:"L08", t:"Bitmuster (Masken, Startwerte, Vergleichswerte) schreibst du als Hex-Konstante mit allen Stellen des Datentyps: <code>16#0F</code> für ein Byte, <code>16#0001</code> für ein Word.", w:"Jede Hex-Ziffer steht für vier Bits. So siehst du jedes einzelne Bit auf einen Blick und verwechselst kein Muster mit einer Zahl.", q:'<a href="https://cache.industry.siemens.com/dl/files/084/109478084/att_900344/v1/81318674_Programming_Styleguide_DOC_v12_de.pdf">Siemens Programmierstyleguide S7-1200/S7-1500 V1.2, Kap. 4.2.5 Initialisierung in der gebräuchlichen Darstellung</a>'},
 {ab:"L10", t:"Feste Zahlenwerte legst du als lokale Konstante im Bereich Constant an, der Name in GROSSSCHRIFT mit Unterstrichen (z. B. <code>BUFFER_PLACES</code>). Globale Konstanten verwendest du in Bausteinen nicht. Ausnahmen in diesem Handbuch: 0 und 1 sowie Schrittnummern als Marken im <code>CASE</code> (ab L17).", w:"Ein Wert mit Namen erklärt sich selbst, wird nur an einer Stelle geändert, und der Baustein bleibt ohne globale Daten wiederverwendbar.", q:'<a href="https://support.industry.siemens.com/cs/ww/de/view/109478084">Siemens Programmierstyleguide S7-1200/S7-1500, Kap. 4.2.2 Konstanten</a>'},
 {ab:"L03", t:"Ein Baustein bekommt seine Signale über seine Schnittstelle (Eingänge, Ausgänge). Im Baustein greifst du nicht direkt auf PLC-Variablen oder fremde Instanzen zu, verschaltet wird beim Aufruf im OB1.", w:"So siehst du an der Schnittstelle, was der Baustein braucht und liefert, und kannst ihn wiederverwenden.", q:'<a href="https://support.industry.siemens.com/cs/ww/de/view/109478084">Siemens Programmierstyleguide S7-1200/S7-1500</a>'},
 {ab:"L05", t:"Daten, die mehrere Bausteine gemeinsam brauchen, liegen im globalen Datenbaustein <code>PlantData</code>, nicht in Merkern. Du verschaltest ihn im OB1 mit den Schnittstellen der Bausteine, im Baustein selbst greifst du nicht darauf zu. Jede Variable in PlantData hat genau einen Schreiber.", w:"Gemeinsame Daten an einer Stelle sind leichter zu finden und zu prüfen, und die Bausteine bleiben trotzdem unabhängig.", q:'<a href="https://support.industry.siemens.com/cs/ww/de/view/81318674">Siemens Programmierleitfaden S7-1200/S7-1500, Kap. 3.2.6 Globale Datenbausteine</a>; <a href="https://cache.industry.siemens.com/dl/files/084/109478084/att_900344/v1/81318674_Programming_Styleguide_DOC_v12_de.pdf">Siemens Programmierstyleguide S7-1200/S7-1500 V1.2, Kap. 4.1.3 Innerhalb eines Bausteins nur lokale Variablen</a>'},
 {ab:"L17", t:"Jede <code>CASE</code>-Anweisung hat einen <code>ELSE</code>-Zweig.", w:"Steht die Variable auf einem unerwarteten Wert, landet das Programm in einem festgelegten Zustand statt nichts zu tun.", q:'<a href="https://support.industry.siemens.com/cs/ww/de/view/109478084">Siemens Programmierstyleguide S7-1200/S7-1500</a>'}
]
