// Inhalte der 32 Übungen (Lernsituationen). Wird von build.mjs in vorlage.html eingesetzt.
[
/* ================= STUFE 1 ================= */
{id:"L01", st:1, t:"Signale erkunden", sub:"Schließer, Öffner und Forcen", ue:2, vor:"keine", repo:"–", bild:["08-signalmonitor.jpg","Signalmonitor in der Seitenleiste: jeder Eingang lässt sich forcen"],
 einst:"Alles <i>automatisch</i>, Demo ohne SPS genügt.",
 ziele:["jedem Bedienelement Adresse und Signalpegel zuordnen","Schließer und Öffner unterscheiden","drahtbruchsichere Verdrahtung begründen"],
 sig:"BG2 BG4 BG5 BG8 BG9 SF1 SF2 SF4 SA1 SA3 KF2 BG39",
 sit:"Sie übernehmen die Inbetriebnahme einer Verzinnungsanlage. Bevor Sie eine Zeile programmieren, prüfen Sie die Verdrahtung Signal für Signal – der klassische Loop-Check.",
 auf:["Legen Sie eine Pegeltabelle aller Eingänge %I0.0 bis %I2.7 an – mit gekoppelter SPS (Bridge und PLCSIM) als Beobachtungstabelle in TIA, mit der Demo direkt im Signalmonitor des Zwillings.","Betätigen Sie jedes Bedienelement im Zwilling (3D-Pult und Seitenleiste). Notieren Sie den Pegel unbetätigt und betätigt.","Lassen Sie die Demo eine Grundstellung anfahren und notieren Sie, welche Endlagensensoren 1 melden.","Forcen Sie im Signalmonitor −BG9 auf 0 und beschreiben Sie, was die Demo-SPS daraufhin nicht mehr tut."],
 lf:["Warum ist STOP −SF2 ein Öffner, START −SF1 aber ein Schließer?","Was meldet −BG39 am Kühlwassertank bei Drahtbruch, und warum ist das die sichere Seite?","Worin unterscheidet sich Forcen im Signalmonitor des Zwillings vom Steuern einer Variable in TIA?"],
 pr:["Pegeltabelle für alle 24 Eingänge %I0.0 bis %I2.7 vollständig","Grundstellung −BG2, −BG4, −BG5, −BG8 = 1 erkannt","Wirkung von −BG9 = 0 richtig beschrieben"],
 plus:"Erstellen Sie aus <code>signale.csv</code> eine Symboltabelle in Excel mit den Spalten Typ (DI/DQ/AI/AQ), Gerät und Wirkrichtung."},

{id:"L02", st:1, t:"Verknüpfungen", sub:"UND, ODER, NICHT, XOR an Signalen der Anlage", ue:3, vor:"L01", repo:"–", bild:["02-bedienpult.jpg","Meldeleuchten −PF1 bis −PF4 am Bedienpult"],
 einst:"<i>Verzinnen: Portal = SPS</i>, alles andere automatisch. Ihr Programm schaltet nur Meldeleuchten – das Portal bleibt stehen.",
 ziele:["Grundverknüpfungen in FUP und KOP programmieren","Funktionstabellen aufstellen und am Zwilling prüfen","Öffner und Negation sicher unterscheiden"],
 sig:"BG9 BG10 BG40 BG14 BG15 SF1 SF4 PF1 PF2 PF3 PF4",
 sit:"Der Schichtleiter will am Bedienpult auf einen Blick sehen, ob das Zinnbad bereit ist und ein Korb wartet. Außerdem soll ein Lampentest alle Meldeleuchten prüfen, und der Anschlag −MM5 soll sich selbst überwachen: Er darf nie beide oder keine Endlage zugleich melden.",
 tpl:{cap:"Funktionstabelle Endlagen-Plausibilität −MM5", head:["−BG14 zu","−BG15 offen","plausibel (XOR)","Störung"], rows:[["0","0"],["0","1"],["1","0"],["1","1"]], inputs:2},
 auf:["UND: −PF2 „Bad bereit“ leuchtet, wenn Temperatur −BG9 UND Füllhöhe −BG10 in Ordnung sind.","NICHT: −PF3 „Füllhöhe unterschritten“ leuchtet, wenn −BG10 NICHT meldet.","Zuweisung: −PF4 „Korb vorhanden“ zeigt −BG40.","ODER: Lampentest – solange −SF4 gedrückt ist, leuchten alle vier Meldeleuchten, zusätzlich zu ihrer eigentlichen Bedingung.","XOR: Bilden Sie <code>#stopperPlausible</code> := −BG14 XOR −BG15 und füllen Sie die Funktionstabelle aus.","Programmieren Sie jede Verknüpfung einmal in FUP und einmal in KOP und vergleichen Sie die Darstellung."],
 lf:["Warum leuchtet −PF3 bei NICHT −BG10 und nicht einfach bei −BG10 = 0 über einen Öffner?","Welche Verknüpfung entsteht, wenn Sie in KOP zwei Kontakte in Reihe bzw. parallel schalten?","Warum ist XOR für die Endlagen eines Zylinders eine sinnvolle Plausibilitätsprüfung? Welcher Zustand ist während der Bewegung kurz zulässig?"],
 pr:["−BG9 oder −BG10 auf 0 forcen → −PF2 aus","−BG10 auf 0 forcen → −PF3 leuchtet","−SF4 gedrückt → alle Meldeleuchten an, losgelassen → wieder normal","Funktionstabelle XOR vollständig, −BG14 und −BG15 gemeinsam auf 1 forcen → #stopperPlausible = 0"],
 plus:"Erweitern Sie die Plausibilität: Ein Zustand ohne Endlage ist während der Bewegung erlaubt, aber höchstens 2 s – das lösen Sie in L04 mit einer Zeit."},

{id:"L03", st:1, t:"Speichern und Flanken", sub:"RS/SR, Selbsthaltung, R_TRIG und F_TRIG im FB", ue:3, vor:"L02", repo:"–", bild:["02-bedienpult.jpg","START −SF1, STOP −SF2 und Quittieren −SF4 am Bedienpult"],
 einst:"<i>Verzinnen: Portal = SPS</i>, alles andere automatisch. Ihr Programm schaltet nur Meldeleuchten.",
 ziele:["Zustände in einem FB als statische Variablen speichern","setz- und rücksetzdominante Speicher begründet auswählen","Flanken auswerten: Wiederanlaufsperre und Meldung mit Quittierung"],
 sig:"SF1 SF2 SF4 KF2 BG20 PF1 PF5",
 sit:"Am Bedienpult schaltet START die Anlage betriebsbereit, STOP schaltet sie ab. Der Bediener tippt die Taster nur an – die Betriebsbereitschaft −PF1 muss trotzdem bleiben, bis STOP, Not-Halt oder eine Störung kommt. Greift jemand in den Lichtvorhang −BG20, ist das Schutzfeld kurz darauf wieder frei. Die Meldung „Schutzfeld verletzt“ muss aber stehen bleiben, bis der Bediener quittiert hat.",
 tab:{cap:"Speicher und Flanken in TIA (KOP/FUP)", ...T(["Baustein","Verhalten","Typische Anwendung"],[["SR – Eingänge S und R1","Rücksetzen dominant – S und R1 gleichzeitig: Ausgang 0 (der Eingang mit der 1 hat Vorrang)","Betriebsbereitschaft, Störmeldung"],["RS – Eingänge R und S1","Setzen dominant – R und S1 gleichzeitig: Ausgang 1","selten; nur wenn Einschalten Vorrang haben darf"],["R_TRIG","ein Zyklus 1 bei steigender Flanke","Taster genau einmal auswerten, Quittieren"],["F_TRIG","ein Zyklus 1 bei fallender Flanke","Schutzfeld wird verletzt, Freigabe fällt weg"]])},
 auf:["Legen Sie einen FB <code>Operation</code> mit Instanz-DB an. Zustände speichern Sie als statische Variablen (<code>#statReady</code>, <code>#statMsgLightCurtain</code>) – nicht als globale Merker.","Betriebsbereitschaft: Eine steigende Flanke an START −SF1 setzt <code>#statReady</code>. STOP −SF2 (Öffner), −KF2 = 0 oder eine anstehende Meldung setzen zurück – rücksetzdominant. −PF1 zeigt den Zustand.","Wiederanlaufsperre: Wer nach einem Not-Halt den START-Taster gedrückt hält, darf die Anlage nach dem Quittieren nicht einschalten – erst ein neuer Tastendruck. Prüfen Sie, warum das nur mit der Flanke funktioniert.","Meldung mit Quittierung: Fällt −BG20 „Schutzfeld frei“ ab (F_TRIG), wird <code>#statMsgLightCurtain</code> gesetzt. Der Leuchttaster −PF5 leuchtet als Quittieraufforderung (blinken lassen Sie ihn in L04). Zurückgesetzt wird nur mit einer steigenden Flanke an −SF4 UND wenn −BG20 wieder frei ist.","Bauen Sie die Betriebsbereitschaft zum Vergleich einmal als klassische Selbsthaltung in KOP (Parallelkontakt am Ausgang)."],
 lf:["Warum muss der Zustand gespeichert werden, obwohl der Bediener START gedrückt hat? Was würde ohne Speicher passieren?","Was passiert bei RS und bei SR, wenn START und STOP gleichzeitig gedrückt werden? Welche Variante ist für eine Maschine richtig – und warum?","Warum wird STOP als Öffner verdrahtet, und wie fragen Sie ihn deshalb am Rücksetzeingang ab? Was passiert bei Drahtbruch?","Warum gehören Zustände als statische Variablen in einen FB statt als Merker in den globalen Speicher?"],
 pr:["START antippen → −PF1 an und bleibt an","START und STOP gleichzeitig → −PF1 aus","−SF2 auf 0 forcen (Drahtbruch) → Anlage nicht einschaltbar","Not-Halt, START gedrückt halten, quittieren → Anlage bleibt aus, erst neuer Tastendruck schaltet ein","Durchgriff Lichtvorhang → −PF5 blinkt weiter, nachdem das Schutzfeld wieder frei ist","Quittieren während −BG20 noch unterbrochen ist → Meldung bleibt"],
 plus:"Machen Sie aus der Meldung mit Quittierung einen eigenen FB <code>Message</code> (Eingänge Signal und Quittieren, Ausgang Meldung). Sie brauchen ihn in fast jeder späteren Übung – je Meldung eine Instanz."},

{id:"L04", st:1, t:"Zeiten", sub:"TON, TOF, TP und ein Blinker", ue:4, vor:"L03", repo:"–", bild:["09-weg-zeit-diagramm.jpg","Weg-Zeit-Diagramm – Zeiten sichtbar machen"],
 einst:"<i>Verzinnen: Portal = SPS</i>, alles andere automatisch.",
 ziele:["Einschalt-, Ausschalt- und Impulszeiten einsetzen","Impulsdiagramme zeichnen und am Zwilling prüfen","Signale entprellen und einen Taktgeber bauen"],
 sig:"BG9 BG10 BG40 SF1 SF4 PF2 PF3 PF4 PF1 BG14 BG15",
 sit:"Später taucht das Portal den Korb genau 10 s ins Zinn – Zeiten sind das Herz jeder Ablaufsteuerung. Hier üben Sie sie an Meldeleuchten: Die Badtemperatur soll erst als „bereit“ gelten, wenn sie stabil ansteht, und ein abgefahrener Korb soll noch kurz angezeigt werden.",
 tab:{cap:"IEC-Zeiten", ...T(["Zeit","Ausgang Q","Anwendung an der Anlage"],[["TON Einschaltverzögerung","wird PT nach steigender Flanke von IN 1, solange IN 1 bleibt","Tauchzeit, Entprellen, Überwachungszeit"],["TOF Ausschaltverzögerung","sofort 1, nach fallender Flanke von IN noch PT lang 1","Nachlauf eines Bandes, Nachleuchten"],["TP Impuls","PT lang 1 ab steigender Flanke, unabhängig von IN","Kamera-Trigger, Ausblasimpuls"]])},
 auf:["TON: −PF2 „Bad bereit“ erst, wenn −BG9 UND −BG10 seit 3 s ununterbrochen anstehen (Entprellen) – das erweitert die Bedingung aus L02.","TOF: −PF4 leuchtet nach dem Abtransport des Korbs (−BG40 fällt ab) noch 5 s nach.","TP: Bauen Sie den Lampentest aus L02 um – ein Druck auf −SF4 lässt alle Meldeleuchten genau 2 s leuchten, auch wenn der Taster länger gedrückt wird. Jede Leuchte behält dabei genau eine Schreibstelle.","Blinker: Bauen Sie aus zwei TON einen Takt 0,5 s an / 0,5 s aus und lassen Sie damit −PF3 bei fehlender Füllhöhe blinken. Kapseln Sie den Blinker als FB <code>Clock</code> mit dem Eingang frequency – so empfiehlt es der Siemens-Programmierleitfaden statt eines Taktmerkers.","Ergänzen Sie aus L02 die Endlagen-Plausibilität −MM5: Keine Endlage länger als 2 s → Störung.","Zeichnen Sie für TON, TOF und TP je ein Impulsdiagramm (Vorlage Trend unter Planen)."],
 lf:["Welche Zeit nehmen Sie, um ein kurzes Flackern eines Sensors zu unterdrücken – und warum?","Was zeigt der Ausgang ET einer Zeit an, und wofür können Sie ihn nutzen?","Warum empfiehlt Siemens einen eigenen Taktgeber-Baustein statt des Taktmerkers der CPU?"],
 pr:["−BG9 forcen: unter 3 s zurück → −PF2 bleibt aus, länger → an","−BG40 fällt ab → −PF4 noch 5 s an","−SF4 lange gedrückt → Lampentest genau 2 s","−PF3 blinkt gleichmäßig 1 Hz bei −BG10 = 0","Beide Endlagen −MM5 auf 0 forcen → nach 2 s Störung"],
 plus:"Messen Sie mit ET, wie lange ein Korb am Anschlag liegt (−BG40), und zeigen Sie den letzten Wert in einer Beobachtungstabelle an."},

{id:"L05", st:1, t:"Zähler", sub:"CTU, CTD, CTUD an Körben und Teilen", ue:3, vor:"L04", repo:"–", bild:["06-pruefstation.jpg","Prüfstation: i.O.- und n.i.O.-Teile zählen"],
 einst:"<i>Verzinnen: Portal = automatisch</i>, <i>Band, Anschlag, Vereinzeler = automatisch</i>. So laufen Körbe durch die Anlage, und Ihr Programm zählt nur mit.",
 ziele:["Vorwärts-, Rückwärts- und Vor-/Rückwärtszähler einsetzen","Zähler mit Flanken richtig ansteuern und zurücksetzen","Zählerstände sinnvoll auswerten und anzeigen"],
 sig:"BG40 BG12 BG11 BG28 BG29 SF4 PF3 PF4",
 sit:"Die Produktion will wissen, wie viele Körbe heute verzinnt wurden, wie viele gerade auf Band 1 warten und wie viele Kabelschuhe gut oder schlecht waren. Ihr Programm zählt mit, ohne in den Ablauf einzugreifen.",
 tab:{cap:"IEC-Zähler", ...T(["Zähler","Eingänge","Ausgänge"],[["CTU","CU vorwärts, R zurücksetzen, PV Vorgabe","Q = 1 ab CV ≥ PV, CV Zählerstand"],["CTD","CD rückwärts, LD laden mit PV","Q = 1 bei CV ≤ 0"],["CTUD","CU, CD, R, LD, PV","QU, QD, CV"]])},
 auf:["CTU Tageszähler: Jeder neue Korb am Anschlag (steigende Flanke −BG40) zählt +1. Zurücksetzen mit −SF4, aber nur wenn die Taste 3 s gehalten wird (TON aus L04). Ein kurzer Druck bleibt Quittieren bzw. Lampentest.","Wartungshinweis: Nach je 10 Körben blinkt −PF3 „Zinnstand prüfen“, bis quittiert wird.","CTUD Pufferbelegung Band 1: +1 bei Korb am Bandanfang (−BG12), −1 wenn ein Korb den Übergabeplatz erreicht (−BG11). Zeigen Sie die Anzahl wartender Körbe in einer Beobachtungstabelle.","Zählen Sie getrennt i.O.-Teile (−BG28) und n.i.O.-Teile (−BG29) der Prüfstation. Je Korb sind es 36 Teile."],
 lf:["CTU wertet CU selbst als Flanke aus. Warum zählt dagegen eine selbst programmierte Addition #statCount := #statCount + 1 ohne Flanke falsch?","Was passiert mit dem Zählerstand nach einem Neustart der CPU – und wie verhindern Sie das (Stichwort remanent)?","Warum kann die Pufferbelegung negativ werden, und wie fangen Sie das ab?"],
 pr:["Fünf Körbe durchlaufen lassen → Tageszähler = 5","−SF4 kurz → kein Reset, 3 s → Reset","Nach 10 Körben blinkt −PF3","Pufferbelegung stimmt mit der Zahl der Körbe auf Band 1 überein","Summe i.O. + n.i.O. = 36 je Korb"],
 plus:"Berechnen Sie die Ausschussquote in Prozent (vorbereitend für L06: Datentypen beachten!)."},

{id:"L06", st:1, t:"Vergleichen und Rechnen", sub:"Datentypen, Analogwert, Überlauf", ue:3, vor:"L05", repo:"–", bild:["04-zinnbad.jpg","Zinnbad: Temperatur −BT1 als Analogwert"],
 einst:"<i>Verzinnen: Portal = SPS</i>, alles andere automatisch.",
 ziele:["Datentypen Bool, Int, DInt, Real und Time sicher wählen","Analogwerte lesen, umrechnen und vergleichen","Überlauf und Rundungsfehler erkennen und vermeiden"],
 sig:"BT1 BL1 BG9 PF2 PF3",
 sit:"Der Schalter −BG9 meldet nur „ab 250 °C“. Für die Qualität zählt aber, ob das Zinn wirklich zwischen 270 und 290 °C liegt. Die Analogbaugruppe liefert die Temperatur als Zahl von 0 bis 27648 – Ihr Programm rechnet sie selbst in Grad um.",
 tab:{cap:"Datentypen an der Anlage", ...T(["Typ","Bereich","Beispiel aus der Anlage"],[["Bool","0 / 1","−BG9 Temperatur erreicht"],["Int","−32768 … 32767","−BT1 %IW64, 0 … 27648"],["DInt","± 2,1 Milliarden","Zwischenergebnis 27648 × 400"],["Real","Gleitkomma","Temperatur 281,7 °C"],["Time","T#10S","Tauchzeit"]])},
 auf:["Lesen Sie −BT1 (%IW64) in eine Int-Variable und beobachten Sie den Rohwert, während die Temperatur steigt.","Rechnen Sie in °C um: Temperatur = Rohwert × 400 / 27648. Machen Sie es zuerst bewusst in Int – was passiert? – und dann richtig in DInt und in Real.","Bereichsvergleich: −PF2 leuchtet nur, wenn 270 °C ≤ Temperatur ≤ 290 °C (IN_RANGE oder zwei Vergleicher). Das ersetzt die Bedingung mit −BG9 aus L04 – −BG10 und die 3 s bleiben.","−PF3 meldet „Zinnstand niedrig“, wenn −BL1 (%IW66) unter 40 % liegt – vergleichen Sie mit −BG10.","Rechnen Sie aus dem Korbzähler von L05 die verzinnten Kabelschuhe aus (36 je Korb)."],
 lf:["Warum liefert 27648 × 400 in Int ein falsches Ergebnis? Wie groß wäre es wirklich?","Wann ist Real nötig, wann reicht DInt mit sinnvoller Einheit (z. B. Zehntelgrad)?","Warum vergleicht man Real-Werte nie auf Gleichheit?"],
 pr:["Rohwert 13824 (forcen) → 200 °C","Int-Rechnung zeigt den Überlauf, DInt und Real rechnen richtig","Temperatur im Bereich → −PF2 an, darunter und darüber aus","−BL1 unter 40 % → −PF3 an, Vergleich mit −BG10 dokumentiert"],
 plus:"Schreiben Sie eine Funktion ScaleAnalog (Rohwert, Min, Max → Real) und vergleichen Sie sie mit NORM_X und SCALE_X, die Sie in L23 einsetzen."},

{id:"L07", st:1, t:"Grundstellung und Freigabe", sub:"Verknüpfen, melden, strukturieren", ue:3, vor:"L06", repo:"1", bild:["02-bedienpult.jpg","Bedienpult mit Meldeleuchten −PF1 bis −PF4"],
 einst:"<i>Verzinnen: Portal = SPS</i>, alles andere automatisch.",
 ziele:["Verknüpfungen aus mehreren Bedingungen bilden","Meldeleuchten richtig ansteuern","das Programm in FC und Netzwerke gliedern"],
 sig:"BG2 BG4 BG5 BG8 BG9 BG10 KF2 BG40 PF2 PF3 PF4",
 sit:"Die Anlage darf nur starten, wenn das Portal in Grundstellung steht, das Zinn heiß genug ist, genug Zinn im Bad ist und das Sicherheitsrelais freigibt.",
 auf:["Bilden Sie in einem FC <code>StartRelease</code> die Ausgangsparameter <code>#homePosition</code> und <code>#readyToStart</code>.","Steuern Sie die Meldeleuchten an: −PF2 Temperatur ok, −PF3 Füllhöhe <b>unterschritten</b> (Achtung: Negation), −PF4 Korb vorhanden.","Dokumentieren Sie die Verknüpfung als Funktionstabelle und als FUP."],
 lf:["Warum leuchtet −PF3 bei fehlender Füllhöhe und nicht bei vorhandener?","Welche Bedingung gehört in die Freigabe, welche nur in die Startbedingung des ersten Schritts?"],
 pr:["Jede Grundstellungs-Endlage einzeln auf 0 forcen → #homePosition = 0","−BG9 auf 0 forcen → −PF2 aus, kein Start möglich","−BG10 auf 0 forcen → −PF3 leuchtet","Not-Halt betätigt → #readyToStart = 0"],
 plus:"−PF3 soll bei unterschrittener Füllhöhe mit 1 Hz blinken – mit dem Blinker aus L04."},

{id:"L08", st:1, t:"Handbetrieb", sub:"Zylinder einzeln verfahren – Tippen und gespeicherte Stellung", ue:3, vor:"L07", repo:"4", bild:["03-schaltschrank.jpg","Tableau Handbetrieb an der Schaltschranktür"],
 einst:"<i>Verzinnen: Portal = SPS</i> und <i>Band, Anschlag, Vereinzeler = SPS</i>, alles andere automatisch. So schaltet nur Ihr Programm den Anschlag −MM5 über −MB9; das Band bleibt stehen, solange Ihr Programm es nicht einschaltet – im Handbetrieb gewollt. Die Handtaster finden Sie auf dem Tableau an der Schaltschranktür.",
 ziele:["jeden Handtaster seinem Ventil und seiner Endlage zuordnen","bistabile und monostabile Ventile im Handbetrieb richtig ansteuern","Gefahren eines Handbetriebs ohne Verriegelung erkennen"],
 sig:"SA3 PF7 SF11 SF12 SF13 SF14 SF15 SF16 SF17 SF18 SF19 SF20 MB1 MB2 MB3 MB4 MB5 MB6 MB7 MB8 MB9",
 sit:"Bevor es einen Automatikablauf gibt, will der Inbetriebnehmer jede Bewegung einzeln fahren: Schaltet das richtige Ventil, kommt die richtige Endlage, sind die Drosseln sinnvoll eingestellt? Dafür bekommt die Anlage einen Handbetrieb. Mit dem Wahlschalter −SA3 an der Schaltschranktür auf HAND wirken die Handtaster des Tableaus.",
 tab:{cap:"Handtaster, Ventile, Endlagen", ...T(["Bewegung","Taster","Ventil","Endlage","Ventiltyp"],[["−MM1 einhängen / lösen","−SF11 / −SF12","−MB1 / −MB2","−BG1 / −BG2","5/2 bistabil"],["−MM2 senken / anheben","−SF13 / −SF14","−MB3 / −MB4","−BG4 / −BG3","5/2 bistabil"],["−MM3 zum Bad / zum Band","−SF15 / −SF16","−MB5 / −MB6","−BG6 / −BG5","5/2 bistabil"],["−MM4 abdecken / öffnen","−SF17 / −SF18","−MB7 / −MB8","−BG8 / −BG7","5/2 bistabil"],["−MM5 Anschlag öffnen / schließen","−SF19 / −SF20","−MB9","−BG15 / −BG14","5/2 monostabil, Feder schließt"]])},
 auf:["Legen Sie einen FB <code>Manual</code> an. Er wirkt nur, solange −SA3 auf HAND steht; −PF7 zeigt den Handbetrieb an.","Bistabile Ventile (−MM1 bis −MM4) im Tippbetrieb: Die Spule ist nur angesteuert, solange der Taster gedrückt ist.","Monostabiles Ventil −MB9 (Anschlag −MM5): −SF19 öffnet, −SF20 schließt. Speichern Sie die gewünschte Stellung als statische Variable <code>#statStopperOpen</code> – ohne Signal schließt die Feder sofort.","Gegentaster: Werden beide Taster einer Bewegung zugleich gedrückt, wird keine Spule angesteuert.","Schreiben Sie jeden Ausgang an genau einer Stelle im Programm. In L11 wird daraus die Befehlsausgabe.","Fahren Sie bewusst eine gefährliche Kombination, z. B. −MM3 mit abgesenktem Korb. Beobachten Sie in der 3D-Ansicht und der Ereignisliste, was passiert – das ist der Auftrag für L09."],
 lf:["Warum genügt bei einem bistabilen Ventil Tippen, beim monostabilen −MB9 aber nicht?","Was passiert mit einem bistabilen Ventil, wenn beide Spulen gleichzeitig angesteuert werden?","Ein bistabiles Ventil wird nur angetippt – warum fährt der Zylinder trotzdem bis in die Endlage, und was bedeutet das für den Handbetrieb?","Welche Bewegungen dürfen in welcher Lage nicht gefahren werden? Sammeln Sie für L09."],
 pr:["Jede Bewegung fährt mit ihrem Taster und meldet die richtige Endlage","−SA3 auf AUTO → Handtaster wirkungslos, −PF7 aus","Beide Gegentaster gleichzeitig → keine Spule angesteuert","−MM5 bleibt nach −SF19 offen, schließt mit −SF20","Tabelle Taster – Ventil – Endlage vollständig"],
 plus:"Ergänzen Sie für das HMI eine Seite Handbetrieb mit je zwei Schaltflächen und den Endlagen jeder Bewegung – die Befehle laufen über dieselben Variablen wie die Taster."},

{id:"L09", st:1, t:"Verriegelungen", sub:"Kollisionen im Handbetrieb ausschließen", ue:3, vor:"L08", repo:"4", bild:["03-schaltschrank.jpg","Tableau Handbetrieb an der Schaltschranktür"],
 einst:"<i>Verzinnen: Portal = SPS</i> und <i>Band, Anschlag, Vereinzeler = SPS</i>, alles andere automatisch. So schaltet nur Ihr Programm den Anschlag −MM5 über −MB9; das Band bleibt stehen, solange Ihr Programm es nicht einschaltet – im Handbetrieb gewollt.",
 ziele:["Verriegelungen aus Kollisionsgefahren ableiten","Freigaben je Bewegung als eigene Bedingung programmieren","Verriegelungen systematisch prüfen und dokumentieren"],
 sig:"SA3 PF7 SF11 SF12 SF13 SF14 SF15 SF16 SF17 SF18 SF19 SF20 BG2 BG3 BG4 BG5 BG6 BG7 BG8 BG14 BG15 BG40",
 sit:"Nach einer Störung hängt der Korb über dem Bad. Der Instandhalter muss die Zylinder einzeln fahren können – ohne das Portal zu beschädigen. Ihr Handbetrieb aus L08 erlaubt bisher jede Bewegung in jeder Lage.",
 tab:{cap:"Mindest-Verriegelungen (vom Betreiber vorgegeben)", ...T(["Bewegung","Nur erlaubt, wenn"],[
  ["−MM3 zum Bad / zum Band","Korb angehoben (−BG3)"],["−MM2 senken","über dem Band (−BG5) oder über dem Bad bei offener Abdeckung (−BG6 und −BG7)"],["−MM1 lösen","abgesenkt (−BG4) und über dem Band (−BG5)"],["−MM4 abdecken","nicht, wenn der Korb über dem Bad hängt und nicht oben ist"]])},
 auf:["Erstellen Sie eine Gefährdungsmatrix: Welche Bewegung darf in welcher Lage nicht ausgeführt werden? Prüfen Sie jede Zeile am Zwilling.","Bilden Sie je Bewegung eine Freigabe, z. B. <code>#releaseToBath</code> := −BG3 – in einem eigenen Baustein <code>Interlock</code>, getrennt vom Handbetrieb.","Der Handbetrieb fährt nur noch, wenn Taster UND Freigabe anstehen. Fehlt die Freigabe, blinkt −PF7.","Ergänzen Sie die Verriegelungen, die in der Tabelle noch fehlen: Anschlag −MM5 und Anheben bzw. Absenken am Übergabeplatz."],
 lf:["Warum braucht −MM2 zum Absenken über dem Bad zwei Bedingungen, über dem Band nur eine?","Warum verriegeln Sie auf die gemeldete Endlage (z. B. −BG3) und nicht auf den zuletzt gegebenen Befehl „anheben“?","Welche Verriegelung fehlt in der Tabelle noch? (Tipp: Anschlag −MM5 und Anheben am Übergabeplatz)"],
 pr:["Jede Verriegelung einzeln geprüft: Taster in verbotener Lage → keine Bewegung","Freigabe fehlt → −PF7 blinkt","Sensor der Freigabe auf 0 forcen (z. B. −BG3) → zugehöriger Taster wirkungslos","Gefährdungsmatrix vollständig und von der Lehrkraft abgezeichnet"],
 plus:"Zeigen Sie auf dem HMI zu jeder gesperrten Bewegung, welche Bedingung fehlt – so findet der Instandhalter den Grund ohne Programmiergerät."},

/* ================= STUFE 2 ================= */
{id:"L10", st:2, t:"Betriebsarten HAND und AUTO", sub:"Betriebsartenteil – umschalten, ohne dass sich etwas bewegt", ue:3, vor:"L09", repo:"3, 4", bild:["03-schaltschrank.jpg","Wahlschalter −SA3 Hand / Auto und Leuchte −PF7 an der Schaltschranktür"],
 einst:"<i>Verzinnen: Portal = SPS</i> und <i>Band, Anschlag, Vereinzeler = SPS</i>, alles andere automatisch. So schaltet nur Ihr Programm den Anschlag −MM5 über −MB9; das Band bleibt stehen, solange Ihr Programm es nicht einschaltet – im Handbetrieb gewollt.",
 ziele:["einen Betriebsartenteil mit sich gegenseitig ausschließenden Betriebsarten programmieren","Betriebsarten stoßfrei wechseln: der Wechsel selbst löst keine Bewegung aus","Bedingungen für AUTO festlegen: Grundstellung, Freigabe, kein Not-Halt"],
 sig:"SA3 PF7 PF1 SF1 SF2 KF2 BG2 BG4 BG5 BG8",
 sit:"Neben den Handbetrieb aus L08 kommt bald eine Automatik. Bevor der erste Automatikschritt programmiert wird, legen Sie fest, wer die Anlage wann führt: −SA3 an der Schaltschranktür wählt HAND oder AUTO. Es darf nie beides zugleich aktiv sein, und das Umschalten selbst darf nichts bewegen.",
 tab:{cap:"Betriebsarten der Verzinnungsanlage", ...T(["Betriebsart","aktiv, wenn","Wirkung"],[["HAND","−SA3 = 1 und −KF2 gibt frei","Handtaster wirken über die Verriegelungen, die Automatik ruht, −PF7 leuchtet"],["AUTO","−SA3 = 0 und −KF2 gibt frei","Automatik darf auf START hin arbeiten, Handtaster wirkungslos; ohne Grundstellung blinkt −PF1"],["keine","−KF2 = 0 (Not-Halt, Schutzfeld)","alle Befehle gelöscht; nach dem Quittieren bewegt sich nichts von selbst"]])},
 auf:["Legen Sie einen FB <code>ModeSelect</code> an, der <code>#statModeManual</code> und <code>#statModeAuto</code> bildet. Prüfen Sie im Programm, dass nie beide 1 sind.","Bei −KF2 = 0 sind beide Betriebsarten 0. Nach dem Quittieren wird die gewählte Betriebsart wieder aktiv, aber nichts bewegt sich selbstständig.","AUTO ist erst startbereit, wenn die Grundstellung aus L07 vorliegt. Sonst blinkt −PF1 mit 1 Hz.","Legen Sie fest, was mit der gespeicherten Handstellung des Anschlags −MM5 beim Wechsel nach AUTO geschieht. Fällt sie ab, schließt der Anschlag – eine Bewegung, die niemand befohlen hat. Entscheiden und begründen Sie.","Zeichnen Sie die Betriebsarten als Zustandsdiagramm mit allen Übergängen und Bedingungen."],
 lf:["Warum müssen sich Betriebsarten gegenseitig ausschließen? Was könnte sonst passieren?","Warum darf ein Betriebsartenwechsel keine Bewegung auslösen?","Warum gehört die Grundstellung in die Bedingung für AUTO, aber nicht für HAND?","Warum sitzt der Wahlschalter HAND / AUTO an der Schaltschranktür und nicht am Bedienpult?"],
 pr:["−SA3 auf HAND → #statModeManual = 1, #statModeAuto = 0, −PF7 an","Umschalten in jeder Lage → keine unbefohlene Bewegung (Verhalten von −MM5 wie festgelegt)","AUTO ohne Grundstellung → −PF1 blinkt, kein Start möglich","Not-Halt → beide Betriebsarten 0; nach dem Quittieren fährt nichts","Zustandsdiagramm stimmt mit dem Programm überein"],
 plus:"Zeigen Sie die aktive Betriebsart auf dem HMI und protokollieren Sie jeden Wechsel mit Uhrzeit in einer Ereignisliste."},

{id:"L11", st:2, t:"Befehlsausgabe", sub:"Hand und Automatik zusammenführen – jeder Ausgang genau einmal", ue:3, vor:"L10", repo:"4", bild:["03-schaltschrank.jpg","Ventilinsel und Ausgänge im Schaltschrank"],
 einst:"<i>Verzinnen: Portal = SPS</i> und <i>Band, Anschlag, Vereinzeler = SPS</i>, alles andere automatisch. So schaltet nur Ihr Programm den Anschlag −MM5 über −MB9; das Band bleibt stehen, solange Ihr Programm es nicht einschaltet – im Handbetrieb gewollt.",
 ziele:["das Programm in Betriebsartenteil, Ablaufteil und Befehlsausgabe gliedern","jeden Ausgang an genau einer Stelle zuweisen und Doppelzuweisungen finden","Verriegelungen so anordnen, dass sie in jeder Betriebsart wirken"],
 sig:"MB1 MB2 MB3 MB4 MB5 MB6 MB7 MB8 MB9 SA3 PF7",
 sit:"Bisher schaltet Ihr Handbetrieb die Ventile selbst. Sobald in L12 die Schrittkette dazukommt, liegt es nahe, dieselben Ventile dort noch einmal zuzuweisen. Dann gewinnt die letzte Zuweisung im Zyklus, die erste ist wirkungslos – im Handbetrieb bewegt sich plötzlich nichts mehr, oder die Kette hängt. Deshalb bekommt die Anlage eine Befehlsausgabe: Sie ist die einzige Stelle, die Ventile schreibt.",
 tab:{cap:"Gliederung einer Ablaufsteuerung", ...T(["Teil","Baustein","liefert"],[["Betriebsartenteil","FB ModeSelect (L10)","#statModeManual, #statModeAuto"],["Handbetrieb","FB Manual (L08)","Handbefehl je Bewegung"],["Ablaufteil","FB Tinning (ab L12)","Auto-Befehl je Bewegung"],["Verriegelungen","Interlock (L09)","Freigabe je Bewegung"],["Befehlsausgabe","FB CommandOutput","einzige Zuweisung an −MB1 … −MB9"]])},
 auf:["Öffnen Sie in TIA die Querverweisliste der Ausgänge %Q0.0 bis %Q2.2 und notieren Sie jede Stelle, an der ein Ausgang geschrieben wird.","Ändern Sie den Handbetrieb: Er liefert nur noch Handbefehle (z. B. <code>#manLower</code>), keine Ausgänge.","Legen Sie einen FB <code>CommandOutput</code> an. Je Ventil genau eine Zuweisung: Ventil := ((Handbefehl UND HAND) ODER (Auto-Befehl UND AUTO)) UND Freigabe.","Verknüpfen Sie die Freigaben aus <code>Interlock</code> (L09) in der Befehlsausgabe statt im Handbetrieb. Damit gelten sie in HAND und AUTO.","Bistabile Ventile: Kommen Befehle für beide Spulen zugleich, wird keine Spule angesteuert.","Testen Sie die Auto-Seite schon jetzt ohne Kette: Setzen Sie die Auto-Befehle in einer Beobachtungstabelle."],
 lf:["Ein Ausgang wird in Netzwerk 3 auf 1 und in Netzwerk 12 auf 0 geschrieben. Was sieht das Ventil – und warum ist dieser Fehler so schwer zu finden?","Warum gehören Verriegelungen in die Befehlsausgabe und nicht in den Handbetrieb oder in die Schrittkette?","Welche Vorteile hat es für Diagnose, Erweiterung und Test, wenn Hand und Automatik nur Befehle liefern?"],
 pr:["Querverweisliste: jedes Ventil −MB1 bis −MB9 hat genau eine Schreibstelle","HAND: Auto-Befehl in der Beobachtungstabelle gesetzt → keine Bewegung","AUTO: Handtaster betätigt → keine Bewegung","AUTO: Auto-Befehl −MM3 zum Bad bei abgesenktem Korb → Verriegelung sperrt","Beide Spulen eines bistabilen Ventils nie gleichzeitig 1"],
 plus:"Kapseln Sie eine Bewegung als FB <code>Cylinder</code> (je Zylinder eine Multiinstanz) mit Befehlen, Freigaben, Endlagen und Ventilausgängen. In L17 kommt die Überwachungszeit dazu."},

{id:"L12", st:2, t:"Schrittkette Verzinnen", sub:"Automatik als GRAFCET entwerfen und umsetzen", ue:6, vor:"L11", repo:"2", bild:["04-zinnbad.jpg","Portal über dem Zinnbad mit −MM1 bis −MM4"],
 einst:"<i>Verzinnen: Portal = SPS</i>, alles andere automatisch (Band, Anschlag, Vereinzeler wieder <i>automatisch</i>). Den Anschlag −MM5 öffnet hier das Bandmodul; Ihr Befehl für −MB9 wirkt erst wieder ab L16.",
 ziele:["eine Ablaufsteuerung als GRAFCET nach DIN EN 60848 entwerfen","Schritte als statische Bool-Variablen im FB (Setzen/Rücksetzen) oder als CASE-Anweisung in SCL umsetzen","Schritt, Transition und Aktion unterscheiden"],
 sig:"SF1 SA3 KF2 MB1 MB2 MB3 MB4 MB5 MB6 MB7 MB8 BG1 BG2 BG3 BG4 BG5 BG6 BG7 BG8 BG15 BG40",
 sit:"Ein Korb liegt am Anschlag (−BG40). Das Portal soll ihn auf START einmal komplett verzinnen. Tauch- und Abtropfzeit betragen je 10 s; einstellbar sind sie unter <i>Prozess</i> von 2 bis 30 s.",
 tab:{cap:"Soll-Ablauf", ...T(["Schritt","Aktion","Ventil","Weiter, wenn"],[
  ["1","Initialschritt, warten","–","startbereit und START"],["2","Korb einhängen","−MB1","−BG1 und Anschlag offen −BG15"],["3","Anheben","−MB4","−BG3"],["4","Zum Zinnbad","−MB5","−BG6"],["5","Bad öffnen","−MB8","−BG7"],["6","Tauchen","−MB3","−BG4 und Tauchzeit abgelaufen"],["7","Anheben, abtropfen","−MB4","−BG3 und Abtropfzeit abgelaufen"],["8","Bad abdecken, zurück zum Band","−MB7 und −MB6","−BG8 und −BG5"],["9","Absenken","−MB3","−BG4"],["10","Korb lösen","−MB2","−BG2, zurück zu Schritt 1"]])},
 auf:["Zeichnen Sie den GRAFCET mit Schritten, Transitionen und Aktionen.","Programmieren Sie die Kette in einem FB <code>Tinning</code>. Variante A: je Schritt eine statische Bool-Variable mit Setzen/Rücksetzen in FUP. Variante B: <code>CASE #statStep OF</code> in SCL.","Die Aktionen setzen nur die Auto-Befehle der Befehlsausgabe aus L11 – kein Schritt schreibt selbst einen Ausgang. Die Kette läuft nur in AUTO.","Die Zeiten in Schritt 6 und 7 laufen erst ab Erreichen der Endlage (<code>TON</code> mit Eingang Schritt UND Endlage)."],
 lf:["Warum starten die Zeiten in Schritt 6 und 7 erst ab Endlage und nicht beim Schrittwechsel?","Warum darf in Schritt 8 gleichzeitig abgedeckt und zurückgefahren werden?","Was passiert mit dem Korb, wenn Sie in Schritt 2 einhängen und anheben, bevor −BG15 meldet?"],
 pr:["Ein Zyklus läuft vollständig, die Ereignisliste meldet keinen „Korb mangelhaft“","Weg-Zeit-Diagramm zeigt die Bewegungen in der Reihenfolge der Tabelle","Tauchzeit auf 5 s geändert → Programm hält sich daran (Sollwert als Variable)","−BG7 auf 0 forcen → Kette bleibt in Schritt 5 stehen","Querverweisliste: Ventile weiterhin nur in der Befehlsausgabe geschrieben"],
 plus:"Setzen Sie dieselbe Kette in S7-GRAPH um und vergleichen Sie die Diagnose im HMI."},

{id:"L13", st:2, t:"Dauer- und Einzelzyklus", sub:"Zyklusende abwarten, START als Flanke", ue:3, vor:"L12", repo:"3", bild:["02-bedienpult.jpg","Wahlschalter −SA1 Dauerbetrieb / Einzelzyklus am Bedienpult"],
 einst:"<i>Verzinnen: Portal = SPS</i>, alles andere automatisch.",
 ziele:["Dauer- und Einzelzyklus im Betriebsartenteil umsetzen","START als Flanke auswerten","„Zyklusende abwarten“ umsetzen"],
 sig:"SA1 SF1 SF2 PF1 KF2",
 sit:"Die Automatik aus L12 läuft genau einen Zyklus. Der Betreiber will in AUTO zwei Ablaufarten, gewählt mit −SA1 am Bedienpult. Dauerbetrieb: Zyklus um Zyklus, bis STOP gedrückt wird; der laufende Korb wird fertig. Einzelzyklus: genau ein Zyklus je START.",
 auf:["Erweitern Sie den Betriebsartenteil aus L10 um die statische Variable <code>#statContinuous</code>: setzen mit positiver Flanke START bei −SA1 = Dauerbetrieb, rücksetzen mit STOP, Wechsel auf Einzelzyklus, Wechsel auf HAND oder Not-Halt.","Die Transition 1 → 2 lautet: AUTO UND startbereit UND (<code>#statContinuous</code> ODER Flanke START im Einzelzyklus).","−PF1 leuchtet dauernd bei <code>#statContinuous</code> und blinkt wie in L10, solange die Grundstellung fehlt – weiterhin eine einzige Schreibstelle für −PF1."],
 lf:["Warum braucht START eine Flankenauswertung? Was passiert ohne, wenn jemand die Taste hält?","Wie verhält sich Ihre Anlage, wenn im laufenden Zyklus von Dauerbetrieb auf Einzelzyklus umgeschaltet wird?","Warum hält STOP die Kette erst am Zyklusende an und nicht sofort?"],
 pr:["Dauerbetrieb + START → mehrere Zyklen hintereinander, −PF1 an","STOP in Schritt 6 → Korb wird fertig, dann Halt in Schritt 1","Einzelzyklus, START gedrückt halten → nur ein Zyklus","Not-Halt während AUTO → nach Quittieren kein selbstständiger Wiederanlauf"],
 plus:"Programmieren Sie die Grundstellungsfahrt als eigene Schrittkette (anheben → zurück und abdecken → senken → lösen) mit den Schrittnummern 11 bis 14. Sie startet in AUTO, wenn die Anlage nicht in Grundstellung steht."},

{id:"L14", st:2, t:"Not-Halt-Diagnose und Erstwert", sub:"Sicherheitsfunktion und Diagnose trennen", ue:3, vor:"L07", repo:"5", bild:["02-bedienpult.jpg","Not-Halt −SF0 und Quittiertaster −SF4 am Bedienpult"],
 einst:"<i>Verzinnen: Portal = SPS</i>, alles andere automatisch. Alle fünf Not-Halt-Taster sind in der 3D-Ansicht unter <i>Ansicht → Steuerstellen</i> erreichbar.",
 ziele:["Sicherheitsfunktion und Diagnose trennen","eine Erstwertmeldung bilden","Blinkmelder ansteuern"],
 sig:"KF2 SF0 SF8 SF9 SF10 SF33 SF4 SF41 SF42 SF43 SF44 PF5 PF12 PF13 PF14 PF15 BG20",
 sit:"Die Anlage hat fünf Not-Halt-Taster. Nach einem Stillstand fragt der Schichtleiter: Welcher Taster hat ausgelöst, und wo wurde quittiert?",
 auf:["Speichern Sie den <b>ersten</b> ausgelösten Taster in <code>#statFirstEStop</code> (Int 0 bis 5). Weitere Taster überschreiben ihn nicht.","Erkennen Sie beim Wiederanlauf von −KF2 (positive Flanke), an welchem Quittiertaster quittiert wurde.","Alle Quittier-Leuchttaster blinken mit 2 Hz, sobald quittiert werden kann: alle Not-Halt-Taster entriegelt, −KF2 gibt aber noch nicht frei.","Geben Sie Erstwert und Quittierort als Meldetext auf dem HMI aus."],
 lf:["Warum werden die Meldekontakte nur gemeldet und nicht zum Abschalten benutzt?","Wie unterscheiden Sie Not-Halt und Lichtvorhang, obwohl beide über −KF2 abschalten? Bedenken Sie: Das Schutzfeld meldet nach dem Durchgriff sofort wieder frei."],
 pr:["−SF9 drücken, dann −SF0 → Erstwert = −SF9","Beide entriegeln, an −S30 quittieren → „quittiert an −S30“","Durchgriff Lichtvorhang → eigene Meldung, kein Not-Halt-Erstwert","Leuchttaster blinken nur bei Quittierbedarf"]},

{id:"L15", st:2, t:"Band 1 mit Vor-Ort-Steuerstelle", sub:"Wendeschütz, Selbsthaltung, Motorschutz", ue:3, vor:"L09", repo:"6", bild:null,
 einst:"<i>Portal = automatisch</i>, <i>Band = SPS steuert</i>, Antrieb Band 1 = <i>Schütz</i>. Die übrige Förderstrecke bleibt in dieser Übung stehen.",
 ziele:["eine Wendeschützsteuerung mit Selbsthaltung und gegenseitiger Verriegelung umsetzen","den Motorschutz auswerten","Steuerstellen per Schlüsselschalter umschalten"],
 sig:"SA2 SF5 SF6 SF7 SF8 KF2 FA1 QA1 QA2 PF6",
 sit:"Für Reinigung und Wartung soll Band 1 direkt an der Vor-Ort-Steuerstelle −S10 gefahren werden – in beide Richtungen.",
 auf:["Mit −SA2 = 1 hat die Vor-Ort-Steuerstelle Vorrang, −PF6 leuchtet.","Rechts und Links mit Selbsthaltung; Halt (Öffner) oder Motorschutz löscht beide.","Gegenseitige Verriegelung: Richtungswechsel nur über Halt.","Zeichnen Sie zuerst den Stromlaufplan der Wendeschützschaltung in konventioneller Technik und übertragen Sie ihn dann in KOP."],
 lf:["Die Schütze sind mechanisch verriegelt. Warum programmieren Sie trotzdem eine Verriegelung?","Warum wird −SF7 als Öffner abgefragt, und was passiert bei Drahtbruch?"],
 pr:["Rechts drücken und loslassen → Band läuft weiter","Links während Rechtslauf → keine Reaktion","−FA1 auf 0 forcen → Band steht, Meldung","−SA2 = 0 → Vor-Ort-Befehle wirkungslos"]},

{id:"L16", st:2, t:"Anschlag, Vereinzeler, Übergabeplatz", sub:"Zwei Teilsysteme über Signale koordinieren", ue:6, vor:"L12, L15", repo:"7", bild:["10-drosselventile.jpg","Anschlag −MM5 mit Drosselrückschlagventilen"],
 einst:"Übungsumfang <i>Stufe 0</i>: <i>Portal = automatisch</i>, <i>Band = SPS steuert</i>.",
 ziele:["Portal und Band über Signale koordinieren","einen Positionssensor statt einer Wartezeit auswerten","eine Laufzeitüberwachung programmieren"],
 sig:"BG11 BG40 BG12 BG14 BG15 BG16 BG17 BG1 BG2 BG3 MB9 MB10 QA1",
 sit:"Körbe kommen in beliebigen Abständen auf Band 1. Der Vereinzeler −MM6 gibt sie einzeln frei, der Anschlag −MM5 hält sie am Übergabeplatz, das Portal holt sie ab.",
 list:{cap:"Pflichtreihenfolge am Übergabeplatz", items:["Korb läuft ein, <b>−BG40</b> meldet → Band stoppen.","Anschlag −MM5 öffnen (−MB9), warten auf −BG15 – erst dann darf das Portal einhängen und anheben.","Der Anschlag bleibt offen, bis der fertige Korb abgesetzt, gelöst (−BG2) und abgefahren ist (−BG11 frei).","Anschlag schließen (−BG14), erst dann den Vereinzeler öffnen.","Solange der Haken im Korb ist, steht das Band."]},
 auf:["Programmieren Sie die Pflichtreihenfolge als Schrittkette für den Übergabeplatz.","Einlaufüberwachung: Kommt nach −BG11 nicht innerhalb von 3 s −BG40, Meldung „Korb klemmt“ und Band aus.","Der Vereinzeler gibt den nächsten Korb erst bei geschlossenem Anschlag frei."],
 lf:["Warum ist eine Wartezeit nach −BG11 statt der Abfrage von −BG40 eine schlechte Lösung? (Tipp: Bandgeschwindigkeit am Umrichter)","Was passiert mechanisch, wenn bei geschlossenem Anschlag angehoben wird? Probieren Sie es aus und beschreiben Sie es."],
 pr:["Zehn Körbe hintereinander ohne Meldung in der Ereignisliste","−BG40 auf 0 forcen → nach 3 s „Korb klemmt“, Band steht","Vereinzeler öffnet nie bei offenem Anschlag","Kein abgerissener Anschlag, kein schief abgesetzter Korb"]},

{id:"L17", st:2, t:"Überwachungszeiten auslegen", sub:"Messen, begründen, Störungen melden", ue:4, vor:"L12", repo:"13, 14", bild:["09-weg-zeit-diagramm.jpg","Weg-Zeit-Diagramm mit Messlinien und Drosseln"],
 einst:"<i>Verzinnen: Portal = SPS</i>, alles andere automatisch.",
 ziele:["Fahrzeiten messen und Überwachungszeiten begründet ableiten","Störungen mit Zylinder und Richtung melden","Warten und Störung unterscheiden"],
 sig:"BG1 BG2 BG3 BG4 BG5 BG6 BG7 BG8 SF4",
 sit:"Ein Zylinder klemmt, und die Anlage steht ohne Meldung. Künftig soll jede Bewegung überwacht werden – mit Zeiten, die zur Anlage passen.",
 auf:["Messen Sie im Weg-Zeit-Diagramm („Groß öffnen“, Messlinien) die Fahrzeit jedes Zylinders in beiden Richtungen bei Drossel 50 %. Tragen Sie sie in die Tabelle ein.","Legen Sie die Überwachungszeit fest: Fahrzeit × Sicherheitsfaktor (Vorschlag 1,5 bis 2), Begründung schriftlich.","Ergänzen Sie jeden Bewegungsschritt um eine Laufzeitüberwachung. Bei Ablauf: Kette hält, Meldung wie „−MM2 senken: Endlage −BG4 nicht erreicht“, Quittierung mit −SF4.","Testen Sie mit Drossel 0 % (Zylinder steht) und mit −BG7 auf 0 geforct."],
 tpl:{cap:"Fahrzeiten", head:["Zylinder","Richtung","Fahrzeit bei 50 % (s)","Faktor","Überwachungszeit (s)"], rows:[["−MM1","einhängen"],["−MM1","lösen"],["−MM2","senken"],["−MM2","anheben"],["−MM3","zum Bad"],["−MM3","zum Band"],["−MM4","abdecken"],["−MM4","öffnen"]], inputs:3},
 lf:["Was unterscheidet „Schritt wartet auf Bedingung“ von „Störung“?","Welche Folgen hat eine zu kurze, welche eine zu lange Überwachungszeit?"],
 pr:["Fahrzeitentabelle für 4 Zylinder × 2 Richtungen vollständig","Jede Drossel einzeln auf 0 % → richtige Meldung mit Zylinder und Richtung","Nach Beheben und Quittieren läuft die Kette im selben Schritt weiter"],
 plus:"Projektieren Sie die Meldungen über <code>Program_Alarm</code>, sodass sie im HMI-Meldefenster mit Zeitstempel erscheinen."},

/* ================= STUFE 3 ================= */
{id:"L18", st:3, t:"Übergabe-Handshake", sub:"Band 1 → Rollenkurve → Band 2 → Kippmulde", ue:6, vor:"L16", repo:"8", bild:["05-rollenkurve.jpg","Rollenkurve −MA6 mit Lichtschranken −BG35 und −BG36"],
 einst:"<i>Portal = automatisch</i>, <i>Band = SPS steuert</i>. Die Förderstrecke aus L16 wird erweitert.",
 ziele:["eine Übergabe als Zustandsautomat modellieren","Sensorlücken mit gespeichertem Übergabe-Zustand oder Nachlaufzeit überbrücken","Stau und Kollision verhindern"],
 sig:"BG13 BG35 BG36 BG21 BG24 BG37 BG33 BG30 QA1 QA10 QA5 QA12 FA1 FA5 FA7 FA8",
 sit:"An jeder Stoßstelle liegt der Korb auf beiden Förderern. Er bewegt sich nur, wenn beide in dieselbe Richtung laufen. Zwischen den Lichtschranken einer Übergabe liegt eine Lücke von 22 bis 35 mm.",
 tab:{cap:"Regeln an den Übergaben", ...T(["Übergabe","Abgebender Förderer","Aufnehmender Förderer"],[
  ["Band 1 → Kurve","läuft mit, solange −BG13 oder −BG35 belegt ist (plus Lücke)","läuft, wenn die Kurve frei ist bzw. übernimmt"],["Kurve → Band 2","Korb an −BG36 wartet, bis Band 2 läuft und −BG21 frei ist","läuft, wenn −BG21 frei ist"],["Band 2 → Mulde","Korb an −BG24","Mulde unten (−BG30) und leer (−BG37, −BG33 frei); Muldenrollen laufen bis −BG33"]])},
 auf:["Zeichnen Sie je Übergabe ein Zustandsdiagramm (frei → übergeben → übernommen).","Überbrücken Sie die Sensorlücke mit einem Übergabe-Zustand (statische Variable im FB): gesetzt am abgebenden, zurückgesetzt am aufnehmenden Sensor. Vergleichen Sie mit einer Nachlaufzeit von 1 s.","Überwachen Sie jede Übergabe: Ist der Korb nach 4 s nicht übernommen, Störung mit Ort."],
 lf:["Warum ist der gespeicherte Übergabe-Zustand robuster als eine Nachlaufzeit?","Warum lohnt sich je Förderer ein eigener FB mit der Schnittstelle „Korb abgeben / Korb übernehmen“?"],
 pr:["Zehn Körbe ohne Meldung „Korb hängt an der Übergabe“","Mulde gekippt → Band 2 hält den Korb an −BG24","−FA7 auf 0 → Kurve steht, Band 1 fördert keinen Korb mehr nach"]},

{id:"L19", st:3, t:"Positionieren mit dem Inkrementalgeber", sub:"Spur A/B, Nullimpuls, Weg", ue:4, vor:"L18", repo:"9", bild:null,
 einst:"Wie L18.",
 ziele:["Spur A/B richtungsabhängig auswerten","Impulse in Weg umrechnen","über den Nullimpuls referenzieren"],
 sig:"BG18 BG27 BG22",
 sit:"Am Kühlplatz soll der Korb genauer stehen, als es eine Lichtschranke erlaubt. Band 1 und Band 2 haben je einen Inkrementalgeber an der Trommel.",
 tab:{cap:"Geberdaten", ...T(["Größe","Wert"],[["Impulse je Umdrehung","10"],["Bandweg je Impuls","24,5 mm"],["Bandweg je Umdrehung (Nullimpuls)","245 mm"],["Richtung vorwärts","B = 1 bei steigender Flanke A"]])},
 auf:["Zählen Sie die steigenden Flanken von A; B entscheidet über +1 oder −1.","Rechnen Sie in mm um (Real) und korrigieren Sie die Position beim Nullimpuls auf ein Vielfaches von 245 mm.","Positionieren Sie den Korb auf Band 2 am Kühlplatz über den Geber statt über −BG22. Vergleichen Sie die Genauigkeit."],
 lf:["Bei 100 mm/s kommen rund 4 Impulse pro Sekunde. Reicht das Zählen im OB1? Ab welcher Frequenz brauchen Sie einen HSC oder einen Weckalarm-OB?","Wie groß ist die Auflösung, und wie groß ist der Nachlaufweg nach dem Abschalten?"],
 pr:["Zählerstand steigt vorwärts und fällt rückwärts (Vor-Ort Links)","1 m Bandweg ergibt rund 41 Impulse","Positionierfehler am Kühlplatz gemessen und dokumentiert"]},

{id:"L20", st:3, t:"Abschrecken", sub:"Analogwert als Wartebedingung", ue:3, vor:"L18", repo:"10", bild:["07-spruehkuehlung.jpg","Sprühkühlung mit Pyrometer −BT2 und Luftmesser −MB14"],
 einst:"Wie L18.",
 ziele:["einen Analogwert skalieren","Aggregate in fester Reihenfolge schalten","Verbraucher bereichsabhängig schalten"],
 sig:"BG22 BT2 QA7 MB13 MB14",
 sit:"Ein Korb kommt mit über 200 °C aus dem Zinnbad. An Luft bräuchte er rund 3 Minuten, im Sprühwasser wenige Sekunden. Weiter darf er erst unter 60 °C.",
 auf:["Band 2 hält am Kühlplatz, bis −BT2 unter 60 °C meldet.","Pumpe −QA7 läuft vor dem Ventil −MB13 an; das Ventil wirkt nur bei laufender Pumpe.","Der Luftmesser −MB14 bläst nur, solange der Korb im Auslaufbereich ist.","Skalieren Sie −BT2 (%IW68, 0 bis 27648 = 0 bis 400 °C) mit <code>NORM_X</code> und <code>SCALE_X</code>."],
 lf:["Warum Pumpe vor Ventil und nicht gleichzeitig?","Wie lange braucht ein Korb an Luft, wie lange im Sprühwasser? Messen Sie beides."],
 pr:["Kein Korb verlässt den Kühlplatz über 60 °C","Kein Korb kommt nass zur Prüfstation – sonst bewertet die Kamera rund 30 % der Teile wegen Wasserflecken als n.i.O.","Luftmesser läuft nicht im Leerlauf"]},

{id:"L21", st:3, t:"Ausschussbehandlung", sub:"Teileverfolgung an der Prüfstation", ue:5, vor:"L20", repo:"12", bild:["06-pruefstation.jpg","Prüfstation mit Kamera −KF10 und Ausblasdüse −MB16"],
 einst:"Wie L18.",
 ziele:["ein kurzzeitig gültiges Ergebnissignal sicher übernehmen","Teile über eine Laufzeit verfolgen (FIFO)","einen Auswerfer zeitrichtig steuern"],
 sig:"BG33 BG37 MB15 BG30 BG31 QA8 QA9 BG32 KF10 BG28 BG29 MB16 BG34",
 sit:"Nach dem Kippen laufen 36 Teile einzeln unter der Kamera durch. n.i.O.-Teile müssen in den roten Behälter, i.O.-Teile in den blauen KLT – keines darf falsch landen.",
 auf:["Kippen nur mit Korb an −BG33 und −BG37; danach Vibrorinne und Prüfband starten.","Bei jeder positiven Flanke an −BG32 die Kamera triggern; das Ergebnis (−BG28 / −BG29) innerhalb von 0,3 s übernehmen.","Die Düse sitzt 200 mm hinter der Kamera. Berechnen Sie die Laufzeit aus der Bandgeschwindigkeit und blasen Sie nur n.i.O.-Teile aus.","Mehrere Teile können gleichzeitig zwischen Kamera und Düse liegen: Verwenden Sie ein Array als FIFO mit Ausblaszeitpunkten.","Bei −BG34 die Vibrorinne anhalten und den KLT-Wechsel melden."],
 lf:["Warum reicht ein einfacher <code>TP</code> für die Düse nicht mehr, sobald zwei Teile unterwegs sind?","Was passiert, wenn das Ergebnis nicht innerhalb von 0,3 s gelesen wird?"],
 pr:["Ereignisliste: kein „Gutteil ausgeblasen“, kein „n.i.O.-Teil im KLT“","KLT voll → Rinne steht, Meldung","Kipper kippt nie ohne Korb am Endanschlag"]},

{id:"L22", st:3, t:"Kühlwassertank: Zweipunkt", sub:"Grenzschalter und Drahtbruch", ue:2, vor:"L07", repo:"21", bild:["14-kuehlwassertank.jpg","Kühlwassertank mit −BL2, −BG38, −BG39, −MB17 und −MB18"],
 einst:"<i>Kühlwassertank: Nachspeisung = SPS regelt</i> und <i>Band, Anschlag, Vereinzeler = SPS</i> – nur dann schaltet Ihr Programm die Pumpe −QA7, und der Trockenlaufschutz liegt bei Ihnen. Alles andere automatisch. Den Ablasshahn als Störgröße nutzen.",
 ziele:["eine Zweipunktsteuerung mit Grenzschaltern programmieren","das Ruhestromprinzip anwenden","Drahtbruch erkennen"],
 sig:"BG38 BG39 MB17 MB18 QA7",
 sit:"Beim Abschrecken verliert der Tank Wasser. Er soll mit zwei Grenzschaltern automatisch nachgespeist werden, und die Pumpe darf nie trocken laufen.",
 auf:["−MB17 öffnen, sobald −BG38 abfällt; schließen, wenn −BG39 abfällt. −MB18 fest auf 100 % (27648 auf %QW80).","Pumpe −QA7 nur mit −BG38 freigeben (Trockenlaufschutz).","Drahtbruch: −BG39 im Signalmonitor auf 0 forcen → keine Nachspeisung mehr, Störmeldung."],
 lf:["Warum meldet −BG39 bei Drahtbruch „voll“ und −BG38 „leer“? Warum ist beides die sichere Seite?"],
 pr:["Pegel pendelt zwischen 25 und 90 %","Ereignisliste: kein „Tank läuft über“, kein „Pumpe läuft trocken“","Drahtbruch −BG39 erkannt und gemeldet"]},

{id:"L23", st:3, t:"Analogwert, Hysterese, Plausibilität", sub:"Zwei Messungen gegeneinander prüfen", ue:3, vor:"L22", repo:"22", bild:["14-kuehlwassertank.jpg","Radarsensor −BL2 im Tankdeckel"],
 einst:"Wie L22.",
 ziele:["Analogwerte normieren","eine Hysterese bauen","zwei unabhängige Messungen gegeneinander prüfen"],
 sig:"BL2 BG38 BG39 MB17",
 sit:"Der Radarsensor −BL2 liefert den Füllstand stetig. Damit soll feiner geregelt werden – die Grenzschalter bleiben als unabhängige Sicherheitsebene.",
 auf:["−BL2 (%IW72) mit <code>NORM_X</code> und <code>SCALE_X</code> in Prozent umrechnen.","Zweipunktregler mit Hysterese: ein unter 60 %, aus über 80 %.","Die Grenzschalter bleiben als Sicherheitsebene darüber.","Plausibilität: −BL2 über 95 % bei freiem −BG39, oder −BL2 unter 20 % bei bedecktem −BG38 → „Messung gestört“."],
 lf:["Warum braucht ein Zweipunktregler eine Hysterese? Was passiert ohne?","Warum ist die Plausibilitätsprüfung mit einer zeitlichen Verzögerung sinnvoll?"],
 pr:["Schaltpunkte 60 % und 80 % im Trend nachgewiesen","Testwert für −BL2 im FB statt des Rohwerts aufgeschaltet (Analogwerte lassen sich im Signalmonitor nicht forcen) → Plausibilitätsmeldung"]},

{id:"L24", st:3, t:"Temperaturregelung Zinnbad", sub:"Drei Reglerarten an einer Strecke", ue:6, vor:"L23", repo:"11", bild:["04-zinnbad.jpg","Zinnbad mit Heizung −TB1"],
 einst:"<i>Zinnbad Temperatur/Füllstand = SPS regelt</i>.",
 ziele:["drei Reglerarten an derselben Strecke umsetzen","Regelergebnisse nach Überschwingen, Schwankung und Schalthäufigkeit bewerten"],
 sig:"BT1 BL1 TB1 MB11 BG9 BG10",
 sit:"Das Zinn muss auf 280 °C gehalten werden; unter 250 °C fällt −BG9 ab und kein Korb darf mehr getaucht werden. Jedes Tauchen kühlt das Bad um 5 K und verbraucht 4 % Zinn.",
 tab:{cap:"Regelstrecke", ...T(["Größe","Wert"],[["Heizelement","PT1, 6 s"],["Bad","PT1, 150 s"],["100 % Heizleistung","360 °C im Beharrungszustand"],["für 280 °C","ca. 76 %"],["−BT1 / −BL1","%IW64 / %IW66, 0 bis 27648 = 0 bis 400 °C / 0 bis 100 %"],["Nachfüllen −MB11","ca. 2 %/s"]])},
 auf:["Variante A: Zweipunktregler mit Hysterese ±3 K um 280 °C.","Variante B: Impuls/PWM mit fester Periode, Tastverhältnis aus einem P-Regler.","Variante C: <code>PID_Compact</code> mit <code>Output_PWM</code> und Selbstoptimierung.","Nachfüllen: −MB11 öffnen unter 50 %, schließen bei 70 %. Begründen Sie die Grenzen.","Halten Sie für jede Variante den Trend fest und tragen Sie Schwankungsbreite und Schaltspiele je Minute ein."],
 tpl:{cap:"Vergleich der Reglerarten", head:["Variante","Schwankung (K)","Überschwingen (K)","Schaltspiele / min"], rows:[["A Zweipunkt"],["B PWM"],["C PID_Compact"]], inputs:3},
 lf:["Warum schwingt der Zweipunktregler trotz Hysterese über?","Welche Variante schaltet −TB1 am häufigsten? Wäre das mit einem Schütz statt Halbleiterrelais ein Problem – und welche Variante belastet den Netzanschluss am gleichmäßigsten?"],
 pr:["Ereignisliste: kein „Zinn nicht auf Temperatur“ im Dauerbetrieb","Vergleichstabelle der drei Varianten mit Messwerten ausgefüllt"]},

/* ================= STUFE 4 ================= */
{id:"L25", st:4, t:"Stetige Regelung mit PID_Compact", sub:"Integrierende Strecke, P und PI", ue:5, vor:"L23, L24", repo:"23", bild:["14-kuehlwassertank.jpg","Regelventil −MB18 mit Stellungsanzeige"],
 einst:"<i>Kühlwassertank: Nachspeisung = SPS regelt</i>.",
 ziele:["<code>PID_Compact</code> parametrieren","den Einfluss von P- und I-Anteil an einer integrierenden Strecke erklären","die Selbstoptimierung nutzen"],
 sig:"BL2 MB17 MB18 BG39 KF2",
 sit:"Der Füllstand soll ruhig auf 70 % gehalten werden – auch wenn jemand den Ablasshahn öffnet.",
 tab:{cap:"Regelstrecke", ...T(["Größe","Wert"],[["Streckentyp","integrierend (ohne Ausgleich)"],["Zulauf","bis 1,5 %/s bei −MB17 offen und −MB18 100 %"],["Stellzeit Regelventil","8 s für 0 bis 100 %"],["Verbrauch beim Sprühen","ca. 0,3 %/s plus Verdampfung"],["Ablasshahn (Störgröße)","ca. 1 %/s"]])},
 auf:["<code>PID_Compact</code> im Weckalarm-OB (z. B. OB30, 100 ms): Sollwert 70 %, Istwert −BL2 in %, Stellwert <code>Output_PER</code> auf %QW80.","−MB17 als Freigabe: zu bei −BG39 = 0 oder Not-Halt.","Erst als reiner P-Regler: bleibende Regelabweichung bei offenem Ablasshahn messen. Dann als PI-Regler.","Selbstoptimierung (Vor- und Feinoptimierung) durchführen und die Parameter dokumentieren."],
 lf:["Warum reicht an einer integrierenden Strecke ohne Störgröße ein P-Regler?","Warum entsteht mit Ablasshahn eine bleibende Abweichung, und warum beseitigt der I-Anteil sie?","Was geschieht mit dem I-Anteil, während −MB17 geschlossen ist – und wie verhindern Sie das (Stichwort Windup)?"],
 pr:["Trend Soll-, Ist- und Stellwert für P und PI dokumentiert","Bleibende Regelabweichung des P-Reglers in % angegeben","Ablasshahn auf und zu → PI-Regler führt zurück auf 70 %"]},

{id:"L26", st:4, t:"Stellglied und Zulauf überwachen", sub:"Prozessstörungen aus dem Verlauf erkennen", ue:3, vor:"L25", repo:"24", bild:null,
 einst:"Wie L25.",
 ziele:["ein Stellglied über die Stellungsrückmeldung überwachen","Prozessstörungen aus dem Verlauf des Istwerts erkennen"],
 sig:"MB18 MB17 BL2",
 sit:"Ein klemmendes Regelventil oder eine abgesperrte Frischwasserleitung fällt erst auf, wenn der Tank leer ist. Ihr Programm soll das früher merken.",
 auf:["Stellwert (%QW80) mit Stellungsrückmeldung (%IW74) vergleichen: Abweichung über 10 % länger als 15 s → „Regelventil klemmt“.","−MB17 offen, −MB18 deutlich geöffnet (z. B. über 50 %) und der Pegel steigt in 20 s nicht um 1 % → „Frischwasser fehlt“, Nachspeisung abschalten. Legen Sie die Bedingung so fest, dass der eingeschwungene Regelbetrieb keinen Fehlalarm auslöst.","Begründen Sie die 15 s mit der Stellzeit des Ventils."],
 lf:["Warum darf die Überwachung nicht anschlagen, während das Ventil normal von 0 auf 100 % fährt?"],
 pr:["Testwert für die Stellungsrückmeldung im FB aufgeschaltet → Meldung nach 15 s","Kein Fehlalarm beim normalen Stellen von 0 auf 100 %"]},

{id:"L27", st:4, t:"Förderstrecke am Umrichter", sub:"G120, Telegramm 1, TO_SpeedAxis", ue:6, vor:"L18", repo:"17", bild:["11-umrichter.jpg","Fenster Umrichter: Bedienpanel, Telegramm 1 und Rampen live"],
 einst:"<i>Band = SPS steuert</i>, unter <i>Übungsumfang → Antriebe</i> Band 1, Rollenkurve und Band 2 auf <i>Umrichter</i>.",
 ziele:["SINAMICS G120 an PROFINET mit Standardtelegramm 1 projektieren","<code>TO_SpeedAxis</code> anlegen","Förderer über PLCopen-Bausteine führen"],
 sig:"TA2 TA3 TA4 KF2",
 sit:"Die Förderer sollen sanft anfahren und ihre Geschwindigkeit an den Prozess anpassen. Dafür laufen sie künftig am Frequenzumrichter statt am Wendeschütz.",
 tab:{cap:"Umrichter und Telegrammadressen", ...T(["Umrichter","Antrieb","STW1 / NSOLL_A","ZSW1 / NIST_A","100 % (16#4000)"],[["−TA2","Band 1","%QW256 / %QW258","%IW256 / %IW258","100 mm/s"],["−TA3","Band 2","%QW260 / %QW262","%IW260 / %IW262","120 mm/s"],["−TA4","Rollenkurve","%QW264 / %QW266","%IW264 / %IW266","110 mm/s"]])},
 auf:["Umrichter in der Netzsicht einfügen, Telegramm 1 mit obigen Adressen, je Antrieb ein <code>TO_SpeedAxis</code>. <b>Keine Simulation / virtuelle Achse aktivieren.</b>","Bezugsdrehzahl 1500 1/min und Maximaldrehzahl 2250 1/min von Hand eintragen.","<code>MC_Power</code>, <code>MC_MoveVelocity</code>, <code>MC_Halt</code> und <code>MC_Reset</code> in einem FB je Förderer.","Geschwindigkeiten so abstimmen, dass an den Übergaben kein Korb hängt; rückwärts über negative Geschwindigkeit.","Rampen im Fenster <i>Umrichter → Rampen live</i> prüfen."],
 lf:["An einer Übergabe bewegt sich der Korb nur so schnell wie der langsamere Förderer. Was folgt daraus für die Sollwerte?","Welche Drehzahl in 1/min brauchen Sie für 100 mm/s an Band 2?"],
 pr:["Alle drei Achsen fahren, Status im TO-DB plausibel","Zehn Körbe ohne Übergabemeldung","Not-Halt → STO, nach Quittieren Wiederanlauf mit MC_Reset"]},

{id:"L28", st:4, t:"Telegramm von Hand", sub:"PROFIdrive-Zustandsmaschine bitgenau", ue:4, vor:"L27", repo:"18", bild:["12-umrichter-schrank.jpg","Umrichter −TA2 bis −TA5 im Schaltschrank"],
 einst:"Wie L27, aber ohne Technologieobjekt.",
 ziele:["Steuerwort und Sollwert bitgenau bilden","das Zustandswort auswerten","die PROFIdrive-Zustandsmaschine durchlaufen"],
 sig:"TA2",
 sit:"Ein Technologieobjekt nimmt Ihnen viel ab. Um Antriebsstörungen im Feld zu verstehen, gehen Sie einmal den Weg ohne: Sie sprechen den Umrichter direkt an.",
 auf:["STW1 und NSOLL_A selbst schreiben, ZSW1 und NIST_A lesen.","Zustandsfolge: S1 Einschaltsperre → STW1 = <code>16#047E</code> (AUS1 = 0) → S2 Einschaltbereit → S3 Betriebsbereit → STW1 = <code>16#047F</code> → S4 Betrieb.","Sollwert normieren: mm/s in ein Wort mit <code>16#4000</code> = 100 %.","AUS1, AUS2 und AUS3 nacheinander ausprobieren und im Fenster <i>Rampen live</i> vergleichen."],
 lf:["Warum kommt man aus der Einschaltsperre nur mit AUS1 = 0 heraus?","Was bewirkt STW1.10 = 0?","Warum lesen Sie die Bits besser über den Slice der Word-Variable als über %I-Bitadressen? (Stichwort Byte-Reihenfolge)"],
 pr:["Bit für Bit im Fenster Umrichter nachvollzogen und protokolliert","AUS1 (Rampe), AUS2 (Austrudeln) und AUS3 (Schnellhalt) unterschieden"]},

{id:"L29", st:4, t:"Prüfband mit variabler Geschwindigkeit", sub:"Potentiometer-Sollwert und dynamische Laufzeit", ue:3, vor:"L21, L28", repo:"20", bild:["13-vorort-pruefband.jpg","Vor-Ort-Steuerstelle −S50 mit Drehzahlpotentiometer −SF47"],
 einst:"<i>Band = SPS steuert</i>, Prüfband −MA5 am Umrichter −TA5.",
 ziele:["einen Potentiometer-Sollwert verarbeiten","Wertebereiche umrechnen","eine Laufzeitberechnung an die Istgeschwindigkeit anpassen"],
 sig:"SA7 SF45 SF46 SF47 TA5 PF16 MB16",
 sit:"Für Probeläufe will der Werker das Prüfband vor Ort langsamer stellen können. Die Ausschleusung muss trotzdem jedes n.i.O.-Teil treffen.",
 auf:["Schlüssel −SA7, EIN/AUS mit Selbsthaltung, −PF16 zeigt Vor-Ort.","Poti 0 bis 27648 auf NSOLL_A 0 bis <code>16#4000</code> umrechnen (100 % = 150 mm/s, nur vorwärts).","Ausblaszeit aus NIST_A berechnen: t = 200 mm / v_ist."],
 lf:["Warum NIST_A und nicht NSOLL_A für die Laufzeit von der Kamera bis zur Düse?"],
 pr:["Bei 30 %, 60 % und 100 % kein Gutteil ausgeblasen und kein n.i.O.-Teil im KLT"]},

{id:"L30", st:4, t:"Antriebsstörungen beherrschen", sub:"Melden, quittieren, sperren", ue:3, vor:"L27 oder L28", repo:"19", bild:["11-umrichter.jpg","Störungen auslösen im Fenster Umrichter"],
 einst:"Wie L27 oder L28.",
 ziele:["Stör- und Sperrbits auswerten","regelgerecht quittieren","quittierbare von zeitlich gesperrten Störungen unterscheiden"],
 sig:"TA2 TA3 TA4 KF2",
 sit:"Ein Bandmotor ist überlastet, ein anderer überhitzt. Das Bedienpersonal braucht klare Meldungen und einen sicheren Weg zurück in den Betrieb.",
 auf:["Im Fenster des Umrichters <i>Störung Überlast</i> (F30005) und <i>Motor überhitzt</i> (F07011) auslösen.","Not-Halt drücken (STO) und am Bedienpanel auf HAND schalten (ZSW1.9 fällt ab).","Ihr Programm meldet Störung (ZSW1.3), Einschaltsperre (ZSW1.6) und fehlende Führung (ZSW1.9) im Klartext.","Quittieren mit <code>MC_Reset</code> bzw. Flanke an STW1.7 – F07011 erst nach dem Abkühlen."],
 lf:["Warum lässt sich F07011 nicht sofort quittieren?"],
 pr:["Alle vier Fälle unterschiedlich gemeldet","Kein automatischer Wiederanlauf nach Quittieren"]},

{id:"L31", st:4, t:"Fehlersuche und Taktzeit", sub:"Systematisch eingrenzen, messbar verbessern", ue:4, vor:"L17", repo:"15, 16", bild:["10-drosselventile.jpg","Drosselrückschlagventile: jede Richtung einzeln einstellbar"],
 einst:"Die Lehrkraft stellt den Übungsumfang passend zu den Störfällen ein.",
 ziele:["eine Fehlersuchstrategie anwenden (Symptom → Hypothese → Test → Ursache)","Ergebnisse mit Messungen belegen","eine Taktzeit unter Randbedingungen optimieren"],
 sig:"FA1 BG20 BG9 KF2",
 sit:"<b>Teil A:</b> Die Lehrkraft löst verdeckt Störungen aus – Motorschutz, Lichtvorhang (Person durchlaufen lassen), Heizung aus, Drossel zu, Sensor geforct. <b>Teil B:</b> Der Betreiber will mehr Körbe pro Stunde, ohne die Mechanik zu gefährden.",
 auf:["Führen Sie für jeden Störfall das Fehlerprotokoll: Symptom, Vermutung, Prüfschritt, Ursache, Behebung, Zeit.","Stellen Sie die Drosseln so ein, dass die Zykluszeit sinkt, ohne dass ein Zylinder hart in die Endlage schlägt oder sich Bewegungen überschneiden.","Belegen Sie das Ergebnis mit den Messlinien (Schrittwechsel 2 bis Schrittwechsel 1).","Prüfen Sie, welche Schritte sich parallelisieren lassen."],
 tpl:{cap:"Fehlerprotokoll", head:["Nr.","Symptom","Vermutung","Prüfschritt","Ursache","Behebung","min"], rows:[["1"],["2"],["3"],["4"],["5"]], inputs:6},
 lf:["Welcher Prüfschritt grenzt einen Fehler am schnellsten ein: Signalmonitor, Beobachtungstabelle oder Weg-Zeit-Diagramm? Begründen Sie an einem Beispiel."],
 pr:["Fünf Störfälle mit vollständigem Fehlerprotokoll","Taktzeit vorher und nachher gemessen, Einsparung in %"]},

{id:"L32", st:4, t:"Abschlussprojekt Gesamtanlage", sub:"Planen, programmieren, abnehmen, präsentieren", ue:24, vor:"alle Stufen", repo:"–", bild:["01-gesamtanlage.jpg","Die ganze Anlage hängt an Ihrem Programm"],
 einst:"Übungsumfang <i>Stufe 3</i>: Das Modell fährt nichts mehr selbst.",
 ziele:["eine vollständige Anlagensteuerung im Team planen, programmieren, testen und dokumentieren","die Lösung im Fachgespräch begründen"],
 sig:"KF1 KF2",
 sit:"Ein Kunde bestellt die Verzinnungsanlage schlüsselfertig. Ihr Team liefert die komplette Steuerungssoftware und nimmt sie gemeinsam mit dem Kunden ab.",
 list:{cap:"Lastenheft (Auszug)", items:["Betriebsarten HAND und AUTO (Dauerbetrieb, Einzelzyklus) mit Grundstellungsfahrt.","Portal, Förderstrecke, Abschrecken, Entleeren, Prüfen mit allen Handshakes.","Zinnbad- und Kühlwasserregelung, die Wahl der Reglerart begründet.","Mindestens ein Förderer am Umrichter.","Meldekonzept: Störungen mit Ort und Ursache, Not-Halt-Erstwert, HMI-Bild.","Programmstruktur: OB1 ruft je Anlagenteil einen FB mit Instanz-DB, Betriebsarten zentral, globale Daten nur in einem Schnittstellen-DB.","Programmierstil durchgehend nach Siemens-Programmierstyleguide (Bezeichner, Präfixe, Multiinstanzen, Konstanten, Bausteinkopf) – geprüft mit dem Stil-Check."]},
 auf:["Pflichtenheft mit Technologieschema, GRAFCETs und E/A-Zuordnung erstellen.","Rollen verteilen: Projektleitung, Portal und Betriebsarten, Förderstrecke und Prüfstation, Regelung und Antriebe. Rollen nach der Hälfte wechseln.","Programmieren und Abschnitt für Abschnitt in Betrieb nehmen.","Inbetriebnahmeprotokoll mit allen Prüffällen der Stufen 1 bis 4 führen.","Präsentation (15 min) und Fachgespräch (15 min) vorbereiten."],
 lf:["Welche Entscheidung in Ihrer Programmstruktur würden Sie beim nächsten Projekt anders treffen, und warum?"],
 pr:["Not-Halt an jeder der fünf Stellen: Stillstand, Erstwert und Quittierort korrekt","Lichtvorhang durchgriffen: Stillstand, eigene Meldung","HAND, AUTO im Dauerbetrieb und im Einzelzyklus, Grundstellungsfahrt aus beliebiger Lage","Zehn Körbe in Folge ohne Eintrag in der Ereignisliste","Zinnbad hält 280 °C ± 5 K über zehn Zyklen","Kühlwassertank: Ablasshahn auf, die Regelung hält den Sollwert","Ein Umrichter: Störung ausgelöst, gemeldet, quittiert","Drei verdeckt eingebaute Fehler gefunden","Projektarchiv, Pflichtenheft und Präsentation vollständig"]}
]
